"use client";

import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CheckCircle2,Copy,RefreshCw,ShieldAlert,ShieldCheck,SlidersHorizontal} from "lucide-react";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type RuleSet={id:string;plan_component_id:string;name:string;purpose:string;description:string|null;version:number;is_active:boolean;predicates:any[];nodes:any[]};
type Catalog={rule_sets:RuleSet[];fields:any[]};
type Validation={ready:boolean;issues:string[];predicate_count:number;referenced_predicate_count:number;root_count:number};
const box={background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15} as const;
function label(v:string){return String(v||"").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}

export default function RuleSetManagement(){
 const[data,setData]=useState<Catalog>({rule_sets:[],fields:[]});const[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");const[validations,setValidations]=useState<Record<string,Validation>>({});
 const validateAll=async(ruleSets:RuleSet[])=>{const inactive=ruleSets.filter(x=>!x.is_active);const pairs=await Promise.all(inactive.map(async s=>{const{data:d}=await supabase.rpc("validate_comp_rule_set_for_activation",{target_rule_set_id:s.id});return [s.id,d as Validation] as const}));setValidations(Object.fromEntries(pairs.filter(([,v])=>v)))};
 const load=async()=>{setLoading(true);setError("");const{data:d,error:e}=await supabase.rpc("get_comp_rule_builder_catalog",{target_plan_component_id:null});if(e)setError(e.message);else{const next=(d||{rule_sets:[],fields:[]}) as Catalog;setData(next);await validateAll(next.rule_sets)}setLoading(false)};
 useEffect(()=>{load()},[]);
 const version=async(id:string)=>{setError("");setMessage("");const{error:e}=await supabase.rpc("create_comp_rule_set_version",{target_rule_set_id:id});if(e)setError(e.message);else{setMessage("New inactive rule version created. Review and preview it before activation.");await load()}};
 const activate=async(id:string,active:boolean)=>{setError("");setMessage("");if(active&&validations[id]&&!validations[id].ready){setError(`This version is not ready to activate: ${validations[id].issues.join(" ")}`);return}const{error:e}=await supabase.rpc("set_comp_rule_set_active",{target_rule_set_id:id,target_active:active});if(e)setError(e.message);else{setMessage(active?"Rule version activated. Other versions of the same rule set were deactivated.":"Rule version deactivated.");await load()}};
 const refreshFields=async()=>{setError("");setMessage("");const{data:d,error:e}=await supabase.rpc("refresh_comp_rule_deal_field_catalog");if(e)setError(e.message);else{setMessage(`HubSpot field catalog refreshed. ${d?.catalog_count||0} Deal fields are now available.`);await load()}};
 const grouped=Object.values(data.rule_sets.reduce((a,s)=>{const k=`${s.plan_component_id}:${s.name}`;(a[k]??=[]).push(s);return a},{} as Record<string,RuleSet[]>));
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1280,margin:"0 auto"}}>
  <Link href="/plans" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700}}><ArrowLeft size={15}/>Plans</Link>
  <header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",margin:"12px 0 18px",flexWrap:"wrap"}}><div><small style={{fontWeight:900,color:"#2095f3",letterSpacing:1}}>RULE GOVERNANCE</small><h1 style={{margin:"5px 0"}}>Rule sets & versions</h1><p style={{margin:0,color:"#647184",maxWidth:760}}>Active rule versions are locked. Create an inactive successor, edit and preview it, resolve validation issues, then activate it explicitly.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={refreshFields} style={{padding:"10px 12px",border:"1px solid #cfd9e3",borderRadius:9,background:"white",fontWeight:800}}><RefreshCw size={15}/> Refresh HubSpot fields</button><Link href="/plans/rules" style={{padding:"10px 12px",borderRadius:9,background:"#051b34",color:"white",fontWeight:800,textDecoration:"none"}}><SlidersHorizontal size={15}/> Build rules</Link></div></header>
  {error&&<div style={{...box,background:"#fff1f1",marginBottom:12}}>{error}</div>}{message&&<div style={{...box,background:"#edf9f2",marginBottom:12}}>{message}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginBottom:16}}>{[["Saved rule sets",grouped.length],["Versions",data.rule_sets.length],["Active versions",data.rule_sets.filter(x=>x.is_active).length],["Available Deal fields",data.fields.filter(x=>x.object_type==="deal").length]].map(([k,v])=><div key={String(k)} style={box}><small style={{color:"#647184"}}>{k}</small><b style={{display:"block",fontSize:26,marginTop:3}}>{loading?"—":v}</b></div>)}</section>
  {grouped.length===0&&!loading?<div style={box}>No saved rule sets yet. Build and save the first rule set, then it will appear here for version control.</div>:<section style={{display:"grid",gap:12}}>{grouped.map((versions,i)=>{const sorted=[...versions].sort((a,b)=>b.version-a.version);return <article key={i} style={box}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 4px",fontSize:20}}>{sorted[0].name}</h2><small style={{color:"#647184"}}>{label(sorted[0].purpose)} · {sorted.length} version{sorted.length===1?"":"s"}</small></div><button onClick={()=>version(sorted[0].id)} style={{padding:"8px 10px",border:"1px solid #cfd9e3",borderRadius:8,background:"white",fontWeight:800}}><Copy size={14}/> New version from latest</button></div><div style={{display:"grid",gap:8,marginTop:12}}>{sorted.map(s=>{const v=validations[s.id];const ready=s.is_active||v?.ready;return <div key={s.id} style={{display:"grid",gridTemplateColumns:"100px 120px minmax(180px,1fr) minmax(170px,1fr) auto",gap:10,alignItems:"center",padding:11,border:"1px solid #e4eaf0",borderRadius:9,background:s.is_active?"#f2fbf6":"#fafbfd"}}><b>Version {s.version}</b><span style={{fontWeight:800,color:s.is_active?"#0f7a50":"#718096"}}>{s.is_active?"ACTIVE":"INACTIVE"}</span><span style={{fontSize:13,color:"#647184"}}>{s.predicates?.length||0} rules · {s.nodes?.length||0} expression nodes</span><span style={{fontSize:12,fontWeight:800,color:ready?"#0f7a50":"#a95d00",display:"flex",gap:5,alignItems:"center"}}>{ready?<CheckCircle2 size={14}/>:<ShieldAlert size={14}/>} {ready?"Ready":"Needs validation"}{!ready&&v?.issues?.length?` · ${v.issues[0]}`:""}</span><div style={{display:"flex",gap:7}}><Link href={`/plans/rules?ruleSet=${s.id}`} style={{padding:"7px 9px",border:"1px solid #cfd9e3",borderRadius:7,textDecoration:"none",color:"#051b34",fontWeight:700}}>{s.is_active?"View":"Edit"}</Link><button disabled={!s.is_active&&!ready} onClick={()=>activate(s.id,!s.is_active)} style={{padding:"7px 9px",border:0,borderRadius:7,background:s.is_active?"#eef2f6":ready?"#2095f3":"#d9e1e8",color:s.is_active?"#34465a":"white",fontWeight:800,cursor:!s.is_active&&!ready?"not-allowed":"pointer"}}><ShieldCheck size={14}/> {s.is_active?"Deactivate":"Activate"}</button></div></div>})}</div></article>})}</section>}
 </div></main>;
}
