"use client";

import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CheckCircle2,Copy,GitCompareArrows,RefreshCw,ShieldAlert,ShieldCheck,SlidersHorizontal,X} from "lucide-react";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type RuleSet={id:string;plan_component_id:string;name:string;purpose:string;description:string|null;version:number;is_active:boolean;predicates:any[];nodes:any[]};
type Catalog={rule_sets:RuleSet[];fields:any[]};
type Validation={ready:boolean;issues:string[];predicate_count:number;referenced_predicate_count:number;root_count:number};
type PredicateChange={rule_key:string;change_type:"added"|"removed"|"changed";left:any;right:any};
type Comparison={left:{id:string;version:number;active:boolean};right:{id:string;version:number;active:boolean};metadata_changed:Record<string,boolean>;predicate_changes:PredicateChange[];expression_changed:boolean};
const box={background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15} as const;
function label(v:string){return String(v||"").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function valueText(v:unknown){if(v==null)return "—";if(Array.isArray(v))return v.join(", ");if(typeof v==="object")return JSON.stringify(v);return String(v)}
function predicateSummary(p:any){if(!p)return "—";return `${label(p.object_type)} · ${label(p.property_name)} · ${label(p.operator_key)} · ${valueText(p.comparison_value)}`}

export default function RuleSetManagement(){
 const[data,setData]=useState<Catalog>({rule_sets:[],fields:[]});const[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");const[validations,setValidations]=useState<Record<string,Validation>>({});
 const[comparison,setComparison]=useState<Comparison|null>(null);const[comparing,setComparing]=useState<string|null>(null);const[versioning,setVersioning]=useState<string|null>(null);const[activating,setActivating]=useState<string|null>(null);
 const validateAll=async(ruleSets:RuleSet[])=>{const inactive=ruleSets.filter(x=>!x.is_active);const pairs=await Promise.all(inactive.map(async s=>{const{data:d}=await supabase.rpc("validate_comp_rule_set_for_activation",{target_rule_set_id:s.id});return [s.id,d as Validation] as const}));setValidations(Object.fromEntries(pairs.filter(([,v])=>v)))};
 const load=async()=>{setLoading(true);setError("");const{data:d,error:e}=await supabase.rpc("get_comp_rule_builder_catalog",{target_plan_component_id:null});if(e)setError(e.message);else{const next=(d||{rule_sets:[],fields:[]}) as Catalog;setData(next);await validateAll(next.rule_sets)}setLoading(false)};
 useEffect(()=>{load()},[]);
 const version=async(id:string)=>{if(versioning)return;setError("");setMessage("");setComparison(null);setVersioning(id);const{data:newId,error:e}=await supabase.rpc("create_comp_rule_set_version",{target_rule_set_id:id});if(e){setError(e.message);setVersioning(null);return}if(!newId){setError("The new rule version was created but its ID was not returned.");setVersioning(null);return}window.location.assign(`/plans/rules?ruleSet=${String(newId)}`)};
 const activate=async(id:string,active:boolean,versionNumber:number)=>{setError("");setMessage("");setComparison(null);if(active&&validations[id]&&!validations[id].ready){setError(`This version is not ready to activate: ${validations[id].issues.join(" ")}`);return}const confirmed=window.confirm(active?`Activate Version ${versionNumber}? This will deactivate the currently active version of this rule set.`:`Deactivate Version ${versionNumber}? This rule set may have no active version until another version is activated.`);if(!confirmed)return;setActivating(id);const{error:e}=await supabase.rpc("set_comp_rule_set_active",{target_rule_set_id:id,target_active:active});setActivating(null);if(e)setError(e.message);else{setMessage(active?"Rule version activated. Other versions of the same rule set were deactivated.":"Rule version deactivated.");await load()}};
 const refreshFields=async()=>{setError("");setMessage("");setComparison(null);const{data:d,error:e}=await supabase.rpc("refresh_comp_rule_deal_field_catalog");if(e)setError(e.message);else{setMessage(`HubSpot field catalog refreshed. ${d?.catalog_count||0} Deal fields are now available.`);await load()}};
 const compare=async(older:RuleSet,newer:RuleSet)=>{setError("");setMessage("");setComparison(null);setComparing(newer.id);const{data:d,error:e}=await supabase.rpc("compare_comp_rule_set_versions",{left_rule_set_id:older.id,right_rule_set_id:newer.id});if(e)setError(e.message);else setComparison(d as Comparison);setComparing(null)};
 const grouped=Object.values(data.rule_sets.reduce((a,s)=>{const k=`${s.plan_component_id}:${s.name}`;(a[k]??=[]).push(s);return a},{} as Record<string,RuleSet[]>));
 const changedMetadata=comparison?Object.entries(comparison.metadata_changed||{}).filter(([,changed])=>changed).map(([key])=>label(key)):[];
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1280,margin:"0 auto"}}>
  <Link href="/plans" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700}}><ArrowLeft size={15}/>Plans</Link>
  <header style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",margin:"12px 0 18px",flexWrap:"wrap"}}><div><small style={{fontWeight:900,color:"#2095f3",letterSpacing:1}}>RULE GOVERNANCE</small><h1 style={{margin:"5px 0"}}>Rule sets & versions</h1><p style={{margin:0,color:"#647184",maxWidth:760}}>Active rule versions are locked. Create an inactive successor, edit and preview it, resolve validation issues, compare it with the prior version, then activate it explicitly.</p></div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={refreshFields} style={{padding:"10px 12px",border:"1px solid #cfd9e3",borderRadius:9,background:"white",fontWeight:800}}><RefreshCw size={15}/> Refresh HubSpot fields</button><Link href="/plans/rules" style={{padding:"10px 12px",borderRadius:9,background:"#051b34",color:"white",fontWeight:800,textDecoration:"none"}}><SlidersHorizontal size={15}/> Build rules</Link></div></header>
  {error&&<div style={{...box,background:"#fff1f1",marginBottom:12}}>{error}</div>}{message&&<div style={{...box,background:"#edf9f2",marginBottom:12}}>{message}</div>}
  {comparison&&<section style={{...box,marginBottom:16,borderColor:"#b9d9f5"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start"}}><div><small style={{fontWeight:900,color:"#2095f3",letterSpacing:.8}}>VERSION COMPARISON</small><h2 style={{margin:"4px 0 3px",fontSize:20}}>Version {comparison.left.version} → Version {comparison.right.version}</h2><p style={{margin:0,color:"#647184",fontSize:13}}>{comparison.predicate_changes.length} rule change{comparison.predicate_changes.length===1?"":"s"} · {comparison.expression_changed?"Expression changed":"Expression unchanged"}{changedMetadata.length?` · Metadata: ${changedMetadata.join(", ")}`:""}</p></div><button onClick={()=>setComparison(null)} aria-label="Close comparison" style={{border:0,background:"transparent",padding:4,cursor:"pointer"}}><X size={18}/></button></div>
    {comparison.predicate_changes.length===0&&!comparison.expression_changed&&changedMetadata.length===0?<div style={{marginTop:12,padding:12,borderRadius:8,background:"#edf9f2",fontWeight:800,color:"#0f7a50"}}>No functional differences detected between these versions.</div>:<div style={{display:"grid",gap:8,marginTop:12}}>{comparison.predicate_changes.map(c=><div key={c.rule_key} style={{padding:11,border:"1px solid #e1e8ef",borderRadius:8,background:"#fafbfd"}}><div style={{display:"flex",justifyContent:"space-between",gap:8,flexWrap:"wrap"}}><b>{c.right?.name||c.left?.name||label(c.rule_key)}</b><span style={{fontSize:12,fontWeight:900,color:c.change_type==="added"?"#0f7a50":c.change_type==="removed"?"#a33a3a":"#a95d00"}}>{c.change_type.toUpperCase()}</span></div>{c.change_type!=="added"&&<div style={{fontSize:12,color:"#647184",marginTop:5}}><b>Before:</b> {predicateSummary(c.left)}</div>}{c.change_type!=="removed"&&<div style={{fontSize:12,color:"#34465a",marginTop:3}}><b>After:</b> {predicateSummary(c.right)}</div>}</div>)}{comparison.expression_changed&&<div style={{padding:11,border:"1px solid #f0d5a6",borderRadius:8,background:"#fff9ec",fontSize:13}}><b>Expression logic changed.</b> The AND / OR / NOT structure or rule ordering differs from the prior version.</div>}{changedMetadata.length>0&&<div style={{padding:11,border:"1px solid #dbe4ec",borderRadius:8,background:"#f8fafc",fontSize:13}}><b>Metadata changed:</b> {changedMetadata.join(", ")}.</div>}</div>}
  </section>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginBottom:16}}>{[["Saved rule sets",grouped.length],["Versions",data.rule_sets.length],["Active versions",data.rule_sets.filter(x=>x.is_active).length],["Available Deal fields",data.fields.filter(x=>x.object_type==="deal").length]].map(([k,v])=><div key={String(k)} style={box}><small style={{color:"#647184"}}>{k}</small><b style={{display:"block",fontSize:26,marginTop:3}}>{loading?"—":v}</b></div>)}</section>
  {grouped.length===0&&!loading?<div style={box}>No saved rule sets yet. Build and save the first rule set, then it will appear here for version control.</div>:<section style={{display:"grid",gap:12}}>{grouped.map((versions,i)=>{const sorted=[...versions].sort((a,b)=>b.version-a.version);return <article key={i} style={box}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 4px",fontSize:20}}>{sorted[0].name}</h2><small style={{color:"#647184"}}>{label(sorted[0].purpose)} · {sorted.length} version{sorted.length===1?"":"s"}</small></div><button disabled={!!versioning} onClick={()=>version(sorted[0].id)} style={{padding:"8px 10px",border:"1px solid #cfd9e3",borderRadius:8,background:"white",fontWeight:800,cursor:versioning?"not-allowed":"pointer",opacity:versioning&&versioning!==sorted[0].id?.7:1}}><Copy size={14}/> {versioning===sorted[0].id?"Creating version…":"New version from latest"}</button></div><div style={{display:"grid",gap:8,marginTop:12}}>{sorted.map((s,index)=>{const v=validations[s.id];const ready=s.is_active||v?.ready;const prior=sorted[index+1];return <div key={s.id} style={{display:"grid",gridTemplateColumns:"100px 120px minmax(160px,1fr) minmax(160px,1fr) auto",gap:10,alignItems:"center",padding:11,border:"1px solid #e4eaf0",borderRadius:9,background:s.is_active?"#f2fbf6":"#fafbfd"}}><b>Version {s.version}</b><span style={{fontWeight:800,color:s.is_active?"#0f7a50":"#718096"}}>{s.is_active?"ACTIVE":"INACTIVE"}</span><span style={{fontSize:13,color:"#647184"}}>{s.predicates?.length||0} rules · {s.nodes?.length||0} expression nodes</span><span style={{fontSize:12,fontWeight:800,color:ready?"#0f7a50":"#a95d00",display:"flex",gap:5,alignItems:"center"}}>{ready?<CheckCircle2 size={14}/>:<ShieldAlert size={14}/>} {ready?"Ready":"Needs validation"}{!ready&&v?.issues?.length?` · ${v.issues[0]}`:""}</span><div style={{display:"flex",gap:7,flexWrap:"wrap",justifyContent:"flex-end"}}>{prior&&<button onClick={()=>compare(prior,s)} disabled={comparing===s.id} style={{padding:"7px 9px",border:"1px solid #cfd9e3",borderRadius:7,background:"white",color:"#051b34",fontWeight:700}}><GitCompareArrows size={14}/> {comparing===s.id?"Comparing…":"Compare"}</button>}<Link href={`/plans/rules?ruleSet=${s.id}`} style={{padding:"7px 9px",border:"1px solid #cfd9e3",borderRadius:7,textDecoration:"none",color:"#051b34",fontWeight:700}}>{s.is_active?"View":"Edit"}</Link><button disabled={activating===s.id||(!s.is_active&&!ready)} onClick={()=>activate(s.id,!s.is_active,s.version)} style={{padding:"7px 9px",border:0,borderRadius:7,background:s.is_active?"#eef2f6":ready?"#2095f3":"#d9e1e8",color:s.is_active?"#34465a":"white",fontWeight:800,cursor:activating===s.id||(!s.is_active&&!ready)?"not-allowed":"pointer"}}><ShieldCheck size={14}/> {activating===s.id?"Updating…":s.is_active?"Deactivate":"Activate"}</button></div></div>})}</div></article>})}</section>}
 </div></main>;
}
