"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,ArrowRight,ChevronRight,Plus,Save} from "lucide-react";
import PlanBuilderProgress from "../../components/plan-builder-progress";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Component={component_id:string;name:string;component_code:string;calculation_type:string|null;measurement_source:string|null;measurement_period:string|null;maximum_payout:number|null;rule_configuration:any};
type Assignment={employee_id:string;employee_name:string};
type Version={version_id:string;version_number:number;status:string;effective_start_date:string;effective_end_date:string|null;currency_code:string;notes?:string|null;components:Component[];assignments:Assignment[];draft_assignments:Assignment[]};
type Plan={plan_id:string;name:string;plan_code:string;description:string|null;versions:Version[]};
const title=(value:string|null|undefined)=>String(value||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase());
const pct=(value:any)=>`${Number(value)*100}%`;
function paySummary(component:Component){const cfg=component.rule_configuration||{};if(component.calculation_type==="percentage"&&cfg.rate!=null)return `${pct(cfg.rate)} of ${title(component.measurement_source)}`;if(component.calculation_type==="tiered_percentage"&&Array.isArray(cfg.tiers))return cfg.tiers.map((tier:any)=>`${tier.minimum_contract_years||0}${tier.maximum_contract_years?`–${tier.maximum_contract_years}`:"+"} yr: ${pct(tier.rate)}`).join(" · ");if(component.calculation_type==="threshold_bonus")return `${Number(cfg.threshold_amount||0).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0})} threshold → ${Number(cfg.bonus_amount||0).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0})} bonus`;if(component.calculation_type==="fixed_amount"&&cfg.amount!=null)return Number(cfg.amount).toLocaleString("en-US",{style:"currency",currency:"USD"});return title(component.calculation_type)}

export default function ManageDraftPlan(){
 const params=useParams<{versionId:string}>();const router=useRouter();
 const[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const[startDate,setStartDate]=useState(""),[endDate,setEndDate]=useState(""),[currency,setCurrency]=useState("USD"),[notes,setNotes]=useState(""),[dirty,setDirty]=useState(false);
 useEffect(()=>{(async()=>{setLoading(true);const{data,error:loadError}=await supabase.rpc("get_compensation_plan_admin_data");if(loadError){setError(loadError.message);setLoading(false);return}const loaded=(data?.plans||[]) as Plan[];setPlans(loaded);for(const p of loaded){const v=p.versions.find(x=>x.version_id===params.versionId);if(v){setStartDate(v.effective_start_date||"");setEndDate(v.effective_end_date||"");setCurrency(v.currency_code||"USD");setNotes(v.notes||"");break}}setDirty(false);setLoading(false)})()},[params.versionId]);
 useEffect(()=>{document.body.dataset.planDirty=dirty?"true":"false";const onBeforeUnload=(e:BeforeUnloadEvent)=>{if(!dirty)return;e.preventDefault();e.returnValue=""};window.addEventListener("beforeunload",onBeforeUnload);return()=>{delete document.body.dataset.planDirty;window.removeEventListener("beforeunload",onBeforeUnload)}},[dirty]);
 const plan=useMemo(()=>plans.find(p=>p.versions.some(v=>v.version_id===params.versionId))||null,[plans,params.versionId]);const version=plan?.versions.find(v=>v.version_id===params.versionId)||null;const people=version?.status==="draft"?version.draft_assignments:version?.assignments||[];
 const saveDraft=async()=>{if(!version||version.status!=="draft")return false;if(endDate&&startDate&&endDate<startDate){setError("Effective end date cannot be before the effective start date.");return false}setSaving(true);setError("");const{error:saveError}=await supabase.rpc("update_compensation_plan_draft_version",{selected_plan_version_id:version.version_id,selected_effective_start_date:startDate,selected_effective_end_date:endDate||null,selected_currency_code:currency,selected_notes:notes||null});setSaving(false);if(saveError){setError("We couldn't save the plan details. Please try again.");return false}setDirty(false);setMessage("Saved.");return true};
 const save=async(e:FormEvent)=>{e.preventDefault();await saveDraft()};
 const go=async(href:string)=>{if(dirty){const ok=await saveDraft();if(!ok)return}router.push(href)};
 if(loading)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-empty">Loading plan…</div></div></main>;
 if(!plan||!version)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-alert error">Plan version not found.</div></div></main>;
 if(version.status!=="draft")return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-alert warning">Only draft versions can be managed here.</div><Link className="plan-button secondary" href="/plans">Back to plans</Link></div></main>;
 return <main className="plan-workspace"><div className="plan-page-shell" style={{paddingBottom:80}}>
  <div className="plan-breadcrumb"><Link href="/plans"><ArrowLeft size={15}/>Plans</Link><span>/</span><span>{plan.name}</span></div>
  <PlanBuilderProgress versionId={version.version_id} current="earnings" completed={{basics:true,people:people.length>0,earnings:version.components.length>0}} onNavigate={href=>void go(href)}/>
  <header className="plan-page-header"><div><span className="plan-kicker">STEP 3 OF 6</span><h1>What can they earn?</h1><p>Create each Earning Type in this plan. Each one defines the payout, qualifying activity, when it is Earned, and when it becomes eligible for payment.</p></div><span className="plan-status draft">Draft v{version.version_number}</span></header>
  {error&&<div className="plan-alert error">{error}</div>}{message&&<div className="plan-info-row">{message}</div>}
  <details className="plan-step-card"><summary style={{cursor:"pointer",fontWeight:800}}>Plan dates & internal details</summary><form onSubmit={save} style={{marginTop:16}}><div className="plan-form-grid two"><label>Effective start date *<input type="date" required value={startDate} onChange={e=>{setStartDate(e.target.value);setDirty(true)}}/></label><label>Effective end date<input type="date" min={startDate||undefined} value={endDate} onChange={e=>{setEndDate(e.target.value);setDirty(true)}}/></label><label>Currency<select value={currency} onChange={e=>{setCurrency(e.target.value);setDirty(true)}}><option value="USD">USD</option></select></label><label>Version notes<textarea rows={2} value={notes} onChange={e=>{setNotes(e.target.value);setDirty(true)}} placeholder="Optional"/></label></div><div className="plan-actions"><span style={{marginRight:"auto",fontSize:12,color:dirty?"#9a6700":"#667085"}}>{dirty?"Unsaved changes":"Saved"}</span><button className="plan-button secondary" disabled={saving||!dirty}><Save size={14}/>{saving?"Saving…":"Save details"}</button></div></form></details>
  <section id="earning-types" className="plan-step-card"><div className="plan-step-card__head"><div><h2>Earning Types</h2><p>Use one Earning Type for one compensation concept. Tiered rates such as 8% / 10% / 12% belong inside a single Earning Type.</p></div><Link className="plan-button brand" href={`/plans/component/new?version=${version.version_id}`}><Plus size={14}/>Add Earning Type</Link></div>
   {version.components.map(component=><Link key={component.component_id} href={`/plans/component/${component.component_id}?version=${version.version_id}`} style={{textDecoration:"none",color:"inherit",display:"grid",gridTemplateColumns:"minmax(180px,1fr) minmax(220px,1.4fr) 28px",gap:14,alignItems:"center",borderTop:"1px solid #eef1f4",padding:"13px 4px"}}><div><b>{component.name}</b><div style={{fontSize:10.5,color:"#667085",fontFamily:"monospace",marginTop:2}}>{component.component_code}</div></div><div><div style={{fontSize:12,fontWeight:700}}>{paySummary(component)}</div><div style={{fontSize:11,color:"#667085",marginTop:3}}>{title(component.measurement_period)} · {title(component.measurement_source)}</div></div><ChevronRight size={18}/></Link>)}
   {!version.components.length&&<div className="plan-empty">No Earning Types yet. Add the first one to continue.</div>}
  </section>
  <div className="plan-wizard-actions"><button type="button" className="plan-button secondary" onClick={()=>void go(`/plans/applicability/${version.version_id}`)}><ArrowLeft size={15}/>Back</button><div className="plan-wizard-actions__right"><button type="button" className="plan-button brand" disabled={!version.components.length} onClick={()=>void go(`/plans/agreements/${version.version_id}`)}>Next step<ArrowRight size={15}/></button></div></div>
 </div></main>;
}
