"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,BarChart3,CheckCircle2,ClipboardCheck,History,RefreshCw,Settings,ShieldCheck,Users,WalletCards} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;
type Access={full_name?:string;email?:string;roles?:string[];permissions?:string[]};
type Summary={counts:Record<string,number>;amounts:Record<string,number>};
type Approval={approval_level:string;earned_amount:number;approver_name:string|null;assignee_activation_required:boolean};
type Handoff={step_type:string;earned_amount:number;approved_amount:number;assigned_employee_name:string|null;assignee_activation_required:boolean};
type Earning={eligibility_status:string;employee_verification_status:string;manager_approval_status:string;payment_status:string;hold_reason:string|null;source_match_status:string|null;reconciliation_status:string|null;executive_approval_status:string};
type EarningsSummary={summary:{current_earnings:number};earnings:Earning[]};
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function trueIssue(e:Earning){return Boolean(e.hold_reason||["held","error"].includes(e.payment_status)||(e.source_match_status&&!["matched","verified","ok","confirmed"].includes(e.source_match_status))||(e.reconciliation_status&&!["reconciled","complete","matched","not_required","not_reviewed"].includes(e.reconciliation_status))||["returned","rejected"].includes(e.manager_approval_status)||["returned","rejected"].includes(e.executive_approval_status))}
export default function ManagePage(){
 const[access,setAccess]=useState<Access|null>(null),[summary,setSummary]=useState<Summary|null>(null),[approvals,setApprovals]=useState<Approval[]>([]),[handoffs,setHandoffs]=useState<Handoff[]>([]),[earnings,setEarnings]=useState<EarningsSummary|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const[a,b,c,d,e]=await Promise.all([supabase.rpc("get_current_user_access"),supabase.rpc("get_payout_readiness_summary"),supabase.rpc("get_my_comp_earning_approval_requests",{include_completed:false}),supabase.rpc("get_my_comp_earning_handoff_tasks",{include_completed:false}),supabase.rpc("get_admin_earnings_data")]);if(a.error)setError(a.error.message);else setAccess((a.data||{}) as Access);if(b.error)setError(x=>x||b.error.message);else setSummary(b.data as Summary);if(c.error)setError(x=>x||c.error.message);else setApprovals((c.data||[]) as Approval[]);if(d.error)setError(x=>x||d.error.message);else setHandoffs((d.data||[]) as Handoff[]);if(e.error)setError(x=>x||e.error.message);else setEarnings(e.data as EarningsSummary);setLoading(false)};useEffect(()=>{load()},[]);
 const isAdmin=Boolean(access?.roles?.includes("system_administrator"));
 const earningRows=earnings?.earnings||[];
 const readyToSubmit=earningRows.filter(e=>e.eligibility_status==="eligible"&&e.employee_verification_status!=="verified"&&e.manager_approval_status!=="approved").length;
 const submitted=earningRows.filter(e=>e.employee_verification_status==="verified"&&e.manager_approval_status!=="approved").length;
 const issues=earningRows.filter(trueIssue).length;
 const sharonQueue=useMemo(()=>approvals.filter(x=>x.approval_level==="compensation_admin_review"),[approvals]);
 const namitQueue=useMemo(()=>approvals.filter(x=>x.approval_level==="executive_approval"),[approvals]);
 const scottQueue=useMemo(()=>handoffs.filter(x=>x.step_type==="finance_acknowledgement"),[handoffs]);
 const sumApproval=(rows:Approval[])=>rows.reduce((a,b)=>a+Number(b.earned_amount||0),0),sumHandoff=(rows:Handoff[])=>rows.reduce((a,b)=>a+Number(b.approved_amount||b.earned_amount||0),0);
 const operational=[
  {href:"/earnings",icon:<BarChart3/>,title:"Earnings",copy:"Authoritative ledger for earned, eligible, approved, and paid compensation across employees.",metric:`${earnings?.summary?.current_earnings||0} current earnings`},
  {href:"/attention",icon:<AlertTriangle/>,title:"Needs Attention",copy:"True exceptions, returned items, holds, mismatches, and configuration blockers that require human action.",metric:`${issues} exceptions · ${readyToSubmit} employee-ready · ${submitted} in progress`},
  {href:"/submissions",icon:<ClipboardCheck/>,title:"Approvals",copy:"Employee-submitted earnings moving through Sharon review and Namit executive approval.",metric:`${sharonQueue.length} with Sharon · ${namitQueue.length} with Namit`},
  {href:"/payments",icon:<WalletCards/>,title:"Payments",copy:"Scott Finance handoffs, payroll readiness, scheduled pay runs, and confirmed payments.",metric:`${scottQueue.length} with Scott · ${summary?.counts?.ready_for_payroll||0} payroll-ready`}
 ];
 const administration=[{href:"/employees",icon:<Users/>,title:"Employees",copy:"Compensation participation, manager assignment, access readiness, plan setup, and employee act-as testing."},{href:"/plans",icon:<ClipboardCheck/>,title:"Plans",copy:"Effective-dated compensation plan versions, components, assignments, and payout timing."},{href:"/workflow",icon:<ShieldCheck/>,title:"Workflow",copy:"Approval chains, responsible people, pre-provisioning readiness, and Finance handoffs."},{href:"/reconciliation",icon:<History/>,title:"Reconciliation",copy:"Source data, approved compensation, actual payments, and historical corrections."},{href:"/hubspot",icon:<RefreshCw/>,title:"HubSpot",copy:"Source synchronization and compensation-sensitive field changes."},{href:"/users",icon:<Settings/>,title:"Users & Permissions",copy:"Active users, pre-provisioned users, roles, managers, readiness, and permission catalog."},{href:"/audit",icon:<History/>,title:"Audit Log",copy:"Who changed what, when, why, and the before/after state for sensitive actions."}];
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1250,margin:"0 auto"}}>
  <section style={{display:"flex",justifyContent:"space-between",gap:24,alignItems:"flex-start",marginBottom:28,flexWrap:"wrap"}}><div style={{flex:"1 1 700px"}}><small style={{fontWeight:800,letterSpacing:1.2,color:"#2095f3"}}>ENGAGIFII COMPENSATION</small><h1 style={{fontSize:36,margin:"7px 0 8px"}}>Management workspace</h1><p style={{margin:0,color:"#647184",maxWidth:820,lineHeight:1.5}}>Employee-submitted compensation flows through review, executive approval, Finance acceptance, payroll, and confirmed payment. Eligible items can be submitted at any point in the month.</p><small style={{display:"block",marginTop:10,color:"#718096"}}>{access?.full_name||access?.email||"Signed-in user"}{isAdmin?" · System Administrator":""}</small></div><button onClick={load} disabled={loading} style={{display:"flex",alignItems:"center",gap:7,padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:700}}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></section>
  {error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginBottom:22}}>{[["Ready for employees",readyToSubmit,summary?.amounts?.eligible||0],["With Sharon",sharonQueue.length,sumApproval(sharonQueue)],["With Namit",namitQueue.length,sumApproval(namitQueue)],["With Scott",scottQueue.length,sumHandoff(scottQueue)],["Paid",summary?.counts?.paid||0,summary?.amounts?.paid||0]].map(([name,count,amount])=><div key={String(name)} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small style={{fontWeight:800,color:"#718096"}}>{name}</small><b style={{display:"block",fontSize:25,margin:"5px 0"}}>{loading?"—":String(count)}</b><strong>{loading?"—":money(Number(amount))}</strong></div>)}</section>
  <h2 style={{margin:"0 0 10px"}}>Operate compensation</h2><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:14,marginBottom:26}}>{operational.map(card=><Link href={card.href} key={card.href} style={{display:"block",background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:20,textDecoration:"none",color:"inherit"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><span style={{width:42,height:42,borderRadius:10,display:"grid",placeItems:"center",background:"#eaf5ff",color:"#2095f3"}}>{card.icon}</span><CheckCircle2 size={18} color="#9aabb9"/></div><h2 style={{margin:"14px 0 6px"}}>{card.title}</h2><p style={{color:"#647184",lineHeight:1.45,minHeight:58}}>{card.copy}</p><b style={{fontSize:13,color:"#31465a"}}>{card.metric}</b></Link>)}</section>
  <h2 style={{margin:"0 0 10px"}}>Administration</h2><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:12,marginBottom:26}}>{administration.map(card=><Link href={card.href} key={card.href} style={{display:"block",background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:16,textDecoration:"none",color:"inherit"}}><span style={{color:"#2095f3"}}>{card.icon}</span><b style={{display:"block",fontSize:16,margin:"8px 0 4px"}}>{card.title}</b><small style={{color:"#647184",lineHeight:1.45}}>{card.copy}</small></Link>)}</section>
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:14,marginBottom:22}}><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><h2 style={{marginTop:0}}>Canonical workflow</h2>{["Employee verifies and submits an eligible earning.","Sharon reviews the submitted earning and approves, returns, or rejects it.","Namit performs the required executive approval.","Scott accepts the fully approved obligation for payment.","Payroll execution confirms actual payment; Finance acceptance alone is never Paid."].map((x,i)=><div key={x} style={{display:"flex",gap:10,margin:"11px 0"}}><b style={{width:25,height:25,borderRadius:20,display:"grid",placeItems:"center",background:"#eaf5ff",color:"#2095f3",flex:"0 0 auto"}}>{i+1}</b><span>{x}</span></div>)}</div><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><h2 style={{marginTop:0}}>Current readiness</h2><div style={{display:"grid",gap:9}}><div><Users size={17}/> <b>Employee act-as testing</b><p style={{margin:"3px 0",color:"#647184"}}>Authorized managers/admins can exercise employee flows while the audit trail preserves the real actor.</p></div><div><ShieldCheck size={17}/> <b>Pre-provisioned approvers</b><p style={{margin:"3px 0",color:"#647184"}}>Namit and Scott can remain uninvited without being skipped from the configured workflow.</p></div><div><History size={17}/> <b>Historical integrity</b><p style={{margin:"3px 0",color:"#647184"}}>Paid records are not silently rewritten; corrections become traceable adjustments.</p></div></div></div></section>
 </div></main>
}
