"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,Download,FileText,Plus,Trash2,Upload} from "lucide-react";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");

type Employee={employee_id:string;employee_name:string;email:string};
type Plan={plan_id:string;name:string;plan_code:string;versions:{version_id:string;version_number:number;status:string}[]};
type Agreement={agreement_id:string;employee_id:string|null;employee_name:string|null;applies_to_everyone:boolean;file_name:string;storage_path:string;mime_type:string|null;file_size_bytes:number|null;signed_at:string|null;notes:string|null;created_at:string};
const safeName=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").slice(-120);
const prettySize=(bytes:number|null)=>bytes==null?"":bytes<1024*1024?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/(1024*1024)).toFixed(1)} MB`;

export default function PlanAgreementsPage(){
 const params=useParams<{versionId:string}>();const versionId=params.versionId;
 const[plans,setPlans]=useState<Plan[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[agreements,setAgreements]=useState<Agreement[]>([]);
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const[file,setFile]=useState<File|null>(null),[scope,setScope]=useState<"employee"|"everyone">("employee"),[employeeId,setEmployeeId]=useState(""),[signedAt,setSignedAt]=useState(""),[notes,setNotes]=useState("");
 const plan=useMemo(()=>plans.find(p=>p.versions.some(v=>v.version_id===versionId)),[plans,versionId]);const version=plan?.versions.find(v=>v.version_id===versionId);const editable=version?.status==="draft";
 const load=async()=>{setLoading(true);setError("");const[p,a]=await Promise.all([supabase.rpc("get_compensation_plan_admin_data"),supabase.rpc("get_comp_plan_agreements",{selected_plan_version_id:versionId})]);if(p.error)setError(p.error.message);else{setPlans((p.data?.plans||[]) as Plan[]);setEmployees((p.data?.employees||[]) as Employee[])}if(a.error)setError(x=>x||a.error!.message);else setAgreements((a.data||[]) as Agreement[]);setLoading(false)};
 useEffect(()=>{load()},[versionId]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");setMessage("");if(!file){setError("Choose an agreement file.");return}if(scope==="employee"&&!employeeId){setError("Choose the employee this agreement belongs to.");return}setSaving(true);const path=`${versionId}/${crypto.randomUUID()}-${safeName(file.name)}`;const up=await supabase.storage.from("compensation-agreements").upload(path,file,{contentType:file.type||undefined,upsert:false});if(up.error){setSaving(false);setError(up.error.message);return}const saved=await supabase.rpc("save_comp_plan_agreement",{selected_plan_version_id:versionId,selected_employee_id:scope==="employee"?employeeId:null,selected_applies_to_everyone:scope==="everyone",selected_file_name:file.name,selected_storage_path:path,selected_mime_type:file.type||null,selected_file_size_bytes:file.size,selected_signed_at:signedAt||null,selected_notes:notes||null});if(saved.error){await supabase.storage.from("compensation-agreements").remove([path]);setSaving(false);setError(saved.error.message);return}setFile(null);setSignedAt("");setNotes("");setMessage("Agreement attached. It will also be available from the employee record.");setSaving(false);await load()};
 const openAgreement=async(a:Agreement)=>{setError("");const{data,error:e}=await supabase.storage.from("compensation-agreements").createSignedUrl(a.storage_path,60);if(e||!data?.signedUrl){setError(e?.message||"Could not open this agreement.");return}window.open(data.signedUrl,"_blank","noopener,noreferrer")};
 const removeAgreement=async(a:Agreement)=>{if(!confirm(`Remove ${a.file_name} from this draft plan?`))return;setError("");const del=await supabase.rpc("delete_comp_plan_agreement",{selected_agreement_id:a.agreement_id});if(del.error){setError(del.error.message);return}const storagePath=String(del.data?.storage_path||a.storage_path);const rm=await supabase.storage.from("compensation-agreements").remove([storagePath]);if(rm.error)setError(`The agreement record was removed, but the stored file needs cleanup: ${rm.error.message}`);await load()};
 if(loading)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-empty">Loading agreements…</div></div></main>;
 return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-breadcrumb"><Link href={`/plans?version=${versionId}`}><ArrowLeft size={15}/>Plans</Link><span>/</span><span>{plan?.name||"Plan"}</span><span>/</span><span>Signed agreements</span></div><header className="plan-page-header"><div><span className="plan-kicker">PLAN DOCUMENTS</span><h1>Signed agreements</h1><p>Attach one or more compensation agreements. Scope each file to one employee or to everyone on this plan.</p><small><b>* Required</b></small></div>{version&&<span className={`plan-status ${version.status}`}>{version.status} v{version.version_number}</span>}</header>{error&&<div className="plan-alert error">{error}</div>}{message&&<div className="plan-info-row">{message}</div>}
 {editable&&<form onSubmit={submit} className="plan-editor-card"><div className="plan-editor-heading"><div><span className="plan-step-number"><Upload size={15}/></span><div><h2>Attach an agreement</h2><p>The original file stays private. Administrators can open it from the plan and employee record.</p></div></div></div><div className="plan-form-grid two"><label>Agreement file *<input type="file" accept=".pdf,.docx,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]||null)} required/><small>PDF, Word, PNG or JPG. Maximum 15 MB.</small></label><label>Who does this agreement cover? *<select value={scope} onChange={e=>setScope(e.target.value as "employee"|"everyone")}><option value="employee">One employee</option><option value="everyone">Everyone on this plan</option></select></label>{scope==="employee"&&<label>Employee *<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)} required><option value="">Choose employee…</option>{employees.map(e=><option key={e.employee_id} value={e.employee_id}>{e.employee_name} · {e.email}</option>)}</select></label>}<label>Signed date<input type="date" value={signedAt} onChange={e=>setSignedAt(e.target.value)}/></label></div><label className="plan-full-field">Notes<textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional note about this agreement or amendment."/></label><div className="plan-actions"><button className="plan-button primary" type="submit" disabled={saving}><Plus size={15}/>{saving?"Uploading…":"Attach agreement"}</button></div></form>}
 <section className="plan-section" style={{marginTop:16}}><div className="plan-section-title"><div><h3>Agreements on this plan</h3><p>{agreements.length} file{agreements.length===1?"":"s"}. Employee-specific files are shown only for that person; plan-wide files apply to everyone.</p></div><FileText size={18}/></div>{agreements.length?agreements.map(a=><div key={a.agreement_id} style={{display:"grid",gridTemplateColumns:"1fr auto auto",gap:12,alignItems:"center",padding:"12px 0",borderTop:"1px solid #e6e8ec"}}><div><b>{a.file_name}</b><div style={{fontSize:12,color:"#667085",marginTop:3}}>{a.applies_to_everyone?"Everyone on this plan":a.employee_name||"Employee"}{a.signed_at?` · signed ${a.signed_at}`:""}{a.file_size_bytes?` · ${prettySize(a.file_size_bytes)}`:""}</div>{a.notes&&<div style={{fontSize:12,color:"#475467",marginTop:4}}>{a.notes}</div>}</div><button className="plan-button secondary" onClick={()=>openAgreement(a)}><Download size={14}/>Open</button>{editable&&<button className="plan-button secondary" onClick={()=>removeAgreement(a)} aria-label={`Remove ${a.file_name}`}><Trash2 size={14}/></button>}</div>):<div className="plan-empty">No agreements have been attached yet.</div>}</section>
 </div></main>;
}
