"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,ArrowRight,Download,FileText,Plus,Trash2,Upload} from "lucide-react";
import PlanBuilderProgress from "../../components/plan-builder-progress";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Employee={employee_id:string;employee_name:string;email:string};type Assignment={employee_id:string;employee_name:string};type PlanVersion={version_id:string;version_number:number;status:string;assignments?:Assignment[];draft_assignments?:Assignment[]};type Plan={plan_id:string;name:string;plan_code:string;versions:PlanVersion[]};type Agreement={agreement_id:string;employee_id:string|null;employee_name:string|null;applies_to_everyone:boolean;file_name:string;storage_path:string;mime_type:string|null;file_size_bytes:number|null;signed_at:string|null;notes:string|null;created_at:string};
const safeName=(name:string)=>name.replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-").slice(-120);const prettySize=(bytes:number|null)=>bytes==null?"":bytes<1024*1024?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/(1024*1024)).toFixed(1)} MB`;const MAX_FILE_BYTES=15*1024*1024;

export default function PlanAgreementsPage(){
 const params=useParams<{versionId:string}>();const router=useRouter();const versionId=params.versionId;
 const[plans,setPlans]=useState<Plan[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[agreements,setAgreements]=useState<Agreement[]>([]);const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const[file,setFile]=useState<File|null>(null),[scope,setScope]=useState<"employee"|"everyone">("employee"),[employeeId,setEmployeeId]=useState(""),[signedAt,setSignedAt]=useState(""),[notes,setNotes]=useState("");
 const plan=useMemo(()=>plans.find(p=>p.versions.some(v=>v.version_id===versionId)),[plans,versionId]);const version=plan?.versions.find(v=>v.version_id===versionId);const editable=version?.status==="draft";const assignedIds=useMemo(()=>new Set(((editable?version?.draft_assignments:version?.assignments)||[]).map(a=>a.employee_id)),[editable,version]);const assignedEmployees=useMemo(()=>employees.filter(e=>assignedIds.has(e.employee_id)),[employees,assignedIds]);
 const load=async()=>{setLoading(true);setError("");const[p,a]=await Promise.all([supabase.rpc("get_compensation_plan_admin_data"),supabase.rpc("get_comp_plan_agreements",{selected_plan_version_id:versionId})]);if(p.error)setError(p.error.message);else{setPlans((p.data?.plans||[]) as Plan[]);setEmployees((p.data?.employees||[]) as Employee[])}if(a.error)setError(x=>x||a.error!.message);else setAgreements((a.data||[]) as Agreement[]);setLoading(false)};
 useEffect(()=>{void load()},[versionId]);useEffect(()=>{if(scope==="employee"&&employeeId&&!assignedIds.has(employeeId))setEmployeeId("")},[assignedIds,employeeId,scope]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");setMessage("");if(!file){setError("Choose an agreement file.");return}if(file.size>MAX_FILE_BYTES){setError("Agreement files must be 15 MB or smaller.");return}if(scope==="employee"&&!employeeId){setError("Choose an employee who is assigned to this plan.");return}setSaving(true);const path=`${versionId}/${crypto.randomUUID()}-${safeName(file.name)}`;const up=await supabase.storage.from("compensation-agreements").upload(path,file,{contentType:file.type||undefined,upsert:false});if(up.error){setSaving(false);setError("We couldn't upload that agreement. Please try again.");return}const saved=await supabase.rpc("save_comp_plan_agreement",{selected_plan_version_id:versionId,selected_employee_id:scope==="employee"?employeeId:null,selected_applies_to_everyone:scope==="everyone",selected_file_name:file.name,selected_storage_path:path,selected_mime_type:file.type||null,selected_file_size_bytes:file.size,selected_signed_at:signedAt||null,selected_notes:notes||null});if(saved.error){await supabase.storage.from("compensation-agreements").remove([path]);setSaving(false);setError("The file uploaded, but the agreement could not be attached to this plan.");return}setFile(null);setSignedAt("");setNotes("");setEmployeeId("");setMessage("Agreement saved.");setSaving(false);await load()};
 const openAgreement=async(a:Agreement)=>{const{data,error:e}=await supabase.storage.from("compensation-agreements").createSignedUrl(a.storage_path,60);if(e||!data?.signedUrl){setError("Could not open this agreement.");return}window.open(data.signedUrl,"_blank","noopener,noreferrer")};
 const removeAgreement=async(a:Agreement)=>{if(!confirm(`Remove ${a.file_name} from this draft plan?`))return;const del=await supabase.rpc("delete_comp_plan_agreement",{selected_agreement_id:a.agreement_id});if(del.error){setError("We couldn't remove that agreement.");return}await supabase.storage.from("compensation-agreements").remove([String(del.data?.storage_path||a.storage_path)]);await load()};
 if(loading)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-empty">Loading agreements…</div></div></main>;
 return <main className="plan-workspace"><div className="plan-page-shell">
  <div className="plan-breadcrumb"><Link href="/plans"><ArrowLeft size={15}/>Plans</Link><span>/</span><span>{plan?.name||"Plan"}</span></div>
  <PlanBuilderProgress versionId={versionId} current="agreements" completed={{basics:true,people:assignedIds.size>0,earnings:true,agreements:agreements.length>0}}/>
  <header className="plan-page-header"><div><span className="plan-kicker">STEP 4 OF 6</span><h1>Agreements</h1><p>Attach the signed compensation agreement or amendment that governs this plan. You can use one plan-wide agreement or employee-specific files.</p></div>{version&&<span className={`plan-status ${version.status}`}>{version.status} v{version.version_number}</span>}</header>
  {error&&<div className="plan-alert error">{error}</div>}{message&&<div className="plan-info-row">{message}</div>}
  {editable&&<form onSubmit={submit} className="plan-editor-card"><div className="plan-editor-heading"><div><span className="plan-step-number"><Upload size={15}/></span><div><h2>Attach agreement</h2><p>The file remains private and is available from the plan and employee record.</p></div></div></div>{assignedEmployees.length===0&&<div className="plan-alert warning">No one is assigned to this plan yet. Go back to Who it applies to before attaching an employee-specific agreement.</div>}<div className="plan-form-grid two"><label>Agreement file *<input type="file" accept=".pdf,.docx,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]||null)} required/><small>PDF, Word, PNG or JPG. Maximum 15 MB.</small></label><label>Who does it cover? *<select value={scope} onChange={e=>{setScope(e.target.value as "employee"|"everyone");setEmployeeId("")}}><option value="employee">One employee</option><option value="everyone">Everyone on this plan</option></select></label>{scope==="employee"&&<label>Employee *<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)} required disabled={assignedEmployees.length===0}><option value="">Choose assigned employee…</option>{assignedEmployees.map(e=><option key={e.employee_id} value={e.employee_id}>{e.employee_name}</option>)}</select></label>}<label>Signed date<input type="date" value={signedAt} onChange={e=>setSignedAt(e.target.value)}/></label></div><label className="plan-full-field">Notes<textarea rows={2} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional"/></label><div className="plan-actions"><button className="plan-button secondary" type="submit" disabled={saving||(scope==="employee"&&assignedEmployees.length===0)}><Plus size={15}/>{saving?"Uploading…":"Save agreement"}</button></div></form>}
  <section className="plan-step-card"><div className="plan-step-card__head"><div><h3>Agreements on this plan</h3><p>{agreements.length} file{agreements.length===1?"":"s"} attached.</p></div><FileText size={18}/></div>{agreements.length?agreements.map(a=><div key={a.agreement_id} style={{display:"grid",gridTemplateColumns:"1fr auto auto",gap:10,alignItems:"center",padding:"10px 0",borderTop:"1px solid #e6e8ec"}}><div><b>{a.file_name}</b><div style={{fontSize:11.5,color:"#667085",marginTop:2}}>{a.applies_to_everyone?"Everyone on this plan":a.employee_name||"Employee"}{a.signed_at?` · signed ${a.signed_at}`:""}{a.file_size_bytes?` · ${prettySize(a.file_size_bytes)}`:""}</div></div><button className="plan-button secondary" onClick={()=>void openAgreement(a)}><Download size={14}/>Open</button>{editable&&<button className="plan-button secondary" onClick={()=>void removeAgreement(a)} aria-label={`Remove ${a.file_name}`}><Trash2 size={14}/></button>}</div>):<div className="plan-empty">No agreement attached yet.</div>}</section>
  <div className="plan-wizard-actions"><Link className="plan-button secondary" href={`/plans/manage/${versionId}#earning-types`}><ArrowLeft size={15}/>Back</Link><div className="plan-wizard-actions__right"><button type="button" className="plan-button brand" disabled={!agreements.length} onClick={()=>router.push(`/plans/manage/${versionId}/approvals`)}>Next step<ArrowRight size={15}/></button></div></div>
 </div></main>;
}
