"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,Braces,Plus,Save,Trash2} from "lucide-react";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Obj={object_type:string;display_name:string};type Field={object_type:string;property_name:string;display_name:string;data_type:string};type Op={operator_key:string;display_name:string;value_arity:string;supported_data_types:string[]};
type Comp={component_id:string;name:string;component_code:string};type Plan={name:string;versions:{status:string;components:Comp[]}[]};
type Rule={id:string,key:string,name:string,objectType:string,property:string,operator:string,value:string};
type RuleNode={id:string;type:"rule";ruleId:string;negate:boolean};type GroupNode={id:string;type:"group";op:"AND"|"OR";negate:boolean;children:(RuleNode|GroupNode)[]};type Node=RuleNode|GroupNode;
const uid=()=>Math.random().toString(36).slice(2,10);const box={background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:14} as const;
function blankRule(n:number):Rule{return{id:uid(),key:`rule_${n}`,name:`Rule ${n}`,objectType:"deal",property:"dealtype",operator:"is",value:""}}
function expressionText(node:Node,rules:Rule[]):string{if(node.type==="rule"){const r=rules.find(x=>x.id===node.ruleId);return `${node.negate?"NOT ":""}${r?.name||"Unassigned rule"}`}const inner=node.children.map(x=>expressionText(x,rules)).join(` ${node.op} `)||"(empty)";return `${node.negate?"NOT ":""}(${inner})`}
function GroupEditor({node,rules,onChange,isRoot=false}:{node:GroupNode;rules:Rule[];onChange:(n:GroupNode)=>void;isRoot?:boolean}){const patchChild=(id:string,next:Node)=>onChange({...node,children:node.children.map(c=>c.id===id?next:c)});const remove=(id:string)=>onChange({...node,children:node.children.filter(c=>c.id!==id)});return <div style={{border:"1px solid #d7e1eb",borderRadius:10,padding:12,background:isRoot?"#f8fbfe":"white",marginTop:8}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><b>{isRoot?"Root group":"Group"}</b><select value={node.op} onChange={e=>onChange({...node,op:e.target.value as "AND"|"OR"})}><option>AND</option><option>OR</option></select><label><input type="checkbox" checked={node.negate} onChange={e=>onChange({...node,negate:e.target.checked})}/> NOT this group</label><button onClick={()=>onChange({...node,children:[...node.children,{id:uid(),type:"rule",ruleId:rules[0]?.id||"",negate:false}]})}>+ Rule reference</button><button onClick={()=>onChange({...node,children:[...node.children,{id:uid(),type:"group",op:"AND",negate:false,children:[]}]})}>+ Group</button></div>{node.children.map(child=>child.type==="group"?<div key={child.id} style={{marginLeft:18}}><GroupEditor node={child} rules={rules} onChange={n=>patchChild(child.id,n)}/><button onClick={()=>remove(child.id)} style={{fontSize:12}}>Remove group</button></div>:<div key={child.id} style={{display:"flex",gap:8,alignItems:"center",padding:"9px 0 0 18px",flexWrap:"wrap"}}><span style={{fontWeight:800,color:"#647184"}}>{node.op}</span><select value={child.ruleId} onChange={e=>patchChild(child.id,{...child,ruleId:e.target.value})}>{rules.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><label><input type="checkbox" checked={child.negate} onChange={e=>patchChild(child.id,{...child,negate:e.target.checked})}/> NOT</label><button onClick={()=>remove(child.id)} aria-label="remove"><Trash2 size={14}/></button></div>)}</div>}
export default function RuleBuilder(){const[plans,setPlans]=useState<Plan[]>([]),[objects,setObjects]=useState<Obj[]>([]),[fields,setFields]=useState<Field[]>([]),[ops,setOps]=useState<Op[]>([]),[component,setComponent]=useState(""),[name,setName]=useState("Qualification rules"),[purpose,setPurpose]=useState("qualification"),[rules,setRules]=useState<Rule[]>([blankRule(1)]),[root,setRoot]=useState<GroupNode>({id:"root",type:"group",op:"AND",negate:false,children:[]}),[message,setMessage]=useState(""),[error,setError]=useState("");
useEffect(()=>{(async()=>{const p=await supabase.rpc("get_compensation_plan_admin_data");if(!p.error){const ps=(p.data?.plans||[]) as Plan[];setPlans(ps);const first=ps.flatMap(x=>x.versions.flatMap(v=>v.components))[0];if(first)setComponent(first.component_id)}const c=await supabase.rpc("get_comp_rule_builder_catalog",{target_plan_component_id:null});if(c.error)setError(c.error.message);else{setObjects(c.data?.objects||[]);setFields(c.data?.fields||[]);setOps(c.data?.operators||[])}})()},[]);
const components=useMemo(()=>plans.flatMap(p=>p.versions.flatMap(v=>v.components.map(c=>({...c,plan:p.name,status:v.status})))),[plans]);
const updateRule=(id:string,patch:Partial<Rule>)=>setRules(rs=>rs.map(r=>r.id===id?{...r,...patch}:r));const removeRule=(id:string)=>{setRules(rs=>rs.filter(r=>r.id!==id));const scrub=(n:GroupNode):GroupNode=>({...n,children:n.children.filter(c=>c.type!=="rule"||c.ruleId!==id).map(c=>c.type==="group"?scrub(c):c)});setRoot(scrub(root))};
const flatten=(g:GroupNode,parent:string|null=null,out:any[]=[]):any[]=>{out.push({client_key:g.id,parent_client_key:parent,node_type:"group",logical_operator:g.op,negate:g.negate,sort_order:out.length});g.children.forEach((c,i)=>{if(c.type==="group")flatten(c,g.id,out);else out.push({client_key:c.id,parent_client_key:g.id,node_type:"predicate",predicate_client_key:c.ruleId,negate:c.negate,sort_order:i})});return out};
const save=async()=>{setError("");setMessage("");if(!component){setError("Choose a plan component.");return}if(root.children.length===0){setError("Add at least one rule reference to the expression.");return}const predicates=rules.map(r=>({client_key:r.id,rule_key:r.key,display_name:r.name,object_type:r.objectType,property_name:r.property,operator_key:r.operator,comparison_value:ops.find(o=>o.operator_key===r.operator)?.value_arity==="none"?null:r.value,comparison_value_type:fields.find(f=>f.object_type===r.objectType&&f.property_name===r.property)?.data_type||"string",association_path:[],association_quantifier:r.objectType==="deal"?"record":"any"}));const{error:e}=await supabase.rpc("save_comp_rule_set",{payload:{plan_component_id:component,name,purpose,evaluation_scope:"record",predicates,nodes:flatten(root)}});if(e)setError(e.message);else setMessage("Rule set saved.")};
return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1300,margin:"0 auto"}}><Link href="/plans" style={{color:"#647184",fontWeight:700,textDecoration:"none"}}><ArrowLeft size={15}/> Plans</Link><div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"start",margin:"12px 0 18px"}}><div><small style={{fontWeight:900,color:"#2095f3",letterSpacing:1}}>PLAN RULE ENGINE</small><h1 style={{margin:"5px 0"}}>Rule builder</h1><p style={{margin:0,color:"#647184"}}>Build reusable HubSpot predicates and combine them into nested AND / OR / NOT logic.</p></div><button onClick={save} style={{background:"#2095f3",color:"white",border:0,borderRadius:9,padding:"10px 14px",fontWeight:800}}><Save size={16}/> Save rule set</button></div>{error&&<div style={{...box,background:"#fff1f1",marginBottom:12}}>{error}</div>}{message&&<div style={{...box,background:"#edf9f2",marginBottom:12}}>{message}</div>}
<section style={{...box,display:"grid",gridTemplateColumns:"2fr 1fr 1fr",gap:10,marginBottom:14}}><label>Plan component<select value={component} onChange={e=>setComponent(e.target.value)} style={{display:"block",width:"100%",marginTop:5}}>{components.map(c=><option key={c.component_id} value={c.component_id}>{c.plan} · {c.name} ({c.status})</option>)}</select></label><label>Rule-set name<input value={name} onChange={e=>setName(e.target.value)} style={{display:"block",width:"100%",marginTop:5}}/></label><label>Purpose<select value={purpose} onChange={e=>setPurpose(e.target.value)} style={{display:"block",width:"100%",marginTop:5}}>{["qualification","rate_selection","calculation","eligibility","credit","payout","exception"].map(x=><option key={x}>{x}</option>)}</select></label></section>
<section style={{...box,marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h2 style={{margin:"0 0 3px"}}>1. Define reusable rules</h2><small style={{color:"#647184"}}>Each rule is an atomic HubSpot filter: object → field → operator → value.</small></div><button onClick={()=>setRules(r=>[...r,blankRule(r.length+1)])}><Plus size={15}/> Add rule</button></div><div style={{display:"grid",gap:9,marginTop:12}}>{rules.map((r,i)=>{const availableFields=fields.filter(f=>f.object_type===r.objectType);const fieldType=availableFields.find(f=>f.property_name===r.property)?.data_type;const availableOps=ops.filter(o=>!fieldType||o.supported_data_types.includes(fieldType));const arity=ops.find(o=>o.operator_key===r.operator)?.value_arity;return <div key={r.id} style={{border:"1px solid #e3e9ef",borderRadius:10,padding:10,display:"grid",gridTemplateColumns:"150px 130px minmax(180px,1fr) 170px minmax(150px,1fr) 36px",gap:8,alignItems:"end"}}><label>Name<input value={r.name} onChange={e=>updateRule(r.id,{name:e.target.value,key:`rule_${i+1}`})}/></label><label>HubSpot object<select value={r.objectType} onChange={e=>updateRule(r.id,{objectType:e.target.value,property:""})}>{objects.map(o=><option key={o.object_type} value={o.object_type}>{o.display_name}</option>)}</select></label><label>Field<select value={r.property} onChange={e=>updateRule(r.id,{property:e.target.value})}><option value="">Choose field…</option>{availableFields.map(f=><option key={f.property_name} value={f.property_name}>{f.display_name}</option>)}</select><input placeholder="or property internal name" value={r.property} onChange={e=>updateRule(r.id,{property:e.target.value})}/></label><label>Operator<select value={r.operator} onChange={e=>updateRule(r.id,{operator:e.target.value})}>{availableOps.map(o=><option key={o.operator_key} value={o.operator_key}>{o.display_name}</option>)}</select></label><label>Value{arity==="none"?<div style={{padding:"8px",color:"#718096"}}>No value needed</div>:<input value={r.value} onChange={e=>updateRule(r.id,{value:e.target.value})} placeholder={arity==="multiple"?"value1, value2":"Value"}/>}</label><button onClick={()=>removeRule(r.id)}><Trash2 size={15}/></button></div>})}</div></section>
<section style={{...box,marginBottom:14}}><h2 style={{margin:"0 0 3px"}}>2. Build the logic expression</h2><small style={{color:"#647184"}}>Groups can be nested indefinitely, switched between AND/OR, and negated. A rule can be referenced more than once.</small><GroupEditor node={root} rules={rules} onChange={setRoot} isRoot/></section>
<section style={{...box,background:"#051b34",color:"white"}}><div style={{display:"flex",gap:8,alignItems:"center"}}><Braces size={18}/><b>Expression preview</b></div><code style={{display:"block",marginTop:10,whiteSpace:"pre-wrap",color:"#badefa"}}>{expressionText(root,rules)}</code><p style={{margin:"10px 0 0",fontSize:13,color:"#c5d2df"}}>Example supported: (Rule 1 AND Rule 2) OR (Rule 1 AND NOT Rule 3).</p></section></div></main>}
