"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,ArrowLeft,CheckCircle2,Clock3,RefreshCw,Search} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Earning={earning_id:string;employee_name:string;earning_name:string;source_external_id:string|null;earned_date:string|null;earned_amount:number;eligibility_status:string;eligible_amount:number;employee_verification_status:string;manager_approval_status:string;executive_approval_status:string;payment_status:string;paid_amount:number;hold_reason:string|null;expected_payment_date:string|null;expected_pay_period_label:string|null;reconciliation_status:string|null;source_match_status:string|null;updated_at:string;};
type Payload={summary:{awaiting_approval:number;payment_exceptions:number};earnings:Earning[]};
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function label(v:string|null|undefined){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function issue(e:Earning){if(e.hold_reason||["held","error"].includes(e.payment_status))return {type:"Payment issue",detail:e.hold_reason||`Payment status is ${label(e.payment_status)}`,priority:1};if(e.source_match_status&&!["matched","verified","ok"].includes(e.source_match_status))return {type:"Source issue",detail:`Source match: ${label(e.source_match_status)}`,priority:2};if(e.reconciliation_status&&!["reconciled","complete","matched","not_required"].includes(e.reconciliation_status))return {type:"Reconciliation",detail:`Reconciliation: ${label(e.reconciliation_status)}`,priority:3};if(["returned","rejected"].includes(e.manager_approval_status)||["returned","rejected"].includes(e.executive_approval_status))return {type:"Returned approval",detail:"Approval requires review or correction",priority:2};if(e.eligibility_status==="eligible"&&e.payment_status==="not_payable")return {type:"Readiness mismatch",detail:"Eligible earning is still marked not payable",priority:2};return null}

export default function AttentionPage(){
  const[data,setData]=useState<Payload>({summary:{awaiting_approval:0,payment_exceptions:0},earnings:[]});
  const[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState("");
  const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const{data:result,error:rpcError}=await supabase.rpc("get_admin_earnings_data");if(rpcError)setError(rpcError.message);else setData((result||data) as Payload);setLoading(false)};
  useEffect(()=>{load()},[]);
  const waiting=useMemo(()=>data.earnings.filter(e=>e.eligibility_status!=="eligible"&&!["paid"].includes(e.payment_status)),[data.earnings]);
  const issues=useMemo(()=>data.earnings.map(e=>({earning:e,issue:issue(e)})).filter(x=>x.issue).sort((a,b)=>(a.issue?.priority||9)-(b.issue?.priority||9)).filter(x=>!query||`${x.earning.employee_name} ${x.earning.earning_name} ${x.earning.source_external_id||""} ${x.issue?.type||""}`.toLowerCase().includes(query.toLowerCase())),[data.earnings,query]);
  return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1250,margin:"0 auto"}}>
    <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:22,flexWrap:"wrap"}}><div><Link href="/manage" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700,fontSize:13}}><ArrowLeft size={15}/>Management</Link><small style={{display:"block",fontWeight:800,letterSpacing:1.1,color:"#2095f3",marginTop:12}}>OPERATIONS QUEUE</small><h1 style={{fontSize:34,margin:"6px 0"}}>Needs attention</h1><p style={{margin:0,color:"#647184"}}>Only items that need a human decision, correction, or follow-up belong here. Normal waiting states remain separate.</p></div><button onClick={load} disabled={loading} style={{display:"flex",gap:7,alignItems:"center",padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:700}}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>
    {error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}
    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:10,marginBottom:18}}><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small style={{fontWeight:800,color:"#718096"}}>Needs human attention</small><b style={{display:"block",fontSize:26,margin:"5px 0"}}>{loading?"—":issues.length}</b><span style={{color:"#647184"}}>Errors, holds, mismatches, returns</span></div><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small style={{fontWeight:800,color:"#718096"}}>Awaiting approval</small><b style={{display:"block",fontSize:26,margin:"5px 0"}}>{loading?"—":data.summary.awaiting_approval}</b><span style={{color:"#647184"}}>Normal workflow, not necessarily an exception</span></div><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small style={{fontWeight:800,color:"#718096"}}>Waiting</small><b style={{display:"block",fontSize:26,margin:"5px 0"}}>{loading?"—":waiting.length}</b><span style={{color:"#647184"}}>Prerequisite not yet satisfied</span></div></section>
    <label style={{display:"block",position:"relative",marginBottom:14}}><Search size={17} style={{position:"absolute",left:11,top:11,color:"#8b98a8"}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search exceptions" style={{width:"100%",boxSizing:"border-box",padding:"10px 12px 10px 36px",border:"1px solid #d6dee8",borderRadius:9}}/></label>
    {issues.length===0?<section style={{background:"white",border:"1px dashed #cbd5df",borderRadius:14,padding:34,textAlign:"center"}}><CheckCircle2 size={30}/><h2>No items need attention</h2><p style={{color:"#647184"}}>Normal waiting and approval states stay out of this queue.</p></section>:<section style={{display:"grid",gap:10}}>{issues.map(({earning:e,issue:i})=><article key={e.earning_id} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:16,display:"grid",gridTemplateColumns:"auto 1.2fr 1.7fr .8fr",gap:12,alignItems:"center"}}><span style={{width:36,height:36,borderRadius:10,display:"grid",placeItems:"center",background:i?.priority===1?"#fff2e6":"#fff8e7",color:"#a65b00"}}><AlertTriangle size={18}/></span><div><b>{e.employee_name}</b><small style={{display:"block",color:"#718096",marginTop:3}}>{e.earned_date||"No earned date"}</small></div><div><b>{i?.type}</b><small style={{display:"block",color:"#647184",marginTop:3}}>{e.earning_name} · {i?.detail}</small></div><div style={{textAlign:"right"}}><b>{money(e.eligible_amount||e.earned_amount)}</b><small style={{display:"block",color:"#718096",marginTop:3}}>{label(e.payment_status)}</small></div></article>)}</section>}
    <section style={{marginTop:18,background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:16}}><div style={{display:"flex",gap:9,alignItems:"flex-start"}}><Clock3 size={18}/><div><b>Waiting is not an error</b><p style={{margin:"4px 0 0",color:"#647184"}}>An earning waiting for customer payment or another normal eligibility prerequisite should remain visible in Earnings, but it should not clutter this exception queue unless something actually requires human intervention.</p></div></div></section>
  </div></main>
}
