"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,ArrowRight,Plus,Save,Trash2} from "lucide-react";
import PlanBuilderProgress from "../../../components/plan-builder-progress";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Approver={employee_id:string;full_name:string;email:string|null;user_id:string|null;provisioning_status:string};
type Step={id?:string;approval_order:number;step_name:string;approval_level:string;approver_employee_id:string;approver_name?:string|null;backup_approver_employee_id?:string|null;backup_approver_name?:string|null;is_required:boolean;conditions?:any};
type Plan={plan_id:string;name:string;versions:{version_id:string;version_number:number;status:string}[]};
const blank=(order:number):Step=>({approval_order:order,step_name:`Approval ${order}`,approval_level:"manager",approver_employee_id:"",backup_approver_employee_id:null,is_required:true,conditions:{notify_when:"turn"}});

export default function PlanApprovalsPage(){
 const params=useParams<{versionId:string}>();const router=useRouter();
 const[steps,setSteps]=useState<Step[]>([]),[approvers,setApprovers]=useState<Approver[]>([]),[plans,setPlans]=useState<Plan[]>([]);const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[dirty,setDirty]=useState(false);
 async function load(){setLoading(true);setError("");const[cfg,admin,planData]=await Promise.all([supabase.rpc("get_comp_plan_approval_configuration",{selected_plan_version_id:params.versionId}),supabase.rpc("get_approval_workflow_admin_data"),supabase.rpc("get_compensation_plan_admin_data")]);if(cfg.error||admin.error||planData.error){setError("We couldn't load the approval workflow.");setLoading(false);return}const existing=(cfg.data?.steps||[]) as Step[];setSteps(existing.map((s,i)=>({...s,approval_order:i+1,conditions:s.conditions||{notify_when:"turn"}})));setApprovers((admin.data?.eligible_approvers||[]) as Approver[]);setPlans((planData.data?.plans||[]) as Plan[]);setDirty(false);setLoading(false)}
 useEffect(()=>{void load()},[params.versionId]);useEffect(()=>{document.body.dataset.planDirty=dirty?"true":"false";const onBeforeUnload=(e:BeforeUnloadEvent)=>{if(!dirty)return;e.preventDefault();e.returnValue=""};window.addEventListener("beforeunload",onBeforeUnload);return()=>{delete document.body.dataset.planDirty;window.removeEventListener("beforeunload",onBeforeUnload)}},[dirty]);
 const plan=useMemo(()=>plans.find(p=>p.versions.some(v=>v.version_id===params.versionId))||null,[plans,params.versionId]);const version=plan?.versions.find(v=>v.version_id===params.versionId)||null;const editable=version?.status==="draft";const requiredCount=steps.filter(s=>s.is_required).length;
 const change=(index:number,patch:Partial<Step>)=>{setSteps(v=>v.map((s,i)=>i===index?{...s,...patch}:s));setDirty(true);setMessage("")};const remove=(index:number)=>{setSteps(v=>v.filter((_,i)=>i!==index).map((s,i)=>({...s,approval_order:i+1})));setDirty(true)};const add=()=>{setSteps(v=>[...v,blank(v.length+1)]);setDirty(true)};
 const save=async()=>{if(!editable){setError("Only draft plans can change approvals.");return false}if(steps.some(s=>!s.approver_employee_id)){setError("Choose an approver for every step.");return false}if(requiredCount===0){setError("At least one approval step must be Required.");return false}setSaving(true);setError("");const payload=steps.map((s,i)=>({approval_order:i+1,step_name:s.step_name.trim()||`Approval ${i+1}`,approval_level:s.approval_level||"manager",approver_employee_id:s.approver_employee_id,backup_approver_employee_id:s.backup_approver_employee_id||null,is_required:s.is_required,conditions:s.conditions||{}}));const{error:e}=await supabase.rpc("save_comp_plan_approval_configuration",{selected_plan_version_id:params.versionId,selected_steps:payload});setSaving(false);if(e){setError("We couldn't save the approval workflow. Your changes are still here.");return false}setDirty(false);setMessage("Approval workflow saved.");await load();return true};
 const next=async()=>{if(dirty){const ok=await save();if(!ok)return}router.push(`/plans/manage/${params.versionId}/review`)};
 if(loading)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-empty">Loading approval workflow…</div></div></main>;
 return <main className="plan-workspace"><div className="plan-page-shell" style={{paddingBottom:90}}>
  <div className="plan-breadcrumb"><Link href="/plans"><ArrowLeft size={15}/>Plans</Link><span>/</span><span>{plan?.name||"Plan"}</span></div>
  <PlanBuilderProgress versionId={params.versionId} current="approvals" completed={{basics:true,people:true,earnings:true,agreements:true,approvals:requiredCount>0}} onNavigate={href=>{if(dirty){window.alert("Use Next step or Save approvals before leaving this step.");return}router.push(href)}}/>
  <header className="plan-page-header"><div><span className="plan-kicker">STEP 5 OF 6</span><h1>Approval workflow</h1><p>Choose who reviews compensation and in what order. Required steps block progression. Optional steps are advisory and should not prevent the next required step from moving forward.</p></div>{version&&<span className={`plan-status ${version.status}`}>{version.status} v{version.version_number}</span>}</header>
  {error&&<div className="plan-alert error">{error}</div>}{message&&<div className="plan-info-row">{message}</div>}
  <section className="plan-step-card"><div className="plan-step-card__head"><div><h2>Approval sequence</h2><p>Example: Sharon = Required, Namit = Optional, Scott = Required. Optional steps can be notified without blocking payment progression.</p></div>{editable&&<button type="button" className="plan-button secondary" onClick={add}><Plus size={14}/>Add step</button>}</div>
   {!steps.length&&<div className="plan-empty">No approval steps yet. Add at least one Required step.</div>}
   {steps.map((s,i)=><div key={s.id||i} style={{display:"grid",gridTemplateColumns:"44px minmax(150px,1fr) minmax(190px,1.2fr) 130px 150px auto",gap:10,alignItems:"end",borderTop:"1px solid #eef1f4",padding:"12px 0"}}><div style={{fontWeight:800,fontSize:17,textAlign:"center",paddingBottom:9}}>{i+1}</div><label>Step name<input value={s.step_name} disabled={!editable} onChange={e=>change(i,{step_name:e.target.value})}/></label><label>Approver *<select value={s.approver_employee_id||""} disabled={!editable} onChange={e=>change(i,{approver_employee_id:e.target.value})}><option value="">Choose approver</option>{approvers.map(a=><option key={a.employee_id} value={a.employee_id}>{a.full_name}</option>)}</select></label><label>Type<select value={s.is_required?"required":"optional"} disabled={!editable} onChange={e=>change(i,{is_required:e.target.value==="required"})}><option value="required">Required</option><option value="optional">Optional</option></select></label><label>Notify<select value={s.conditions?.notify_when||"turn"} disabled={!editable} onChange={e=>change(i,{conditions:{...(s.conditions||{}),notify_when:e.target.value}})}><option value="turn">When it reaches this step</option><option value="immediate">When submitted</option></select></label>{editable&&<button type="button" className="plan-button secondary" onClick={()=>remove(i)} aria-label={`Remove approval step ${i+1}`}><Trash2 size={14}/></button>}</div>)}
   {editable&&<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginTop:16,flexWrap:"wrap"}}><span style={{fontSize:12,color:dirty?"#9a6700":"#667085"}}>{dirty?"Unsaved changes":`${requiredCount} required · ${steps.length-requiredCount} optional`}</span><button type="button" className="plan-button secondary" disabled={saving||!dirty} onClick={()=>void save()}><Save size={14}/>{saving?"Saving…":"Save approvals"}</button></div>}
  </section>
  <div className="plan-info-row"><b>Optional means non-blocking.</b>&nbsp;The runtime notification/skip behavior is being completed with the Plan Builder V2 backend so an optional reviewer can be informed without holding the next required step.</div>
  <div className="plan-wizard-actions"><Link className="plan-button secondary" href={`/plans/agreements/${params.versionId}`}><ArrowLeft size={15}/>Back</Link><div className="plan-wizard-actions__right"><button type="button" className="plan-button brand" disabled={!steps.length||requiredCount===0||saving} onClick={()=>void next()}>{saving?"Saving…":"Next step"}<ArrowRight size={15}/></button></div></div>
 </div></main>;
}
