"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@supabase/supabase-js";
import { AlertTriangle, ChevronRight, RefreshCw, Search, ShieldCheck, UserPlus, Users } from "lucide-react";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "";
const supabase = supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;

type EmployeeAdminRecord = {
  employee_id: string; full_name: string; email?: string|null; title?: string|null; department?: string|null; manager_name?: string|null; is_active?: boolean;
  profile_status?: string|null; has_app_access?: boolean; draft_user_id?: string|null; draft_status?: string|null; draft_roles?: string[]|null;
  compensation_participant?: boolean; plan_name?: string|null; plan_status?: string|null; plan_effective_start_date?: string|null; plan_effective_end_date?: string|null;
  earnings_eligibility_date?: string|null; workflow_name?: string|null; workflow_status?: string|null; readiness?: string|null; readiness_reasons?: string[]|null;
};

function badge(label:string,tone:"good"|"warn"|"muted"|"info"="muted"){return <span className={`employee-admin-badge ${tone}`}>{label}</span>}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"—"}
function roleLabel(role:string){return role.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}

export default function EmployeeAdministration(){
 const[employees,setEmployees]=useState<EmployeeAdminRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[selected,setSelected]=useState<EmployeeAdminRecord|null>(null);
 const load=async()=>{if(!supabase){setError("Database connection is unavailable.");setLoading(false);return}setLoading(true);setError("");const{data,error}=await supabase.rpc("get_employee_administration_data");if(error){setError(error.message);setEmployees([])}else{const raw:any=data||{};setEmployees(Array.isArray(raw)?raw:(raw.employees||[]))}setLoading(false)};
 useEffect(()=>{load()},[]);useEffect(()=>{if(selected){const fresh=employees.find(x=>x.employee_id===selected.employee_id);if(fresh)setSelected(fresh)}},[employees]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return employees;return employees.filter(x=>[x.full_name,x.email,x.title,x.department,x.manager_name,x.plan_name,...(x.draft_roles||[])].some(v=>String(v||"").toLowerCase().includes(q)))},[employees,query]);
 const counts=useMemo(()=>({total:employees.length,access:employees.filter(x=>x.has_app_access).length,preinvite:employees.filter(x=>!x.has_app_access&&x.draft_user_id).length,compParticipants:employees.filter(x=>x.compensation_participant).length,plansReady:employees.filter(x=>x.compensation_participant&&x.plan_name).length,workflowsReady:employees.filter(x=>x.compensation_participant&&x.workflow_name).length}),[employees]);
 return <div className="employee-admin">
  <div className="title employee-admin-title"><div><h1>People & Access</h1><p>Employees and application access are related, but intentionally separate. Manage both from one directory.</p></div><div className="employee-admin-actions"><button className="secondary" onClick={load} disabled={loading}><RefreshCw/>Refresh</button><a className="primary" href="/user-administration"><UserPlus/>Add employee</a></div></div>
  <div className="employee-admin-stats"><article><small>EMPLOYEE RECORDS</small><b>{counts.total}</b><span>People represented in the organization</span></article><article><small>APP ACCESS</small><b>{counts.access}</b><span>{counts.preinvite} additional pre-invite configured</span></article><article><small>COMP PLANS READY</small><b>{counts.plansReady}/{counts.compParticipants}</b><span>Compensation participants with plan</span></article><article><small>WORKFLOW READY</small><b>{counts.workflowsReady}/{counts.compParticipants}</b><span>Compensation participants with routing</span></article></div>
  <section className="card employee-admin-card"><div className="employee-admin-toolbar"><div><Users/><span><b>People directory</b><small>Employment, access, compensation participation, and operational readiness</small></span></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people, roles, plans..."/></label></div>
  {error&&<div className="employee-admin-warning"><AlertTriangle/><div><b>Unable to load People & Access</b><small>{error}</small></div></div>}
  {loading?<div className="employee-admin-empty">Loading people…</div>:filtered.length===0?<div className="employee-admin-empty">No people match this search.</div>:<div className="employee-admin-table"><div className="employee-admin-head"><span>Employee</span><span>Application access</span><span>Compensation</span><span>Approval workflow</span><span>Readiness</span><span/></div>{filtered.map(employee=>{const ready=employee.readiness==="ready",preinviteReady=employee.readiness==="preinvite_ready";return <button className="employee-admin-row" key={employee.employee_id} onClick={()=>setSelected(employee)}><span className="employee-admin-person"><i>{initials(employee.full_name)}</i><span><b>{employee.full_name}</b><small>{[employee.title,employee.department].filter(Boolean).join(" · ")||employee.email||"Employee"}</small></span></span><span>{employee.has_app_access?badge("Active access","good"):employee.draft_user_id?badge("Pre-invite configured","info"):badge("No app access","muted")}</span><span>{!employee.compensation_participant?badge("Not a participant","muted"):employee.plan_name?<><b>{employee.plan_name}</b><small>{employee.plan_status||"Assigned"}{employee.earnings_eligibility_date?` · Eligible ${employee.earnings_eligibility_date}`:""}</small></>:badge("Missing plan","warn")}</span><span>{!employee.compensation_participant?badge("Not required","muted"):employee.workflow_name?<><b>{employee.workflow_name}</b><small>{employee.workflow_status||"Configured"}</small></>:badge("Missing workflow","warn")}</span><span>{ready?badge("Ready","good"):preinviteReady?badge("Ready to invite","info"):badge("Needs setup","warn")}</span><ChevronRight/></button>})}</div>}</section>
  {selected&&<div className="employee-admin-backdrop" onMouseDown={()=>setSelected(null)}><section className="employee-admin-drawer" onMouseDown={e=>e.stopPropagation()}><button className="employee-admin-close" onClick={()=>setSelected(null)}>×</button><div className="employee-admin-profile"><i>{initials(selected.full_name)}</i><div><small>EMPLOYEE RECORD</small><h2>{selected.full_name}</h2><p>{[selected.title,selected.department].filter(Boolean).join(" · ")||selected.email||""}</p></div></div><div className="employee-admin-detail-grid"><article><small>MANAGER</small><b>{selected.manager_name||"Not assigned"}</b></article><article><small>APPLICATION ACCESS</small><b>{selected.has_app_access?"Active":selected.draft_user_id?"Pre-invite configured":"No access"}</b><span>{selected.draft_roles?.length?selected.draft_roles.map(roleLabel).join(" · "):selected.has_app_access?"Active application account":"An employee record does not require application access"}</span></article><article><small>COMPENSATION</small><b>{selected.compensation_participant?(selected.plan_name||"No plan assigned"):"Not a compensation participant"}</b><span>{selected.compensation_participant?(selected.earnings_eligibility_date?`Eligibility ${selected.earnings_eligibility_date}`:"Eligibility date not available"):"No personal variable compensation plan required"}</span></article><article><small>APPROVAL WORKFLOW</small><b>{selected.compensation_participant?(selected.workflow_name||"No workflow configured"):"Not required"}</b><span>{selected.compensation_participant?"Required for personal earnings":"Operational/approver account only"}</span></article></div>
  {selected.readiness_reasons?.length?<div className={`employee-admin-readiness ${selected.readiness==="preinvite_ready"?"info":""}`}><AlertTriangle/><div><b>{selected.readiness==="preinvite_ready"?"Pre-invite configuration ready":"Setup required"}</b>{selected.readiness_reasons.map(reason=><small key={reason}>{reason}</small>)}</div></div>:<div className="employee-admin-readiness good"><ShieldCheck/><div><b>Setup is ready</b><small>No readiness issues are currently reported.</small></div></div>}
  <div className="employee-admin-drawer-actions"><a className="primary" href={`/user-administration?employee=${encodeURIComponent(selected.employee_id)}`}>{selected.draft_user_id?"Continue access setup":selected.has_app_access?"Manage access":"Set up app access"}</a>{selected.compensation_participant&&<a className="secondary" href={`/?workspace=admin&screen=plans&employee=${encodeURIComponent(selected.employee_id)}`}>Manage compensation</a>}{selected.compensation_participant&&<a className="secondary" href={`/approval-workflows?employee=${encodeURIComponent(selected.employee_id)}`}>Approval workflow</a>}</div></section></div>}
 </div>
}
