"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CheckCircle2,Plus,RefreshCw,Search,ShieldCheck,Users} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Permission={permission_key:string;category:string;display_name:string;description:string};
type RolePermission={permission_key:string;allowed:boolean;display_name:string;category:string};
type Role={role_key:string;display_name:string;description:string;is_system:boolean;permissions:RolePermission[]};
type Override={permission_key:string;allowed:boolean;reason:string|null};
type ActiveUser={user_id:string;email:string;full_name:string;roles:string[];overrides:Override[]};
type DraftUser={draft_user_id:string;email:string;full_name:string;status:string;roles:string[];overrides:Override[]};
type AccessData={roles:Role[];permissions:Permission[];active_users:ActiveUser[];draft_users:DraftUser[]};
type Person={id:string;kind:"active"|"draft";full_name:string;email:string;status:string;roles:string[];overrides:Override[]};

export default function UsersPage(){
 const[data,setData]=useState<AccessData>({roles:[],permissions:[],active_users:[],draft_users:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const[tab,setTab]=useState<"people"|"roles"|"permissions">("people"),[selectedPerson,setSelectedPerson]=useState<string>(""),[selectedRole,setSelectedRole]=useState<string>(""),[search,setSearch]=useState("");
 const[newRoleName,setNewRoleName]=useState(""),[newRoleKey,setNewRoleKey]=useState(""),[newRoleDescription,setNewRoleDescription]=useState(""),[copyRole,setCopyRole]=useState("");
 const load=async()=>{if(!supabase){setError("Database connection unavailable.");setLoading(false);return}setLoading(true);setError("");const{data:result,error:rpcError}=await supabase.rpc("get_access_control_admin_data");if(rpcError)setError(rpcError.message);else{const next=(result||{roles:[],permissions:[],active_users:[],draft_users:[]}) as AccessData;setData(next);if(!selectedRole&&next.roles.length)setSelectedRole(next.roles[0].role_key);const people=[...next.active_users.map(x=>x.user_id),...next.draft_users.map(x=>x.draft_user_id)];if(!selectedPerson&&people.length)setSelectedPerson(people[0])}setLoading(false)};
 useEffect(()=>{load()},[]);
 const people=useMemo<Person[]>(()=>[...data.active_users.map(x=>({id:x.user_id,kind:"active" as const,full_name:x.full_name,email:x.email,status:"Active",roles:x.roles,overrides:x.overrides})),...data.draft_users.map(x=>({id:x.draft_user_id,kind:"draft" as const,full_name:x.full_name,email:x.email,status:x.status==="ready"?"Ready · not invited":"Draft",roles:x.roles,overrides:x.overrides}))],[data]);
 const person=people.find(x=>x.id===selectedPerson)||null;const role=data.roles.find(x=>x.role_key===selectedRole)||null;
 const categories=useMemo(()=>Array.from(new Set(data.permissions.map(x=>x.category))).sort(),[data.permissions]);
 const filteredPermissions=useMemo(()=>data.permissions.filter(p=>`${p.category} ${p.display_name} ${p.permission_key} ${p.description}`.toLowerCase().includes(search.toLowerCase())),[data.permissions,search]);
 const inherited=(p:Permission,who:Person)=>who.roles.includes("system_administrator")||who.roles.some(rk=>data.roles.find(r=>r.role_key===rk)?.permissions.some(rp=>rp.permission_key===p.permission_key&&rp.allowed));
 const effective=(p:Permission,who:Person)=>{if(who.roles.includes("system_administrator"))return {allowed:true,source:"System Administrator"};const o=who.overrides.find(x=>x.permission_key===p.permission_key);if(o)return {allowed:o.allowed,source:o.allowed?"User override · Allow":"User override · Deny"};return {allowed:inherited(p,who),source:inherited(p,who)?"Inherited from role":"Not granted"}};
 const rpc=async(name:string,args:Record<string,unknown>,success:string)=>{if(!supabase)return;setBusy(true);setError("");setMessage("");const{error:rpcError}=await supabase.rpc(name,args);if(rpcError)setError(rpcError.message);else{setMessage(success);await load()}setBusy(false)};
 const togglePersonRole=(who:Person,r:Role,assigned:boolean)=>rpc(who.kind==="active"?"admin_set_user_role":"admin_set_draft_user_role",who.kind==="active"?{target_user_id:who.id,target_role_key:r.role_key,requested_assigned:assigned}:{target_draft_user_id:who.id,target_role_key:r.role_key,requested_assigned:assigned},`${r.display_name} ${assigned?"assigned":"removed"}.`);
 const setOverride=(who:Person,p:Permission,state:string)=>rpc(who.kind==="active"?"admin_set_user_permission_override":"admin_set_draft_user_permission_override",who.kind==="active"?{target_user_id:who.id,target_permission_key:p.permission_key,requested_state:state,requested_reason:null}:{target_draft_user_id:who.id,target_permission_key:p.permission_key,requested_state:state,requested_reason:null},`${p.display_name}: ${state}.`);
 const setRolePermission=(r:Role,p:Permission,allowed:boolean)=>rpc("admin_set_role_permission",{target_role_key:r.role_key,target_permission_key:p.permission_key,requested_allowed:allowed},`${r.display_name} updated.`);
 const createRole=async()=>{if(!newRoleName.trim()||!newRoleKey.trim()){setError("Role name and key are required.");return}await rpc("admin_create_role",{requested_role_key:newRoleKey.trim(),requested_display_name:newRoleName.trim(),requested_description:newRoleDescription.trim(),copy_from_role_key:copyRole||null},"Custom role created.");setNewRoleName("");setNewRoleKey("");setNewRoleDescription("");setCopyRole("")};
 const deleteRole=async(r:Role)=>{if(r.is_system||!window.confirm(`Delete ${r.display_name}?`))return;await rpc("admin_delete_role",{target_role_key:r.role_key},"Custom role deleted.")};

 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1380,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:20}}><div><Link href="/manage" style={back}><ArrowLeft size={15}/>Management</Link><small style={eyebrow}>ACCESS CONTROL</small><h1 style={{fontSize:34,margin:"6px 0"}}>Users, roles & permissions</h1><p style={{margin:0,color:"#647184"}}>Role defaults plus per-person overrides. Effective access is always visible before invitation or activation.</p></div><button onClick={load} disabled={loading} style={buttonLight}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>
  {error&&<div style={errorBox}>{error}</div>}{message&&<div style={successBox}>{message}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(160px,1fr))",gap:10,marginBottom:16}}>{[["People",people.length],["Roles",data.roles.length],["Permissions",data.permissions.length],["Overrides",people.reduce((s,p)=>s+p.overrides.length,0)]].map(([a,b])=><div key={String(a)} style={card}><small>{a}</small><b style={{display:"block",fontSize:26}}>{loading?"—":b}</b></div>)}</section>
  <div style={{display:"flex",gap:8,marginBottom:16}}>{([['people','People'],['roles','Roles'],['permissions','Permission catalog']] as const).map(([k,n])=><button key={k} onClick={()=>setTab(k)} style={tabButton(tab===k)}>{n}</button>)}</div>

  {tab==="people"&&<section style={{display:"grid",gridTemplateColumns:"330px 1fr",gap:14}}><aside style={card}><h2 style={h2}><Users size={19}/> People</h2><div style={{display:"grid",gap:6}}>{people.map(p=><button key={p.id} onClick={()=>setSelectedPerson(p.id)} style={{textAlign:"left",padding:11,borderRadius:9,border:selectedPerson===p.id?"2px solid #2095f3":"1px solid #e1e8ef",background:"white",color:"#051b34"}}><b>{p.full_name}</b><small style={{display:"block",color:"#718096"}}>{p.email}</small><small style={{display:"block",marginTop:3,color:p.kind==="active"?"#177245":"#176a9d",fontWeight:800}}>{p.status}</small></button>)}</div></aside>{person&&<div style={{display:"grid",gap:14}}><section style={card}><h2 style={h2}>{person.full_name}</h2><p style={{margin:"0 0 12px",color:"#647184"}}>Assign common roles. Effective permissions below combine these defaults with per-person overrides.</p><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(180px,1fr))",gap:8}}>{data.roles.map(r=>{const checked=person.roles.includes(r.role_key);return <label key={r.role_key} style={choice}><input type="checkbox" checked={checked} disabled={busy} onChange={e=>togglePersonRole(person,r,e.target.checked)}/><span><b>{r.display_name}</b><small style={{display:"block",color:"#718096"}}>{r.role_key}</small></span></label>})}</div></section><section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",marginBottom:10}}><div><h2 style={h2}>Effective permissions</h2><p style={{margin:0,color:"#647184",fontSize:13}}>For each permission: inherit the role result, explicitly allow it, or explicitly deny it.</p></div><Search size={18} color="#718096"/></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search permissions" style={{...input,width:"100%",marginBottom:10}}/><div style={{display:"grid",gap:5,maxHeight:680,overflow:"auto"}}>{filteredPermissions.map(p=>{const eff=effective(p,person);const override=person.overrides.find(x=>x.permission_key===p.permission_key);const state=override?(override.allowed?"allow":"deny"):"inherit";return <div key={p.permission_key} style={{display:"grid",gridTemplateColumns:"1.3fr 110px 180px",gap:10,alignItems:"center",padding:"9px 6px",borderBottom:"1px solid #edf1f5"}}><div><b>{p.display_name}</b><small style={{display:"block",color:"#718096"}}>{p.category} · {p.permission_key}</small></div><span style={{fontWeight:900,color:eff.allowed?"#177245":"#8b2f2f"}}>{eff.allowed?"Allow":"Deny"}<small style={{display:"block",fontWeight:500,color:"#718096"}}>{eff.source}</small></span><select value={state} disabled={busy||person.roles.includes("system_administrator")} onChange={e=>setOverride(person,p,e.target.value)} style={input}><option value="inherit">Inherit</option><option value="allow">Allow override</option><option value="deny">Deny override</option></select></div>})}</div></section></div>}</section>}

  {tab==="roles"&&<section style={{display:"grid",gridTemplateColumns:"330px 1fr",gap:14}}><aside style={card}><h2 style={h2}><ShieldCheck size={19}/> Roles</h2>{data.roles.map(r=><button key={r.role_key} onClick={()=>setSelectedRole(r.role_key)} style={{display:"block",width:"100%",textAlign:"left",padding:10,marginBottom:6,borderRadius:9,border:selectedRole===r.role_key?"2px solid #2095f3":"1px solid #e1e8ef",background:"white",color:"#051b34"}}><b>{r.display_name}</b><small style={{display:"block",color:"#718096"}}>{r.is_system?"Built-in":"Custom"} · {r.role_key}</small></button>)}<details style={{marginTop:12}}><summary style={{fontWeight:900,cursor:"pointer"}}><Plus size={14}/> Create custom role</summary><div style={{display:"grid",gap:7,marginTop:9}}><input value={newRoleName} onChange={e=>{setNewRoleName(e.target.value);if(!newRoleKey)setNewRoleKey(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,""))}} placeholder="Role name" style={input}/><input value={newRoleKey} onChange={e=>setNewRoleKey(e.target.value)} placeholder="role_key" style={input}/><textarea value={newRoleDescription} onChange={e=>setNewRoleDescription(e.target.value)} placeholder="Description" style={input}/><select value={copyRole} onChange={e=>setCopyRole(e.target.value)} style={input}><option value="">Start with no permissions</option>{data.roles.map(r=><option key={r.role_key} value={r.role_key}>Copy {r.display_name}</option>)}</select><button onClick={createRole} disabled={busy} style={buttonDark}>Create role</button></div></details></aside>{role&&<section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div><h2 style={{margin:"0 0 3px"}}>{role.display_name}</h2><p style={{margin:0,color:"#647184"}}>{role.description}</p></div>{!role.is_system&&<button onClick={()=>deleteRole(role)} disabled={busy} style={{...buttonLight,color:"#9d2e2e"}}>Delete</button>}</div><div style={{marginTop:16,display:"grid",gap:5}}>{categories.map(cat=><div key={cat}><h3 style={{fontSize:13,textTransform:"uppercase",letterSpacing:.8,color:"#647184",margin:"14px 0 5px"}}>{cat}</h3>{data.permissions.filter(p=>p.category===cat).map(p=>{const current=role.permissions.find(x=>x.permission_key===p.permission_key)?.allowed||false;const locked=role.role_key==="system_administrator";return <label key={p.permission_key} style={{...choice,marginBottom:5}}><input type="checkbox" checked={locked||current} disabled={busy||locked} onChange={e=>setRolePermission(role,p,e.target.checked)}/><span><b>{p.display_name}</b><small style={{display:"block",color:"#718096"}}>{p.permission_key} · {p.description}</small></span></label>})}</div>)}</div></section>}</section>}

  {tab==="permissions"&&<section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginBottom:12}}><div><h2 style={h2}>Permission catalog</h2><p style={{margin:0,color:"#647184"}}>Granular capabilities used by roles and per-person overrides.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search catalog" style={{...input,minWidth:300}}/></div>{categories.map(cat=>{const list=filteredPermissions.filter(p=>p.category===cat);if(!list.length)return null;return <div key={cat}><h3 style={{fontSize:14,textTransform:"uppercase",letterSpacing:.8,color:"#647184",margin:"16px 0 7px"}}>{cat}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(300px,1fr))",gap:8}}>{list.map(p=><div key={p.permission_key} style={{border:"1px solid #e4ebf1",borderRadius:9,padding:11}}><b>{p.display_name}</b><small style={{display:"block",color:"#2095f3",fontWeight:700,margin:"2px 0"}}>{p.permission_key}</small><small style={{color:"#718096"}}>{p.description}</small></div>)}</div></div>})}</section>}
 </div></main>
}

const card:React.CSSProperties={background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:16};
const input:React.CSSProperties={padding:"9px 10px",border:"1px solid #d6dee8",borderRadius:8,background:"white",color:"#051b34",fontFamily:"inherit"};
const buttonLight:React.CSSProperties={display:"inline-flex",gap:7,alignItems:"center",padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:800,color:"#051b34"};
const buttonDark:React.CSSProperties={display:"inline-flex",gap:7,alignItems:"center",justifyContent:"center",padding:"10px 13px",background:"#051b34",border:0,borderRadius:9,fontWeight:800,color:"white"};
const back:React.CSSProperties={display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700,fontSize:13};
const eyebrow:React.CSSProperties={display:"block",fontWeight:800,letterSpacing:1.1,color:"#2095f3",marginTop:12};
const h2:React.CSSProperties={margin:"0 0 10px",display:"flex",gap:8,alignItems:"center",fontSize:19};
const choice:React.CSSProperties={display:"flex",gap:8,alignItems:"flex-start",padding:9,border:"1px solid #e5ebf1",borderRadius:9,background:"#fbfcfd"};
const errorBox:React.CSSProperties={background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15};
const successBox:React.CSSProperties={background:"#eefaf3",border:"1px solid #bfe4cd",borderRadius:10,padding:13,marginBottom:15,color:"#17643a",fontWeight:700};
function tabButton(active:boolean):React.CSSProperties{return {padding:"9px 13px",border:"1px solid #d6dee8",borderRadius:8,background:active?"#051b34":"white",color:active?"white":"#051b34",fontWeight:800}}
