"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,ArrowLeft,CheckCircle2,Clock3,RefreshCw,ShieldCheck,UserCog,Users} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Employee={employee_id:string;full_name:string;email:string;job_title:string|null;department:string|null;manager_name:string|null;app_access_active:boolean;draft_user_id:string|null;draft_status:string|null;draft_roles:string[];current_plan_name:string|null;earnings_eligibility_date:string|null;current_workflow_name:string|null;access_state:string;setup_blockers:string[]};
type Draft={draft_user_id:string;email:string;full_name:string;status:string;ready_at:string|null;invited_at:string|null;activated_at:string|null;notes:string|null;roles:string[]};
type Role={role_key:string;display_name:string};
type Permission={permission_key:string;display_name:string;category:string};
type Payload={employees:Employee[];drafts:Draft[];roles:Role[];permissions:Permission[]};

function label(v:string|null|undefined){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function StateBadge({state}:{state:string}){const active=state==="active",ready=state==="ready_uninvited";return <span style={{display:"inline-flex",alignItems:"center",gap:5,padding:"5px 8px",borderRadius:999,fontSize:11,fontWeight:800,background:active?"#e9f8ef":ready?"#eaf5ff":"#fff4df",color:active?"#177245":ready?"#176a9d":"#8a5a00"}}>{active?<CheckCircle2 size={13}/>:ready?<Clock3 size={13}/>:<AlertTriangle size={13}/>} {active?"Active":ready?"Ready · not invited":"Setup incomplete"}</span>}

export default function UsersPage(){
 const[data,setData]=useState<Payload>({employees:[],drafts:[],roles:[],permissions:[]}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const{data:result,error:rpcError}=await supabase.rpc("get_user_administration_data");if(rpcError)setError(rpcError.message);else setData((result||{employees:[],drafts:[],roles:[],permissions:[]}) as Payload);setLoading(false)};useEffect(()=>{load()},[]);
 const counts=useMemo(()=>({active:data.employees.filter(x=>x.access_state==="active").length,ready:data.employees.filter(x=>x.access_state==="ready_uninvited").length,incomplete:data.employees.filter(x=>!["active","ready_uninvited"].includes(x.access_state)).length}),[data.employees]);
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1320,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:22,flexWrap:"wrap"}}><div><Link href="/manage" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700,fontSize:13}}><ArrowLeft size={15}/>Management</Link><small style={{display:"block",fontWeight:800,letterSpacing:1.1,color:"#2095f3",marginTop:12}}>ACCESS & CONFIGURATION</small><h1 style={{fontSize:34,margin:"6px 0"}}>Users & permissions</h1><p style={{margin:0,color:"#647184"}}>Configure people completely before invitation. Ready does not mean invited, and invited does not mean activated.</p></div><button onClick={load} disabled={loading} style={{display:"flex",gap:7,alignItems:"center",padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:700}}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>
  {error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginBottom:18}}>{[["Employees",data.employees.length],["Active",counts.active],["Ready · not invited",counts.ready],["Setup incomplete",counts.incomplete],["Roles",data.roles.length],["Permissions",data.permissions.length]].map(([a,b])=><div key={String(a)} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small>{a}</small><b style={{display:"block",fontSize:26}}>{loading?"—":b}</b></div>)}</section>

  <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18,marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start",marginBottom:14}}><div><h2 style={{margin:"0 0 4px"}}>Employee setup readiness</h2><p style={{margin:0,color:"#647184",fontSize:13}}>Identity, roles, manager, compensation plan, and workflow are evaluated independently.</p></div></div><div style={{display:"grid",gap:10}}>{data.employees.map(e=><article key={e.employee_id} style={{border:"1px solid #e5ebf1",borderRadius:11,padding:14}}><div style={{display:"grid",gridTemplateColumns:"minmax(230px,1.25fr) minmax(180px,.85fr) minmax(210px,1fr) auto",gap:14,alignItems:"start"}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><b>{e.full_name}</b><StateBadge state={e.access_state}/></div><small style={{display:"block",color:"#718096",marginTop:3}}>{e.email}{e.job_title?` · ${e.job_title}`:""}</small><small style={{display:"block",color:"#718096",marginTop:3}}>Manager: {e.manager_name||"Not assigned"}</small></div><div><small style={{color:"#718096"}}>Staged roles</small><b style={{display:"block",marginTop:3}}>{e.app_access_active?"Active user":e.draft_roles.length?e.draft_roles.map(label).join(", "):"No roles"}</b><small style={{display:"block",color:"#718096",marginTop:3}}>{e.app_access_active?"Login active":e.draft_status?`Provisioning: ${label(e.draft_status)}`:"Not pre-provisioned"}</small></div><div><small style={{color:"#718096"}}>Compensation setup</small><b style={{display:"block",marginTop:3}}>{e.current_plan_name||"No current plan"}</b><small style={{display:"block",color:"#718096",marginTop:3}}>{e.current_workflow_name||"No active workflow"}</small></div><div style={{minWidth:165}}>{e.setup_blockers?.length?<><b style={{display:"flex",gap:5,alignItems:"center",color:"#8a5a00",fontSize:12}}><AlertTriangle size={14}/>Needs setup</b><ul style={{margin:"6px 0 0",paddingLeft:17,color:"#7a5b22",fontSize:12}}>{e.setup_blockers.map(x=><li key={x}>{x}</li>)}</ul></>:<div style={{display:"flex",gap:5,alignItems:"center",color:"#177245",fontWeight:800,fontSize:12}}><CheckCircle2 size={14}/>{e.access_state==="active"?"Operational":"Staged correctly"}</div>}</div></div></article>)}</div></section>

  <section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><h2 style={{marginTop:0,display:"flex",gap:8,alignItems:"center"}}><UserCog size={19}/> Roles</h2>{data.roles.map(r=><div key={r.role_key} style={{display:"flex",gap:8,alignItems:"center",margin:"9px 0"}}><ShieldCheck size={16} color="#2095f3"/><span><b>{r.display_name}</b><small style={{display:"block",color:"#718096"}}>{r.role_key}</small></span></div>)}</div><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><h2 style={{marginTop:0,display:"flex",gap:8,alignItems:"center"}}><Users size={19}/> Pre-provisioned users</h2>{data.drafts.length===0?<p style={{color:"#647184"}}>No staged users.</p>:data.drafts.map(d=><div key={d.draft_user_id} style={{margin:"10px 0",paddingBottom:10,borderBottom:"1px solid #edf1f5"}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><b>{d.full_name}</b><span style={{fontSize:11,fontWeight:800,textTransform:"uppercase",color:d.status==="ready"?"#176a9d":"#8a5a00"}}>{d.status}</span></div><small style={{display:"block",color:"#718096",marginTop:3}}>{d.roles.map(label).join(", ")}</small><small style={{display:"block",color:"#718096",marginTop:3}}>{d.invited_at?"Invitation recorded":d.status==="ready"?"Configured and ready; no invitation sent":"Configuration still incomplete"}</small>{d.notes&&<small style={{display:"block",color:"#647184",marginTop:4}}>{d.notes}</small>}</div>)}<div style={{marginTop:16,paddingTop:12,borderTop:"1px solid #edf1f5"}}><CheckCircle2 size={16} color="#0f7a50"/> <b>System Administrator remains unrestricted</b><p style={{margin:"4px 0",color:"#647184",fontSize:13}}>Business workflow assignments do not restrict Sharon's administrative authority; interventions remain auditable.</p></div></div></section>
 </div></main>
}
