"use client";

import { useMemo, useState, useEffect } from "react";
import { CheckCircle2, Eye, Save, Send, ShieldCheck, UserPlus } from "lucide-react";
import { createClient } from "@supabase/supabase-js";
import AdminShell from "../components/admin-shell";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
const today=()=>new Date().toISOString().slice(0,10);
type AdminData={employees:any[];drafts:any[];managers:any[];organization_units:any[];active_plan_versions:any[];roles:any[];permissions:any[]};
const empty:AdminData={employees:[],drafts:[],managers:[],organization_units:[],active_plan_versions:[],roles:[],permissions:[]};

export default function UserAdministrationPage(){
 const[data,setData]=useState<AdminData>(empty),[employeeId,setEmployeeId]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[title,setTitle]=useState(""),[department,setDepartment]=useState(""),[managerId,setManagerId]=useState(""),[orgId,setOrgId]=useState(""),[planVersionId,setPlanVersionId]=useState(""),[startDate,setStartDate]=useState(today()),[eligibilityDate,setEligibilityDate]=useState(""),[roles,setRoles]=useState<string[]>(["employee"]),[draftId,setDraftId]=useState(""),[draftStatus,setDraftStatus]=useState(""),[preview,setPreview]=useState<any>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const selectedEmployee=useMemo(()=>data.employees.find((x:any)=>x.employee_id===employeeId),[data,employeeId]);
 const hydrate=(next:AdminData,id:string)=>{const employee=next.employees.find((x:any)=>x.employee_id===id);const draft=next.drafts.find((x:any)=>x.employee_id===id&&x.status!=="cancelled");setEmployeeId(id);setName(draft?.full_name||employee?.full_name||"");setEmail(draft?.email||employee?.email||"");setTitle(draft?.job_title||employee?.job_title||"");setDepartment(draft?.department||employee?.department||"");setManagerId(draft?.manager_employee_id||employee?.manager_employee_id||"");setOrgId(draft?.primary_org_unit_id||"");setPlanVersionId(draft?.plan_version_id||"");setStartDate(draft?.employee_effective_start_date||today());setEligibilityDate(draft?.earnings_eligibility_date||"");setRoles(Array.isArray(draft?.roles)&&draft.roles.length?draft.roles:["employee"]);setDraftId(draft?.draft_user_id||"");setDraftStatus(draft?.status||"");setPreview(null);if(draft)setNotice("Existing pre-invite configuration loaded. No invitation has been sent.")};
 const load=async(preferredEmployeeId?:string)=>{setError("");const{data:r,error:e}=await supabase.rpc("get_user_administration_data");if(e)return setError(e.message);const next={...empty,...(r||{})};setData(next);const requested=preferredEmployeeId||(typeof window!=="undefined"?new URLSearchParams(window.location.search).get("employee")||"":"");if(requested&&next.employees.some((x:any)=>x.employee_id===requested))hydrate(next,requested)};
 useEffect(()=>{load()},[]);
 const chooseEmployee=(id:string)=>{setError("");setNotice("");setPreview(null);if(!id){setEmployeeId("");setDraftId("");setDraftStatus("");setName("");setEmail("");setTitle("");setDepartment("");setManagerId("");setOrgId("");setPlanVersionId("");setEligibilityDate("");setStartDate(today());setRoles(["employee"]);return}hydrate(data,id)};
 const toggleRole=(key:string)=>setRoles(x=>x.includes(key)?(x.length===1?x:x.filter(v=>v!==key)):[...x,key]);
 const createDraft=async()=>{setBusy(true);setError("");setNotice("");const{data:r,error:e}=await supabase.rpc("create_app_user_draft",{selected_email:email,selected_full_name:name,selected_employee_id:employeeId||null,selected_role_keys:roles,selected_notes:"Configured in People & Access"});if(e){setError(e.message);setBusy(false);return}const id=r?.draft_user_id||r?.id;setDraftId(id);setDraftStatus("draft");setNotice("Provisioning draft created. No invitation has been sent.");setBusy(false);await load(employeeId)};
 const saveProfile=async()=>{if(!draftId)return setError("Create the provisioning draft first.");setBusy(true);setError("");const{error:e}=await supabase.rpc("set_app_user_draft_employee_profile",{selected_draft_user_id:draftId,selected_job_title:title||null,selected_department:department||null,selected_manager_employee_id:managerId||null,selected_primary_org_unit_id:orgId||null,selected_plan_version_id:planVersionId||null,selected_effective_start_date:startDate});if(e){setError(e.message);setBusy(false);return}if(planVersionId){const eligibility=await supabase.rpc("set_app_user_draft_earnings_eligibility",{selected_draft_user_id:draftId,selected_earnings_eligibility_date:eligibilityDate||null});if(eligibility.error){setError(eligibility.error.message);setBusy(false);return}}setNotice("Employment and compensation configuration saved to the provisioning draft.");setBusy(false);await load(employeeId)};
 const showPreview=async()=>{if(!draftId)return setError("Create the provisioning draft first.");setBusy(true);const{data:r,error:e}=await supabase.rpc("get_app_user_draft_preview",{selected_draft_user_id:draftId});if(e)setError(e.message);else setPreview(r);setBusy(false)};
 const prepare=async()=>{if(!draftId)return setError("Create the provisioning draft first.");setBusy(true);setError("");const{data:r,error:e}=await supabase.rpc("prepare_app_user_draft_invitation",{selected_draft_user_id:draftId});if(e)setError(e.message);else{setNotice("Invitation is prepared but has not been sent.");setDraftStatus("ready");setPreview(r)}setBusy(false);await load(employeeId)};
 const preInvite=!!draftId&&!selectedEmployee?.app_access_active;
 return <AdminShell section="people" title="Add or Configure Employee" description="Employee record, application access, compensation participation, and invitation readiness."><div className="user-admin-route">
  <div className="mb-4 flex items-center justify-between gap-3"><a href="/employee-administration" className="secondary">← Back to People & Access</a><span className="secure"><ShieldCheck size={15}/> Draft-first provisioning</span></div>
  {error&&<div className="ua-message error">{error}</div>}{notice&&<div className="ua-message success">{notice}</div>}{preInvite&&<div className="ua-message info">Pre-invite configuration: this employee does not yet have active application access. No invitation is sent until the invitation step is deliberately completed.</div>}
  <div className="ua-steps"><span className={draftId?"done":"active"}>1 Employee</span><span className={draftId?"active":""}>2 Access & compensation</span><span>3 Review setup</span><span>4 Prepare invitation</span></div>
  <section className="ua-grid"><div className="ua-card"><h2>1. Employee identity & application roles</h2><p>Create a new employee record or link an existing employee before configuring application access.</p><label>Existing employee<select value={employeeId} onChange={e=>chooseEmployee(e.target.value)} disabled={!!draftId}><option value="">Create a new employee</option>{data.employees.map((x:any)=><option key={x.employee_id} value={x.employee_id}>{x.full_name} — {x.email}</option>)}</select></label><div className="two-col"><label>Full name<input value={name} onChange={e=>setName(e.target.value)} disabled={!!draftId}/></label><label>Engagifii email<input value={email} onChange={e=>setEmail(e.target.value)} disabled={!!draftId}/></label></div><fieldset><legend>Application roles</legend><div className="role-grid">{data.roles.map((r:any)=><label key={r.role_key} className={roles.includes(r.role_key)?"selected":""}><input type="checkbox" checked={roles.includes(r.role_key)} onChange={()=>toggleRole(r.role_key)} disabled={!!draftId}/>{roles.includes(r.role_key)&&<CheckCircle2/>}<span>{r.display_name}</span></label>)}</div></fieldset>{draftId?<div className="draft-loaded"><ShieldCheck size={16}/><span><b>Provisioning draft loaded</b><small>Status: {draftStatus||"draft"}. Identity and roles are preserved until explicit editing controls are added.</small></span></div>:<button className="primary" onClick={createDraft} disabled={busy||!name||!email}><UserPlus size={15}/>Create provisioning draft</button>}</div>
  <div className={`ua-card ${!draftId?"locked":""}`}><h2>2. Employment, organization & compensation</h2><p>Employee data remains conceptually separate from application access. Compensation assignment is optional when this person is not a compensation participant.</p><div className="two-col"><label>Job title<input value={title} onChange={e=>setTitle(e.target.value)} disabled={!draftId}/></label><label>Department<input value={department} onChange={e=>setDepartment(e.target.value)} disabled={!draftId}/></label></div><div className="two-col"><label>Manager<select value={managerId} onChange={e=>setManagerId(e.target.value)} disabled={!draftId}><option value="">No manager</option>{data.managers.filter((x:any)=>x.employee_id!==employeeId).map((x:any)=><option key={x.employee_id} value={x.employee_id}>{x.full_name}</option>)}</select></label><label>Primary organization<select value={orgId} onChange={e=>setOrgId(e.target.value)} disabled={!draftId}><option value="">No organization unit</option>{data.organization_units.map((x:any)=><option key={x.org_unit_id} value={x.org_unit_id}>{x.name}</option>)}</select></label></div><div className="two-col"><label>Effective start<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} disabled={!draftId}/></label><label>Compensation plan<select value={planVersionId} onChange={e=>{setPlanVersionId(e.target.value);if(!e.target.value)setEligibilityDate("")}} disabled={!draftId}><option value="">No compensation plan</option>{data.active_plan_versions.map((x:any)=><option key={x.plan_version_id} value={x.plan_version_id}>{x.name} · v{x.version_number}</option>)}</select></label></div>{planVersionId&&<label>Earnings eligibility date<input type="date" value={eligibilityDate} onChange={e=>setEligibilityDate(e.target.value)} disabled={!draftId}/><small>Eligibility can differ from employment start and is controlled by the effective plan unless explicitly overridden.</small></label>}<button className="primary" onClick={saveProfile} disabled={busy||!draftId||(!!planVersionId&&!eligibilityDate)}><Save size={15}/>Save setup</button></div></section>
  <section className="ua-card preview-card"><div><h2>3. Review access & setup</h2><p>Review effective roles, permissions, workspace access, and compensation setup. This is a provisioning review — not the administrator View-as-User capability.</p></div><div className="preview-actions"><button className="secondary" onClick={showPreview} disabled={busy||!draftId}><Eye size={15}/>Review access & setup</button><button className="primary" onClick={prepare} disabled={busy||!draftId}><Send size={15}/>Prepare invitation</button></div>{preview&&<div className="preview-result"><div><small>EMPLOYEE / USER</small><b>{preview.user?.full_name||name}</b><span>{preview.user?.email||email}</span></div><div><small>ROLES</small><b>{(preview.roles||roles).map((x:any)=>typeof x==="string"?x:x.role_key).join(", ")||"—"}</b></div><div><small>PLAN</small><b>{preview.compensation_preview?.plan?.name||"No compensation plan"}</b></div><div><small>INVITATION</small><b>{preview.invitation_sent?"Sent":"Not sent"}</b></div></div>}</section>
 </div></AdminShell>;
}
