"use client";

import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,ArrowLeft,CheckCircle2,RefreshCw} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Change={detected_at:string;deal_name:string;field_name:string;old_value:string|null;new_value:string|null;review_status:string};
type Data={deals:number;companies:number;associations:number;unlinkedDeals:number;unreviewedChanges:number;lastSync:string|null;recentChanges:Change[]};
const empty:Data={deals:0,companies:0,associations:0,unlinkedDeals:0,unreviewedChanges:0,lastSync:null,recentChanges:[]};

export default function HubSpotPage(){
 const[data,setData]=useState<Data>(empty),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[error,setError]=useState("");
 const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const{data:result,error:rpcError}=await supabase.rpc("get_compensation_dashboard_data");if(rpcError)setError(rpcError.message);else setData((result||empty) as Data);setLoading(false)};
 useEffect(()=>{load()},[]);
 const refresh=async()=>{if(!supabase)return;setSyncing(true);setError("");const{error:rpcError}=await supabase.rpc("refresh_compensation_management_data",{force_refresh:true});if(rpcError)setError(rpcError.message);else await load();setSyncing(false)};
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1250,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:22,flexWrap:"wrap"}}><div><Link href="/manage" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700,fontSize:13}}><ArrowLeft size={15}/>Management</Link><small style={{display:"block",fontWeight:800,letterSpacing:1.1,color:"#2095f3",marginTop:12}}>SOURCE DATA</small><h1 style={{fontSize:34,margin:"6px 0"}}>HubSpot integration</h1><p style={{margin:0,color:"#647184"}}>Source-of-truth deal, company, ownership, stage, amount, association, payment-date, and change data used by compensation logic.</p></div><button onClick={refresh} disabled={syncing||loading} style={{display:"flex",gap:7,alignItems:"center",padding:"10px 13px",background:"#2095f3",color:"white",border:0,borderRadius:9,fontWeight:800}}><RefreshCw size={16}/>{syncing?"Refreshing…":"Refresh HubSpot"}</button></header>{error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(185px,1fr))",gap:10,marginBottom:18}}>{[["Deals",data.deals],["Companies",data.companies],["Associations",data.associations],["Unlinked deals",data.unlinkedDeals],["Changes to review",data.unreviewedChanges]].map(([a,b])=><div key={String(a)} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small>{a}</small><b style={{display:"block",fontSize:26,marginTop:4}}>{loading?"—":Number(b).toLocaleString()}</b></div>)}</section>
 <section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14,marginBottom:18}}><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><h2 style={{marginTop:0}}>Data synchronized</h2>{["Deals: pipeline, type, stage, owner, ARR, term and payment fields","Companies and account ownership","Deal/company associations","HubSpot change history for audit and recalculation"].map(x=><div key={x} style={{display:"flex",gap:8,margin:"10px 0"}}><CheckCircle2 size={17} color="#0f7a50"/><span>{x}</span></div>)}</div><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><h2 style={{marginTop:0}}>Automatic review conditions</h2>{["Paid stage and invoice-paid date disagree","Deal has no company association","Compensation-sensitive field changes after calculation","Ownership or attribution is unclear"].map(x=><div key={x} style={{display:"flex",gap:8,margin:"10px 0"}}><AlertTriangle size={17} color="#b7791f"/><span>{x}</span></div>)}</div></section>
 <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 4px"}}>Recent compensation-relevant changes</h2><small style={{color:"#718096"}}>Last completed sync: {data.lastSync?new Date(data.lastSync).toLocaleString():"Not available"}</small></div></div>{data.recentChanges.length===0?<p style={{color:"#647184"}}>No recent changes returned.</p>:<div style={{display:"grid",gap:8,marginTop:14}}>{data.recentChanges.map((x,i)=><div key={`${x.detected_at}-${i}`} style={{display:"grid",gridTemplateColumns:"150px 1.2fr 1fr 1.4fr auto",gap:10,alignItems:"center",padding:"10px 0",borderBottom:"1px solid #edf1f5",fontSize:13}}><span>{new Date(x.detected_at).toLocaleString()}</span><b>{x.deal_name}</b><span>{x.field_name}</span><span>{x.old_value||"—"} → {x.new_value||"—"}</span><em>{x.review_status}</em></div>)}</div>}</section></div></main>
}
