"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {CheckCircle2,RefreshCw,Search,WalletCards} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;
type Access={roles?:string[];permissions?:string[]};
type Handoff={task_id:string;earning_id:string;status:string;assigned_employee_name:string|null;assignee_activation_required:boolean;employee_name:string;earning_name:string;earned_date:string;approved_amount:number;earned_amount:number};
type PaymentItem={earning_id:string;employee_id:string;employee_name:string;earning_name:string;earned_date:string;approved_amount:number;paid_amount:number;remaining_amount?:number;payment_status:string;pay_period_start:string|null;pay_period_end:string|null;pay_period_label:string|null;actual_payment_date?:string|null;payment_reference?:string|null;payment_method?:string|null};
type Workspace={accepted_unpaid:PaymentItem[];paid:PaymentItem[]};
type PeriodChoice={month:string;kind:"first"|"second"|"custom";start:string;end:string};

function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function today(){return new Date().toISOString().slice(0,10)}
function monthKey(){return today().slice(0,7)}
function lastDay(month:string){if(!/^\d{4}-\d{2}$/.test(month))return "";const[y,m]=month.split("-").map(Number);return new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)}
function prettyDate(d:string|null|undefined){if(!d)return "—";return new Date(`${d}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}
function prettyPeriod(start:string|null,end:string|null,label?:string|null){return label||(start&&end?`${prettyDate(start)} – ${prettyDate(end)}`:"Not assigned")}
function periodDates(p:PeriodChoice){if(p.kind==="custom")return{start:p.start,end:p.end,label:p.start&&p.end?`${prettyDate(p.start)} – ${prettyDate(p.end)}`:""};const start=`${p.month}-${p.kind==="first"?"01":"16"}`;const end=p.kind==="first"?`${p.month}-15`:lastDay(p.month);return{start,end,label:`${prettyDate(start)} – ${prettyDate(end)}`}}
function defaultPeriod():PeriodChoice{return{month:monthKey(),kind:"first",start:"",end:""}}

export default function PaymentsPage(){
 const[access,setAccess]=useState<Access|null>(null),[handoffs,setHandoffs]=useState<Handoff[]>([]),[workspace,setWorkspace]=useState<Workspace>({accepted_unpaid:[],paid:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState<string|null>(null);
 const[view,setView]=useState<"current"|"past">("current"),[search,setSearch]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState("");
 const[periods,setPeriods]=useState<Record<string,PeriodChoice>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[paidDate,setPaidDate]=useState<Record<string,string>>({}),[paymentRef,setPaymentRef]=useState<Record<string,string>>({}),[paymentMethod,setPaymentMethod]=useState<Record<string,string>>({});
 const isAdmin=Boolean(access?.roles?.includes("system_administrator"));
 const canView=isAdmin||Boolean(access?.permissions?.includes("payments.view"));
 const canMarkPaid=isAdmin||Boolean(access?.permissions?.includes("payments.mark_paid"));
 const load=async()=>{if(!supabase){setError("Payments are temporarily unavailable.");setLoading(false);return}setLoading(true);setError("");const[a,b,c]=await Promise.all([supabase.rpc("get_current_user_access"),supabase.rpc("get_my_comp_earning_handoff_tasks",{include_completed:false}),supabase.rpc("get_finance_payment_workspace_data")]);if(a.error)setError("We couldn't verify your payment access. Refresh and try again.");else setAccess((a.data||{}) as Access);if(b.error)setError(x=>x||"We couldn't load items waiting for Finance acceptance.");else setHandoffs(((b.data||[]) as Handoff[]).filter(x=>x.status==="pending"));if(c.error)setError(x=>x||"We couldn't load the payment ledger. Refresh and try again.");else setWorkspace((c.data||{accepted_unpaid:[],paid:[]}) as Workspace);setLoading(false)};
 useEffect(()=>{load()},[]);
 const periodFor=(id:string)=>periods[id]||defaultPeriod();
 const setPeriod=(id:string,patch:Partial<PeriodChoice>)=>setPeriods(x=>({...x,[id]:{...periodFor(id),...patch}}));
 const accept=async(task:Handoff)=>{if(!supabase||!canView)return;const p=periodDates(periodFor(task.task_id));if(!p.start||!p.end){setError("Choose a payroll period before accepting.");return}setBusy(task.task_id);setError("");setMessage("");const{error:e}=await supabase.rpc("accept_comp_earning_for_pay_period",{target_task_id:task.task_id,requested_pay_period_start:p.start,requested_pay_period_end:p.end,requested_pay_period_label:p.label||null,action_comments:notes[task.task_id]?.trim()||null});if(e)setError("This earning could not be accepted into the selected payroll period. Refresh and try again.");else{setMessage(`${task.employee_name} accepted for ${p.label}.`);await load()}setBusy(null)};
 const markPaid=async(item:PaymentItem)=>{if(!supabase||!canMarkPaid)return;const date=paidDate[item.earning_id]||today();if(!window.confirm(`Confirm ${money(item.remaining_amount||0)} paid to ${item.employee_name} on ${prettyDate(date)}?`))return;setBusy(item.earning_id);setError("");const{error:e}=await supabase.rpc("mark_comp_earning_paid",{target_earning_id:item.earning_id,requested_actual_payment_date:date,requested_payment_reference:paymentRef[item.earning_id]?.trim()||null,requested_payment_method:paymentMethod[item.earning_id]?.trim()||"Payroll",requested_notes:null});if(e)setError("The payment could not be recorded. Nothing was marked paid. Refresh and try again.");else{setMessage(`${item.employee_name}: payment recorded.`);await load()}setBusy(null)};
 const match=(name:string,date:string|null|undefined)=>{const q=search.trim().toLowerCase();if(q&&!name.toLowerCase().includes(q))return false;if(dateFrom&&date&&date<dateFrom)return false;if(dateTo&&date&&date>dateTo)return false;return true};
 const currentHandoffs=useMemo(()=>handoffs.filter(x=>match(`${x.employee_name} ${x.earning_name}`,x.earned_date)),[handoffs,search,dateFrom,dateTo]);
 const currentUnpaid=useMemo(()=>workspace.accepted_unpaid.filter(x=>match(`${x.employee_name} ${x.earning_name}`,x.earned_date)),[workspace.accepted_unpaid,search,dateFrom,dateTo]);
 const paidRows=useMemo(()=>workspace.paid.filter(x=>match(`${x.employee_name} ${x.earning_name}`,x.actual_payment_date||x.earned_date)),[workspace.paid,search,dateFrom,dateTo]);
 const unpaidTotal=workspace.accepted_unpaid.reduce((s,x)=>s+Number(x.remaining_amount||0),0);
 const paidTotal=workspace.paid.reduce((s,x)=>s+Number(x.paid_amount||0),0);
 const PeriodPicker=({id}:{id:string})=>{const p=periodFor(id);return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:8}}><input className="eng-input" type="month" value={p.month} onChange={e=>setPeriod(id,{month:e.target.value})}/><select className="eng-input" value={p.kind} onChange={e=>setPeriod(id,{kind:e.target.value as PeriodChoice["kind"]})}><option value="first">1–15</option><option value="second">16–end</option><option value="custom">Custom</option></select>{p.kind==="custom"&&<><input className="eng-input" type="date" value={p.start} onChange={e=>setPeriod(id,{start:e.target.value})}/><input className="eng-input" type="date" value={p.end} onChange={e=>setPeriod(id,{end:e.target.value})}/></>}</div>};

 return <main className="eng-page"><div className="eng-page__shell">
  <nav className="eng-breadcrumb" aria-label="Breadcrumb"><Link href="/manage">Control Center</Link><span className="eng-breadcrumb__sep">/</span><span className="eng-breadcrumb__current">Payments</span></nav>
  <header className="eng-page-header"><div className="eng-page-header__main"><span className="eng-page-header__eyebrow">FINANCE & PAYROLL</span><div className="eng-page-header__titlerow"><h1>Payments</h1></div><p className="eng-page-header__lede">Current and past compensation payments by employee, payroll period, and paid date. Approval history stays in Pending Actions; this workspace is the Finance payment ledger.</p></div><div className="eng-page-header__actions"><button onClick={load} disabled={loading} className="eng-btn"><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></div></header>
  {error&&<div className="eng-callout eng-callout--danger"><div className="eng-callout__body">{error}</div></div>}{message&&<div className="eng-callout eng-callout--success" style={{marginTop:10}}><div className="eng-callout__body">{message}</div></div>}

  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,margin:"16px 0"}}>
   <div className="eng-card"><div className="eng-card__body"><small>Pending Finance acceptance</small><b className="eng-figure" style={{display:"block",fontSize:26,marginTop:4}}>{loading?"—":handoffs.length}</b></div></div>
   <div className="eng-card"><div className="eng-card__body"><small>Accepted / unpaid</small><b className="eng-figure" style={{display:"block",fontSize:26,marginTop:4}}>{loading?"—":workspace.accepted_unpaid.length}</b><div className="eng-figure eng-figure--strong">{money(unpaidTotal)}</div></div></div>
   <div className="eng-card"><div className="eng-card__body"><small>Paid history</small><b className="eng-figure" style={{display:"block",fontSize:26,marginTop:4}}>{loading?"—":workspace.paid.length}</b><div className="eng-figure eng-figure--strong">{money(paidTotal)}</div></div></div>
  </section>

  <section className="eng-card" style={{marginBottom:18}}><div className="eng-card__body" style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><button onClick={()=>setView("current")} className={`eng-btn ${view==="current"?"eng-btn--primary":""}`}>Current / pending</button><button onClick={()=>setView("past")} className={`eng-btn ${view==="past"?"eng-btn--primary":""}`}>Past payments</button><label style={{display:"flex",alignItems:"center",gap:7,marginLeft:"auto",minWidth:240}}><Search size={15}/><input className="eng-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search employee or earning"/></label><input className="eng-input" type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} aria-label="Date from"/><input className="eng-input" type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} aria-label="Date to"/></div></section>

  {loading?<div className="eng-card"><div className="eng-card__body">Loading payments…</div></div>:view==="current"?<>
   <section style={{marginBottom:24}}><div className="eng-card__head" style={{paddingLeft:0,paddingRight:0,borderBottom:0}}><div><h2>Pending Finance acceptance</h2><p>Approved compensation waiting to be assigned to a payroll period.</p></div></div>{currentHandoffs.length===0?<div className="eng-empty eng-empty--inline"><div className="eng-empty__icon eng-empty__icon--success"><CheckCircle2 size={22}/></div><h2>Nothing is waiting for Finance acceptance</h2><p>Approved earnings that need a payroll period will appear here.</p></div>:<div style={{display:"grid",gap:10}}>{currentHandoffs.map(task=><article key={task.task_id} className="eng-card"><div className="eng-card__body"><div style={{display:"grid",gridTemplateColumns:"minmax(220px,1.5fr) repeat(2,minmax(150px,1fr))",gap:14}}><div><b>{task.employee_name}</b><div style={{color:"var(--eng-ink-meta)",fontSize:13}}>{task.earning_name}</div></div><div><small>Earned date</small><div>{prettyDate(task.earned_date)}</div></div><div><small>Approved amount</small><b className="eng-figure">{money(task.approved_amount||task.earned_amount)}</b></div></div><div style={{marginTop:12}}><small>Pay period</small><PeriodPicker id={task.task_id}/></div><input className="eng-input" value={notes[task.task_id]||""} onChange={e=>setNotes(x=>({...x,[task.task_id]:e.target.value}))} placeholder="Optional Finance note" style={{width:"100%",marginTop:8}}/><button onClick={()=>accept(task)} disabled={busy!==null} className="eng-btn eng-btn--primary" style={{marginTop:10}}><CheckCircle2 size={16}/>{busy===task.task_id?"Accepting…":"Accept into payroll period"}</button></div></article>)}</div>}</section>
   <section><div className="eng-card__head" style={{paddingLeft:0,paddingRight:0,borderBottom:0}}><div><h2>Accepted / unpaid</h2><p>Items in a payroll period that have not yet been recorded as paid.</p></div></div>{currentUnpaid.length===0?<div className="eng-empty eng-empty--inline"><div className="eng-empty__icon"><WalletCards size={22}/></div><h2>No accepted unpaid compensation</h2><p>Accepted items will stay here until Finance records payment.</p></div>:<div style={{display:"grid",gap:10}}>{currentUnpaid.map(item=><article key={item.earning_id} className="eng-card"><div className="eng-card__body"><div style={{display:"grid",gridTemplateColumns:"minmax(220px,1.5fr) repeat(3,minmax(150px,1fr))",gap:14}}><div><b>{item.employee_name}</b><div style={{color:"var(--eng-ink-meta)",fontSize:13}}>{item.earning_name}</div></div><div><small>Earned date</small><div>{prettyDate(item.earned_date)}</div></div><div><small>Pay period</small><div>{prettyPeriod(item.pay_period_start,item.pay_period_end,item.pay_period_label)}</div></div><div><small>Pending payment</small><b className="eng-figure">{money(item.remaining_amount||0)}</b></div></div>{canMarkPaid&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:8,marginTop:12}}><label><small>Paid date</small><input className="eng-input" type="date" value={paidDate[item.earning_id]||today()} onChange={e=>setPaidDate(x=>({...x,[item.earning_id]:e.target.value}))} style={{width:"100%"}}/></label><label><small>Payment method</small><input className="eng-input" value={paymentMethod[item.earning_id]||"Payroll"} onChange={e=>setPaymentMethod(x=>({...x,[item.earning_id]:e.target.value}))} style={{width:"100%"}}/></label><label><small>Reference</small><input className="eng-input" value={paymentRef[item.earning_id]||""} onChange={e=>setPaymentRef(x=>({...x,[item.earning_id]:e.target.value}))} placeholder="Optional" style={{width:"100%"}}/></label><div style={{display:"flex",alignItems:"end"}}><button onClick={()=>markPaid(item)} disabled={busy!==null} className="eng-btn eng-btn--primary">{busy===item.earning_id?"Saving…":"Mark paid"}</button></div></div>}</div></article>)}</div>}</section>
  </>:<section><div className="eng-card__head" style={{paddingLeft:0,paddingRight:0,borderBottom:0}}><div><h2>Payment history</h2><p>Completed payments by employee, date paid, payroll period, method, and reference.</p></div></div>{paidRows.length===0?<div className="eng-empty eng-empty--inline"><div className="eng-empty__icon"><WalletCards size={22}/></div><h2>No paid compensation matches these filters</h2><p>Adjust the employee search or date range to see additional payment history.</p></div>:<div className="eng-card" style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900}}><thead><tr>{["Employee","Earning","Earned","Paid date","Pay period","Paid amount","Method / reference"].map(h=><th key={h} style={{textAlign:"left",padding:"11px 12px",borderBottom:"1px solid var(--eng-border)",fontSize:12,color:"var(--eng-ink-meta)"}}>{h}</th>)}</tr></thead><tbody>{paidRows.map(item=><tr key={item.earning_id}><td style={{padding:12,borderBottom:"1px solid var(--eng-border-soft)",fontWeight:700}}>{item.employee_name}</td><td style={{padding:12,borderBottom:"1px solid var(--eng-border-soft)"}}>{item.earning_name}</td><td style={{padding:12,borderBottom:"1px solid var(--eng-border-soft)"}}>{prettyDate(item.earned_date)}</td><td style={{padding:12,borderBottom:"1px solid var(--eng-border-soft)"}}>{prettyDate(item.actual_payment_date)}</td><td style={{padding:12,borderBottom:"1px solid var(--eng-border-soft)"}}>{prettyPeriod(item.pay_period_start,item.pay_period_end,item.pay_period_label)}</td><td className="eng-figure eng-figure--strong" style={{padding:12,borderBottom:"1px solid var(--eng-border-soft)"}}>{money(item.paid_amount||0)}</td><td style={{padding:12,borderBottom:"1px solid var(--eng-border-soft)"}}>{item.payment_method||"—"}{item.payment_reference?` · ${item.payment_reference}`:""}</td></tr>)}</tbody></table></div>}</section>}
 </div></main>;
}
