"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,CheckCircle2,ChevronRight,Clock3,Home,Plus,RefreshCw,WalletCards} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Access={full_name?:string;email?:string;roles?:string[];permissions?:string[]};
type Summary={counts:Record<string,number>;amounts:Record<string,number>;employees:Array<{employee_id:string;employee_name:string;eligible_count:number;approved_count:number;ready_for_payroll_count:number;held_count:number;ready_amount:number}>};
type Handoff={task_id:string;earning_id:string;step_name:string;status:string;comments:string|null;assigned_employee_name:string|null;assignee_activation_required:boolean;employee_name:string;earning_name:string;earned_date:string;approved_amount:number;earned_amount:number;requires_payment_details:boolean};
type ReadyEarning={earning_id:string;employee_id:string;employee_name:string;earning_name:string;earned_date:string;earned_amount:number;approved_amount:number;remaining_amount:number;payment_status:string};
type BatchItem={id:string;earning_id:string;employee_id:string;employee_name:string;earning_name:string;amount:number;payment_details:string|null};
type PayrollBatch={id:string;batch_name:string;payroll_period_start:string|null;payroll_period_end:string|null;scheduled_payment_date:string|null;actual_payment_date:string|null;status:string;payment_reference:string|null;payment_method:string|null;notes:string|null;created_at:string;items:BatchItem[]};
type PayrollData={ready_earnings:ReadyEarning[];batches:PayrollBatch[]};

function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function label(v:string|null|undefined){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function today(){return new Date().toISOString().slice(0,10)}

export default function PaymentsPage(){
 const[summary,setSummary]=useState<Summary|null>(null),[handoffs,setHandoffs]=useState<Handoff[]>([]),[access,setAccess]=useState<Access|null>(null),[payroll,setPayroll]=useState<PayrollData>({ready_earnings:[],batches:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState<string|null>(null),[comments,setComments]=useState<Record<string,string>>({}),[showHistory,setShowHistory]=useState(false);
 const[selected,setSelected]=useState<string[]>([]),[activeBatch,setActiveBatch]=useState("");
 const[batchName,setBatchName]=useState(""),[periodStart,setPeriodStart]=useState(""),[periodEnd,setPeriodEnd]=useState(""),[scheduledDate,setScheduledDate]=useState(""),[batchNotes,setBatchNotes]=useState("");
 const[paidDate,setPaidDate]=useState(today()),[paymentRef,setPaymentRef]=useState(""),[paymentMethod,setPaymentMethod]=useState("Payroll"),[paidNotes,setPaidNotes]=useState("");
 const isAdmin=Boolean(access?.roles?.includes("system_administrator"));
 const canSchedule=isAdmin||Boolean(access?.permissions?.includes("payments.schedule"));
 const canMarkPaid=isAdmin||Boolean(access?.permissions?.includes("payments.mark_paid"));
 const canFinance=isAdmin||Boolean(access?.permissions?.includes("payments.view"));

 const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const[a,b,c,d]=await Promise.all([supabase.rpc("get_current_user_access"),supabase.rpc("get_payout_readiness_summary"),supabase.rpc("get_my_comp_earning_handoff_tasks",{include_completed:showHistory}),supabase.rpc("get_comp_payroll_management_data")]);if(a.error)setError(a.error.message);else setAccess((a.data||{}) as Access);if(b.error)setError(x=>x||b.error.message);else setSummary(b.data as Summary);if(c.error)setError(x=>x||c.error.message);else setHandoffs((c.data||[]) as Handoff[]);if(d.error)setError(x=>x||d.error.message);else{const data=(d.data||{ready_earnings:[],batches:[]}) as PayrollData;setPayroll(data);setSelected(current=>current.filter(id=>data.ready_earnings.some(e=>e.earning_id===id)));if(!activeBatch){const draft=data.batches.find(x=>x.status==="draft");if(draft)setActiveBatch(draft.id)}}setLoading(false)};
 useEffect(()=>{load()},[showHistory]);
 const pending=useMemo(()=>handoffs.filter(x=>x.status==="pending"),[handoffs]);
 const completed=useMemo(()=>handoffs.filter(x=>x.status!=="pending"),[handoffs]);
 const drafts=useMemo(()=>payroll.batches.filter(x=>x.status==="draft"),[payroll.batches]);
 const scheduled=useMemo(()=>payroll.batches.filter(x=>x.status==="scheduled"||x.status==="finalized"),[payroll.batches]);
 const readyTotal=useMemo(()=>payroll.ready_earnings.reduce((s,e)=>s+Number(e.remaining_amount||0),0),[payroll.ready_earnings]);

 const accept=async(task:Handoff)=>{if(!supabase||!canFinance)return;setBusy(task.task_id);setError("");setMessage("");const{error:rpcError}=await supabase.rpc("act_on_comp_earning_handoff",{target_task_id:task.task_id,requested_action:"acknowledged",requested_payment_details:null,action_comments:comments[task.task_id]?.trim()||null});if(rpcError)setError(rpcError.message);else{setComments(x=>({...x,[task.task_id]:""}));setMessage("Finance accepted the earning for payment processing.");await load()}setBusy(null)};
 const createBatch=async()=>{if(!supabase||!canSchedule)return;if(!batchName.trim()){setError("Batch name is required.");return}setBusy("create-batch");setError("");setMessage("");const{data,error:rpcError}=await supabase.rpc("create_comp_payroll_batch",{requested_batch_name:batchName.trim(),requested_period_start:periodStart||null,requested_period_end:periodEnd||null,requested_payment_date:scheduledDate||null,requested_notes:batchNotes.trim()||null});if(rpcError)setError(rpcError.message);else{setActiveBatch(String(data));setBatchName("");setPeriodStart("");setPeriodEnd("");setScheduledDate("");setBatchNotes("");setMessage("Draft payroll batch created.");await load()}setBusy(null)};
 const addSelected=async()=>{if(!supabase||!canSchedule||!activeBatch||!selected.length)return;setBusy("add-items");setError("");setMessage("");let added=0;for(const id of selected){const earning=payroll.ready_earnings.find(x=>x.earning_id===id);const{error:rpcError}=await supabase.rpc("add_comp_earning_to_payroll_batch",{target_payroll_batch_id:activeBatch,target_earning_id:id,requested_amount:earning?.remaining_amount||null,requested_payment_details:null});if(rpcError){setError(rpcError.message);break}else added++}if(added){setSelected([]);setMessage(`Added ${added} earning${added===1?"":"s"} to the payroll batch.`);await load()}setBusy(null)};
 const scheduleBatch=async(batch:PayrollBatch)=>{if(!supabase||!canSchedule)return;if(!window.confirm(`Schedule ${batch.batch_name}? Once scheduled, its items are locked for this pay run.`))return;setBusy(`schedule-${batch.id}`);setError("");setMessage("");const{error:rpcError}=await supabase.rpc("schedule_comp_payroll_batch",{target_payroll_batch_id:batch.id});if(rpcError)setError(rpcError.message);else{setMessage(`${batch.batch_name} is scheduled.`);await load()}setBusy(null)};
 const markPaid=async(batch:PayrollBatch)=>{if(!supabase||!canMarkPaid)return;if(!paidDate){setError("Actual payment date is required.");return}if(!window.confirm(`Confirm ${batch.batch_name} was actually paid? This will mark included compensation Paid.`))return;setBusy(`paid-${batch.id}`);setError("");setMessage("");const{error:rpcError}=await supabase.rpc("mark_comp_payroll_batch_paid",{target_payroll_batch_id:batch.id,requested_actual_payment_date:paidDate,requested_payment_reference:paymentRef.trim()||null,requested_payment_method:paymentMethod.trim()||null,requested_notes:paidNotes.trim()||null});if(rpcError)setError(rpcError.message);else{setMessage(`${batch.batch_name} marked Paid.`);setPaymentRef("");setPaidNotes("");await load()}setBusy(null)};

 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1280,margin:"0 auto"}}>
  <nav style={{display:"flex",gap:9,alignItems:"center",marginBottom:18,flexWrap:"wrap"}}><Link href="/" style={{display:"inline-flex",alignItems:"center",gap:6,color:"#31465a",textDecoration:"none",fontWeight:700}}><Home size={16}/>Workspace</Link><ChevronRight size={15} color="#9aa7b4"/><Link href="/submissions" style={{color:"#31465a",fontWeight:700,textDecoration:"none"}}>Approvals</Link><ChevronRight size={15} color="#9aa7b4"/><b>Payments</b></nav>
  <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:18,flexWrap:"wrap"}}><div><small style={{fontWeight:800,letterSpacing:1.2,color:"#2095f3"}}>FINANCE & PAYROLL</small><h1 style={{fontSize:34,margin:"7px 0"}}>Payments</h1><p style={{margin:0,color:"#647184",maxWidth:850}}>Approved compensation moves through Finance acceptance, payroll scheduling, and actual payment confirmation. An earning remains <b>Unpaid</b> until payment is confirmed.</p></div><button onClick={load} disabled={loading} style={{display:"flex",alignItems:"center",gap:7,padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:700}}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>
  <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:16,marginBottom:18}}><div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}>{["Employee submits","Sharon reviews","Namit approves","Scott accepts","Payroll scheduled","Paid"].map((x,i)=><div key={x} style={{display:"flex",alignItems:"center",gap:8}}><span style={{padding:"8px 10px",border:"1px solid #dbe4ee",borderRadius:8,background:i===3?"#eaf5ff":"#f8fafc",fontWeight:700,fontSize:13}}>{x}</span>{i<5&&<ChevronRight size={15} color="#8b98a8"/>}</div>)}</div></section>
  {error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}
  {message&&<div style={{background:"#eefaf3",border:"1px solid #bfe4cd",borderRadius:10,padding:13,marginBottom:15,color:"#17643a",fontWeight:700}}>{message}</div>}

  <section style={{display:"flex",gap:8,marginBottom:14}}><button onClick={()=>setShowHistory(false)} style={{padding:"9px 12px",border:"1px solid #d6dee8",borderRadius:8,background:!showHistory?"#051b34":"white",color:!showHistory?"white":"#051b34",fontWeight:800}}>Finance handoff {pending.length}</button><button onClick={()=>setShowHistory(true)} style={{padding:"9px 12px",border:"1px solid #d6dee8",borderRadius:8,background:showHistory?"#051b34":"white",color:showHistory?"white":"#051b34",fontWeight:800}}>Handoff history</button></section>
  {!loading&&(showHistory?completed:pending).length>0&&<section style={{display:"grid",gap:10,marginBottom:18}}>{(showHistory?completed:pending).map(task=><article key={task.task_id} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:13,padding:17}}><div style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"flex-start",flexWrap:"wrap"}}><div><small style={{fontWeight:900,color:"#2095f3"}}>{task.step_name.toUpperCase()}</small><h2 style={{fontSize:19,margin:"5px 0 3px"}}>{task.employee_name} · {task.earning_name}</h2><small style={{color:"#718096"}}>Earned {task.earned_date} · Approved {money(task.approved_amount||task.earned_amount)} · Unpaid</small></div><span style={{fontWeight:800,padding:"5px 8px",borderRadius:999,background:task.status==="pending"?"#fff4df":"#e9f8ef"}}>{label(task.status)}</span></div>{task.assignee_activation_required&&task.status==="pending"&&<div style={{marginTop:11,padding:10,background:"#fff8e7",border:"1px solid #e7cf91",borderRadius:8,display:"flex",gap:7}}><AlertTriangle size={16}/><div><b>Configured for {task.assigned_employee_name||"Finance"}, but that user is not activated yet.</b><small style={{display:"block",marginTop:2,color:"#6d5a2f"}}>{isAdmin?"System Administrator may exercise this step for controlled testing; the audit trail preserves the actual actor.":"This handoff becomes actionable when the configured Finance user is activated."}</small></div></div>}{task.status==="pending"&&canFinance&&<div style={{marginTop:12,display:"grid",gap:8}}><input value={comments[task.task_id]||""} onChange={e=>setComments(x=>({...x,[task.task_id]:e.target.value}))} placeholder="Optional Finance note" style={{padding:"9px 10px",border:"1px solid #d6dee8",borderRadius:8}}/><button onClick={()=>accept(task)} disabled={busy!==null} style={{justifySelf:"start",display:"flex",gap:7,alignItems:"center",padding:"9px 12px",border:0,borderRadius:8,background:"#051b34",color:"white",fontWeight:800}}><CheckCircle2 size={16}/>{busy===task.task_id?"Accepting…":task.assignee_activation_required&&isAdmin?`Admin test accept as ${task.assigned_employee_name||"Finance"}`:"Accept for payment"}</button></div>}</article>)}</section>}

  <section style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(170px,1fr))",gap:10,marginBottom:20}}>{[["Ready for payroll",payroll.ready_earnings.length,readyTotal],["Scheduled",summary?.counts?.scheduled||0,summary?.amounts?.scheduled||0],["Held",summary?.counts?.held||0,summary?.amounts?.held||0],["Paid",summary?.counts?.paid||0,summary?.amounts?.paid||0]].map(([name,count,amount])=><div key={String(name)} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small style={{display:"block",fontWeight:800,color:"#718096"}}>{name}</small><b style={{display:"block",fontSize:24,margin:"5px 0"}}>{loading?"—":String(count)}</b><strong>{loading?"—":money(Number(amount))}</strong></div>)}</section>

  {canSchedule&&<section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18,marginBottom:18}}><div style={{display:"flex",justifyContent:"space-between",gap:15,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 4px"}}>Create payroll batch</h2><p style={{margin:0,color:"#647184"}}>Create a draft pay run, add ready earnings, then schedule it.</p></div><Plus size={22}/></div><div style={{display:"grid",gridTemplateColumns:"2fr repeat(3,1fr)",gap:9,marginTop:14}}><input value={batchName} onChange={e=>setBatchName(e.target.value)} placeholder="Batch name, e.g. Sep 15 Payroll" style={{padding:10,border:"1px solid #d6dee8",borderRadius:8}}/><input type="date" value={periodStart} onChange={e=>setPeriodStart(e.target.value)} title="Payroll period start" style={{padding:10,border:"1px solid #d6dee8",borderRadius:8}}/><input type="date" value={periodEnd} onChange={e=>setPeriodEnd(e.target.value)} title="Payroll period end" style={{padding:10,border:"1px solid #d6dee8",borderRadius:8}}/><input type="date" value={scheduledDate} onChange={e=>setScheduledDate(e.target.value)} title="Scheduled payment date" style={{padding:10,border:"1px solid #d6dee8",borderRadius:8}}/></div><div style={{display:"flex",gap:9,marginTop:9}}><input value={batchNotes} onChange={e=>setBatchNotes(e.target.value)} placeholder="Optional batch note" style={{flex:1,padding:10,border:"1px solid #d6dee8",borderRadius:8}}/><button onClick={createBatch} disabled={busy!==null} style={{padding:"10px 14px",border:0,borderRadius:8,background:"#2095f3",color:"white",fontWeight:800}}>Create draft batch</button></div></section>}

  <section style={{display:"grid",gridTemplateColumns:"minmax(0,1.15fr) minmax(360px,.85fr)",gap:16,alignItems:"start"}}><div style={{display:"grid",gap:16}}><section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 4px"}}>Ready for payroll</h2><p style={{margin:0,color:"#647184"}}>Approved and Finance-accepted earnings that are still unpaid.</p></div>{payroll.ready_earnings.length>0&&<b>{money(readyTotal)}</b>}</div>{payroll.ready_earnings.length===0?<div style={{padding:"24px 0",textAlign:"center",color:"#647184"}}>Nothing is ready for payroll.</div>:<div style={{display:"grid",gap:8,marginTop:14}}>{payroll.ready_earnings.map(e=><label key={e.earning_id} style={{display:"grid",gridTemplateColumns:"auto 1.3fr 1fr auto",gap:10,alignItems:"center",padding:"11px 12px",background:"#f8fafc",borderRadius:9}}><input type="checkbox" checked={selected.includes(e.earning_id)} onChange={()=>setSelected(s=>s.includes(e.earning_id)?s.filter(x=>x!==e.earning_id):[...s,e.earning_id])}/><div><b>{e.employee_name}</b><small style={{display:"block",color:"#718096"}}>{e.earning_name} · {e.earned_date}</small></div><span><small style={{display:"block",color:"#718096"}}>Status</small><b>Unpaid</b></span><strong>{money(e.remaining_amount)}</strong></label>)}</div>}{canSchedule&&payroll.ready_earnings.length>0&&<div style={{display:"flex",gap:9,marginTop:14,alignItems:"center",flexWrap:"wrap"}}><select value={activeBatch} onChange={e=>setActiveBatch(e.target.value)} style={{padding:10,border:"1px solid #d6dee8",borderRadius:8,minWidth:230}}><option value="">Select draft batch</option>{drafts.map(b=><option key={b.id} value={b.id}>{b.batch_name}</option>)}</select><button onClick={addSelected} disabled={!activeBatch||!selected.length||busy!==null} style={{padding:"10px 13px",border:0,borderRadius:8,background:"#051b34",color:"white",fontWeight:800,opacity:!activeBatch||!selected.length?.5:1}}>Add selected ({selected.length})</button></div>}</section>

  <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><h2 style={{marginTop:0}}>Payroll batches</h2>{payroll.batches.length===0?<div style={{textAlign:"center",padding:24,color:"#647184"}}><Clock3 size={24}/><p>No payroll batches yet.</p></div>:<div style={{display:"grid",gap:10}}>{payroll.batches.map(batch=>{const amount=batch.items.reduce((s,i)=>s+Number(i.amount||0),0);return <article key={batch.id} style={{border:"1px solid #e2e8ef",borderRadius:11,padding:13}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start"}}><div><b>{batch.batch_name}</b><small style={{display:"block",marginTop:4,color:"#718096"}}>{batch.items.length} item{batch.items.length===1?"":"s"} · {money(amount)}</small></div><span style={{fontWeight:800,padding:"4px 8px",borderRadius:999,background:batch.status==="paid"?"#e9f8ef":batch.status==="scheduled"?"#eaf5ff":"#f3f5f7"}}>{label(batch.status)}</span></div>{batch.items.length>0&&<div style={{display:"grid",gap:5,marginTop:10}}>{batch.items.map(i=><div key={i.id} style={{display:"flex",justifyContent:"space-between",gap:10,fontSize:13}}><span>{i.employee_name} · {i.earning_name}</span><b>{money(i.amount)}</b></div>)}</div>}{batch.status==="draft"&&canSchedule&&<button onClick={()=>scheduleBatch(batch)} disabled={!batch.items.length||busy!==null} style={{marginTop:11,padding:"9px 12px",border:0,borderRadius:8,background:"#2095f3",color:"white",fontWeight:800}}>Schedule payroll</button>}{(batch.status==="scheduled"||batch.status==="finalized")&&canMarkPaid&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:11}}><input type="date" value={paidDate} onChange={e=>setPaidDate(e.target.value)} style={{padding:9,border:"1px solid #d6dee8",borderRadius:8}}/><input value={paymentRef} onChange={e=>setPaymentRef(e.target.value)} placeholder="Payment reference" style={{padding:9,border:"1px solid #d6dee8",borderRadius:8}}/><input value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)} placeholder="Payment method" style={{padding:9,border:"1px solid #d6dee8",borderRadius:8}}/><input value={paidNotes} onChange={e=>setPaidNotes(e.target.value)} placeholder="Optional payment note" style={{padding:9,border:"1px solid #d6dee8",borderRadius:8}}/><button onClick={()=>markPaid(batch)} disabled={busy!==null} style={{gridColumn:"1 / -1",padding:"9px 12px",border:0,borderRadius:8,background:"#14804a",color:"white",fontWeight:800}}>Confirm Paid</button></div>}{batch.status==="paid"&&<small style={{display:"block",marginTop:9,color:"#17643a",fontWeight:700}}>Paid {batch.actual_payment_date||""}{batch.payment_reference?` · ${batch.payment_reference}`:""}</small>}</article>})}</div>}</section></div>

  <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><h2 style={{marginTop:0}}>Employee payout status</h2><p style={{color:"#647184",marginTop:-7}}>One concise view of where approved compensation stands.</p><div style={{display:"grid",gap:8,marginTop:14}}>{(summary?.employees||[]).filter(x=>x.ready_for_payroll_count||x.held_count).map(row=><div key={row.employee_id} style={{display:"grid",gridTemplateColumns:"1.5fr .7fr 1fr",gap:10,alignItems:"center",padding:"11px 12px",background:"#f8fafc",borderRadius:9}}><b>{row.employee_name}</b><span><small style={{display:"block",color:"#7b8794"}}>Ready</small>{row.ready_for_payroll_count}</span><strong style={{textAlign:"right"}}>{money(row.ready_amount)}</strong></div>)}</div></section></section>
 </div></main>
}
