"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {CheckCircle2,ChevronRight,Home,RefreshCw,Search} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;
type Access={roles?:string[];permissions?:string[]};
type Handoff={task_id:string;earning_id:string;status:string;assigned_employee_name:string|null;assignee_activation_required:boolean;employee_name:string;earning_name:string;earned_date:string;approved_amount:number;earned_amount:number};
type PaymentItem={earning_id:string;employee_id:string;employee_name:string;earning_name:string;earned_date:string;approved_amount:number;paid_amount:number;remaining_amount?:number;payment_status:string;pay_period_start:string|null;pay_period_end:string|null;pay_period_label:string|null;actual_payment_date?:string|null;payment_reference?:string|null;payment_method?:string|null};
type Workspace={accepted_unpaid:PaymentItem[];paid:PaymentItem[]};
type PeriodChoice={month:string;kind:"first"|"second"|"custom";start:string;end:string};

const C={navy:"#051b34",blue:"#2095f3",muted:"#647184",border:"#dfe6ee",bg:"#f5f7fa"};
const card={background:"white",border:`1px solid ${C.border}`,borderRadius:14,padding:18} as const;
const input={boxSizing:"border-box" as const,padding:"10px 12px",border:"1px solid #d6dee8",borderRadius:9,background:"white",font:"inherit",color:C.navy};
const buttonLight={display:"inline-flex",alignItems:"center",gap:7,padding:"10px 13px",background:"white",border:"1px solid #d6dee8",borderRadius:9,fontWeight:800,color:C.navy,cursor:"pointer"} as const;
const buttonDark={display:"inline-flex",alignItems:"center",gap:7,padding:"10px 14px",background:C.navy,border:"none",borderRadius:9,fontWeight:800,color:"white",cursor:"pointer"} as const;
const labelStyle={display:"block",fontSize:12,fontWeight:800,color:"#718096",marginBottom:4};
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function today(){return new Date().toISOString().slice(0,10)}
function monthKey(){return today().slice(0,7)}
function lastDay(month:string){if(!/^\d{4}-\d{2}$/.test(month))return "";const[y,m]=month.split("-").map(Number);return new Date(Date.UTC(y,m,0)).toISOString().slice(0,10)}
function prettyDate(d:string|null|undefined){if(!d)return "—";return new Date(`${d}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}
function prettyPeriod(start:string|null,end:string|null,label?:string|null){return label||(start&&end?`${prettyDate(start)} – ${prettyDate(end)}`:"Not assigned")}
function periodDates(p:PeriodChoice){if(p.kind==="custom")return{start:p.start,end:p.end,label:p.start&&p.end?`${prettyDate(p.start)} – ${prettyDate(p.end)}`:""};const start=`${p.month}-${p.kind==="first"?"01":"16"}`;const end=p.kind==="first"?`${p.month}-15`:lastDay(p.month);return{start,end,label:`${prettyDate(start)} – ${prettyDate(end)}`}}
function defaultPeriod():PeriodChoice{return{month:monthKey(),kind:"first",start:"",end:""}}

export default function PaymentsPage(){
 const[access,setAccess]=useState<Access|null>(null),[handoffs,setHandoffs]=useState<Handoff[]>([]),[workspace,setWorkspace]=useState<Workspace>({accepted_unpaid:[],paid:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState<string|null>(null);
 const[view,setView]=useState<"current"|"past">("current"),[search,setSearch]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState("");
 const[periods,setPeriods]=useState<Record<string,PeriodChoice>>({}),[notes,setNotes]=useState<Record<string,string>>({}),[paidDate,setPaidDate]=useState<Record<string,string>>({}),[paymentRef,setPaymentRef]=useState<Record<string,string>>({}),[paymentMethod,setPaymentMethod]=useState<Record<string,string>>({});
 const isAdmin=Boolean(access?.roles?.includes("system_administrator"));
 const canView=isAdmin||Boolean(access?.permissions?.includes("payments.view"));
 const canMarkPaid=isAdmin||Boolean(access?.permissions?.includes("payments.mark_paid"));
 const load=async()=>{if(!supabase){setError("Database connection unavailable.");setLoading(false);return}setLoading(true);setError("");const[a,b,c]=await Promise.all([supabase.rpc("get_current_user_access"),supabase.rpc("get_my_comp_earning_handoff_tasks",{include_completed:false}),supabase.rpc("get_finance_payment_workspace_data")]);if(a.error)setError(a.error.message);else setAccess((a.data||{}) as Access);if(b.error)setError(x=>x||b.error.message);else setHandoffs(((b.data||[]) as Handoff[]).filter(x=>x.status==="pending"));if(c.error)setError(x=>x||c.error.message);else setWorkspace((c.data||{accepted_unpaid:[],paid:[]}) as Workspace);setLoading(false)};
 useEffect(()=>{load()},[]);
 const periodFor=(id:string)=>periods[id]||defaultPeriod();
 const setPeriod=(id:string,patch:Partial<PeriodChoice>)=>setPeriods(x=>({...x,[id]:{...periodFor(id),...patch}}));
 const accept=async(task:Handoff)=>{if(!supabase||!canView)return;const p=periodDates(periodFor(task.task_id));if(!p.start||!p.end){setError("Choose a payroll period before accepting.");return}setBusy(task.task_id);setError("");setMessage("");const{error:e}=await supabase.rpc("accept_comp_earning_for_pay_period",{target_task_id:task.task_id,requested_pay_period_start:p.start,requested_pay_period_end:p.end,requested_pay_period_label:p.label||null,action_comments:notes[task.task_id]?.trim()||null});if(e)setError(e.message);else{setMessage(`${task.employee_name} accepted for ${p.label}.`);await load()}setBusy(null)};
 const markPaid=async(item:PaymentItem)=>{if(!supabase||!canMarkPaid)return;const date=paidDate[item.earning_id]||today();if(!window.confirm(`Confirm ${money(item.remaining_amount||0)} paid to ${item.employee_name} on ${prettyDate(date)}?`))return;setBusy(item.earning_id);setError("");const{error:e}=await supabase.rpc("mark_comp_earning_paid",{target_earning_id:item.earning_id,requested_actual_payment_date:date,requested_payment_reference:paymentRef[item.earning_id]?.trim()||null,requested_payment_method:paymentMethod[item.earning_id]?.trim()||"Payroll",requested_notes:null});if(e)setError(e.message);else{setMessage(`${item.employee_name}: payment recorded.`);await load()}setBusy(null)};
 const match=(name:string,date:string|null|undefined)=>{const q=search.trim().toLowerCase();if(q&&!name.toLowerCase().includes(q))return false;if(dateFrom&&date&&date<dateFrom)return false;if(dateTo&&date&&date>dateTo)return false;return true};
 const currentHandoffs=useMemo(()=>handoffs.filter(x=>match(`${x.employee_name} ${x.earning_name}`,x.earned_date)),[handoffs,search,dateFrom,dateTo]);
 const currentUnpaid=useMemo(()=>workspace.accepted_unpaid.filter(x=>match(`${x.employee_name} ${x.earning_name}`,x.earned_date)),[workspace.accepted_unpaid,search,dateFrom,dateTo]);
 const paidRows=useMemo(()=>workspace.paid.filter(x=>match(`${x.employee_name} ${x.earning_name}`,x.actual_payment_date||x.earned_date)),[workspace.paid,search,dateFrom,dateTo]);
 const unpaidTotal=workspace.accepted_unpaid.reduce((s,x)=>s+Number(x.remaining_amount||0),0);
 const paidTotal=workspace.paid.reduce((s,x)=>s+Number(x.paid_amount||0),0);
 const PeriodPicker=({id}:{id:string})=>{const p=periodFor(id);return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(140px,1fr))",gap:8}}><input type="month" value={p.month} onChange={e=>setPeriod(id,{month:e.target.value})} style={input}/><select value={p.kind} onChange={e=>setPeriod(id,{kind:e.target.value as PeriodChoice["kind"]})} style={input}><option value="first">1–15</option><option value="second">16–end</option><option value="custom">Custom</option></select>{p.kind==="custom"&&<><input type="date" value={p.start} onChange={e=>setPeriod(id,{start:e.target.value})} style={input}/><input type="date" value={p.end} onChange={e=>setPeriod(id,{end:e.target.value})} style={input}/></>}</div>};

 return <main style={{minHeight:"100vh",background:C.bg,padding:"clamp(16px,3vw,28px)",fontFamily:"Inter,Arial,sans-serif",color:C.navy}}><div style={{maxWidth:1280,margin:"0 auto"}}>
  <nav style={{display:"flex",gap:9,alignItems:"center",marginBottom:18}}><Link href="/manage" style={{display:"inline-flex",alignItems:"center",gap:6,color:"#31465a",textDecoration:"none",fontWeight:700}}><Home size={16}/>Control Center</Link><ChevronRight size={15}/><b>Payments</b></nav>
  <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:18,flexWrap:"wrap"}}><div><small style={{fontWeight:800,letterSpacing:1.2,color:C.blue}}>FINANCE & PAYROLL</small><h1 style={{fontSize:34,margin:"7px 0"}}>Payments</h1><p style={{margin:0,color:C.muted,maxWidth:800}}>See what is waiting to be paid, what Finance has accepted, and the complete payment history by employee and date.</p></div><button onClick={load} disabled={loading} style={buttonLight}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>
  {error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:14,color:"#8b2f2f"}}>{error}</div>}{message&&<div style={{background:"#edf9f2",border:"1px solid #bfe6ce",borderRadius:10,padding:13,marginBottom:14,color:"#17643a"}}>{message}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginBottom:16}}><div style={card}><small style={labelStyle}>Pending Finance acceptance</small><b style={{fontSize:26}}>{handoffs.length}</b></div><div style={card}><small style={labelStyle}>Accepted / unpaid</small><b style={{fontSize:26}}>{workspace.accepted_unpaid.length}</b><div style={{fontWeight:800}}>{money(unpaidTotal)}</div></div><div style={card}><small style={labelStyle}>Paid history</small><b style={{fontSize:26}}>{workspace.paid.length}</b><div style={{fontWeight:800}}>{money(paidTotal)}</div></div></section>
  <section style={{...card,marginBottom:16,padding:14}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><button onClick={()=>setView("current")} style={{...buttonLight,background:view==="current"?C.navy:"white",color:view==="current"?"white":C.navy}}>Current / pending</button><button onClick={()=>setView("past")} style={{...buttonLight,background:view==="past"?C.navy:"white",color:view==="past"?"white":C.navy}}>Past payments</button><div style={{display:"flex",alignItems:"center",gap:6,marginLeft:"auto",minWidth:220}}><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search employee or earning" style={{...input,width:"100%"}}/></div><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} style={input} aria-label="Date from"/><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} style={input} aria-label="Date to"/></div></section>

  {view==="current"?<>
   <section style={{marginBottom:24}}><h2 style={{fontSize:20}}>Pending Finance acceptance</h2>{currentHandoffs.length===0?<div style={{...card,textAlign:"center",color:C.muted}}>Nothing is waiting for Finance acceptance.</div>:<div style={{display:"grid",gap:10}}>{currentHandoffs.map(task=><article key={task.task_id} style={card}><div style={{display:"grid",gridTemplateColumns:"minmax(220px,1.5fr) repeat(2,minmax(150px,1fr))",gap:14}}><div><b>{task.employee_name}</b><div style={{color:C.muted,fontSize:13}}>{task.earning_name}</div></div><div><small style={labelStyle}>Earned date</small>{prettyDate(task.earned_date)}</div><div><small style={labelStyle}>Amount</small><b>{money(task.approved_amount||task.earned_amount)}</b></div></div><div style={{marginTop:12}}><small style={labelStyle}>Pay period</small><PeriodPicker id={task.task_id}/></div><input value={notes[task.task_id]||""} onChange={e=>setNotes(x=>({...x,[task.task_id]:e.target.value}))} placeholder="Optional Finance note" style={{...input,width:"100%",marginTop:8}}/><button onClick={()=>accept(task)} disabled={busy!==null} style={{...buttonDark,marginTop:10}}><CheckCircle2 size={16}/>{busy===task.task_id?"Accepting…":"Accept into payroll period"}</button></article>)}</div>}</section>
   <section><h2 style={{fontSize:20}}>Accepted / unpaid</h2>{currentUnpaid.length===0?<div style={{...card,textAlign:"center",color:C.muted}}>No accepted unpaid compensation.</div>:<div style={{display:"grid",gap:10}}>{currentUnpaid.map(item=><article key={item.earning_id} style={card}><div style={{display:"grid",gridTemplateColumns:"minmax(220px,1.5fr) repeat(3,minmax(150px,1fr))",gap:14}}><div><b>{item.employee_name}</b><div style={{color:C.muted,fontSize:13}}>{item.earning_name}</div></div><div><small style={labelStyle}>Earned date</small>{prettyDate(item.earned_date)}</div><div><small style={labelStyle}>Pay period</small>{prettyPeriod(item.pay_period_start,item.pay_period_end,item.pay_period_label)}</div><div><small style={labelStyle}>Pending payment</small><b>{money(item.remaining_amount||0)}</b></div></div>{canMarkPaid&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:8,marginTop:12}}><label><small style={labelStyle}>Paid date</small><input type="date" value={paidDate[item.earning_id]||today()} onChange={e=>setPaidDate(x=>({...x,[item.earning_id]:e.target.value}))} style={{...input,width:"100%"}}/></label><label><small style={labelStyle}>Payment method</small><input value={paymentMethod[item.earning_id]||"Payroll"} onChange={e=>setPaymentMethod(x=>({...x,[item.earning_id]:e.target.value}))} style={{...input,width:"100%"}}/></label><label><small style={labelStyle}>Reference</small><input value={paymentRef[item.earning_id]||""} onChange={e=>setPaymentRef(x=>({...x,[item.earning_id]:e.target.value}))} placeholder="Optional" style={{...input,width:"100%"}}/></label><div style={{display:"flex",alignItems:"end"}}><button onClick={()=>markPaid(item)} disabled={busy!==null} style={buttonDark}>{busy===item.earning_id?"Saving…":"Mark paid"}</button></div></div>}</article>)}</div>}</section>
  </>:<section><h2 style={{fontSize:20}}>Payment history</h2>{paidRows.length===0?<div style={{...card,textAlign:"center",color:C.muted}}>No paid compensation matches these filters.</div>:<div style={{overflowX:"auto",background:"white",border:`1px solid ${C.border}`,borderRadius:14}}><table style={{width:"100%",borderCollapse:"collapse",minWidth:900}}><thead><tr>{["Employee","Earning","Earned","Paid date","Pay period","Paid amount","Method / reference"].map(h=><th key={h} style={{textAlign:"left",padding:"11px 12px",borderBottom:`1px solid ${C.border}`,fontSize:12,color:"#718096"}}>{h}</th>)}</tr></thead><tbody>{paidRows.map(item=><tr key={item.earning_id}><td style={{padding:12,borderBottom:"1px solid #eef1f4",fontWeight:800}}>{item.employee_name}</td><td style={{padding:12,borderBottom:"1px solid #eef1f4"}}>{item.earning_name}</td><td style={{padding:12,borderBottom:"1px solid #eef1f4"}}>{prettyDate(item.earned_date)}</td><td style={{padding:12,borderBottom:"1px solid #eef1f4"}}>{prettyDate(item.actual_payment_date)}</td><td style={{padding:12,borderBottom:"1px solid #eef1f4"}}>{prettyPeriod(item.pay_period_start,item.pay_period_end,item.pay_period_label)}</td><td style={{padding:12,borderBottom:"1px solid #eef1f4",fontWeight:800}}>{money(item.paid_amount||0)}</td><td style={{padding:12,borderBottom:"1px solid #eef1f4"}}>{item.payment_method||"—"}{item.payment_reference?` · ${item.payment_reference}`:""}</td></tr>)}</tbody></table></div>}</section>}
 </div></main>;
}
