"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowLeft, ChevronDown, ChevronUp, Eye, History, Plus, Save, ShieldCheck, Trash2, Users, WalletCards } from "lucide-react";
import { createClient } from "@supabase/supabase-js";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");

type WorkflowSummary={workflow_version_id:string;workflow_name:string;effective_start_date:string;effective_end_date:string|null;status:string;step_count:number;unresolved_approver_count?:number;post_approval_step_count?:number;unresolved_post_assignee_count?:number};
type Employee={employee_id:string;full_name:string;email:string;job_title:string|null;is_active:boolean;current_workflow:WorkflowSummary|null;planned_workflow?:WorkflowSummary|null};
type Approver={employee_id:string;user_id:string|null;full_name:string;email:string;provisioning_status:"active"|"preinvite"|"unavailable"};
type Step={step_name:string;approver_employee_id:string;backup_approver_employee_id:string};
type PostStep={id:string;step_order:number;step_name:string;step_type:string;assignee_name:string|null;assignee_provisioning_status:string;is_required:boolean;requires_payment_details:boolean};
type HistoryRow={workflow_version_id:string;workflow_name:string;status:string;effective_start_date:string;effective_end_date:string|null;steps:any[];post_approval_steps?:PostStep[]};

const blank=():Step=>({step_name:"",approver_employee_id:"",backup_approver_employee_id:""});
const today=()=>new Date().toISOString().slice(0,10);
const yearOf=(d:string)=>d?.slice(0,4)||new Date().getFullYear().toString();
const stageLabel=(s:PostStep)=>s.step_type==="finance_acknowledgement"?"Required finance handoff":s.step_type==="optional_executive_review"?"Optional executive review":"Post-approval task";

export default function ApprovalWorkflowsPage(){
 const [data,setData]=useState<{employees:Employee[];eligible_approvers:Approver[]}>({employees:[],eligible_approvers:[]}); const [employeeId,setEmployeeId]=useState(""); const [history,setHistory]=useState<HistoryRow[]>([]); const [start,setStart]=useState(today()); const [notes,setNotes]=useState(""); const [steps,setSteps]=useState<Step[]>([blank()]); const [previewDate,setPreviewDate]=useState(today()); const [preview,setPreview]=useState<any>(null); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [saving,setSaving]=useState(false);
 const employee=useMemo(()=>data.employees.find(x=>x.employee_id===employeeId)||null,[data,employeeId]); const approvers=useMemo(()=>data.eligible_approvers.filter(x=>x.employee_id!==employeeId),[data,employeeId]); const activeApprovers=approvers.filter(x=>x.provisioning_status==="active"); const plannedApprovers=approvers.filter(x=>x.provisioning_status==="preinvite"); const workflowName=employee?`${employee.full_name} Approval Workflow — ${yearOf(start)}`:"Approval Workflow"; const replacementValid=!employee?.current_workflow||start>employee.current_workflow.effective_start_date; const valid=!!start&&replacementValid&&steps.every(x=>x.step_name.trim()&&x.approver_employee_id); const containsPreinvite=steps.some(s=>approvers.find(a=>a.employee_id===s.approver_employee_id)?.provisioning_status==="preinvite"||(s.backup_approver_employee_id&&approvers.find(a=>a.employee_id===s.backup_approver_employee_id)?.provisioning_status==="preinvite"));
 const selectedSaved=history.find(h=>h.workflow_version_id===(employee?.planned_workflow?.workflow_version_id||employee?.current_workflow?.workflow_version_id));
 const savedPostSteps=selectedSaved?.post_approval_steps||[];
 const load=async()=>{setError("");const {data:r,error:e}=await supabase.rpc("get_approval_workflow_admin_data");if(e){setError(e.message);return}const d=r||{employees:[],eligible_approvers:[]};const requestedEmployee=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("employee")||"":"";setData(d);setEmployeeId(current=>current&&d.employees?.some((x:Employee)=>x.employee_id===current)?current:requestedEmployee&&d.employees?.some((x:Employee)=>x.employee_id===requestedEmployee)?requestedEmployee:d.employees?.[0]?.employee_id||"")};
 const loadHistory=async(id:string)=>{const {data:r,error:e}=await supabase.rpc("get_employee_approval_workflows",{selected_employee_id:id});if(e)setError(e.message);else setHistory(r||[])};
 useEffect(()=>{load()},[]); useEffect(()=>{if(employeeId){loadHistory(employeeId);setStart(today());setNotes("");setSteps([blank()]);setPreview(null);setError("");setNotice("")}},[employeeId]);
 const updateStep=(i:number,patch:Partial<Step>)=>setSteps(xs=>xs.map((s,n)=>n===i?{...s,...patch}:s)); const move=(i:number,d:number)=>setSteps(xs=>{const next=[...xs],j=i+d;if(j<0||j>=next.length)return xs;[next[i],next[j]]=[next[j],next[i]];return next}); const payload=()=>steps.map(s=>({step_name:s.step_name.trim(),approval_level:"other",approver_employee_id:s.approver_employee_id,backup_approver_employee_id:s.backup_approver_employee_id||null,is_required:true,conditions:{}}));
 const save=async()=>{if(!employee||!valid)return;setSaving(true);setError("");setNotice("");const args={selected_workflow_name:workflowName,selected_effective_start_date:start,selected_effective_end_date:null,selected_steps:payload(),selected_notes:notes||null};const result=employee.current_workflow?await supabase.rpc("replace_employee_approval_workflow",{selected_current_workflow_version_id:employee.current_workflow.workflow_version_id,...args}):await supabase.rpc("create_employee_approval_workflow",{selected_employee_id:employeeId,...args});if(result.error){setError(result.error.message);setSaving(false);return}const status=result.data?.status;if(status==="draft_pending_approvers"||status==="replacement_pending_approvers")setNotice("Planned workflow saved. It cannot route earnings until every required participant has an active app account.");else setNotice(employee.current_workflow?"Workflow replacement saved and activated.":"Approval workflow saved and activated.");await load();await loadHistory(employeeId);setSteps([blank()]);setNotes("");setSaving(false)};
 const activatePlanned=async()=>{if(!employee?.planned_workflow)return;setSaving(true);setError("");setNotice("");const {data:r,error:e}=await supabase.rpc("activate_ready_employee_approval_workflow",{selected_workflow_version_id:employee.planned_workflow.workflow_version_id});if(e)setError(e.message);else if(r?.status==="not_ready")setNotice(`Workflow is still waiting on ${r.unresolved_approver_count} required participant account${r.unresolved_approver_count===1?"":"s"}.`);else setNotice("Planned workflow is now active.");await load();await loadHistory(employeeId);setSaving(false)};
 const testRouting=async()=>{const {data:r,error:e}=await supabase.rpc("preview_employee_approval_workflow",{selected_employee_id:employeeId,selected_earned_date:previewDate});if(e)setError(e.message);else setPreview(r)};
 return <main className="min-h-screen bg-[#f6f8fc] text-[#252b35]">
 <header className="border-t-[7px] border-[#a7e3e5] bg-white shadow-sm"><div className="mx-auto flex max-w-[1500px] items-center justify-between px-6 py-4"><div className="flex items-center gap-4"><a href="/employee-administration" className="grid h-9 w-9 place-items-center rounded-lg border text-[#2095f3]"><ArrowLeft size={17}/></a><div><p className="text-[10px] font-extrabold tracking-[.12em] text-[#8d939c]">ADMINISTRATION</p><h1 className="text-xl font-bold">Approval Workflows</h1></div></div><div className="flex items-center gap-2 rounded-lg bg-[#edf6ff] px-3 py-2 text-xs font-semibold text-[#0879d5]"><ShieldCheck size={15}/> Effective-dated & history-safe</div></div></header>
 <div className="mx-auto grid max-w-[1500px] gap-5 px-6 py-6 lg:grid-cols-[360px_minmax(0,1fr)]">
 <aside className="self-start rounded-xl border bg-white p-4 shadow-sm"><div className="mb-4 flex justify-between"><div><h2 className="text-sm font-bold">Employees</h2><p className="mt-1 text-xs text-[#77808e]">Select an employee to manage routing.</p></div><Users size={18} className="text-[#2095f3]"/></div>{data.employees.map(x=><button key={x.employee_id} onClick={()=>setEmployeeId(x.employee_id)} className={`mb-2 w-full rounded-lg border p-3 text-left ${x.employee_id===employeeId?"border-[#2095f3] bg-[#eef7ff]":"bg-white"}`}><div className="flex justify-between gap-2"><div><b className="text-sm">{x.full_name}</b><div className="mt-1 text-[11px] text-[#77808e]">{x.job_title||x.email}</div></div><span className={`h-fit rounded-full px-2 py-1 text-[10px] font-bold ${x.current_workflow?"bg-[#e9f8f2] text-[#17795e]":x.planned_workflow?"bg-[#edf6ff] text-[#0879d5]":"bg-[#fff1d3] text-[#946407]"}`}>{x.current_workflow?"Active":x.planned_workflow?"Planned":"Missing workflow"}</span></div>{x.planned_workflow&&<div className="mt-2 text-[10px] text-[#66717f]">Waiting on {x.planned_workflow.unresolved_approver_count||0} required participant account{x.planned_workflow.unresolved_approver_count===1?"":"s"}</div>}</button>)}</aside>
 <section className="space-y-5">{error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
 <div className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><b className="text-sm">Available approvers</b><p className="mt-1 text-xs text-[#77808e]">Active accounts can route immediately. Pre-invite people can be included in planned workflows, which stay inactive until required participants activate.</p></div><div className="flex gap-2"><span className="rounded-full bg-[#e9f8f2] px-3 py-1 text-[10px] font-bold text-[#17795e]">{activeApprovers.length} active</span><span className="rounded-full bg-[#edf6ff] px-3 py-1 text-[10px] font-bold text-[#0879d5]">{plannedApprovers.length} pre-invite</span></div></div></div>
 {employee?.planned_workflow&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-sm font-bold text-blue-900"><AlertTriangle size={16}/> Planned workflow is not live</div><p className="mt-1 text-xs text-blue-800">{employee.planned_workflow.workflow_name} is saved, but {employee.planned_workflow.unresolved_approver_count||0} required participant account{employee.planned_workflow.unresolved_approver_count===1?" is":"s are"} unresolved. No approval or payment tasks can route yet.</p></div><button onClick={activatePlanned} disabled={saving} className="rounded-lg border border-blue-300 bg-white px-3 py-2 text-xs font-bold text-blue-800">Check & activate</button></div></div>}
 {savedPostSteps.length>0&&<div className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><WalletCards size={17} className="text-[#2095f3]"/><h3 className="text-sm font-bold">Saved approval & payment flow</h3></div><p className="mt-1 text-xs text-[#77808e]">After required approval is complete, these tasks open together. Required finance tasks can hold payment; optional executive review cannot.</p><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-lg border border-emerald-100 bg-[#f3fbf7] p-3"><div className="text-[10px] font-extrabold text-emerald-700">1 · REQUIRED APPROVAL</div><div className="mt-1 text-sm font-bold">{selectedSaved?.steps?.[0]?.step_name||"Approval"}</div><div className="mt-1 text-xs">{selectedSaved?.steps?.[0]?.approver_name||"Unassigned"}</div></div>{savedPostSteps.map((s,i)=><div key={s.id} className={`rounded-lg border p-3 ${s.is_required?"border-amber-200 bg-amber-50":"border-blue-100 bg-blue-50"}`}><div className={`text-[10px] font-extrabold ${s.is_required?"text-amber-800":"text-blue-700"}`}>2{String.fromCharCode(65+i)} · {stageLabel(s).toUpperCase()}</div><div className="mt-1 text-sm font-bold">{s.step_name}</div><div className="mt-1 text-xs">{s.assignee_name||"Unassigned"}</div><div className="mt-2 flex flex-wrap gap-1"><span className="rounded-full bg-white px-2 py-0.5 text-[9px] font-bold">{s.is_required?"Required":"Optional"}</span>{s.requires_payment_details&&<span className="rounded-full bg-white px-2 py-0.5 text-[9px] font-bold">Payment info required</span>}<span className="rounded-full bg-white px-2 py-0.5 text-[9px] font-bold">{s.assignee_provisioning_status==="active"?"Active":"Pre-invite"}</span></div></div>)}</div></div>}
 <div className="rounded-xl border bg-white p-5 shadow-sm"><div className="mb-5 flex justify-between gap-4"><div><p className="text-[10px] font-extrabold tracking-[.1em] text-[#2095f3]">EMPLOYEE WORKFLOW</p><h2 className="mt-1 text-xl font-bold">{employee?.full_name||"Select employee"}</h2><p className="mt-1 text-xs text-[#77808e]">{employee?.job_title||employee?.email}</p></div>{employee?.current_workflow?<div className="h-fit min-w-[260px] rounded-lg border border-emerald-100 bg-[#f3fbf7] px-3 py-2 text-xs"><b className="text-[#17795e]">Current workflow</b><div className="mt-1 font-semibold">{employee.current_workflow.step_count} approval step{employee.current_workflow.step_count===1?"":"s"}</div><div className="mt-1 text-[#66717f]">Effective {employee.current_workflow.effective_start_date} until replaced</div></div>:<span className="h-fit rounded-lg bg-[#fff6df] px-3 py-2 text-xs font-semibold text-[#946407]">Workflow required</span>}</div>
 <div className="grid gap-4 rounded-lg border bg-[#fafbfd] p-4 md:grid-cols-2"><div><div className="text-xs font-semibold">Workflow</div><div className="mt-1 rounded-lg border bg-white px-3 py-2.5 text-sm">{workflowName}</div><span className="mt-1 block text-[10px] text-[#77808e]">Named automatically from the employee and effective year.</span></div><label className="text-xs font-semibold">Effective start *<input type="date" value={start} onChange={e=>setStart(e.target.value)} className="mt-1 w-full rounded-lg border bg-white px-3 py-2.5 text-sm font-normal"/></label></div>
 <div className="mt-5"><div className="mb-3 flex justify-between"><div><h3 className="text-sm font-bold">Approval steps</h3><p className="mt-1 text-xs text-[#77808e]">These are required approval gates. Finance/payment handoffs are shown separately above when configured.</p></div><button onClick={()=>setSteps(xs=>[...xs,blank()])} className="flex items-center gap-1 rounded-lg border border-[#2095f3] px-3 py-2 text-xs font-bold text-[#0879d5]"><Plus size={14}/>Add step</button></div><div className="space-y-3">{steps.map((s,i)=><div key={i} className="grid gap-3 rounded-lg border p-3 md:grid-cols-[42px_1.2fr_1fr_1fr_auto]"><div className="grid h-8 w-8 place-items-center rounded-full bg-[#2095f3] text-xs font-bold text-white">{i+1}</div><label className="text-[10px] font-bold">STEP LABEL<input value={s.step_name} onChange={e=>updateStep(i,{step_name:e.target.value})} placeholder="e.g. Manager approval" className="mt-1 w-full rounded-lg border px-3 py-2 text-xs font-normal"/></label><label className="text-[10px] font-bold">PRIMARY APPROVER<select value={s.approver_employee_id} onChange={e=>updateStep(i,{approver_employee_id:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 text-xs font-normal"><option value="">Select approver</option>{approvers.map(a=><option key={a.employee_id} value={a.employee_id}>{a.full_name}{a.provisioning_status==="preinvite"?" · pre-invite":""}</option>)}</select></label><label className="text-[10px] font-bold">BACKUP (OPTIONAL)<select value={s.backup_approver_employee_id} onChange={e=>updateStep(i,{backup_approver_employee_id:e.target.value})} className="mt-1 w-full rounded-lg border px-3 py-2 text-xs font-normal"><option value="">No backup</option>{approvers.filter(a=>a.employee_id!==s.approver_employee_id).map(a=><option key={a.employee_id} value={a.employee_id}>{a.full_name}{a.provisioning_status==="preinvite"?" · pre-invite":""}</option>)}</select></label><div className="flex items-end gap-1"><button onClick={()=>move(i,-1)} disabled={i===0} className="rounded border p-2 disabled:opacity-30"><ChevronUp size={14}/></button><button onClick={()=>move(i,1)} disabled={i===steps.length-1} className="rounded border p-2 disabled:opacity-30"><ChevronDown size={14}/></button><button onClick={()=>setSteps(xs=>xs.filter((_,n)=>n!==i))} disabled={steps.length===1} className="rounded border p-2 text-red-500 disabled:opacity-30"><Trash2 size={14}/></button></div></div>)}</div></div>
 {containsPreinvite&&<div className="mt-4 rounded-lg border border-blue-200 bg-blue-50 p-3 text-xs text-blue-800"><b>Planned workflow:</b> one or more approvers are configured before invitation. Saving preserves the workflow, but it remains inactive until every required participant has an active account.</div>}<label className="mt-4 block text-xs font-semibold">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} className="mt-1 w-full rounded-lg border p-3 text-sm font-normal" placeholder="Why this routing applies, exceptions, or implementation notes"/></label><div className="mt-5 flex justify-end"><button onClick={save} disabled={!valid||saving} className="flex items-center gap-2 rounded-lg bg-[#2095f3] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-40"><Save size={15}/>{employee?.current_workflow?"Save replacement":"Save workflow"}</button></div></div>
 <div className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Eye size={17} className="text-[#2095f3]"/><h3 className="text-sm font-bold">Test routing</h3></div><p className="mt-1 text-xs text-[#77808e]">Tests live/historical routing for an earned date. Draft/planned workflows are intentionally excluded until activation.</p><div className="mt-4 flex flex-wrap items-end gap-3"><label className="text-xs font-semibold">Earned date<input type="date" value={previewDate} onChange={e=>setPreviewDate(e.target.value)} className="mt-1 block rounded-lg border px-3 py-2 text-sm font-normal"/></label><button onClick={testRouting} disabled={!employeeId} className="rounded-lg border border-[#2095f3] px-4 py-2.5 text-xs font-bold text-[#0879d5]">Preview routing</button></div>{preview&&<pre className="mt-4 overflow-auto rounded-lg bg-[#0b1e34] p-4 text-[11px] text-white">{JSON.stringify(preview,null,2)}</pre>}</div>
 <div className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><History size={17} className="text-[#2095f3]"/><h3 className="text-sm font-bold">Workflow history</h3></div><div className="mt-4 space-y-3">{history.length===0?<p className="text-xs text-[#77808e]">No saved workflow versions.</p>:history.map(h=><div key={h.workflow_version_id} className="rounded-lg border p-3"><div className="flex justify-between gap-3"><div><b className="text-sm">{h.workflow_name}</b><div className="mt-1 text-[11px] text-[#77808e]">{h.effective_start_date} → {h.effective_end_date||"open ended"}</div></div><span className="h-fit rounded-full bg-[#eef2f7] px-2 py-1 text-[10px] font-bold">{h.status}</span></div><div className="mt-3 flex flex-wrap gap-2">{h.steps?.map((s:any)=><span key={s.id} className="rounded-full bg-[#f4f6f8] px-2 py-1 text-[10px]">{s.step_order}. {s.step_name} · {s.approver_name||"unassigned"}{s.approver_provisioning_status==="preinvite"?" (pre-invite)":""}</span>)}</div>{h.post_approval_steps?.length?<div className="mt-3 border-t pt-3"><div className="text-[10px] font-extrabold text-[#77808e]">POST-APPROVAL / PAYMENT</div><div className="mt-2 flex flex-wrap gap-2">{h.post_approval_steps.map(s=><span key={s.id} className="rounded-full bg-[#edf6ff] px-2 py-1 text-[10px]">{s.step_name} · {s.assignee_name||"unassigned"} · {s.is_required?"required":"optional"}</span>)}</div></div>:null}</div>)}</div></div>
 </section></div></main>;
}
