"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,Plus,Save,Trash2} from "lucide-react";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Component={component_id:string;name:string;component_code:string;description:string|null;calculation_type:string|null;measurement_source:string|null;measurement_period:string|null;calculation_order:number;maximum_payout:number|null;is_active:boolean;payout_timing_method:string;measurement_label:string|null;allow_manager_payout_override:boolean;rule_configuration:any};
type Version={version_id:string;version_number:number;status:string;components:Component[]};type Plan={plan_id:string;name:string;versions:Version[]};
type Tier={minimum_contract_years:string;maximum_contract_years:string;rate:string};
const pct=(v:any)=>v==null?"":String(Number(v)*100);const num=(v:string)=>v===""?null:Number(v);
export default function PayoutRuleEditor(){const params=useParams<{componentId:string}>();const router=useRouter();const[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");const[rate,setRate]=useState(""),[tiers,setTiers]=useState<Tier[]>([]),[threshold,setThreshold]=useState(""),[bonus,setBonus]=useState(""),[fixedAmount,setFixedAmount]=useState("");
useEffect(()=>{(async()=>{const{data,error:e}=await supabase.rpc("get_compensation_plan_admin_data");if(e){setError(e.message);setLoading(false);return}const ps=(data?.plans||[]) as Plan[];setPlans(ps);for(const p of ps)for(const v of p.versions){const c=v.components.find(x=>x.component_id===params.componentId);if(c){const cfg=c.rule_configuration||{};setRate(pct(cfg.rate));setThreshold(cfg.threshold_amount==null?"":String(cfg.threshold_amount));setBonus(cfg.bonus_amount==null?"":String(cfg.bonus_amount));setFixedAmount(cfg.amount==null?"":String(cfg.amount));setTiers(Array.isArray(cfg.tiers)?cfg.tiers.map((t:any)=>({minimum_contract_years:String(t.minimum_contract_years??""),maximum_contract_years:String(t.maximum_contract_years??""),rate:pct(t.rate)})):[])}}setLoading(false)})()},[params.componentId]);
const found=useMemo(()=>{for(const p of plans)for(const v of p.versions){const c=v.components.find(x=>x.component_id===params.componentId);if(c)return{plan:p,version:v,component:c}}return null},[plans,params.componentId]);
const save=async(e:FormEvent)=>{e.preventDefault();if(!found||found.version.status!=="draft")return;const c=found.component,cfg={...(c.rule_configuration||{})};if(c.calculation_type==="percentage")cfg.rate=Number(rate)/100;if(c.calculation_type==="tiered_percentage")cfg.tiers=tiers.map(t=>({minimum_contract_years:Number(t.minimum_contract_years),maximum_contract_years:t.maximum_contract_years===""?null:Number(t.maximum_contract_years),rate:Number(t.rate)/100}));if(c.calculation_type==="threshold_bonus"){cfg.threshold_amount=Number(threshold);cfg.bonus_amount=Number(bonus)}if(c.calculation_type==="fixed_amount")cfg.amount=Number(fixedAmount);setSaving(true);setError("");setMessage("");const{error:se}=await supabase.rpc("save_compensation_plan_component",{selected_plan_version_id:found.version.version_id,selected_component_id:c.component_id,selected_name:c.name,selected_component_code:c.component_code,selected_description:c.description||null,selected_calculation_type:c.calculation_type,selected_measurement_source:c.measurement_source,selected_measurement_period:c.measurement_period,selected_calculation_order:c.calculation_order||1,selected_rule_configuration:cfg,selected_maximum_payout:c.maximum_payout,selected_is_active:c.is_active,selected_payout_timing_method:c.payout_timing_method||"annual",selected_allow_manager_payout_override:c.allow_manager_payout_override,selected_measurement_label:c.measurement_label||null});setSaving(false);if(se){setError(se.message);return}setMessage("Payout rule saved.")};
if(loading)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-empty">Loading payout rule…</div></div></main>;if(!found)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-alert error">Earning Type not found.</div></div></main>;const{plan,version,component:c}=found;const editable=version.status==="draft";
return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-breadcrumb"><Link href={`/plans/manage/${version.version_id}`}><ArrowLeft size={15}/>Manage plan</Link><span>/</span><span>{c.name}</span></div><header className="plan-page-header"><div><span className="plan-kicker">PAYOUT RULE</span><h1>{c.name}</h1><p>View and manage exactly how this Earning Type calculates its payout.</p></div><span className={`plan-status ${version.status}`}>{version.status} v{version.version_number}</span></header>{error&&<div className="plan-alert error">{error}</div>}{message&&<div className="plan-info-row">{message}</div>}
<form className="plan-editor-card" onSubmit={save}><section><h2 style={{marginTop:0}}>How it pays</h2><div className="plan-info-row" style={{marginBottom:16}}><span><b>Method:</b> {String(c.calculation_type||"").replaceAll("_"," ")} &nbsp; · &nbsp; <b>Based on:</b> {String(c.measurement_source||"").replaceAll("_"," ")} &nbsp; · &nbsp; <b>Calculated:</b> {String(c.measurement_period||"").replaceAll("_"," ")}</span></div>
{c.calculation_type==="percentage"&&<div className="plan-form-grid two"><label>Rate *<div style={{display:"flex",alignItems:"center"}}><input type="number" min="0" step="0.01" value={rate} onChange={e=>setRate(e.target.value)} required disabled={!editable}/><b style={{marginLeft:8}}>%</b></div></label></div>}
{c.calculation_type==="tiered_percentage"&&<div><p style={{fontSize:12,color:"#667085"}}>Contract-term tiers. A blank maximum means that tier has no upper limit.</p>{tiers.map((t,i)=><div key={i} style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 42px",gap:10,alignItems:"end",marginBottom:10}}><label>Minimum years<input type="number" min="0" step="1" value={t.minimum_contract_years} onChange={e=>setTiers(x=>x.map((r,j)=>j===i?{...r,minimum_contract_years:e.target.value}:r))} required disabled={!editable}/></label><label>Maximum years<input type="number" min="0" step="1" value={t.maximum_contract_years} onChange={e=>setTiers(x=>x.map((r,j)=>j===i?{...r,maximum_contract_years:e.target.value}:r))} placeholder="No max" disabled={!editable}/></label><label>Rate %<input type="number" min="0" step="0.01" value={t.rate} onChange={e=>setTiers(x=>x.map((r,j)=>j===i?{...r,rate:e.target.value}:r))} required disabled={!editable}/></label><button type="button" className="plan-button secondary" disabled={!editable||tiers.length<=1} onClick={()=>setTiers(x=>x.filter((_,j)=>j!==i))} aria-label="Remove tier"><Trash2 size={14}/></button></div>)}{editable&&<button type="button" className="plan-button secondary" onClick={()=>setTiers(x=>[...x,{minimum_contract_years:"",maximum_contract_years:"",rate:""}])}><Plus size={14}/>Add tier</button>}</div>}
{c.calculation_type==="threshold_bonus"&&<div className="plan-form-grid two"><label>Threshold amount *<input type="number" min="0" step="0.01" value={threshold} onChange={e=>setThreshold(e.target.value)} required disabled={!editable}/></label><label>Bonus paid when threshold is met *<input type="number" min="0" step="0.01" value={bonus} onChange={e=>setBonus(e.target.value)} required disabled={!editable}/></label></div>}
{c.calculation_type==="fixed_amount"&&<div className="plan-form-grid two"><label>Fixed payout amount *<input type="number" min="0" step="0.01" value={fixedAmount} onChange={e=>setFixedAmount(e.target.value)} required disabled={!editable}/></label></div>}
{!["percentage","tiered_percentage","threshold_bonus","fixed_amount"].includes(c.calculation_type||"")&&<div className="plan-alert warning">This payout method is visible but does not yet have a safe first-class editor. Use the full Earning Type editor for its conditions and do not change the payout method here.</div>}
</section><section style={{marginTop:24,borderTop:"1px solid #e3e8ef",paddingTop:20}}><h3>Earned & payment conditions</h3><p style={{fontSize:12,color:"#667085"}}>Payout math and qualifying/payment conditions are separate. Open the full Earning Type to review when this is Earned and when it becomes eligible for payment.</p><Link className="plan-button secondary" href={`/plans/component/${c.component_id}?version=${version.version_id}`}>Review Earned & payment conditions</Link></section>{editable&&<div style={{display:"flex",justifyContent:"flex-end",gap:8,marginTop:24}}><button type="button" className="plan-button secondary" onClick={()=>router.push(`/plans/manage/${version.version_id}`)}>Cancel</button><button className="plan-button brand" disabled={saving}><Save size={14}/>{saving?"Saving…":"Save payout rule"}</button></div>}</form></div></main>}
