"use client";

import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@supabase/supabase-js";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey,{auth:{flowType:"pkce",detectSessionInUrl:false,persistSession:true,autoRefreshToken:true}}):null;
type Access={roles?:string[];permissions?:string[]};

function callbackUrl(){return `${window.location.origin}/auth/callback`}

export default function Home(){
 const router=useRouter();const[message,setMessage]=useState("Opening your compensation workspace…"),[signedOut,setSignedOut]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[sending,setSending]=useState(false),[sent,setSent]=useState(false),[mode,setMode]=useState<"password"|"link">("password");
 useEffect(()=>{(async()=>{if(!supabase){setMessage("Database connection unavailable.");return}const{data:{session}}=await supabase.auth.getSession();if(!session){setSignedOut(true);setMessage("Sign in with your existing Engagifii Compensation account.");return}const{data,error}=await supabase.rpc("get_current_user_access");if(error){setMessage(error.message);return}const access=(data||{}) as Access;const roles=access.roles||[];
  if(roles.includes("system_administrator")){router.replace("/manage");return}
  if(roles.includes("finance_payroll")){router.replace("/finance");return}
  if(roles.includes("executive_administrator")){router.replace("/executive");return}
  if(roles.includes("management_approver")){router.replace("/submissions");return}
  if(roles.includes("plan_administrator")){router.replace("/plans");return}
  router.replace("/me");
 })()},[router]);
 const google=async()=>{if(!supabase)return;setSending(true);setMessage("");const{error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:callbackUrl()}});if(error){setMessage(error.message);setSending(false)}};
 const signIn=async(e:FormEvent)=>{e.preventDefault();if(!supabase||!email.trim())return;setSending(true);setMessage("");if(mode==="password"){const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error){setMessage("We couldn't sign you in with that email and password.")}else{window.location.assign(window.location.origin)}setSending(false);return}const{error}=await supabase.auth.signInWithOtp({email:email.trim(),options:{shouldCreateUser:false,emailRedirectTo:callbackUrl()}});if(error){setMessage(error.message);setSent(false)}else{setSent(true);setMessage(`Check ${email.trim()} for your secure sign-in link.`)}setSending(false)};
 const inputStyle={width:"100%",padding:"12px 13px",border:"1px solid #ccd8e4",borderRadius:9,fontSize:16,boxSizing:"border-box" as const};
 return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#f5f7fa",fontFamily:"Inter,Arial,sans-serif",color:"#051b34",padding:20}}><div style={{width:"min(100%,440px)",background:"white",border:"1px solid #dfe6ee",borderRadius:16,padding:"clamp(24px,6vw,38px)",boxShadow:"0 18px 45px rgba(5,27,52,.08)",textAlign:"center"}}><div style={{fontWeight:900,letterSpacing:1.2,color:"#2095f3",fontSize:13}}>ENGAGIFII COMPENSATION</div><h1 style={{margin:"12px 0 7px",fontSize:"clamp(27px,6vw,34px)"}}>Compensation Tracker</h1><p style={{color:"#647184",lineHeight:1.5,margin:"0 0 22px"}}>{message}</p>{signedOut&&!sent&&<><button type="button" onClick={google} disabled={sending} style={{width:"100%",padding:"12px 14px",border:"1px solid #ccd8e4",borderRadius:9,background:"white",color:"#25384b",fontWeight:800,fontSize:15}}>Continue with Google</button><div style={{display:"flex",alignItems:"center",gap:10,margin:"18px 0",color:"#8793a1",fontSize:12}}><span style={{height:1,background:"#e2e8f0",flex:1}}/><span>or</span><span style={{height:1,background:"#e2e8f0",flex:1}}/></div><form onSubmit={signIn} style={{display:"grid",gap:10,textAlign:"left"}}><label style={{fontSize:12,fontWeight:800,color:"#42566a"}}>Work email</label><input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@engagifii.com" style={inputStyle}/>{mode==="password"&&<><label style={{fontSize:12,fontWeight:800,color:"#42566a",marginTop:3}}>Password</label><input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" style={inputStyle}/></>}<button type="submit" disabled={sending} style={{marginTop:3,padding:"12px 14px",border:0,borderRadius:9,background:"#2095f3",color:"white",fontWeight:800,fontSize:15}}>{sending?"Signing in…":mode==="password"?"Sign in":"Email me a sign-in link"}</button></form><button type="button" onClick={()=>{setMode(mode==="password"?"link":"password");setMessage("Sign in with your existing Engagifii Compensation account.")}} style={{marginTop:13,border:0,background:"transparent",color:"#0879d5",fontWeight:750,fontSize:13}}>{mode==="password"?"Email me a sign-in link instead":"Use email and password instead"}</button><small style={{display:"block",color:"#718096",lineHeight:1.45,textAlign:"center",marginTop:14}}>Sign-in is limited to accounts already provisioned for Engagifii Compensation. This screen does not invite or create users.</small></>}{sent&&<button onClick={()=>{setSent(false);setMode("password");setMessage("Sign in with your existing Engagifii Compensation account.")}} style={{padding:"10px 13px",border:"1px solid #ccd8e4",borderRadius:9,background:"white",fontWeight:750}}>Back to sign in</button>}</div></main>
}
