"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,ArrowLeft,CheckCircle2,Eye,Play,RefreshCw,ShieldCheck,XCircle} from "lucide-react";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Candidate={candidate_key:string;hubspot_deal_id:string;company_name:string;deal_name:string;employee_name:string;employee_id:string;component_name:string;credit_percentage:number;calculated_earning_amount:number;eligibility_status:string;payment_status?:string};
type Target={id:string;full_name:string;email:string};
type Correction={id:string;candidate_key:string;hubspot_deal_id:string;current_employee_name?:string;requested_employee_name?:string;current_credit_percentage:number;requested_credit_percentage:number;reason:string;status:string;correction_path:"direct"|"reopen_required"|"paid_adjustment";resolution_notes?:string;earning_payment_status?:string;earning_paid_amount?:number};
type Preview={valid:boolean;status:string;message?:string;original_employee_name?:string;original_credit_percentage?:number;original_earned_amount?:number;target_employee_name?:string;target_credit_percentage?:number;credited_basis?:number;target_component_name?:string;target_component_code?:string;rate?:number|null;corrected_earned_amount?:number;comp_period_name?:string;calculation_container_action?:string;validation?:{message?:string}};
const money=(v?:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0));
const nice=(v?:string)=>String(v||"").replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const pathCopy=(p?:string)=>p==="paid_adjustment"?"Paid history protected · adjustment/reversal required":p==="reopen_required"?"Approval history protected · return/reopen required":"Pre-approval · direct controlled correction";

export default function CorrectionsPage(){
 const[candidates,setCandidates]=useState<Candidate[]>([]),[targets,setTargets]=useState<Target[]>([]),[requests,setRequests]=useState<Correction[]>([]),[selected,setSelected]=useState(""),[employee,setEmployee]=useState(""),[credit,setCredit]=useState("100"),[reason,setReason]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[notes,setNotes]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=async()=>{setLoading(true);setError("");const[a,b,c]=await Promise.all([supabase.rpc("get_compensation_credits_workspace_data"),supabase.rpc("get_comp_credit_correction_targets"),supabase.rpc("get_comp_credit_correction_queue")]);if(a.error)setError(a.error.message);else setCandidates((a.data?.lineage||[]) as Candidate[]);if(b.error)setError(x=>x||b.error.message);else setTargets((b.data||[]) as Target[]);if(c.error)setError(x=>x||c.error.message);else setRequests((c.data||[]) as Correction[]);setLoading(false)};
 useEffect(()=>{void load()},[]);useEffect(()=>setPreview(null),[selected,employee,credit]);
 const candidate=useMemo(()=>candidates.find(x=>x.candidate_key===selected),[candidates,selected]);
 const active=requests.filter(r=>["pending_review","approved_for_correction","ready_to_apply","adjustment_pending"].includes(r.status));
 const run=async(fn:()=>Promise<{data:any;error:any}>,ok:string)=>{setBusy(true);setError("");setSuccess("");const{data,error:e}=await fn();if(e)setError(e.message);else{setSuccess(typeof data?.status==="string"?`${ok} Status: ${nice(data.status)}.`:ok);await load()}setBusy(false)};
 const previewCorrection=()=>run(async()=>{const r=await supabase.rpc("preview_comp_credit_correction_replacement",{target_candidate_key:selected,target_employee_id:employee,target_credit_percentage:Number(credit)});if(!r.error)setPreview(r.data as Preview);return r},"Preview complete.");
 const submit=()=>run(()=>supabase.rpc("request_comp_credit_correction",{target_candidate_key:selected,target_employee_id:employee,target_credit_percentage:Number(credit),correction_reason:reason}),"Correction request created. No compensation record was changed.");
 const review=(id:string,decision:"approved_for_correction"|"rejected")=>run(()=>supabase.rpc("review_comp_credit_correction",{target_request_id:id,requested_decision:decision,review_notes:(notes[id]||"").trim()}),decision==="approved_for_correction"?"Correction approved for controlled processing.":"Correction rejected.");
 const process=(r:Correction)=>run(()=>supabase.rpc("process_comp_credit_correction",{target_request_id:r.id,processing_reason:(notes[r.id]||"").trim()}),r.correction_path==="paid_adjustment"?"Paid correction routed to adjustment/reversal.":r.correction_path==="reopen_required"?"Existing approval state returned safely. Correction is ready to apply.":"Correction is ready to apply.");
 const apply=(r:Correction)=>run(()=>supabase.rpc("apply_comp_credit_correction_replacement",{target_request_id:r.id,application_reason:(notes[r.id]||"").trim()}),"Replacement earning created and original earning preserved as superseded.");
 const inputStyle={width:"100%",marginTop:6,padding:10,border:"1px solid #ccd8e4",borderRadius:8,boxSizing:"border-box" as const};
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:"clamp(16px,3vw,28px)",fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1200,margin:"0 auto"}}>
  <header style={{marginBottom:22}}><Link href="/credits" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700,fontSize:13}}><ArrowLeft size={15}/>Earnings & Credits</Link><small style={{display:"block",fontWeight:800,letterSpacing:1.1,color:"#2095f3",marginTop:12}}>CONTROLLED CORRECTIONS</small><h1 style={{fontSize:"clamp(28px,5vw,36px)",margin:"6px 0"}}>Attribution Corrections</h1><p style={{margin:0,color:"#647184",maxWidth:900,lineHeight:1.5}}>Preview, request, review, process, then apply. Each step preserves historical approval and payment integrity.</p></header>
  {error&&<div style={{padding:13,borderRadius:10,background:"#fff5f5",border:"1px solid #fed7d7",marginBottom:12}}><b>Action blocked.</b> {error}</div>}{success&&<div style={{padding:13,borderRadius:10,background:"#f0fff4",border:"1px solid #c6f6d5",marginBottom:12}}>{success}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginBottom:18}}>{[{t:"Open",v:active.length},{t:"Pending review",v:active.filter(r=>r.status==="pending_review").length},{t:"Ready to process",v:active.filter(r=>r.status==="approved_for_correction").length},{t:"Ready to apply",v:active.filter(r=>r.status==="ready_to_apply").length},{t:"Paid adjustment",v:active.filter(r=>r.status==="adjustment_pending").length}].map(x=><div key={x.t} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:13,padding:16}}><b style={{fontSize:26}}>{loading?"—":x.v}</b><div style={{fontWeight:800,marginTop:4}}>{x.t}</div></div>)}</section>
  <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18,marginBottom:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:0}}>Request a correction</h2><p style={{margin:"5px 0 0",color:"#647184",fontSize:13}}>A valid historical replacement preview is required first.</p></div><button onClick={load} style={{padding:"9px 11px",border:"1px solid #d7e0e8",background:"white",borderRadius:8,fontWeight:700}}><RefreshCw size={15}/> Refresh</button></div>
   <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12,marginTop:16}}><label style={{fontWeight:700,fontSize:13}}>Source transaction<select value={selected} onChange={e=>setSelected(e.target.value)} style={inputStyle}><option value="">Select transaction</option>{candidates.map(c=><option key={c.candidate_key} value={c.candidate_key}>{c.company_name||c.deal_name} · {c.employee_name} · {money(c.calculated_earning_amount)}</option>)}</select></label><label style={{fontWeight:700,fontSize:13}}>Correct employee<select value={employee} onChange={e=>setEmployee(e.target.value)} style={inputStyle}><option value="">Select employee</option>{targets.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label><label style={{fontWeight:700,fontSize:13}}>Credit %<input type="number" min="1" max="100" value={credit} onChange={e=>setCredit(e.target.value)} style={inputStyle}/></label></div>
   {candidate&&<div style={{marginTop:12,padding:12,borderRadius:10,background:"#f8fafc",fontSize:13}}><b>Current:</b> {candidate.employee_name} · {Number(candidate.credit_percentage||0)}% · {candidate.component_name} · {money(candidate.calculated_earning_amount)} · {nice(candidate.payment_status||candidate.eligibility_status)}</div>}
   <button disabled={busy||!selected||!employee||!credit} onClick={previewCorrection} style={{marginTop:12,padding:"10px 14px",border:"1px solid #b8d9f3",borderRadius:8,background:"#eef7ff",color:"#0c5f9c",fontWeight:800}}><Eye size={15}/> Preview corrected earning</button>
   {preview&&<div style={{marginTop:14,padding:14,borderRadius:11,background:preview.valid?"#f0fff4":"#fff8e8",border:`1px solid ${preview.valid?"#c6f6d5":"#f4d28b"}`}}>{preview.valid?<><b>Valid replacement preview</b><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:9,fontSize:13}}><div>{preview.original_employee_name}<br/>{Number(preview.original_credit_percentage||0)}% · {money(preview.original_earned_amount)}</div><div>{preview.target_employee_name}<br/>{Number(preview.target_credit_percentage||0)}% · {money(preview.credited_basis)} basis</div><div>{preview.target_component_name}<br/>{preview.rate!=null?`${Number(preview.rate)*100}% · `:""}{preview.target_component_code}</div><div><b style={{fontSize:20}}>{money(preview.corrected_earned_amount)}</b><br/>{preview.comp_period_name}</div></div></>:<><b>Replacement blocked</b><div>{preview.message||preview.validation?.message||nice(preview.status)}</div></>}</div>}
   <label style={{display:"block",fontWeight:700,fontSize:13,marginTop:12}}>Required reason<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} style={inputStyle}/></label><button disabled={busy||reason.trim().length<8||!preview?.valid} onClick={submit} style={{marginTop:12,padding:"10px 14px",border:0,borderRadius:8,background:"#2095f3",color:"white",fontWeight:800,opacity:busy||!preview?.valid?.5:1}}>Create correction request</button>
  </section>
  <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,overflow:"hidden"}}><div style={{padding:18,borderBottom:"1px solid #edf1f5"}}><h2 style={{margin:0}}>Correction queue</h2><p style={{margin:"5px 0 0",color:"#647184",fontSize:13}}>Actions appear only when the request reaches the appropriate lifecycle stage.</p></div>{requests.length===0&&!loading?<div style={{padding:24,color:"#718096"}}>No correction requests.</div>:requests.map(r=><div key={r.id} style={{padding:16,borderBottom:"1px solid #edf1f5"}}><div style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap"}}><div><b>{r.current_employee_name||"Current employee"} → {r.requested_employee_name||"Requested employee"}</b><div style={{fontSize:13,color:"#647184",marginTop:3}}>Deal #{r.hubspot_deal_id} · {Number(r.current_credit_percentage)}% → {Number(r.requested_credit_percentage)}%</div><div style={{fontSize:12,fontWeight:800,marginTop:5}}>{pathCopy(r.correction_path)}</div><div style={{fontSize:13,marginTop:6}}>{r.reason}</div>{r.resolution_notes&&<div style={{fontSize:12,color:"#647184",marginTop:5}}>History: {r.resolution_notes}</div>}</div><span style={{height:"fit-content",padding:"5px 8px",borderRadius:20,background:"#f4f6f8",fontWeight:800,fontSize:12}}>{nice(r.status)}</span></div>
    {["pending_review","approved_for_correction","ready_to_apply"].includes(r.status)&&<div style={{marginTop:12}}><label style={{fontSize:12,fontWeight:700}}>Action notes<input value={notes[r.id]||""} onChange={e=>setNotes(x=>({...x,[r.id]:e.target.value}))} placeholder={r.status==="pending_review"?"Review notes":"Reason for this controlled action"} style={inputStyle}/></label><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:8}}>{r.status==="pending_review"&&<><button disabled={busy||(notes[r.id]||"").trim().length<4} onClick={()=>review(r.id,"approved_for_correction")} style={{padding:"9px 11px",border:0,borderRadius:8,background:"#2095f3",color:"white",fontWeight:800}}><CheckCircle2 size={14}/> Approve for correction</button><button disabled={busy||(notes[r.id]||"").trim().length<4} onClick={()=>review(r.id,"rejected")} style={{padding:"9px 11px",border:"1px solid #d7e0e8",borderRadius:8,background:"white",fontWeight:800}}><XCircle size={14}/> Reject</button></>}{r.status==="approved_for_correction"&&<button disabled={busy||(notes[r.id]||"").trim().length<8} onClick={()=>process(r)} style={{padding:"9px 11px",border:0,borderRadius:8,background:"#2095f3",color:"white",fontWeight:800}}><Play size={14}/> Process lifecycle</button>}{r.status==="ready_to_apply"&&<button disabled={busy||(notes[r.id]||"").trim().length<8} onClick={()=>apply(r)} style={{padding:"9px 11px",border:0,borderRadius:8,background:"#2095f3",color:"white",fontWeight:800}}><ShieldCheck size={14}/> Apply replacement earning</button>}</div></div>}
    {r.status==="adjustment_pending"&&<div style={{marginTop:10,padding:10,borderRadius:8,background:"#fff8e8",fontSize:13}}><AlertTriangle size={14}/> Paid history exists. The reversal/adjustment must complete before any replacement earning can be created.</div>}
   </div>)}</section>
  <section style={{marginTop:18,padding:14,borderRadius:10,background:"#eef7ff",border:"1px solid #cfe8fb",fontSize:13}}><b>Lifecycle protection:</b> request → review → process/reopen if needed → apply replacement. Paid history never gets rewritten in place.</section>
 </div></main>;
}
