"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,CheckCircle2,Eye,Play,RefreshCw,ShieldCheck,XCircle} from "lucide-react";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Candidate={candidate_key:string;hubspot_deal_id:string;company_name:string;deal_name:string;employee_name:string;employee_id:string;component_name:string;credit_percentage:number;calculated_earning_amount:number;eligibility_status:string;payment_status?:string};
type Target={id:string;full_name:string;email:string};
type Correction={id:string;candidate_key:string;hubspot_deal_id:string;current_employee_name?:string;requested_employee_name?:string;current_credit_percentage:number;requested_credit_percentage:number;reason:string;status:string;correction_path:"direct"|"reopen_required"|"paid_adjustment";resolution_notes?:string;earning_payment_status?:string;earning_paid_amount?:number};
type Preview={valid:boolean;status:string;message?:string;original_employee_name?:string;original_credit_percentage?:number;original_earned_amount?:number;target_employee_name?:string;target_credit_percentage?:number;credited_basis?:number;target_component_name?:string;target_component_code?:string;rate?:number|null;corrected_earned_amount?:number;comp_period_name?:string;calculation_container_action?:string;validation?:{message?:string}};
type ActionResult={data:any;error:any};
const money=(v?:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0));
const nice=(v?:string)=>String(v||"").replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const pathCopy=(p?:string)=>p==="paid_adjustment"?"Paid history protected · adjustment/reversal required":p==="reopen_required"?"Approval history protected · return/reopen required":"Pre-approval · direct controlled correction";
const friendlyError=(e:any)=>e?.message?"The correction action could not be completed. Review the details and try again.":"The correction action could not be completed.";

export default function CorrectionsPage(){
 const[candidates,setCandidates]=useState<Candidate[]>([]),[targets,setTargets]=useState<Target[]>([]),[requests,setRequests]=useState<Correction[]>([]),[selected,setSelected]=useState(""),[employee,setEmployee]=useState(""),[credit,setCredit]=useState("100"),[reason,setReason]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[notes,setNotes]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=async()=>{setLoading(true);setError("");const[a,b,c]=await Promise.all([supabase.rpc("get_compensation_credits_workspace_data"),supabase.rpc("get_comp_credit_correction_targets"),supabase.rpc("get_comp_credit_correction_queue")]);if(a.error)setError(friendlyError(a.error));else setCandidates((a.data?.lineage||[]) as Candidate[]);if(b.error)setError(x=>x||friendlyError(b.error));else setTargets((b.data||[]) as Target[]);if(c.error)setError(x=>x||friendlyError(c.error));else setRequests((c.data||[]) as Correction[]);setLoading(false)};
 useEffect(()=>{void load()},[]);useEffect(()=>setPreview(null),[selected,employee,credit]);
 const candidate=useMemo(()=>candidates.find(x=>x.candidate_key===selected),[candidates,selected]);
 const active=requests.filter(r=>["pending_review","approved_for_correction","ready_to_apply","adjustment_pending"].includes(r.status));
 const run=async(fn:()=>PromiseLike<ActionResult>,ok:string)=>{setBusy(true);setError("");setSuccess("");const{data,error:e}=await fn();if(e)setError(friendlyError(e));else{setSuccess(typeof data?.status==="string"?`${ok} Status: ${nice(data.status)}.`:ok);await load()}setBusy(false)};
 const previewCorrection=()=>run(async()=>{const r=await supabase.rpc("preview_comp_credit_correction_replacement",{target_candidate_key:selected,target_employee_id:employee,target_credit_percentage:Number(credit)});if(!r.error)setPreview(r.data as Preview);return r},"Preview complete.");
 const submit=()=>run(()=>supabase.rpc("request_comp_credit_correction",{target_candidate_key:selected,target_employee_id:employee,target_credit_percentage:Number(credit),correction_reason:reason}),"Correction request created. No compensation record was changed.");
 const review=(id:string,decision:"approved_for_correction"|"rejected")=>run(()=>supabase.rpc("review_comp_credit_correction",{target_request_id:id,requested_decision:decision,review_notes:(notes[id]||"").trim()}),decision==="approved_for_correction"?"Correction approved for controlled processing.":"Correction rejected.");
 const process=(r:Correction)=>run(()=>supabase.rpc("process_comp_credit_correction",{target_request_id:r.id,processing_reason:(notes[r.id]||"").trim()}),r.correction_path==="paid_adjustment"?"Paid correction routed to adjustment/reversal.":r.correction_path==="reopen_required"?"Existing approval state returned safely. Correction is ready to apply.":"Correction is ready to apply.");
 const apply=(r:Correction)=>run(()=>supabase.rpc("apply_comp_credit_correction_replacement",{target_request_id:r.id,application_reason:(notes[r.id]||"").trim()}),"Replacement earning created and original earning preserved as superseded.");
 const stat=(title:string,value:number)=><div className="eng-card"><div className="eng-card__body"><small className="eng-page-header__eyebrow">{title.toUpperCase()}</small><b className="eng-figure eng-figure--strong" style={{display:"block",fontSize:26}}>{loading?"—":value}</b></div></div>;
 return <main className="eng-page"><div className="eng-page__shell">
  <nav className="eng-breadcrumb"><Link href="/manage">Control Center</Link><span className="eng-breadcrumb__sep">/</span><Link href="/credits">Earnings & Credits</Link><span className="eng-breadcrumb__sep">/</span><span className="eng-breadcrumb__current">Attribution Corrections</span></nav>
  <header className="eng-page-header"><div className="eng-page-header__main"><span className="eng-page-header__eyebrow">CONTROLLED CORRECTIONS</span><h1>Attribution Corrections</h1><p className="eng-page-header__lede">Preview, request, review, process, then apply. Every step preserves approval and payment history rather than rewriting it in place.</p></div><div className="eng-page-header__actions"><button onClick={load} disabled={loading||busy} className="eng-btn"><RefreshCw size={15}/>{loading?"Refreshing…":"Refresh"}</button></div></header>
  {error&&<div className="eng-callout eng-callout--danger"><div className="eng-callout__body"><b>Action blocked</b>{error}</div></div>}{success&&<div className="eng-callout eng-callout--success"><CheckCircle2 size={17}/><div className="eng-callout__body">{success}</div></div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10,margin:"16px 0 18px"}}>{stat("Open",active.length)}{stat("Pending review",active.filter(r=>r.status==="pending_review").length)}{stat("Ready to process",active.filter(r=>r.status==="approved_for_correction").length)}{stat("Ready to apply",active.filter(r=>r.status==="ready_to_apply").length)}{stat("Paid adjustment",active.filter(r=>r.status==="adjustment_pending").length)}</section>

  <section className="eng-card" style={{marginBottom:18}}><div className="eng-card__head"><div><h2>Request a correction</h2><p>A valid replacement preview is required before a request can be submitted.</p></div></div><div className="eng-card__body">
   <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12}}><label><b>Source transaction</b><select value={selected} onChange={e=>setSelected(e.target.value)} className="eng-input" style={{width:"100%",marginTop:6}}><option value="">Select transaction</option>{candidates.map(c=><option key={c.candidate_key} value={c.candidate_key}>{c.company_name||c.deal_name} · {c.employee_name} · {money(c.calculated_earning_amount)}</option>)}</select></label><label><b>Correct employee</b><select value={employee} onChange={e=>setEmployee(e.target.value)} className="eng-input" style={{width:"100%",marginTop:6}}><option value="">Select employee</option>{targets.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label><label><b>Credit %</b><input type="number" min="1" max="100" value={credit} onChange={e=>setCredit(e.target.value)} className="eng-input" style={{width:"100%",marginTop:6}}/></label></div>
   {candidate&&<div className="eng-callout" style={{marginTop:12}}><div className="eng-callout__body"><b>Current attribution</b>{candidate.employee_name} · {Number(candidate.credit_percentage||0)}% · {candidate.component_name} · {money(candidate.calculated_earning_amount)} · {nice(candidate.payment_status||candidate.eligibility_status)}</div></div>}
   <button disabled={busy||!selected||!employee||!credit} onClick={previewCorrection} className="eng-btn" style={{marginTop:12}}><Eye size={15}/>Preview corrected earning</button>
   {preview&&<div className={`eng-callout ${preview.valid?"eng-callout--success":"eng-callout--warn"}`} style={{marginTop:14}}><div className="eng-callout__body">{preview.valid?<><b>Valid replacement preview</b><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:9}}><div>{preview.original_employee_name}<br/>{Number(preview.original_credit_percentage||0)}% · {money(preview.original_earned_amount)}</div><div>{preview.target_employee_name}<br/>{Number(preview.target_credit_percentage||0)}% · {money(preview.credited_basis)} basis</div><div>{preview.target_component_name}<br/>{preview.rate!=null?`${Number(preview.rate)*100}% · `:""}{preview.target_component_code}</div><div><b className="eng-figure" style={{fontSize:20}}>{money(preview.corrected_earned_amount)}</b><br/>{preview.comp_period_name}</div></div></>:<><b>Replacement blocked</b>{preview.message||preview.validation?.message||nice(preview.status)}</>}</div></div>}
   <label style={{display:"block",marginTop:12}}><b>Required reason</b><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} className="eng-input" style={{width:"100%",marginTop:6}}/></label><button disabled={busy||reason.trim().length<8||!preview?.valid} onClick={submit} className="eng-btn eng-btn--primary" style={{marginTop:12}}>Create correction request</button>
  </div></section>

  <section className="eng-card"><div className="eng-card__head"><div><h2>Correction queue</h2><p>Actions appear only when the request reaches the appropriate lifecycle stage.</p></div></div>{requests.length===0&&!loading?<div className="eng-empty eng-empty--inline"><div className="eng-empty__icon"><ShieldCheck size={20}/></div><h2>No correction requests</h2><p>Requested corrections will appear here with their current lifecycle state.</p></div>:requests.map(r=><div key={r.id} style={{padding:16,borderBottom:"1px solid var(--eng-border-soft)"}}><div style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap"}}><div><b>{r.current_employee_name||"Current employee"} → {r.requested_employee_name||"Requested employee"}</b><div style={{fontSize:13,color:"var(--eng-ink-meta)",marginTop:3}}>Deal #{r.hubspot_deal_id} · {Number(r.current_credit_percentage)}% → {Number(r.requested_credit_percentage)}%</div><div style={{fontSize:12,fontWeight:700,marginTop:5}}>{pathCopy(r.correction_path)}</div><div style={{fontSize:13,marginTop:6}}>{r.reason}</div>{r.resolution_notes&&<div style={{fontSize:12,color:"var(--eng-ink-meta)",marginTop:5}}>History: {r.resolution_notes}</div>}</div><span className="eng-badge eng-badge--neutral">{nice(r.status)}</span></div>
   {["pending_review","approved_for_correction","ready_to_apply"].includes(r.status)&&<div style={{marginTop:12}}><label><b>Action notes</b><input value={notes[r.id]||""} onChange={e=>setNotes(x=>({...x,[r.id]:e.target.value}))} placeholder={r.status==="pending_review"?"Review notes":"Reason for this controlled action"} className="eng-input" style={{width:"100%",marginTop:6}}/></label><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:8}}>{r.status==="pending_review"&&<><button disabled={busy||(notes[r.id]||"").trim().length<4} onClick={()=>review(r.id,"approved_for_correction")} className="eng-btn eng-btn--primary"><CheckCircle2 size={14}/>Approve for correction</button><button disabled={busy||(notes[r.id]||"").trim().length<4} onClick={()=>review(r.id,"rejected")} className="eng-btn eng-btn--danger"><XCircle size={14}/>Reject</button></>}{r.status==="approved_for_correction"&&<button disabled={busy||(notes[r.id]||"").trim().length<8} onClick={()=>process(r)} className="eng-btn eng-btn--primary"><Play size={14}/>Process lifecycle</button>}{r.status==="ready_to_apply"&&<button disabled={busy||(notes[r.id]||"").trim().length<8} onClick={()=>apply(r)} className="eng-btn eng-btn--primary"><ShieldCheck size={14}/>Apply replacement earning</button>}</div></div>}
   {r.status==="adjustment_pending"&&<div className="eng-callout eng-callout--warn" style={{marginTop:10}}><AlertTriangle size={16}/><div className="eng-callout__body">Paid history exists. The reversal or adjustment must complete before a replacement earning can be created.</div></div>}
  </div>)}</section>
  <div className="eng-callout eng-callout--info" style={{marginTop:18}}><ShieldCheck size={17}/><div className="eng-callout__body"><b>Lifecycle protection</b>Request → review → process or reopen if needed → apply replacement. Paid history is never rewritten in place.</div></div>
 </div></main>;
}
