"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,ArrowLeft,CheckCircle2,RefreshCw,ShieldCheck,XCircle} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=createClient(supabaseUrl,supabaseKey);

type Candidate={candidate_key:string;hubspot_deal_id:string;company_name:string;deal_name:string;employee_name:string;employee_id:string;component_name:string;credit_percentage:number;calculated_earning_amount:number;eligibility_status:string;earning_id?:string;payment_status?:string};
type Target={id:string;full_name:string;email:string};
type Correction={id:string;candidate_key:string;hubspot_deal_id:string;current_employee_id:string;current_employee_name?:string;requested_employee_id:string;requested_employee_name?:string;current_credit_percentage:number;requested_credit_percentage:number;reason:string;status:string;correction_path:"direct"|"reopen_required"|"paid_adjustment";requested_at:string;resolution_notes?:string;earning_payment_status?:string;earning_paid_amount?:number};

const money=(v?:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0));
const nice=(v?:string)=>String(v||"").replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const pathCopy=(path?:string)=>path==="paid_adjustment"?"Paid history protected · adjustment/reversal required":path==="reopen_required"?"Approval history protected · return/reopen required":"Pre-approval · direct controlled correction path";

export default function CorrectionsPage(){
 const[candidates,setCandidates]=useState<Candidate[]>([]),[targets,setTargets]=useState<Target[]>([]),[requests,setRequests]=useState<Correction[]>([]),[selected,setSelected]=useState(""),[employee,setEmployee]=useState(""),[credit,setCredit]=useState("100"),[reason,setReason]=useState(""),[reviewNotes,setReviewNotes]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const load=async()=>{setLoading(true);setError("");const[a,b,c]=await Promise.all([supabase.rpc("get_compensation_credits_workspace_data"),supabase.rpc("get_comp_credit_correction_targets"),supabase.rpc("get_comp_credit_correction_queue")]);if(a.error)setError(a.error.message);else setCandidates((a.data?.lineage||[]) as Candidate[]);if(b.error)setError(x=>x||b.error.message);else setTargets((b.data||[]) as Target[]);if(c.error)setError(x=>x||c.error.message);else setRequests((c.data||[]) as Correction[]);setLoading(false)};
 useEffect(()=>{void load()},[]);
 const candidate=useMemo(()=>candidates.find(x=>x.candidate_key===selected),[candidates,selected]);
 const open=requests.filter(r=>r.status==="pending_review"||r.status==="approved_for_correction");
 const submit=async()=>{if(!selected||!employee||reason.trim().length<8)return;setSaving(true);setError("");setSuccess("");const{data,error:e}=await supabase.rpc("request_comp_credit_correction",{target_candidate_key:selected,target_employee_id:employee,target_credit_percentage:Number(credit),correction_reason:reason});if(e)setError(e.message);else{const path=data?.correction_path;setSuccess(`Correction request created. ${pathCopy(path)}. No compensation record was changed.`);setSelected("");setEmployee("");setCredit("100");setReason("");await load()}setSaving(false)};
 const review=async(id:string,decision:"approved_for_correction"|"rejected")=>{const notes=(reviewNotes[id]||"").trim();if(notes.length<4){setError("Review notes are required before approving or rejecting a correction request.");return}setSaving(true);setError("");setSuccess("");const{error:e}=await supabase.rpc("review_comp_credit_correction",{target_request_id:id,requested_decision:decision,review_notes:notes});if(e)setError(e.message);else{setSuccess(decision==="approved_for_correction"?"Correction approved for controlled processing. Historical earning/payment records remain unchanged until the required lifecycle action is completed.":"Correction request rejected.");await load()}setSaving(false)};
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:"clamp(16px,3vw,28px)",fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1200,margin:"0 auto"}}>
  <header style={{marginBottom:22}}><Link href="/credits" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700,fontSize:13}}><ArrowLeft size={15}/>Earnings & Credits</Link><small style={{display:"block",fontWeight:800,letterSpacing:1.1,color:"#2095f3",marginTop:12}}>CONTROLLED CORRECTIONS</small><h1 style={{fontSize:"clamp(28px,5vw,36px)",margin:"6px 0"}}>Attribution Corrections</h1><p style={{margin:0,color:"#647184",maxWidth:900,lineHeight:1.5}}>Request a correction once. The system routes it to the correct path based on whether the earning is pre-approval, already approved, or already paid.</p></header>
  {error&&<div style={{padding:13,borderRadius:10,background:"#fff5f5",border:"1px solid #fed7d7",marginBottom:12}}><b>Action blocked.</b> {error}</div>}{success&&<div style={{padding:13,borderRadius:10,background:"#f0fff4",border:"1px solid #c6f6d5",marginBottom:12}}>{success}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:10,marginBottom:18}}>{[{title:"Open requests",value:open.length},{title:"Direct correction",value:open.filter(r=>r.correction_path==="direct").length},{title:"Needs reopen",value:open.filter(r=>r.correction_path==="reopen_required").length},{title:"Paid adjustment",value:open.filter(r=>r.correction_path==="paid_adjustment").length}].map(x=><div key={x.title} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:13,padding:16}}><b style={{fontSize:26}}>{loading?"—":x.value}</b><div style={{fontWeight:800,marginTop:4}}>{x.title}</div></div>)}</section>
  <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18,marginBottom:18}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:0}}>Request a correction</h2><p style={{margin:"5px 0 0",color:"#647184",fontSize:13}}>The request is routed automatically. Creating it never rewrites approved or paid history.</p></div><button onClick={load} style={{display:"inline-flex",gap:6,alignItems:"center",padding:"9px 11px",border:"1px solid #d7e0e8",background:"white",borderRadius:8,fontWeight:700}}><RefreshCw size={15}/>Refresh</button></div>
   <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:12,marginTop:16}}><label style={{fontWeight:700,fontSize:13}}>Source transaction<select value={selected} onChange={e=>setSelected(e.target.value)} style={{width:"100%",marginTop:6,padding:10,border:"1px solid #ccd8e4",borderRadius:8}}><option value="">Select transaction</option>{candidates.map(c=><option key={c.candidate_key} value={c.candidate_key}>{c.company_name||c.deal_name} · {c.employee_name} · {money(c.calculated_earning_amount)}</option>)}</select></label><label style={{fontWeight:700,fontSize:13}}>Correct employee<select value={employee} onChange={e=>setEmployee(e.target.value)} style={{width:"100%",marginTop:6,padding:10,border:"1px solid #ccd8e4",borderRadius:8}}><option value="">Select employee</option>{targets.map(t=><option key={t.id} value={t.id}>{t.full_name}</option>)}</select></label><label style={{fontWeight:700,fontSize:13}}>Credit %<input type="number" min="1" max="100" value={credit} onChange={e=>setCredit(e.target.value)} style={{width:"100%",marginTop:6,padding:10,border:"1px solid #ccd8e4",borderRadius:8}}/></label></div>
   {candidate&&<div style={{marginTop:12,padding:12,borderRadius:10,background:"#f8fafc",fontSize:13}}><b>Current:</b> {candidate.employee_name} · {Number(candidate.credit_percentage||0)}% · {candidate.component_name} · {money(candidate.calculated_earning_amount)} · {nice(candidate.payment_status||candidate.eligibility_status)}</div>}
   <label style={{display:"block",fontWeight:700,fontSize:13,marginTop:12}}>Required reason<textarea value={reason} onChange={e=>setReason(e.target.value)} rows={3} placeholder="Explain why the attribution is incorrect and what should change." style={{width:"100%",marginTop:6,padding:10,border:"1px solid #ccd8e4",borderRadius:8,resize:"vertical"}}/></label><button disabled={saving||!selected||!employee||reason.trim().length<8} onClick={submit} style={{marginTop:12,padding:"10px 14px",border:0,borderRadius:8,background:"#2095f3",color:"white",fontWeight:800,opacity:saving?0.6:1}}>Create correction request</button>
  </section>
  <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,overflow:"hidden"}}><div style={{padding:18,borderBottom:"1px solid #edf1f5"}}><h2 style={{margin:0}}>Correction queue</h2><p style={{margin:"5px 0 0",color:"#647184",fontSize:13}}>Each request shows the lifecycle path required before the correction can be applied.</p></div>{requests.length===0&&!loading?<div style={{padding:24,color:"#718096"}}>No correction requests.</div>:requests.map(r=><div key={r.id} style={{padding:16,borderBottom:"1px solid #edf1f5"}}><div style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap"}}><div><b>{r.current_employee_name||"Current employee"} → {r.requested_employee_name||"Requested employee"}</b><div style={{fontSize:13,color:"#647184",marginTop:3}}>Deal #{r.hubspot_deal_id} · {Number(r.current_credit_percentage)}% → {Number(r.requested_credit_percentage)}%</div><div style={{fontSize:12,fontWeight:800,color:r.correction_path==="paid_adjustment"?"#9b2c2c":r.correction_path==="reopen_required"?"#8a5b00":"#246b45",marginTop:5}}>{pathCopy(r.correction_path)}</div><div style={{fontSize:13,marginTop:6}}>{r.reason}</div>{r.resolution_notes&&<div style={{fontSize:12,color:"#647184",marginTop:5}}>Review: {r.resolution_notes}</div>}</div><div style={{minWidth:180}}><span style={{display:"inline-flex",alignItems:"center",gap:5,padding:"5px 8px",borderRadius:20,background:r.status==="pending_review"?"#fff8e8":r.status==="approved_for_correction"?"#eef7ff":"#f4f6f8",fontWeight:800,fontSize:12}}>{r.status==="pending_review"?<AlertTriangle size={13}/>:r.status==="approved_for_correction"?<CheckCircle2 size={13}/>:<ShieldCheck size={13}/>} {nice(r.status)}</span></div></div>{r.status==="pending_review"&&<div style={{display:"flex",gap:8,alignItems:"flex-end",marginTop:12,flexWrap:"wrap"}}><label style={{flex:"1 1 300px",fontSize:12,fontWeight:700}}>Review notes<input value={reviewNotes[r.id]||""} onChange={e=>setReviewNotes(x=>({...x,[r.id]:e.target.value}))} style={{width:"100%",marginTop:5,padding:9,border:"1px solid #ccd8e4",borderRadius:8}}/></label><button onClick={()=>review(r.id,"approved_for_correction")} disabled={saving} style={{padding:"9px 11px",border:0,borderRadius:8,background:"#2095f3",color:"white",fontWeight:800}}>Approve for correction</button><button onClick={()=>review(r.id,"rejected")} disabled={saving} style={{display:"inline-flex",gap:5,alignItems:"center",padding:"9px 11px",border:"1px solid #d7e0e8",borderRadius:8,background:"white",fontWeight:800}}><XCircle size={14}/>Reject</button></div>}</div>)}</section>
  <section style={{marginTop:18,padding:14,borderRadius:10,background:"#eef7ff",border:"1px solid #cfe8fb",fontSize:13,lineHeight:1.5}}><b>Lifecycle protection:</b> pre-approval corrections use the direct controlled path. Approved or Finance-accepted earnings route to return/reopen. Paid or partially paid earnings route to adjustment/reversal. The request itself never changes money or historical records.</section>
 </div></main>;
}
