"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {CheckCircle2,Plus,RefreshCw,Send} from "lucide-react";
const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;
type Ready={earning_id:string;employee_name:string;earning_name:string;earned_date:string;earned_amount:number;approved_amount:number;payment_status:string;remaining_amount:number};
type Item={id:string;earning_id:string;employee_name:string;earning_name:string;amount:number;payment_details:string|null};
type Batch={id:string;batch_name:string;payroll_period_start:string|null;payroll_period_end:string|null;scheduled_payment_date:string|null;actual_payment_date:string|null;status:string;payment_reference:string|null;payment_method:string|null;notes:string|null;items:Item[]};
type Payload={ready_earnings:Ready[];batches:Batch[]};
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function today(){return new Date().toISOString().slice(0,10)}
export default function PayrollPage(){
 const[data,setData]=useState<Payload>({ready_earnings:[],batches:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const[name,setName]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[payDate,setPayDate]=useState(""),[selectedBatch,setSelectedBatch]=useState(""),[selected,setSelected]=useState<string[]>([]),[paidDate,setPaidDate]=useState(today()),[reference,setReference]=useState(""),[method,setMethod]=useState("Payroll");
 const load=async()=>{if(!supabase){setError("Payroll management is unavailable.");setLoading(false);return}setLoading(true);setError("");const{data:r,error:e}=await supabase.rpc("get_comp_payroll_management_data");if(e)setError("We couldn't load payroll management.");else{const p=(r||{ready_earnings:[],batches:[]}) as Payload;setData(p);const drafts=p.batches.filter(x=>x.status==="draft");if(!selectedBatch&&drafts[0])setSelectedBatch(drafts[0].id)}setLoading(false)};
 useEffect(()=>{load()},[]);
 const drafts=useMemo(()=>data.batches.filter(x=>x.status==="draft"),[data.batches]);
 const createBatch=async()=>{if(!supabase||!name.trim())return;setBusy(true);setError("");const{data:id,error:e}=await supabase.rpc("create_comp_payroll_batch",{requested_batch_name:name.trim(),requested_period_start:start||null,requested_period_end:end||null,requested_payment_date:payDate||null,requested_notes:null});if(e)setError(e.message);else{setMessage("Draft payroll batch created.");setName("");setSelectedBatch(String(id));await load()}setBusy(false)};
 const addSelected=async()=>{if(!supabase||!selectedBatch||!selected.length)return;setBusy(true);setError("");let ok=0;for(const id of selected){const{error:e}=await supabase.rpc("add_comp_earning_to_payroll_batch",{target_payroll_batch_id:selectedBatch,target_earning_id:id,requested_amount:null,requested_payment_details:null});if(e){setError(e.message);break}else ok++}setSelected([]);if(ok)setMessage(`Added ${ok} earning${ok===1?"":"s"} to the payroll batch.`);await load();setBusy(false)};
 const schedule=async(id:string)=>{if(!supabase||!window.confirm("Schedule this payroll batch? This locks the batch and marks its earnings scheduled for payment."))return;setBusy(true);setError("");const{error:e}=await supabase.rpc("schedule_comp_payroll_batch",{target_payroll_batch_id:id});if(e)setError(e.message);else{setMessage("Payroll batch scheduled.");await load()}setBusy(false)};
 const markPaid=async(id:string)=>{if(!supabase||!window.confirm(`Confirm this entire payroll batch was paid on ${paidDate}?`))return;setBusy(true);setError("");const{error:e}=await supabase.rpc("mark_comp_payroll_batch_paid",{target_payroll_batch_id:id,requested_actual_payment_date:paidDate,requested_payment_reference:reference.trim()||null,requested_payment_method:method.trim()||"Payroll",requested_notes:null});if(e)setError(e.message);else{setMessage("Payroll batch recorded as paid.");setReference("");await load()}setBusy(false)};
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 return <main className="eng-page"><div className="eng-page__shell"><nav className="eng-breadcrumb"><Link href="/payments">Payments</Link><span className="eng-breadcrumb__sep">/</span><span>Payroll batches</span></nav>
 <header className="eng-page-header"><div className="eng-page-header__main"><span className="eng-page-header__eyebrow">FINANCE & PAYROLL</span><h1>Payroll batches</h1><p className="eng-page-header__lede">Group approved compensation into a payroll run, schedule it, and record the completed payment with an auditable batch.</p></div><div className="eng-page-header__actions"><Link className="eng-btn" href="/reports">Reports</Link><button className="eng-btn" onClick={load}><RefreshCw size={16}/>Refresh</button></div></header>
 {error&&<div className="eng-callout eng-callout--danger"><div className="eng-callout__body">{error}</div></div>}{message&&<div className="eng-callout eng-callout--success"><div className="eng-callout__body">{message}</div></div>}
 <section className="eng-card" style={{margin:"16px 0"}}><div className="eng-card__head"><div><h2>Create payroll batch</h2><p>Create the pay-period container before adding approved earnings.</p></div></div><div className="eng-card__body" style={{display:"grid",gridTemplateColumns:"1.4fr repeat(3,1fr) auto",gap:8,alignItems:"end"}}><label><small>Batch name *</small><input className="eng-input" value={name} onChange={e=>setName(e.target.value)} placeholder="Sep 30 Compensation"/></label><label><small>Period start</small><input className="eng-input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label><small>Period end</small><input className="eng-input" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label><small>Payment date</small><input className="eng-input" type="date" value={payDate} onChange={e=>setPayDate(e.target.value)}/></label><button className="eng-btn eng-btn--primary" disabled={busy||!name.trim()} onClick={createBatch}><Plus size={16}/>Create</button></div></section>
 <section className="eng-card" style={{marginBottom:18}}><div className="eng-card__head"><div><h2>Ready for payroll</h2><p>{data.ready_earnings.length} approved earning{data.ready_earnings.length===1?"":"s"} available to schedule.</p></div><div style={{display:"flex",gap:8}}><select className="eng-input" value={selectedBatch} onChange={e=>setSelectedBatch(e.target.value)}><option value="">Choose draft batch</option>{drafts.map(b=><option key={b.id} value={b.id}>{b.batch_name}</option>)}</select><button className="eng-btn eng-btn--primary" disabled={busy||!selectedBatch||!selected.length} onClick={addSelected}>Add selected ({selected.length})</button></div></div><div className="eng-card__body">{data.ready_earnings.length===0?<div className="eng-empty eng-empty--inline"><CheckCircle2 size={22}/><h2>Nothing is waiting for payroll</h2><p>Finance-accepted and fully approved earnings will appear here.</p></div>:<div style={{display:"grid",gap:8}}>{data.ready_earnings.map(x=><label key={x.earning_id} style={{display:"grid",gridTemplateColumns:"24px 1.4fr 1fr 1fr",gap:10,alignItems:"center",padding:"10px 4px",borderBottom:"1px solid var(--eng-border,#e6e8ec)"}}><input type="checkbox" checked={selected.includes(x.earning_id)} onChange={()=>toggle(x.earning_id)}/><span><b>{x.employee_name}</b><small style={{display:"block"}}>{x.earning_name} · {x.earned_date}</small></span><span><small>Approved</small><b style={{display:"block"}}>{money(x.approved_amount)}</b></span><span><small>Remaining</small><b style={{display:"block"}}>{money(x.remaining_amount)}</b></span></label>)}</div>}</div></section>
 <section><div className="eng-card__head" style={{paddingLeft:0,paddingRight:0,border:0}}><div><h2>Payroll batches</h2><p>Draft, scheduled, and paid compensation runs.</p></div></div><div style={{display:"grid",gap:10}}>{data.batches.map(b=><article className="eng-card" key={b.id}><div className="eng-card__body"><div style={{display:"grid",gridTemplateColumns:"1.4fr repeat(3,1fr)",gap:12}}><div><b>{b.batch_name}</b><small style={{display:"block",textTransform:"capitalize"}}>{b.status}</small></div><div><small>Pay period</small><div>{b.payroll_period_start||"—"} – {b.payroll_period_end||"—"}</div></div><div><small>Items</small><b style={{display:"block"}}>{b.items.length}</b></div><div><small>Total</small><b style={{display:"block"}}>{money(b.items.reduce((s,x)=>s+Number(x.amount||0),0))}</b></div></div>{b.items.length>0&&<div style={{marginTop:10,fontSize:13}}>{b.items.map(i=><div key={i.id} style={{display:"flex",justifyContent:"space-between",gap:10,padding:"5px 0"}}><span>{i.employee_name} · {i.earning_name}</span><b>{money(i.amount)}</b></div>)}</div>}{b.status==="draft"&&<button className="eng-btn eng-btn--primary" style={{marginTop:10}} disabled={busy||!b.items.length} onClick={()=>schedule(b.id)}><Send size={16}/>Schedule batch</button>}{["scheduled","finalized"].includes(b.status)&&<div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(150px,1fr)) auto",gap:8,alignItems:"end",marginTop:12}}><label><small>Actual paid date</small><input className="eng-input" type="date" value={paidDate} onChange={e=>setPaidDate(e.target.value)}/></label><label><small>Method</small><input className="eng-input" value={method} onChange={e=>setMethod(e.target.value)}/></label><label><small>Reference</small><input className="eng-input" value={reference} onChange={e=>setReference(e.target.value)} placeholder="Payroll reference"/></label><button className="eng-btn eng-btn--primary" disabled={busy} onClick={()=>markPaid(b.id)}><CheckCircle2 size={16}/>Mark batch paid</button></div>}</div></article>)}</div></section>
 </div></main>;
}