create or replace function private.compute_comp_metric_rule_summary(target_rule_set_id uuid,selected_value_field text,selected_start_date date,selected_end_date date)
returns jsonb language plpgsql stable set search_path='' as $$
declare root_id uuid; total_value numeric:=0; matched_count integer:=0; d record; row_value numeric;
begin
 if target_rule_set_id is null then return jsonb_build_object('total',0,'matched_count',0,'value_field',selected_value_field); end if;
 if selected_start_date is null or selected_end_date is null or selected_end_date<selected_start_date then return jsonb_build_object('total',0,'matched_count',0,'value_field',selected_value_field); end if;
 if selected_value_field not in ('amount','average_arr','first_year_arr','total_contract_value','one_time_fee','new_business_arr','expansion_arr','renewal_arr','non_recurring_revenue') then raise exception 'Unsupported aggregate value field: %',selected_value_field using errcode='22023'; end if;
 select n.id into root_id from public.comp_rule_expression_nodes n where n.rule_set_id=target_rule_set_id and n.parent_node_id is null limit 1;
 if root_id is null then raise exception 'Metric qualification rule has no root expression' using errcode='22023'; end if;
 for d in select id,amount,average_arr,first_year_arr,total_contract_value,one_time_fee,new_business_arr,expansion_arr,renewal_arr,non_recurring_revenue from public.hubspot_deals where close_date between selected_start_date and selected_end_date loop
  if public.comp_rule_evaluate_deal_node(root_id,d.id) then
   row_value:=case selected_value_field when 'average_arr' then d.average_arr when 'first_year_arr' then d.first_year_arr when 'total_contract_value' then d.total_contract_value when 'one_time_fee' then d.one_time_fee when 'new_business_arr' then d.new_business_arr when 'expansion_arr' then d.expansion_arr when 'renewal_arr' then d.renewal_arr when 'non_recurring_revenue' then d.non_recurring_revenue else d.amount end;
   total_value:=total_value+coalesce(row_value,0); matched_count:=matched_count+1;
  end if;
 end loop;
 return jsonb_build_object('total',total_value,'matched_count',matched_count,'value_field',selected_value_field);
end;$$;
revoke all on function private.compute_comp_metric_rule_summary(uuid,text,date,date) from public,anon,authenticated;

create or replace function private.compute_comp_component_attainment(target_component_id uuid,target_employee_id uuid,target_year integer)
returns jsonb language plpgsql stable set search_path='' as $$
declare c public.comp_plan_components%rowtype; cfg jsonb; agg jsonb; component_codes text[]; source_total numeric:=0; baseline numeric:=0; total_value numeric:=0; threshold_value numeric:=0; bonus_value numeric:=0; attainment numeric:=0; met boolean:=false; comparison_key text; plan_version uuid; version_status text; plan_start date; plan_end date; assignment_start date; assignment_end date; period_start date; period_end date; qualification_rule_set_id uuid; value_field text; metric_summary jsonb;
begin
 select * into c from public.comp_plan_components where id=target_component_id; if c.id is null then raise exception 'Earning Type not found'; end if;
 cfg:=coalesce(c.rule_configuration,'{}'::jsonb); agg:=coalesce(cfg->'aggregate','{}'::jsonb); plan_version:=c.plan_version_id;
 select pv.status::text,pv.effective_start_date,pv.effective_end_date into version_status,plan_start,plan_end from public.comp_plan_versions pv where pv.id=plan_version;
 select coalesce(array_agg(value),array[]::text[]) into component_codes from jsonb_array_elements_text(coalesce(agg->'source_component_codes',cfg->'aggregate_component_codes','[]'::jsonb));
 baseline:=coalesce(nullif(agg->>'baseline_amount','')::numeric,nullif(cfg->>'aggregate_fixed_uplift','')::numeric,0); threshold_value:=coalesce(nullif(agg->>'benchmark_amount','')::numeric,nullif(cfg->>'threshold_amount','')::numeric,0); bonus_value:=coalesce(nullif(agg->>'payout_amount','')::numeric,nullif(cfg->>'bonus_amount','')::numeric,0); comparison_key:=coalesce(nullif(agg->>'comparison',''),nullif(cfg->>'comparison',''),'greater_than'); qualification_rule_set_id:=nullif(agg->>'qualification_rule_set_id','')::uuid; value_field:=coalesce(nullif(agg->>'value_field',''),'amount');
 if version_status='draft' then select effective_start_date,effective_end_date into assignment_start,assignment_end from public.comp_plan_draft_assignments where plan_version_id=plan_version and employee_id=target_employee_id limit 1; else select effective_start_date,effective_end_date into assignment_start,assignment_end from public.employee_plan_assignments where plan_version_id=plan_version and employee_id=target_employee_id limit 1; end if;
 if qualification_rule_set_id is not null then
  if not exists(select 1 from public.comp_rule_sets rs where rs.id=qualification_rule_set_id and rs.plan_component_id=target_component_id and rs.purpose='metric_qualification') then raise exception 'Metric qualification rule is not attached to this Earning Type' using errcode='22023'; end if;
  if assignment_start is not null then period_start:=greatest(make_date(target_year,1,1),coalesce(plan_start,make_date(target_year,1,1)),assignment_start); period_end:=least(make_date(target_year,12,31),coalesce(plan_end,make_date(target_year,12,31)),coalesce(assignment_end,make_date(target_year,12,31))); metric_summary:=private.compute_comp_metric_rule_summary(qualification_rule_set_id,value_field,period_start,period_end); source_total:=coalesce((metric_summary->>'total')::numeric,0); end if;
 else
  with assignment as (select da.effective_start_date,da.effective_end_date from public.comp_plan_draft_assignments da where version_status='draft' and da.employee_id=target_employee_id and da.plan_version_id=plan_version union all select epa.effective_start_date,epa.effective_end_date from public.employee_plan_assignments epa where version_status<>'draft' and epa.employee_id=target_employee_id and epa.plan_version_id=plan_version), source_components as (select sc.id,sc.component_code,sc.measurement_source from public.comp_plan_components sc where sc.plan_version_id=plan_version and sc.is_active=true and sc.id<>target_component_id and sc.component_code=any(component_codes)), raw as (select sc.id source_component_id,d.hubspot_deal_id,case sc.measurement_source when 'average_arr' then d.average_arr when 'first_year_arr' then d.first_year_arr when 'one_time_fee' then d.one_time_fee when 'total_contract_value' then d.total_contract_value else d.amount end source_amount,case when exists(select 1 from public.comp_user_attribution_rules mr where mr.plan_component_id=sc.id and mr.attribution_purpose='metric' and mr.metric_key='book_of_business' and mr.is_active=true) then private.resolve_comp_user_attribution(target_employee_id,sc.id,d.hubspot_deal_id,'metric','book_of_business') else private.resolve_comp_user_attribution(target_employee_id,sc.id,d.hubspot_deal_id,'earning',null) end attribution from assignment a join source_components sc on true join public.comp_component_deal_rules dr on dr.plan_component_id=sc.id and dr.is_active=true and dr.calculation_action='include' and dr.marks_earned=true join public.hubspot_deals d on d.hubspot_pipeline_id=dr.hubspot_pipeline_id and d.hubspot_stage_id=dr.hubspot_stage_id and d.hubspot_deal_type=dr.hubspot_deal_type join public.comp_plan_versions pv on pv.id=plan_version where extract(year from d.close_date)::int=target_year and d.close_date between greatest(a.effective_start_date,pv.effective_start_date,dr.effective_start_date) and least(coalesce(a.effective_end_date,'infinity'::date),coalesce(pv.effective_end_date,'infinity'::date),coalesce(dr.effective_end_date,'infinity'::date))), deduped as (select source_component_id,hubspot_deal_id,max(source_amount*coalesce(nullif(attribution->>'resolved_credit_percentage','')::numeric,100)/100) credited_source_amount from raw where coalesce((attribution->>'matched')::boolean,false)=true and source_amount is not null group by source_component_id,hubspot_deal_id) select coalesce(sum(credited_source_amount),0) into source_total from deduped;
 end if;
 total_value:=source_total+baseline; attainment:=case when threshold_value>0 then round((total_value/threshold_value)*100,2) else 0 end; met:=case comparison_key when 'greater_than_or_equal' then total_value>=threshold_value when 'equal' then total_value=threshold_value else total_value>threshold_value end;
 return jsonb_build_object('component_id',target_component_id,'employee_id',target_employee_id,'year',target_year,'source_component_codes',to_jsonb(component_codes),'qualification_rule_set_id',qualification_rule_set_id,'value_field',value_field,'source_mode',case when qualification_rule_set_id is null then 'legacy_components' else 'metric_rule' end,'source_total',source_total,'baseline_amount',baseline,'measurement_value',total_value,'threshold',threshold_value,'attainment_percent',attainment,'threshold_met',met,'bonus_amount',bonus_value,'comparison',comparison_key,'metric_key','book_of_business');
end;$$;
revoke all on function private.compute_comp_component_attainment(uuid,uuid,integer) from public,anon,authenticated;