"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,CheckCircle2,RefreshCw,Search,ShieldCheck} from "lucide-react";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Access={roles?:string[];permissions?:string[]};
type SyncObject={hubspot_object_type:string;internal_object_key:string;object_category:string;description?:string|null;read_access:string;record_sync_enabled:boolean;sync_reason?:string|null;updated_at?:string|null};
type LatestRun={id:string;status:string;started_at:string;completed_at?:string|null;schema_summary?:Record<string,any>;data_summary?:Record<string,any>;change_summary?:Record<string,any>;warnings?:any[];error_message?:string|null};
type StatusData={objects:SyncObject[];latest_run:LatestRun|null;summary:{registered_objects:number;readable_objects:number;record_sync_objects:number;properties:number;open_configuration_changes:number}};
const card={background:"white",border:"1px solid var(--eng-border, #dfe6ee)",borderRadius:14,padding:18} as const;
const label=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const coreObjects=new Set(["DEAL","COMPANY","MEETING_EVENT"]);

export default function HubSpotIntegrationPage(){
 const[access,setAccess]=useState<Access|null>(null),[data,setData]=useState<StatusData|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[search,setSearch]=useState("");
 const perms=access?.permissions||[],roles=access?.roles||[];const admin=roles.includes("system_administrator");
 const canView=admin||perms.includes("settings.manage")||perms.includes("settings.hubspot_mapping.view")||perms.includes("settings.hubspot_mapping.edit");
 const canEdit=admin||perms.includes("settings.manage")||perms.includes("settings.hubspot_mapping.edit");
 const load=async()=>{setLoading(true);setError("");const[a,s]=await Promise.all([supabase.rpc("get_current_user_access"),supabase.rpc("get_hubspot_integration_status")]);if(a.data)setAccess(a.data as Access);if(s.error)setError("We couldn't load the HubSpot integration status. Try again.");else setData(s.data as StatusData);setLoading(false)};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();const rows=data?.objects||[];return q?rows.filter(o=>`${o.hubspot_object_type} ${o.internal_object_key} ${o.description||""}`.toLowerCase().includes(q)):rows},[data,search]);
 const synced=filtered.filter(o=>o.record_sync_enabled),available=filtered.filter(o=>!o.record_sync_enabled&&o.read_access==="AVAILABLE"),restricted=filtered.filter(o=>o.read_access!=="AVAILABLE");
 const toggle=async(o:SyncObject,next:boolean)=>{if(!canEdit)return;setBusy(true);setError("");setMessage("");const{error:e}=await supabase.rpc("set_hubspot_object_record_sync",{target_hubspot_object_type:o.hubspot_object_type,enabled:next});if(e)setError("That HubSpot sync setting could not be changed. No compensation rules were changed.");else{setMessage(`${o.hubspot_object_type} ${next?"will now":"will no longer"} sync records during HubSpot re-sync.`);await load()}setBusy(false)};
 const resync=async()=>{if(!canEdit)return;setBusy(true);setError("");setMessage("Re-syncing HubSpot. Schema, pipelines, stages, and enabled records are being refreshed.");const{data:r,error:e}=await supabase.rpc("resync_hubspot_integration");if(e){setError("HubSpot re-sync could not be completed. Existing synchronized data and compensation configuration were not changed by this failed attempt.");setMessage("")}else{const changes=r?.changes||{};const warningCount=Array.isArray(r?.warnings)?r.warnings.length:0;setMessage(`HubSpot re-sync finished${warningCount?" with warnings":""}. ${changes.added||0} new, ${changes.changed||0} updated, and ${changes.removed||0} removed configuration items detected.`);await load()}setBusy(false)};
 if(loading)return <main className="eng-page"><div className="eng-page__shell"><div className="eng-page__empty"><strong>Loading HubSpot Integration…</strong><span>Checking connection and synchronized object configuration.</span></div></div></main>;
 if(!canView)return <main className="eng-page"><div className="eng-page__shell"><div className="eng-page__alert eng-page__alert--danger">You do not have permission to view HubSpot Integration settings.</div></div></main>;
 const last=data?.latest_run;const scopeWarning=Array.isArray(last?.warnings)?last!.warnings!.some((w:any)=>w?.status==="schema_scope_missing"):false;
 return <main className="eng-page"><div className="eng-page__shell">
  <nav className="eng-page__crumbs" aria-label="Breadcrumb"><Link href="/settings">Settings</Link><span>/</span><span>HubSpot Integration</span></nav>
  <header className="eng-page__header"><div><div className="eng-page__eyebrow">DATA INTEGRATION</div><h1>HubSpot Integration</h1><p className="eng-page__lede">Manage what synchronizes from HubSpot into the Compensation Tracker. This integration is read-only from HubSpot to the Tracker; rule availability is configured separately.</p></div><div className="eng-page__actions"><Link className="eng-page__button" href="/hubspot">View source data</Link><Link className="eng-page__button" href="/settings/hubspot-mapping">Rule data</Link><button className="eng-page__button eng-page__button--primary" onClick={resync} disabled={!canEdit||busy}><RefreshCw size={16}/>{busy?"Re-syncing…":"Re-sync HubSpot"}</button></div></header>
  {error&&<div className="eng-page__alert eng-page__alert--danger">{error}</div>}{message&&<div className="eng-page__alert eng-page__alert--success">{message}</div>}
  {scopeWarning&&<div className="eng-page__alert eng-page__alert--warning"><AlertTriangle size={18}/><div><b>HubSpot schema permission is incomplete</b><div>The current credential can refresh registered objects and their known configuration, but cannot automatically discover a brand-new HubSpot object type until the required schema scope is added.</div></div></div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginBottom:14}}>
   <div style={card}><small>Registered objects</small><b style={{display:"block",fontSize:25,marginTop:4}}>{data?.summary.registered_objects||0}</b></div>
   <div style={card}><small>Readable objects</small><b style={{display:"block",fontSize:25,marginTop:4}}>{data?.summary.readable_objects||0}</b></div>
   <div style={card}><small>Syncing records</small><b style={{display:"block",fontSize:25,marginTop:4}}>{data?.summary.record_sync_objects||0}</b></div>
   <div style={card}><small>Available fields</small><b style={{display:"block",fontSize:25,marginTop:4}}>{data?.summary.properties||0}</b></div>
   <div style={card}><small>Changes to review</small><b style={{display:"block",fontSize:25,marginTop:4}}>{data?.summary.open_configuration_changes||0}</b></div>
  </section>
  <section style={{...card,marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 4px"}}>Required source objects</h2><p style={{margin:0}}>Deals, Companies, and Meetings remain synchronized for the current integration foundation.</p></div><ShieldCheck size={22}/></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:9,marginTop:12}}>{["DEAL","COMPANY","MEETING_EVENT"].map(k=>{const o=data?.objects.find(x=>x.hubspot_object_type===k);return <div key={k} style={{border:"1px solid var(--eng-border, #dfe6ee)",borderRadius:10,padding:11}}><b>{k==="MEETING_EVENT"?"Meetings":label(k)}</b><code style={{display:"block",fontSize:11,marginTop:3}}>{k}</code><span style={{display:"inline-flex",gap:5,alignItems:"center",fontSize:12,fontWeight:800,marginTop:8}}>{o?.record_sync_enabled?<CheckCircle2 size={14}/>:<AlertTriangle size={14}/>} {o?.record_sync_enabled?"Record sync on":"Record sync off"}</span></div>})}</div></section>
  <section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap",marginBottom:12}}><div><h2 style={{margin:"0 0 4px"}}>Object sync configuration</h2><p style={{margin:0}}>Enabled objects appear first. Search to find additional HubSpot objects that can be synchronized.</p></div><div style={{position:"relative"}}><Search size={15} style={{position:"absolute",left:10,top:10}}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search HubSpot objects" style={{padding:"8px 10px 8px 31px",border:"1px solid var(--eng-border, #cad5df)",borderRadius:8,minWidth:250}}/></div></div>
   <div style={{display:"grid",gap:18}}>
    <div><h3>Syncing records ({synced.length})</h3><div style={{display:"grid",gap:6}}>{synced.map(o=><div key={o.hubspot_object_type} style={{border:"1px solid var(--eng-border, #e2e8ee)",borderRadius:9,padding:10,display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><b>{o.hubspot_object_type==="MEETING_EVENT"?"Meetings":label(o.internal_object_key)}</b><code style={{display:"block",fontSize:10}}>{o.hubspot_object_type}</code></div><label style={{fontSize:12,fontWeight:800,display:"flex",gap:6,alignItems:"center"}}><input type="checkbox" checked disabled={coreObjects.has(o.hubspot_object_type)||!canEdit||busy} onChange={()=>toggle(o,false)}/> Sync records {coreObjects.has(o.hubspot_object_type)&&<span>· required</span>}</label></div>)}</div></div>
    <div><h3>Available to enable ({available.length})</h3><div style={{display:"grid",gap:6}}>{available.map(o=><div key={o.hubspot_object_type} style={{border:"1px solid var(--eng-border, #edf1f5)",borderRadius:9,padding:10,display:"flex",justifyContent:"space-between",gap:12,alignItems:"center"}}><div><b>{label(o.internal_object_key)}</b><code style={{display:"block",fontSize:10}}>{o.hubspot_object_type}</code>{o.description&&<small style={{display:"block",marginTop:3}}>{o.description}</small>}</div><label style={{fontSize:12,fontWeight:800,display:"flex",gap:6,alignItems:"center"}}><input type="checkbox" checked={false} disabled={!canEdit||busy} onChange={()=>toggle(o,true)}/> Sync records</label></div>)}</div></div>
    {restricted.length>0&&<div><h3>Unavailable with current HubSpot access ({restricted.length})</h3><div style={{display:"grid",gap:6}}>{restricted.map(o=><div key={o.hubspot_object_type} style={{border:"1px solid var(--eng-border, #edf1f5)",borderRadius:9,padding:10,display:"flex",justifyContent:"space-between",gap:12}}><div><b>{label(o.internal_object_key)}</b><code style={{display:"block",fontSize:10}}>{o.hubspot_object_type}</code></div><span style={{fontSize:11,fontWeight:800}}>{label(o.read_access)}</span></div>)}</div></div>}
   </div>
  </section>
  {last&&<section style={{...card,marginTop:14}}><h2 style={{margin:"0 0 5px"}}>Last re-sync</h2><p style={{margin:"0 0 10px"}}>{new Date(last.started_at).toLocaleString()} · <b>{label(last.status)}</b></p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8}}><div><small>New configuration</small><b style={{display:"block",fontSize:20}}>{Number(last.change_summary?.added||0)}</b></div><div><small>Updated configuration</small><b style={{display:"block",fontSize:20}}>{Number(last.change_summary?.changed||0)}</b></div><div><small>Removed configuration</small><b style={{display:"block",fontSize:20}}>{Number(last.change_summary?.removed||0)}</b></div><div><small>Open review items</small><b style={{display:"block",fontSize:20}}>{Number(last.change_summary?.open_changes||0)}</b></div></div></section>}
 </div></main>;
}