"use client";

import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {CheckCircle2,Plus,Trash2} from "lucide-react";
import ValueEditor,{RuleFieldOption} from "../../rules/value-editor";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Obj={object_type:string;display_name:string};
type Field={object_type:string;property_name:string;display_name:string;data_type:string;options?:RuleFieldOption[];is_multi_value?:boolean};
type Op={operator_key:string;display_name:string;value_arity:string;supported_data_types:string[]};
type Condition={id:string;object_type:string;property_name:string;operator_key:string;comparison_value:string};
type ExistingRule={id:string;purpose:string;is_active:boolean;predicates:any[]};
const uid=()=>Math.random().toString(36).slice(2,10);
const blank=():Condition=>({id:uid(),object_type:"deal",property_name:"",operator_key:"is",comparison_value:""});
const inputStyle={width:"100%",padding:"9px 10px",border:"1px solid #d0d5dd",borderRadius:9,background:"white",boxSizing:"border-box" as const};

function toEditorValue(v:any){if(v==null)return"";if(Array.isArray(v))return v.join("\u001f");if(typeof v==="object"&&("low" in v||"high" in v))return `${v.low||""}\u001f${v.high||""}`;return String(v)}
function toPayloadValue(value:string,arity:string){if(arity==="none")return null;if(arity==="multiple")return value.split("\u001f").filter(Boolean);if(arity==="range"){const[low,high]=value.split("\u001f");return{low:low||null,high:high||null}}return value}
function preferredOperator(field:Field|undefined,ops:Op[]){if(!field)return ops.find(o=>o.operator_key==="is");const compatible=ops.filter(o=>o.supported_data_types.includes(field.data_type));if(field.options?.length||["enumeration","user","object_id"].includes(field.data_type))return compatible.find(o=>o.operator_key==="is_any_of")||compatible.find(o=>o.operator_key==="is");return compatible.find(o=>o.operator_key==="is")||compatible[0]}

export default function EarnedConditionsEditor({componentId,disabled=false,onSaved}:{componentId:string;disabled?:boolean;onSaved?:()=>void}){
 const[objects,setObjects]=useState<Obj[]>([]),[fields,setFields]=useState<Field[]>([]),[ops,setOps]=useState<Op[]>([]),[conditions,setConditions]=useState<Condition[]>([blank()]);
 const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{let live=true;(async()=>{setLoading(true);setError("");const{data,error:e}=await supabase.rpc("get_comp_rule_builder_catalog",{target_plan_component_id:componentId});if(!live)return;if(e){setError(e.message);setLoading(false);return}setObjects(data?.objects||[]);setFields(data?.fields||[]);setOps(data?.operators||[]);const existing=((data?.rule_sets||[]) as ExistingRule[]).filter(r=>r.purpose==="qualification").sort((a:any,b:any)=>(b.version||0)-(a.version||0))[0];if(existing?.predicates?.length){setConditions(existing.predicates.map((p:any)=>({id:uid(),object_type:p.object_type||"deal",property_name:p.property_name||"",operator_key:p.operator_key||"is",comparison_value:toEditorValue(p.comparison_value)})))}else setConditions([blank()]);setDirty(false);setLoading(false)})().catch(err=>{if(live){setError(String(err));setLoading(false)}});return()=>{live=false}},[componentId]);
 const add=()=>{setConditions(c=>[...c,blank()]);setDirty(true);setMessage("")};
 const patch=(id:string,next:Partial<Condition>)=>{setConditions(c=>c.map(x=>x.id===id?{...x,...next}:x));setDirty(true);setMessage("")};
 const remove=(id:string)=>{setConditions(c=>c.filter(x=>x.id!==id));setDirty(true);setMessage("")};
 const save=async()=>{setSaving(true);setError("");setMessage("");for(const c of conditions){if(!c.property_name||!c.operator_key){setError("Each Earned condition needs a field and match type.");setSaving(false);return}const op=ops.find(o=>o.operator_key===c.operator_key);if(op?.value_arity!=="none"&&!c.comparison_value){setError("Choose a value for each Earned condition.");setSaving(false);return}}
 const payload=conditions.map(c=>{const op=ops.find(o=>o.operator_key===c.operator_key);return{object_type:c.object_type,property_name:c.property_name,operator_key:c.operator_key,comparison_value:toPayloadValue(c.comparison_value,op?.value_arity||"single")}});
 const{data,error:e}=await supabase.rpc("save_simple_comp_earned_conditions",{selected_component_id:componentId,selected_conditions:payload,selected_name:"Earned conditions"});setSaving(false);if(e){setError(e.message);return}setDirty(false);setMessage(data?.preview?.supported===false?"Saved. Preview could not evaluate this condition set yet.":`Saved and checked against current HubSpot data${data?.preview?.matched_count!=null?` — ${data.preview.matched_count} matching record${data.preview.matched_count===1?"":"s"}`:""}.`);onSaved?.()};
 if(loading)return <div className="plan-info-row">Loading approved fields and values…</div>;
 return <div style={{border:"1px solid #d7e1eb",borderRadius:12,background:"#f8fbfe",padding:14}}>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:12,flexWrap:"wrap"}}><div><b style={{fontSize:15}}>Earn this when all of these are true</b><div style={{fontSize:12,color:"#667085",marginTop:3}}>Choose business fields and valid synchronized HubSpot values. You do not need internal IDs.</div></div><button type="button" className="plan-button secondary" onClick={add} disabled={disabled||saving}><Plus size={14}/>Add condition</button></div>
   {error&&<div className="plan-alert error" style={{marginTop:10}}>{error}</div>}{message&&<div className="plan-info-row" style={{marginTop:10}}><CheckCircle2 size={16}/>{message}</div>}
   <div style={{display:"grid",gap:10,marginTop:12}}>{conditions.map((c,i)=>{const availableFields=fields.filter(f=>f.object_type===c.object_type);const field=availableFields.find(f=>f.property_name===c.property_name);const availableOps=ops.filter(o=>!field?.data_type||o.supported_data_types.includes(field.data_type));const op=ops.find(o=>o.operator_key===c.operator_key);return <div key={c.id} style={{display:"grid",gridTemplateColumns:"135px minmax(220px,1fr) 180px minmax(230px,1fr) 38px",gap:9,alignItems:"start",padding:11,border:"1px solid #e1e8ef",borderRadius:10,background:"white"}}><label style={{fontSize:12,fontWeight:700}}>From<select value={c.object_type} onChange={e=>patch(c.id,{object_type:e.target.value,property_name:"",operator_key:"is",comparison_value:""})} style={{...inputStyle,marginTop:5}} disabled={disabled}>{objects.map(o=><option key={o.object_type} value={o.object_type}>{o.display_name}</option>)}</select></label><label style={{fontSize:12,fontWeight:700}}>Field<select value={c.property_name} onChange={e=>{const next=availableFields.find(f=>f.property_name===e.target.value);const preferred=preferredOperator(next,ops);patch(c.id,{property_name:e.target.value,operator_key:preferred?.operator_key||"is",comparison_value:""})}} style={{...inputStyle,marginTop:5}} disabled={disabled}><option value="">Choose field…</option>{availableFields.map(f=><option key={f.property_name} value={f.property_name}>{f.display_name}</option>)}</select></label><label style={{fontSize:12,fontWeight:700}}>Match<select value={c.operator_key} onChange={e=>patch(c.id,{operator_key:e.target.value,comparison_value:""})} style={{...inputStyle,marginTop:5}} disabled={disabled}>{availableOps.map(o=><option key={o.operator_key} value={o.operator_key}>{o.display_name}</option>)}</select></label><label style={{fontSize:12,fontWeight:700}}>Value<div style={{marginTop:5}}><ValueEditor field={field} operator={op} value={c.comparison_value} onChange={v=>patch(c.id,{comparison_value:v})}/></div></label><button type="button" aria-label={`Remove condition ${i+1}`} onClick={()=>remove(c.id)} disabled={disabled||conditions.length===1} style={{marginTop:24,border:"1px solid #d7e1eb",borderRadius:8,background:"white",height:38,cursor:"pointer"}}><Trash2 size={15}/></button></div>})}</div>
   <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginTop:12,flexWrap:"wrap"}}><span style={{fontSize:12,color:"#667085"}}>{dirty?"Earned conditions have unsaved changes.":"Earned conditions are saved separately from the payout fields above."}</span><button type="button" className="plan-button primary" onClick={save} disabled={disabled||saving||!dirty}>{saving?"Saving & checking…":dirty?"Save Earned conditions":"Earned conditions saved"}</button></div>
 </div>;
}
