"use client";

import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CheckCircle2,ExternalLink,HelpCircle,Save,ShieldCheck} from "lucide-react";
import EarnedConditionsEditor,{EarnedConditionsEditorHandle} from "./earned-conditions-editor";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type EarningType={component_id:string;name:string;component_code:string;description:string|null;calculation_type:string|null;measurement_source:string|null;measurement_period:string|null;calculation_order:number;maximum_payout:number|null;is_active:boolean;payout_timing_method:string;measurement_label:string|null;additional_eligibility_waiting_days:number|null;allow_manager_payout_override:boolean;rule_configuration:any};
type Version={version_id:string;version_number:number;status:string;components:EarningType[]};
type Plan={plan_id:string;name:string;versions:Version[]};
type RuleSetSummary={id:string;plan_component_id:string;name:string;purpose:string;version:number;is_active:boolean};
type EligibilityMode="immediate"|"customer_payment"|"waiting_period"|"rule";
const slug=(v:string)=>v.toUpperCase().trim().replace(/[^A-Z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,80);
function existingMode(c:EarningType|null):EligibilityMode{const e=c?.rule_configuration?.eligibility;if(e?.business_concept==="customer_payment_received")return "customer_payment";if(e?.mode==="immediate"||e?.mode==="waiting_period"||e?.mode==="rule")return e.mode;const legacy=c?.rule_configuration?.eligibility_condition;if(legacy==="customer_payment_received"||legacy==="paid_stage_and_invoice_paid_date")return "customer_payment";return "immediate";}
function Help({children}:{children:React.ReactNode}){return <span style={{display:"flex",alignItems:"center",gap:4,color:"#667085",fontWeight:500,fontSize:11,marginTop:5}}><HelpCircle size={13}/>{children}</span>}
function basisLabel(v:string){return ({amount:"deal amount",average_arr:"annual recurring revenue",book_of_business:"book of business value",hubspot_meeting:"qualifying activity"} as Record<string,string>)[v]||v||"selected basis"}

export default function EarningTypeEditor(){
 const params=useParams<{componentId:string}>();const router=useRouter();const isNew=params.componentId==="new";const earnedRef=useRef<EarnedConditionsEditorHandle>(null);
 const[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const[versionId,setVersionId]=useState("");const[name,setName]=useState(""),[code,setCode]=useState(""),[codeTouched,setCodeTouched]=useState(false),[description,setDescription]=useState("");
 const[calculationType,setCalculationType]=useState("percentage"),[measurementSource,setMeasurementSource]=useState("amount"),[customMeasurementSource,setCustomMeasurementSource]=useState(""),[measurementPeriod,setMeasurementPeriod]=useState("per_deal"),[maximumPayout,setMaximumPayout]=useState("");
 const[ratePercent,setRatePercent]=useState("");const[eligibilityMode,setEligibilityMode]=useState<EligibilityMode>("immediate"),[waitingDays,setWaitingDays]=useState("0"),[eligibilityDescription,setEligibilityDescription]=useState("");
 const[ruleConfig,setRuleConfig]=useState<any>({});const[ruleSets,setRuleSets]=useState<RuleSetSummary[]>([]),[selectedEligibilityRuleSet,setSelectedEligibilityRuleSet]=useState("");const[dirty,setDirty]=useState(false),[earnedDirty,setEarnedDirty]=useState(false),[savedComponentId,setSavedComponentId]=useState(isNew?"":params.componentId);

 useEffect(()=>{(async()=>{setLoading(true);setError("");const q=new URLSearchParams(window.location.search);const requestedVersion=q.get("version")||"",returnedRuleSet=q.get("ruleSet")||"",returnedPurpose=q.get("purpose")||"",returnedChoice=q.get("eligibilityChoice") as EligibilityMode|null;const{data,error:rpcError}=await supabase.rpc("get_compensation_plan_admin_data");if(rpcError){setError(rpcError.message);setLoading(false);return}const ps=(data?.plans||[]) as Plan[];setPlans(ps);if(isNew){setVersionId(requestedVersion);if(returnedChoice)setEligibilityMode(returnedChoice);setLoading(false);return}for(const p of ps)for(const v of p.versions){const c=v.components.find(x=>x.component_id===params.componentId);if(c){const cfg=c.rule_configuration||{};setVersionId(v.version_id);setName(c.name);setCode(c.component_code);setCodeTouched(true);setDescription(c.description||"");setCalculationType(c.calculation_type||"percentage");setMeasurementSource(["amount","average_arr","book_of_business","hubspot_meeting"].includes(c.measurement_source||"")?(c.measurement_source||"amount"):"custom");setCustomMeasurementSource(["amount","average_arr","book_of_business","hubspot_meeting"].includes(c.measurement_source||"")?"":(c.measurement_source||""));setMeasurementPeriod(c.measurement_period||"per_deal");setMaximumPayout(c.maximum_payout==null?"":String(c.maximum_payout));setRatePercent(cfg.rate!=null?String(Number(cfg.rate)*100):"");setRuleConfig(cfg);setEligibilityMode(returnedChoice||existingMode(c));const e=cfg.eligibility;setWaitingDays(String(e?.waiting_days??c.additional_eligibility_waiting_days??0));setEligibilityDescription(e?.description||"");setSelectedEligibilityRuleSet(returnedPurpose==="eligibility"&&returnedRuleSet?returnedRuleSet:e?.rule_set_id||"");}}setLoading(false)})()},[isNew,params.componentId]);
 useEffect(()=>{if(!savedComponentId)return;(async()=>{const{data,error:e}=await supabase.rpc("get_comp_rule_builder_catalog",{target_plan_component_id:savedComponentId});if(e){setError(e.message);return}setRuleSets((data?.rule_sets||[]) as RuleSetSummary[])})()},[savedComponentId]);
 const anyDirty=dirty||earnedDirty;
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(!anyDirty)return;e.preventDefault();e.returnValue=""};window.addEventListener("beforeunload",f);return()=>window.removeEventListener("beforeunload",f)},[anyDirty]);
 const mark=()=>{setDirty(true);setMessage("")};const selectedPlan=useMemo(()=>plans.find(p=>p.versions.some(v=>v.version_id===versionId)),[plans,versionId]);const selectedVersion=selectedPlan?.versions.find(v=>v.version_id===versionId);const editable=selectedVersion?.status==="draft";const eligibilityRuleSets=ruleSets.filter(r=>r.purpose==="eligibility");const actualMeasurementSource=measurementSource==="custom"?customMeasurementSource:measurementSource;
 const planSetupHref=versionId?`/plans/manage/${versionId}`:"/plans";
 const ruleBuilderHref=(purpose:string,ruleSetId?:string)=>{const returnTo=`/plans/component/${savedComponentId}?version=${versionId}${purpose==="eligibility"?`&eligibilityChoice=${eligibilityMode}`:""}`;const q=new URLSearchParams();if(ruleSetId)q.set("ruleSet",ruleSetId);else{q.set("component",savedComponentId);q.set("purpose",purpose)}q.set("returnTo",returnTo);return `/plans/rules?${q.toString()}`};
 const save=async(goBack=false)=>{if(!versionId){setError("A draft plan version is required.");return null}if(!editable){setError("Only draft plan versions can be edited.");return null}if(!name.trim()||!code.trim()){setError("Complete all required fields marked with *.");return null}if(calculationType==="percentage"&&(ratePercent===""||Number(ratePercent)<0)){setError("Enter the percentage this Earning Type pays.");return null}if(!actualMeasurementSource){setError("Choose what the payment is based on.");return null}setSaving(true);setError("");setMessage("");const nextRuleConfig={...(ruleConfig||{})};if(calculationType==="percentage")nextRuleConfig.rate=Number(ratePercent)/100;else delete nextRuleConfig.rate;const{data,error:componentError}=await supabase.rpc("save_compensation_plan_component",{selected_plan_version_id:versionId,selected_component_id:savedComponentId||null,selected_name:name.trim(),selected_component_code:code.trim(),selected_description:description||null,selected_calculation_type:calculationType,selected_measurement_source:actualMeasurementSource,selected_measurement_period:measurementPeriod,selected_calculation_order:1,selected_rule_configuration:nextRuleConfig,selected_maximum_payout:maximumPayout===""?null:Number(maximumPayout),selected_is_active:true,selected_payout_timing_method:"annual",selected_allow_manager_payout_override:true,selected_measurement_label:null});if(componentError){setSaving(false);setError(componentError.message);return null}const id=String(data?.component_id||savedComponentId);setSavedComponentId(id);setRuleConfig(nextRuleConfig);const ruleId=(eligibilityMode==="rule"||eligibilityMode==="customer_payment")?(selectedEligibilityRuleSet||null):null;const{data:eligibilityResult,error:eligError}=await supabase.rpc("save_compensation_plan_component_eligibility",{selected_component_id:id,selected_mode:eligibilityMode,selected_waiting_days:eligibilityMode==="waiting_period"?Number(waitingDays||0):null,selected_rule_set_id:ruleId,selected_description:eligibilityDescription||null});if(eligError){setSaving(false);setError(`The Earning Type was saved, but its payment condition could not be saved: ${eligError.message}`);return null}if(eligibilityMode==="customer_payment"&&eligibilityResult?.rule_set_id)setSelectedEligibilityRuleSet(String(eligibilityResult.rule_set_id));if(earnedDirty&&earnedRef.current){const earnedSaved=await earnedRef.current.save();if(!earnedSaved){setSaving(false);setError("The payout details were saved, but the Earned conditions still need attention below.");return null}}setDirty(false);setEarnedDirty(false);setSaving(false);setMessage(eligibilityMode==="customer_payment"?"All changes saved. Customer payment eligibility was configured and checked against current HubSpot data.":"All changes saved.");if(isNew&&!goBack)router.replace(`/plans/component/${id}?version=${versionId}`);if(goBack)router.push(planSetupHref);return id};
 const submit=(e:FormEvent)=>{e.preventDefault();void save(false)};const example=calculationType==="percentage"&&ratePercent!==""?120000*(Number(ratePercent)/100):null;
 if(loading)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-empty">Loading Earning Type…</div></div></main>;
 return <main className="plan-workspace"><div className="plan-page-shell" style={{paddingBottom:110}}><div className="plan-breadcrumb"><Link href={planSetupHref}><ArrowLeft size={15}/>Plan setup</Link><span>/</span><span>{selectedPlan?.name||"Plan"}</span><span>/</span><span>{isNew?"Add Earning Type":name||"Earning Type"}</span></div>
 <header className="plan-page-header"><div><span className="plan-kicker">EARNING TYPE</span><h1>{isNew?"Add Earning Type":name||"Earning Type"}</h1><p>Answer three questions: what it pays, when it is Earned, and when it can be paid.</p><small><b>* Required</b></small></div>{selectedVersion&&<span className={`plan-status ${selectedVersion.status}`}>{selectedVersion.status} v{selectedVersion.version_number}</span>}</header>
 <div className="plan-lifecycle-strip"><div><span>1</span><b>Qualifying activity</b><small>Deal or other source</small></div><div><span>2</span><b>Earned</b><small>Earned conditions are met</small></div><div><span>3</span><b>Eligible</b><small>Payment condition is met</small></div><div><span>4</span><b>Approved</b><small>Plan approval sequence completes</small></div><div><span>5</span><b>Paid</b><small>Finance/payroll pays</small></div></div>
 {error&&<div className="plan-alert error">{error}</div>}{message&&<div className="plan-info-row"><CheckCircle2 size={16}/>{message}</div>}
 <form onSubmit={submit} className="plan-editor-card"><section><div className="plan-editor-heading"><div><span className="plan-step-number">1</span><div><h2>What it pays <span style={{color:"#b42318"}}>*</span></h2><p>Choose the payout method first. Advanced calculation details stay out of the way unless you need them.</p></div></div></div><div className="plan-form-grid two">
 <label>Earning Type name <span style={{color:"#b42318"}}>*</span><input value={name} onChange={e=>{const v=e.target.value;setName(v);if(!codeTouched)setCode(slug(v));mark()}} placeholder="Retention Commission" required disabled={!editable}/><Help>Use a name employees will recognize when they see an earning.</Help></label>
 <label>Earning Type code <span style={{color:"#b42318"}}>*</span><input value={code} onChange={e=>{setCodeTouched(true);setCode(slug(e.target.value));mark()}} required disabled={!editable}/><Help>Created from the name. Change it only if another system expects a specific code.</Help></label>
 <label>How does it pay? <span style={{color:"#b42318"}}>*</span><select value={calculationType} onChange={e=>{setCalculationType(e.target.value);mark()}} disabled={!editable}><option value="percentage">Percentage</option><option value="tiered_percentage">Different percentages by tier</option><option value="fixed_amount">Fixed dollar amount</option><option value="fixed_amount_per_unit">Fixed amount per qualifying item</option><option value="milestone_bonus">Milestone bonus</option><option value="threshold_bonus">Threshold bonus</option></select></label>
 {calculationType==="percentage"&&<label>Rate <span style={{color:"#b42318"}}>*</span><div style={{display:"flex",alignItems:"center",border:"2px solid #2095f3",borderRadius:9,overflow:"hidden",background:"white"}}><input type="number" min="0" step="0.01" value={ratePercent} onChange={e=>{setRatePercent(e.target.value);mark()}} placeholder="2" required disabled={!editable} style={{height:46,border:0,outline:0,fontSize:20,fontWeight:800,padding:"0 12px",width:"100%"}}/><b style={{padding:"0 14px",fontSize:18}}>%</b></div></label>}
 <label>What is it a percentage or amount of? <span style={{color:"#b42318"}}>*</span><select value={measurementSource} onChange={e=>{setMeasurementSource(e.target.value);mark()}} disabled={!editable}><option value="amount">The deal amount</option><option value="average_arr">Its annual recurring revenue (ARR)</option><option value="book_of_business">Book of business value</option><option value="hubspot_meeting">A qualifying meeting/activity</option><option value="custom">Something else…</option></select><Help>This is the value the rate is multiplied by.</Help></label>
 {measurementSource==="custom"&&<label>Custom payment basis <span style={{color:"#b42318"}}>*</span><input value={customMeasurementSource} onChange={e=>{setCustomMeasurementSource(e.target.value);mark()}} required disabled={!editable}/></label>}
 <label>How often is it calculated? <span style={{color:"#b42318"}}>*</span><select value={measurementPeriod} onChange={e=>{setMeasurementPeriod(e.target.value);mark()}} disabled={!editable}><option value="per_deal">For each qualifying deal/activity</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annually</option></select></label><label>Maximum payout<input type="number" step="0.01" value={maximumPayout} onChange={e=>{setMaximumPayout(e.target.value);mark()}} placeholder="No maximum" disabled={!editable}/><Help>Leave blank when this Earning Type has no cap.</Help></label></div>
 {example!=null&&<div className="plan-info-row" style={{marginTop:14}}><CheckCircle2 size={16}/><span>Example: on a $120,000 {basisLabel(actualMeasurementSource)}, <b>{ratePercent}% pays {new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(example)}</b>.</span></div>}
 <label className="plan-full-field">Description<textarea value={description} onChange={e=>{setDescription(e.target.value);mark()}} rows={2} placeholder="Optional plain-language explanation" disabled={!editable}/></label><details style={{marginTop:14,borderTop:"1px solid #e6e8ec",paddingTop:12}}><summary style={{cursor:"pointer",fontWeight:700}}>Advanced settings</summary><p style={{fontSize:12,color:"#667085"}}>Most plans never need these. Calculation order, rounding, splits, and clawbacks belong here as those capabilities are completed.</p></details></section>
 <section style={{marginTop:30}}><div className="plan-editor-heading"><div><span className="plan-step-number">2</span><div><h2>When is it Earned? <span style={{color:"#b42318"}}>*</span></h2><p>Compensation becomes Earned when these business conditions are true. It is not payable yet.</p></div></div></div>{!savedComponentId?<div className="plan-alert warning">Save the payout details once to create this Earning Type. The Earned-condition builder will then open immediately on this same page.</div>:<EarnedConditionsEditor ref={earnedRef} componentId={savedComponentId} disabled={!editable} onDirtyChange={setEarnedDirty}/>}</section>
 <section style={{marginTop:30}}><div className="plan-editor-heading"><div><span className="plan-step-number">3</span><div><h2>When can it be paid? <span style={{color:"#b42318"}}>*</span></h2><p>Until this condition is met, the employee sees the amount as Earned but it is not Eligible for payment.</p></div></div></div><div className="eligibility-choice-grid">{([['immediate','Nothing else','It becomes Eligible as soon as it is Earned.'],['customer_payment','The customer has paid','The customer must pay Engagifii before this becomes Eligible.'],['waiting_period','A waiting period after it is earned','It becomes Eligible after a defined number of days.'],['rule','Something else','Use another condition from approved synchronized data.']] as [EligibilityMode,string,string][]).map(([value,title,copy])=><label key={value} className={`eligibility-choice ${eligibilityMode===value?'selected':''}`}><input type="radio" name="eligibility" checked={eligibilityMode===value} onChange={()=>{setEligibilityMode(value);if(value==="immediate"||value==="waiting_period")setSelectedEligibilityRuleSet("");mark()}} disabled={!editable}/><div><b>{title}</b><span>{copy}</span></div></label>)}</div>
 {eligibilityMode==="waiting_period"&&<div className="plan-form-grid two" style={{marginTop:14}}><label>Number of days <span style={{color:"#b42318"}}>*</span><input type="number" min="0" value={waitingDays} onChange={e=>{setWaitingDays(e.target.value);mark()}} required disabled={!editable}/></label></div>}
 {eligibilityMode==="customer_payment"&&<div className="plan-info-row" style={{marginTop:14}}><CheckCircle2 size={16}/><span>Customer paid means HubSpot Deal → Invoice Paid Date → is known. Saving this option applies that workspace rule automatically.</span></div>}
 {eligibilityMode==="rule"&&savedComponentId&&<div className="plan-info-row" style={{marginTop:14,justifyContent:"space-between"}}><span>{selectedEligibilityRuleSet?"The custom payment condition is attached.":"Define the custom condition that makes this Eligible."}</span><Link className="plan-button secondary" href={selectedEligibilityRuleSet?ruleBuilderHref("eligibility",selectedEligibilityRuleSet):ruleBuilderHref("eligibility")}><ExternalLink size={14}/>{selectedEligibilityRuleSet?"Edit custom condition":"Define custom condition"}</Link></div>}
 {eligibilityMode==="rule"&&eligibilityRuleSets.length>0&&!selectedEligibilityRuleSet&&<label className="plan-full-field" style={{marginTop:12}}>Existing custom payment condition<select value={selectedEligibilityRuleSet} onChange={e=>{setSelectedEligibilityRuleSet(e.target.value);mark()}}><option value="">Choose a condition…</option>{eligibilityRuleSets.map(r=><option key={r.id} value={r.id}>{r.name} · v{r.version}</option>)}</select></label>}<label className="plan-full-field">Internal note<textarea value={eligibilityDescription} onChange={e=>{setEligibilityDescription(e.target.value);mark()}} rows={2} placeholder="Optional" disabled={!editable}/></label></section>
 <section style={{marginTop:30}}><div className="plan-info-row"><ShieldCheck size={17}/><div><b>Approvals come from this plan</b><div style={{fontSize:12,color:"#667085",marginTop:3}}>After an employee submits an Eligible earning, the approval steps configured for this plan version determine who reviews it before Finance can pay it.</div></div>{versionId&&<Link href={`/plans/manage/${versionId}/approvals`} className="plan-button secondary">Manage plan approvals</Link>}</div></section>
 <div style={{height:20}}/></form>
 {editable&&<div style={{position:"sticky",bottom:0,zIndex:40,background:"white",borderTop:`2px solid ${anyDirty?"#fc9800":"#4b9b68"}`,boxShadow:"0 -8px 24px rgba(5,27,52,.08)",padding:"12px 16px",display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",marginTop:0}}><div><b style={{display:"flex",gap:7,alignItems:"center"}}><span style={{width:8,height:8,borderRadius:"50%",background:anyDirty?"#fc9800":"#4b9b68"}}/>{anyDirty?"Unsaved changes":"All changes saved"}</b><small style={{display:"block",color:"#667085",marginTop:3}}>{anyDirty?`${earnedDirty?"Earned conditions changed · ":""}${ratePercent?`Rate ${ratePercent}% · `:""}${eligibilityMode==="customer_payment"?"can be paid when the customer has paid":eligibilityMode==="immediate"?"can be paid immediately":eligibilityMode==="waiting_period"?`can be paid after ${waitingDays} days`:"custom payment condition"}`:"Nothing pays until the plan is activated."}</small></div><div style={{display:"flex",gap:8}}><button type="button" className="plan-button secondary" disabled={!anyDirty||saving} onClick={()=>window.location.reload()}>Discard changes</button><button type="button" className="plan-button secondary" disabled={saving} onClick={()=>void save(false)}><Save size={14}/>{saving?"Saving…":"Save"}</button><button type="button" className="plan-button primary" disabled={saving} onClick={()=>void save(true)}>{saving?"Saving…":"Save & back to plan setup"}</button></div></div>}
 </div></main>;
