"use client";

import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CheckCircle2,ExternalLink,HelpCircle,Save,ShieldCheck} from "lucide-react";
import EarnedConditionsEditor,{EarnedConditionsEditorHandle} from "./earned-conditions-editor";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");

type EarningType={component_id:string;name:string;component_code:string;description:string|null;calculation_type:string|null;measurement_source:string|null;measurement_period:string|null;maximum_payout:number|null;additional_eligibility_waiting_days:number|null;rule_configuration:any};
type Version={version_id:string;version_number:number;status:string;components:EarningType[]};
type Plan={plan_id:string;name:string;versions:Version[]};
type RuleSetSummary={id:string;name:string;purpose:string;version:number};
type EligibilityMode="immediate"|"customer_payment"|"waiting_period"|"rule";

const slug=(v:string)=>v.toUpperCase().trim().replace(/[^A-Z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,80);
function Help({children}:{children:React.ReactNode}){return <span style={{display:"flex",alignItems:"center",gap:4,color:"#667085",fontWeight:500,fontSize:11,marginTop:5}}><HelpCircle size={13}/>{children}</span>}
function existingMode(c:EarningType|null):EligibilityMode{const e=c?.rule_configuration?.eligibility;if(e?.business_concept==="customer_payment_received")return "customer_payment";if(["immediate","customer_payment","waiting_period","rule"].includes(e?.mode))return e.mode as EligibilityMode;return "immediate"}

export default function EarningTypeEditor(){
 const params=useParams<{componentId:string}>();
 const router=useRouter();
 const isNew=params.componentId==="new";
 const earnedRef=useRef<EarnedConditionsEditorHandle>(null);
 const[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const[versionId,setVersionId]=useState(""),[savedComponentId,setSavedComponentId]=useState(isNew?"":params.componentId);
 const[name,setName]=useState(""),[code,setCode]=useState(""),[codeTouched,setCodeTouched]=useState(false),[description,setDescription]=useState("");
 const[calculationType,setCalculationType]=useState("percentage"),[measurementSource,setMeasurementSource]=useState("amount"),[measurementPeriod,setMeasurementPeriod]=useState("per_deal"),[maximumPayout,setMaximumPayout]=useState(""),[ratePercent,setRatePercent]=useState("");
 const[eligibilityMode,setEligibilityMode]=useState<EligibilityMode>("immediate"),[waitingDays,setWaitingDays]=useState("0"),[eligibilityDescription,setEligibilityDescription]=useState(""),[selectedEligibilityRuleSet,setSelectedEligibilityRuleSet]=useState("");
 const[ruleSets,setRuleSets]=useState<RuleSetSummary[]>([]),[dirty,setDirty]=useState(false),[earnedDirty,setEarnedDirty]=useState(false),[ruleConfig,setRuleConfig]=useState<any>({});

 useEffect(()=>{(async()=>{setLoading(true);setError("");const q=new URLSearchParams(window.location.search);const requestedVersion=q.get("version")||"";const returnedRuleSet=q.get("ruleSet")||"";const returnedPurpose=q.get("purpose")||"";const returnedChoice=q.get("eligibilityChoice") as EligibilityMode|null;const{data,error:e}=await supabase.rpc("get_compensation_plan_admin_data");if(e){setError(e.message);setLoading(false);return}const ps=(data?.plans||[]) as Plan[];setPlans(ps);if(isNew){setVersionId(requestedVersion);if(returnedChoice)setEligibilityMode(returnedChoice);setLoading(false);return}for(const p of ps)for(const v of p.versions){const c=v.components.find(x=>x.component_id===params.componentId);if(!c)continue;const cfg=c.rule_configuration||{};setVersionId(v.version_id);setName(c.name);setCode(c.component_code);setCodeTouched(true);setDescription(c.description||"");setCalculationType(c.calculation_type||"percentage");setMeasurementSource(c.measurement_source||"amount");setMeasurementPeriod(c.measurement_period||"per_deal");setMaximumPayout(c.maximum_payout==null?"":String(c.maximum_payout));setRatePercent(cfg.rate!=null?String(Number(cfg.rate)*100):"");setRuleConfig(cfg);setEligibilityMode(returnedChoice||existingMode(c));setWaitingDays(String(cfg.eligibility?.waiting_days??c.additional_eligibility_waiting_days??0));setEligibilityDescription(cfg.eligibility?.description||"");setSelectedEligibilityRuleSet(returnedPurpose==="eligibility"&&returnedRuleSet?returnedRuleSet:cfg.eligibility?.rule_set_id||"");}setLoading(false)})()},[isNew,params.componentId]);
 useEffect(()=>{if(!savedComponentId)return;(async()=>{const{data,error:e}=await supabase.rpc("get_comp_rule_builder_catalog",{target_plan_component_id:savedComponentId});if(e){setError(e.message);return}setRuleSets((data?.rule_sets||[]) as RuleSetSummary[])})()},[savedComponentId]);
 const selectedPlan=useMemo(()=>plans.find(p=>p.versions.some(v=>v.version_id===versionId)),[plans,versionId]);
 const selectedVersion=selectedPlan?.versions.find(v=>v.version_id===versionId);
 const editable=selectedVersion?.status==="draft";
 const planSetupHref=versionId?`/plans/manage/${versionId}`:"/plans";
 const mark=()=>{setDirty(true);setMessage("")};
 const anyDirty=dirty||earnedDirty;
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(!anyDirty)return;e.preventDefault();e.returnValue=""};window.addEventListener("beforeunload",f);return()=>window.removeEventListener("beforeunload",f)},[anyDirty]);
 const ruleBuilderHref=(ruleSetId?:string)=>{const returnTo=`/plans/component/${savedComponentId}?version=${versionId}&eligibilityChoice=rule`;const q=new URLSearchParams();if(ruleSetId)q.set("ruleSet",ruleSetId);else{q.set("component",savedComponentId);q.set("purpose","eligibility")}q.set("returnTo",returnTo);return `/plans/rules?${q.toString()}`};

 const save=async(goBack=false)=>{if(!versionId||!editable){setError("A draft plan version is required.");return}if(!name.trim()||!code.trim()){setError("Complete the required Earning Type fields.");return}if(calculationType==="percentage"&&(ratePercent===""||Number(ratePercent)<0)){setError("Enter the payout percentage.");return}setSaving(true);setError("");setMessage("");const nextConfig={...(ruleConfig||{})};if(calculationType==="percentage")nextConfig.rate=Number(ratePercent)/100;else delete nextConfig.rate;const{data,error:componentError}=await supabase.rpc("save_compensation_plan_component",{selected_plan_version_id:versionId,selected_component_id:savedComponentId||null,selected_name:name.trim(),selected_component_code:code.trim(),selected_description:description||null,selected_calculation_type:calculationType,selected_measurement_source:measurementSource,selected_measurement_period:measurementPeriod,selected_calculation_order:1,selected_rule_configuration:nextConfig,selected_maximum_payout:maximumPayout===""?null:Number(maximumPayout),selected_is_active:true,selected_payout_timing_method:"annual",selected_allow_manager_payout_override:true,selected_measurement_label:null});if(componentError){setSaving(false);setError(componentError.message);return}const id=String(data?.component_id||savedComponentId);setSavedComponentId(id);setRuleConfig(nextConfig);const ruleId=(eligibilityMode==="rule"||eligibilityMode==="customer_payment")?(selectedEligibilityRuleSet||null):null;const{data:eligibilityResult,error:eligError}=await supabase.rpc("save_compensation_plan_component_eligibility",{selected_component_id:id,selected_mode:eligibilityMode,selected_waiting_days:eligibilityMode==="waiting_period"?Number(waitingDays||0):null,selected_rule_set_id:ruleId,selected_description:eligibilityDescription||null});if(eligError){setSaving(false);setError(`The Earning Type was saved, but its payment condition could not be saved: ${eligError.message}`);return}if(eligibilityMode==="customer_payment"&&eligibilityResult?.rule_set_id)setSelectedEligibilityRuleSet(String(eligibilityResult.rule_set_id));if(earnedDirty&&earnedRef.current){const ok=await earnedRef.current.save();if(!ok){setSaving(false);setError("The payout details were saved, but the Earned conditions still need attention.");return}}setDirty(false);setEarnedDirty(false);setSaving(false);setMessage("All changes saved.");if(isNew&&!goBack)router.replace(`/plans/component/${id}?version=${versionId}`);if(goBack)router.push(planSetupHref)};
 const submit=(e:FormEvent)=>{e.preventDefault();void save(false)};
 if(loading)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-empty">Loading Earning Type…</div></div></main>;

 return <main className="plan-workspace"><div className="plan-page-shell" style={{paddingBottom:110}}>
  <div className="plan-breadcrumb"><Link href={planSetupHref}><ArrowLeft size={15}/>Plan setup</Link><span>/</span><span>{selectedPlan?.name||"Plan"}</span><span>/</span><span>{isNew?"Add Earning Type":name||"Earning Type"}</span></div>
  <header className="plan-page-header"><div><span className="plan-kicker">EARNING TYPE</span><h1>{isNew?"Add Earning Type":name||"Earning Type"}</h1><p>Define what it pays, when it is Earned, and when it becomes Eligible for payment.</p></div>{selectedVersion&&<span className={`plan-status ${selectedVersion.status}`}>{selectedVersion.status} v{selectedVersion.version_number}</span>}</header>
  <div className="plan-lifecycle-strip"><div><span>1</span><b>Qualifying activity</b><small>Deal or source</small></div><div><span>2</span><b>Earned</b><small>Earned conditions met</small></div><div><span>3</span><b>Eligible</b><small>Payment condition met</small></div><div><span>4</span><b>Approved</b><small>Plan approval sequence</small></div><div><span>5</span><b>Paid</b><small>Finance/payroll</small></div></div>
  {error&&<div className="plan-alert error">{error}</div>}{message&&<div className="plan-info-row"><CheckCircle2 size={16}/>{message}</div>}
  <form onSubmit={submit} className="plan-editor-card">
   <section><div className="plan-editor-heading"><div><span className="plan-step-number">1</span><div><h2>What it pays *</h2><p>Choose the payout method and basis.</p></div></div></div><div className="plan-form-grid two">
    <label>Earning Type name *<input value={name} onChange={e=>{const v=e.target.value;setName(v);if(!codeTouched)setCode(slug(v));mark()}} required disabled={!editable}/><Help>Use a name employees will recognize.</Help></label>
    <label>Earning Type code *<input value={code} onChange={e=>{setCodeTouched(true);setCode(slug(e.target.value));mark()}} required disabled={!editable}/></label>
    <label>How does it pay? *<select value={calculationType} onChange={e=>{setCalculationType(e.target.value);mark()}} disabled={!editable}><option value="percentage">Percentage</option><option value="tiered_percentage">Different percentages by tier</option><option value="fixed_amount">Fixed dollar amount</option><option value="fixed_amount_per_unit">Fixed amount per qualifying item</option><option value="milestone_bonus">Milestone bonus</option><option value="threshold_bonus">Threshold bonus</option></select></label>
    {calculationType==="percentage"&&<label>Rate % *<input type="number" min="0" step="0.01" value={ratePercent} onChange={e=>{setRatePercent(e.target.value);mark()}} required disabled={!editable}/></label>}
    <label>Payment basis *<select value={measurementSource} onChange={e=>{setMeasurementSource(e.target.value);mark()}} disabled={!editable}><option value="amount">Deal amount</option><option value="average_arr">ARR</option><option value="book_of_business">Book of business value</option><option value="hubspot_meeting">Qualifying activity</option></select></label>
    <label>Calculated how often? *<select value={measurementPeriod} onChange={e=>{setMeasurementPeriod(e.target.value);mark()}} disabled={!editable}><option value="per_deal">Per qualifying deal/activity</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annually</option></select></label>
    <label>Maximum payout<input type="number" step="0.01" value={maximumPayout} onChange={e=>{setMaximumPayout(e.target.value);mark()}} disabled={!editable}/></label>
   </div><label className="plan-full-field">Description<textarea value={description} onChange={e=>{setDescription(e.target.value);mark()}} rows={2} disabled={!editable}/></label></section>

   <section style={{marginTop:30}}><div className="plan-editor-heading"><div><span className="plan-step-number">2</span><div><h2>When is it Earned? *</h2><p>Define the business conditions that make the compensation Earned.</p></div></div></div>{!savedComponentId?<div className="plan-alert warning">Save once to create this Earning Type; the Earned-condition builder will then appear here on the same page.</div>:<EarnedConditionsEditor ref={earnedRef} componentId={savedComponentId} disabled={!editable} onDirtyChange={setEarnedDirty}/>}</section>

   <section style={{marginTop:30}}><div className="plan-editor-heading"><div><span className="plan-step-number">3</span><div><h2>When can it be paid? *</h2><p>Until this condition is met, the amount remains Earned but not Eligible for payment.</p></div></div></div><div className="eligibility-choice-grid">{([['immediate','Nothing else','Eligible as soon as Earned.'],['customer_payment','The customer has paid','Requires customer payment before eligibility.'],['waiting_period','A waiting period','Eligible after a defined number of days.'],['rule','Something else','Use a custom condition from approved HubSpot rule data.']] as [EligibilityMode,string,string][]).map(([value,t,c])=><label key={value} className={`eligibility-choice ${eligibilityMode===value?'selected':''}`}><input type="radio" checked={eligibilityMode===value} onChange={()=>{setEligibilityMode(value);mark()}} disabled={!editable}/><div><b>{t}</b><span>{c}</span></div></label>)}</div>
    {eligibilityMode==="waiting_period"&&<label className="plan-full-field">Number of days *<input type="number" min="0" value={waitingDays} onChange={e=>{setWaitingDays(e.target.value);mark()}} required disabled={!editable}/></label>}
    {eligibilityMode==="customer_payment"&&<div className="plan-info-row"><CheckCircle2 size={16}/><span>Customer paid = HubSpot Deal → Invoice Paid Date → is known.</span></div>}
    {eligibilityMode==="rule"&&savedComponentId&&<div className="plan-info-row" style={{justifyContent:"space-between"}}><span>{selectedEligibilityRuleSet?"Custom payment condition attached.":"Define the custom payment condition."}</span><Link className="plan-button secondary" href={ruleBuilderHref(selectedEligibilityRuleSet||undefined)}><ExternalLink size={14}/>{selectedEligibilityRuleSet?"Edit condition":"Define condition"}</Link></div>}
    {eligibilityMode==="rule"&&ruleSets.filter(r=>r.purpose==="eligibility").length>0&&!selectedEligibilityRuleSet&&<label className="plan-full-field">Existing payment condition<select value={selectedEligibilityRuleSet} onChange={e=>{setSelectedEligibilityRuleSet(e.target.value);mark()}}><option value="">Choose…</option>{ruleSets.filter(r=>r.purpose==="eligibility").map(r=><option key={r.id} value={r.id}>{r.name} · v{r.version}</option>)}</select></label>}
    <label className="plan-full-field">Internal note<textarea value={eligibilityDescription} onChange={e=>{setEligibilityDescription(e.target.value);mark()}} rows={2} disabled={!editable}/></label>
   </section>

   <section style={{marginTop:30}}><div className="plan-info-row"><ShieldCheck size={17}/><div><b>Approvals come from this plan</b><div style={{fontSize:12,color:"#667085",marginTop:3}}>After an employee submits an Eligible earning, the approval steps configured for this plan determine who reviews it before payment.</div></div>{versionId&&<Link href={`/plans/manage/${versionId}/approvals`} className="plan-button secondary">Manage plan approvals</Link>}</div></section>
  </form>

  {editable&&<div style={{position:"sticky",bottom:0,zIndex:40,background:"white",borderTop:`2px solid ${anyDirty?"#fc9800":"#4b9b68"}`,boxShadow:"0 -8px 24px rgba(5,27,52,.08)",padding:"12px 16px",display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><b>{anyDirty?"Unsaved changes":"All changes saved"}</b><small style={{display:"block",color:"#667085",marginTop:3}}>Nothing pays until the plan is activated.</small></div><div style={{display:"flex",gap:8}}><button type="button" className="plan-button secondary" disabled={!anyDirty||saving} onClick={()=>window.location.reload()}>Discard changes</button><button type="button" className="plan-button secondary" disabled={saving} onClick={()=>void save(false)}><Save size={14}/>{saving?"Saving…":"Save"}</button><button type="button" className="plan-button primary" disabled={saving} onClick={()=>void save(true)}>{saving?"Saving…":"Save & back to plan setup"}</button></div></div>}
 </div></main>;
}
