"use client";

import {useEffect,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CheckCircle2,Layers3,RefreshCw,Users} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Component={component_id:string;name:string;component_code:string;description:string|null;calculation_type:string|null;measurement_source:string|null;measurement_period:string|null;calculation_order:number;maximum_payout:number|null;is_active:boolean;payout_timing_method:string;measurement_label:string|null;additional_eligibility_waiting_days:number};
type Assignment={assignment_id:string;employee_name:string;allocation_percent:number;effective_start_date:string;effective_end_date:string|null;earnings_eligibility_date:string|null};
type Version={version_id:string;version_number:number;status:string;effective_start_date:string;effective_end_date:string|null;currency_code:string;notes:string|null;approved_at:string|null;components:Component[];assignments:Assignment[]};
type Plan={plan_id:string;name:string;plan_code:string;description:string|null;plan_type:string;is_active:boolean;versions:Version[]};
type Payload={plans:Plan[]};
function label(v:string|null|undefined){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function money(v:number|null){return v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v)}

export default function PlansPage(){
 const[data,setData]=useState<Payload>({plans:[]});const[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const{data:result,error:rpcError}=await supabase.rpc("get_compensation_plan_admin_data");if(rpcError)setError(rpcError.message);else setData((result||{plans:[]}) as Payload);setLoading(false)};useEffect(()=>{load()},[]);
 const versions=data.plans.flatMap(p=>p.versions),active=versions.filter(v=>v.status==="active").length,draft=versions.filter(v=>v.status==="draft").length,assignments=versions.reduce((a,v)=>a+v.assignments.length,0);
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1320,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:22,flexWrap:"wrap"}}><div><Link href="/manage" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700,fontSize:13}}><ArrowLeft size={15}/>Management</Link><small style={{display:"block",fontWeight:800,letterSpacing:1.1,color:"#2095f3",marginTop:12}}>PLAN CONFIGURATION</small><h1 style={{fontSize:34,margin:"6px 0"}}>Compensation plans</h1><p style={{margin:0,color:"#647184"}}>Effective-dated plan versions, components, payout timing, and employee assignments from the live compensation model.</p></div><button onClick={load} disabled={loading} style={{display:"flex",gap:7,alignItems:"center",padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:700}}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>{error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginBottom:18}}>{[["Plans",data.plans.length],["Active versions",active],["Draft versions",draft],["Assignments",assignments]].map(([a,b])=><div key={String(a)} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small>{a}</small><b style={{display:"block",fontSize:26}}>{loading?"—":b}</b></div>)}</section>
 <section style={{display:"grid",gap:16}}>{data.plans.map(p=><article key={p.plan_id} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 4px"}}>{p.name}</h2><small style={{color:"#718096"}}>{p.plan_code} · {label(p.plan_type)}</small>{p.description&&<p style={{color:"#647184",margin:"8px 0 0"}}>{p.description}</p>}</div><span style={{fontWeight:800,color:p.is_active?"#0f7a50":"#718096"}}>{p.is_active?"Active plan":"Inactive plan"}</span></div>{p.versions.map(v=><div key={v.version_id} style={{marginTop:16,borderTop:"1px solid #edf1f5",paddingTop:15}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginBottom:12}}><div><b>Version {v.version_number} · {label(v.status)}</b><small style={{display:"block",color:"#718096",marginTop:3}}>{v.effective_start_date} → {v.effective_end_date||"open ended"} · {v.currency_code}</small></div><div style={{display:"flex",gap:14,color:"#647184",fontSize:13}}><span><Layers3 size={15}/> {v.components.length} components</span><span><Users size={15}/> {v.assignments.length} assignments</span></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(245px,1fr))",gap:9}}>{v.components.map(c=><div key={c.component_id} style={{border:"1px solid #e4eaf0",borderRadius:10,padding:12}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><b>{c.name}</b>{c.is_active&&<CheckCircle2 size={15} color="#0f7a50"/>}</div><small style={{display:"block",color:"#718096",marginTop:3}}>{c.component_code} · {label(c.calculation_type)}</small><div style={{fontSize:12,color:"#647184",marginTop:8,lineHeight:1.5}}><div>Measure: {c.measurement_label||label(c.measurement_source)}</div><div>Period: {label(c.measurement_period)} · Payout: {label(c.payout_timing_method)}</div><div>Maximum: {money(c.maximum_payout)}{c.additional_eligibility_waiting_days?` · +${c.additional_eligibility_waiting_days} eligibility days`:""}</div></div></div>)}</div>{v.assignments.length>0&&<div style={{marginTop:12,display:"flex",gap:8,flexWrap:"wrap"}}>{v.assignments.map(a=><span key={a.assignment_id} style={{background:"#f3f7fb",border:"1px solid #e0e7ef",borderRadius:20,padding:"6px 9px",fontSize:12}}><b>{a.employee_name}</b> · {a.allocation_percent}% · eligible {a.earnings_eligibility_date||"not set"}</span>)}</div>}</div>)}</article>)}</section></div></main>
}
