"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BadgeDollarSign, CalendarDays, RefreshCw, Users } from "lucide-react";
import { createClient } from "@supabase/supabase-js";
import AdminShell from "../components/admin-shell";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"");

type PlanVersion={plan_version_id:string;plan_id:string;name:string;version_number:number;effective_start_date:string;effective_end_date:string|null};
type Employee={employee_id:string;full_name:string;email:string;job_title:string|null;department:string|null;current_plan_version_id:string|null;current_plan_name:string|null;earnings_eligibility_date:string|null};
type AdminData={active_plan_versions:PlanVersion[];employees:Employee[]};

const date=(value:string|null|undefined)=>value?new Date(`${value}T00:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}):"Open ended";

export default function PlansPage(){
 const[data,setData]=useState<AdminData>({active_plan_versions:[],employees:[]}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");const{data:r,error:e}=await supabase.rpc("get_user_administration_data");if(e)setError(e.message);else setData({active_plan_versions:r?.active_plan_versions||[],employees:r?.employees||[]});setLoading(false)};
 useEffect(()=>{load()},[]);
 const assigned=useMemo(()=>data.employees.filter(e=>e.current_plan_version_id),[data.employees]);
 const byPlan=useMemo(()=>new Map(data.active_plan_versions.map(p=>[p.plan_version_id,assigned.filter(e=>e.current_plan_version_id===p.plan_version_id)])),[data.active_plan_versions,assigned]);
 return <AdminShell section="plans" title="Plans & Programs" description="Plan versions, effective dates, participation, and employee assignment.">
  <div className="space-y-5">
   <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Plans & Programs</h1><p className="mt-1 text-xs text-[#66717f]">Manage the compensation programs employees participate in without mixing plan design with individual user access.</p></div><button onClick={load} disabled={loading} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs font-bold"><RefreshCw size={14}/>{loading?"Refreshing…":"Refresh"}</button></div>
   {error&&<div className="flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={17}/><div><b>Unable to load plan administration</b><div className="mt-1 text-xs">{error}</div></div></div>}
   <div className="grid gap-3 md:grid-cols-3"><article className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#66717f]">ACTIVE PLAN VERSIONS</span><BadgeDollarSign size={17} className="text-[#2095f3]"/></div><b className="mt-2 block text-2xl">{loading?"—":data.active_plan_versions.length}</b><span className="text-[11px] text-[#77808e]">Currently available for assignment</span></article><article className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#66717f]">ASSIGNED EMPLOYEES</span><Users size={17} className="text-[#2095f3]"/></div><b className="mt-2 block text-2xl">{loading?"—":assigned.length}</b><span className="text-[11px] text-[#77808e]">Employees with a current active assignment</span></article><article className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[#66717f]">UNASSIGNED EMPLOYEES</span><CalendarDays size={17} className="text-[#2095f3]"/></div><b className="mt-2 block text-2xl">{loading?"—":data.employees.filter(e=>!e.current_plan_version_id).length}</b><span className="text-[11px] text-[#77808e]">May be non-participants or still need setup</span></article></div>
   {loading?<div className="rounded-xl border bg-white p-8 text-center text-sm text-[#77808e]">Loading compensation plans…</div>:data.active_plan_versions.length===0?<div className="rounded-xl border bg-white p-8 text-center"><BadgeDollarSign className="mx-auto text-[#2095f3]"/><b className="mt-3 block text-sm">No active plan versions</b><p className="mt-1 text-xs text-[#77808e]">Active plan versions will appear here after approval and activation.</p></div>:<div className="grid gap-4 xl:grid-cols-2">{data.active_plan_versions.map(plan=>{const members=byPlan.get(plan.plan_version_id)||[];return <section key={plan.plan_version_id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-extrabold tracking-[.1em] text-[#2095f3]">ACTIVE PLAN</div><h2 className="mt-1 text-lg font-bold">{plan.name}</h2><p className="mt-1 text-xs text-[#77808e]">Version {plan.version_number} · Effective {date(plan.effective_start_date)} → {date(plan.effective_end_date)}</p></div><span className="rounded-full bg-[#e9f8f2] px-2.5 py-1 text-[10px] font-bold text-[#17795e]">Active</span></div><div className="mt-4 rounded-lg bg-[#fafbfd] p-3"><div className="flex items-center justify-between"><b className="text-xs">Current participants</b><span className="text-xs font-bold text-[#0879d5]">{members.length}</span></div>{members.length===0?<p className="mt-2 text-[11px] text-[#77808e]">No employee currently has this plan version assigned.</p>:<div className="mt-2 divide-y">{members.slice(0,6).map(employee=><a key={employee.employee_id} href={`/employee-administration?employee=${encodeURIComponent(employee.employee_id)}`} className="flex items-center justify-between gap-3 py-2 text-xs no-underline"><span><b className="block text-[#29313d]">{employee.full_name}</b><small className="text-[#77808e]">{employee.job_title||employee.department||employee.email}</small></span><span className="text-[10px] font-semibold text-[#66717f]">Eligible {employee.earnings_eligibility_date?date(employee.earnings_eligibility_date):"—"}</span></a>)}{members.length>6&&<div className="pt-2 text-[10px] font-semibold text-[#77808e]">+ {members.length-6} more participant{members.length-6===1?"":"s"}</div>}</div>}</div><div className="mt-4 flex justify-end"><a href="/employee-administration" className="rounded-lg border px-3 py-2 text-xs font-bold text-[#0879d5]">Manage assignments in People & Access</a></div></section>})}</div>}
   <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-sm font-bold">Plan administration boundary</h2><p className="mt-1 text-xs leading-5 text-[#66717f]">Plan versions are effective-dated and governed separately from employee access. Employee assignment remains in People & Access; plan definition, versioning, approval, activation, retirement, and component rules belong in this workspace. The existing backend functions for those lifecycle actions remain intact while the dedicated editor is migrated out of the legacy root screen.</p></section>
  </div>
 </AdminShell>;
}
