"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,CheckCircle2,ChevronRight,FileText,Plus,RefreshCw,Users} from "lucide-react";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type EarningType={component_id:string;name:string;component_code:string;calculation_type:string|null;measurement_source:string|null;maximum_payout:number|null;rule_configuration:any;additional_eligibility_waiting_days:number|null};
type Assignment={assignment_id?:string;draft_assignment_id?:string;employee_id:string;employee_name:string;allocation_percent:number;effective_start_date:string;effective_end_date:string|null};
type Version={version_id:string;version_number:number;status:string;effective_start_date:string;effective_end_date:string|null;currency_code:string;components:EarningType[];assignments:Assignment[];draft_assignments:Assignment[]};
type Plan={plan_id:string;name:string;plan_code:string;description:string|null;versions:Version[]};
type ReadinessItem={code:string;section:string;message:string;component_id?:string;rule_set_id?:string};
type Readiness={ready:boolean;blocker_count:number;blockers:ReadinessItem[]};
const title=(v:string|null|undefined)=>String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase());
function payText(c:EarningType){const cfg=c.rule_configuration||{};if(cfg.rate!=null)return `${Number(cfg.rate)*100}% of ${c.measurement_source==="amount"?"deal amount":title(c.measurement_source)}`;if(cfg.amount!=null)return `$${Number(cfg.amount).toLocaleString()}`;if(Array.isArray(cfg.tiers))return `${cfg.tiers.length} payout tiers`;return title(c.calculation_type)}
function earnedText(c:EarningType){const cfg=c.rule_configuration||{};if(cfg.earned_condition==="qualifying_stage")return "When its Earned conditions are met";if(cfg.earned_condition==="closed_won")return "When the qualifying deal is won";return "Defined by its Earned conditions"}
function eligibleText(c:EarningType){const e=c.rule_configuration?.eligibility;if(e?.business_concept==="customer_payment_received")return "When the customer has paid";if(e?.mode==="immediate")return "As soon as it is Earned";if(e?.mode==="waiting_period")return `After ${e.waiting_days||0} days`;if(e?.mode==="rule")return e.description||"When its payment condition is met";if(c.rule_configuration?.eligibility_condition)return "When the customer has paid";return "Not configured yet"}
export default function PlansPage(){
 const[data,setData]=useState<{plans:Plan[]}>({plans:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selectedPlanId,setSelectedPlanId]=useState(""),[selectedVersionId,setSelectedVersionId]=useState(""),[readiness,setReadiness]=useState<Readiness|null>(null);
 const load=async()=>{setLoading(true);setError("");const{data:r,error:e}=await supabase.rpc("get_compensation_plan_admin_data");if(e){setError(e.message);setLoading(false);return}const next=(r||{plans:[]}) as {plans:Plan[]};setData(next);const q=new URLSearchParams(window.location.search),requested=q.get("version");const rp=requested?next.plans.find(p=>p.versions.some(v=>v.version_id===requested)):null;setSelectedPlanId(x=>rp?.plan_id||(x&&next.plans.some(p=>p.plan_id===x)?x:""));if(requested)setSelectedVersionId(requested);setLoading(false)};
 useEffect(()=>{load()},[]);
 const selectedPlan=useMemo(()=>data.plans.find(p=>p.plan_id===selectedPlanId)||null,[data.plans,selectedPlanId]);
 useEffect(()=>{if(selectedPlan)setSelectedVersionId(x=>x&&selectedPlan.versions.some(v=>v.version_id===x)?x:selectedPlan.versions[0]?.version_id||"")},[selectedPlan]);
 const version=selectedPlan?.versions.find(v=>v.version_id===selectedVersionId)||selectedPlan?.versions[0];
 useEffect(()=>{let live=true;(async()=>{if(!version||version.status!=="draft"){setReadiness(null);return}const{data:r}=await supabase.rpc("validate_compensation_plan_version_readiness",{selected_plan_version_id:version.version_id});if(live)setReadiness(r as Readiness)})();return()=>{live=false}},[version?.version_id,version?.status,data]);
 if(!selectedPlan)return <main className="plan-workspace"><div className="plan-page-shell"><header className="plan-page-header"><div><span className="plan-kicker">COMPENSATION</span><h1>Compensation plans</h1><p>A plan says who is covered and what they can earn. Each plan holds one or more Earning Types.</p></div><Link className="plan-button brand" href="/plans/new"><Plus size={15}/>New plan</Link></header>{error&&<div className="plan-alert error">{error}</div>}<div style={{display:"grid",gap:12}}>{data.plans.map(p=>{const d=p.versions.find(v=>v.status==="draft"),a=p.versions.find(v=>v.status==="active"),v=d||a||p.versions[0];return <button key={p.plan_id} onClick={()=>setSelectedPlanId(p.plan_id)} style={{textAlign:"left",background:"white",border:"1px solid #e3e8ef",borderRadius:12,padding:"16px 18px",cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:16}}><div><b style={{fontSize:16}}>{p.name}</b><div style={{fontFamily:"monospace",fontSize:11,color:"#667085",marginTop:4}}>{p.plan_code}</div></div><span className={`plan-status ${v?.status||"draft"}`}>{v?`${title(v.status)} v${v.version_number}`:"No version"}</span></div>{v&&<div style={{display:"flex",gap:24,marginTop:14,fontSize:12,color:"#475467"}}><span><b>{v.components.length}</b> Earning Type{v.components.length===1?"":"s"}</span><span><b>{(v.status==="draft"?v.draft_assignments:v.assignments).length}</b> people</span><span>{v.effective_start_date}{v.effective_end_date?` – ${v.effective_end_date}`:""}</span></div>}</button>})}{!loading&&!data.plans.length&&<div className="plan-empty">No compensation plans yet. Create the first plan to get started.</div>}</div></div></main>;
 const assignments=version?.status==="draft"?version.draft_assignments:version?.assignments||[];
 const blockers=readiness?.blockers||[];
 return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-breadcrumb"><Link href="/plans" onClick={()=>{setSelectedPlanId("");setSelectedVersionId("")}}>Plans</Link><span>/</span><span>{selectedPlan.name}</span></div><header className="plan-page-header"><div><span className="plan-kicker">PLAN</span><h1>{selectedPlan.name}</h1><p><code>{selectedPlan.plan_code}</code>{selectedPlan.description?` · ${selectedPlan.description}`:""}</p></div><div style={{display:"flex",gap:8,alignItems:"center"}}>{version&&<span className={`plan-status ${version.status}`}>{title(version.status)} v{version.version_number}</span>}<button className="plan-button secondary" onClick={load}><RefreshCw size={14}/>Refresh</button></div></header>
 {error&&<div className="plan-alert error">{error}</div>}{version&&<>
 <div style={{background:"#fff",border:"1px solid #badefa",borderLeft:"3px solid #2095f3",borderRadius:11,padding:"16px 18px",marginBottom:16}}><div style={{display:"flex",alignItems:"center",gap:9}}>{readiness?.ready?<CheckCircle2 size={18}/>:<AlertTriangle size={18}/>}<h2 style={{margin:0,fontSize:15}}>{readiness?.ready?"This draft is ready for approval":"Here is what is left"}</h2></div><p style={{margin:"5px 0 12px 27px",fontSize:12.5,color:"#5b6b7f"}}>A plan does not pay anything on its own. Finish each item below before activation.</p><div style={{marginLeft:27,display:"grid",gap:8}}>
 {version.components.length===0?<Link href={`/plans/component/new?version=${version.version_id}`} className="plan-button secondary" style={{justifySelf:"start"}}><Plus size={14}/>Add your first Earning Type</Link>:<div style={{fontSize:12}}><CheckCircle2 size={14} style={{verticalAlign:"middle",marginRight:7}}/>At least one Earning Type has been added.</div>}
 {assignments.length===0?<Link href={`/plans/applicability/${version.version_id}`} className="plan-button secondary" style={{justifySelf:"start"}}><Users size={14}/>Add people to this plan</Link>:<div style={{fontSize:12}}><CheckCircle2 size={14} style={{verticalAlign:"middle",marginRight:7}}/>{assignments.length} person{assignments.length===1?"":"s"} added.</div>}
 {blockers.filter(b=>b.section==="agreements").length>0?<Link href={`/plans/agreements/${version.version_id}`} className="plan-button secondary" style={{justifySelf:"start"}}><FileText size={14}/>Attach signed agreement{blockers.filter(b=>b.section==="agreements").length===1?"":"s"}</Link>:assignments.length>0?<div style={{fontSize:12}}><CheckCircle2 size={14} style={{verticalAlign:"middle",marginRight:7}}/>Everyone on the plan has an agreement on file.</div>:null}
 {blockers.filter(b=>b.section!=="agreements").slice(0,4).map((b,i)=><div key={i} style={{fontSize:12,color:"#7a5712"}}><AlertTriangle size={14} style={{verticalAlign:"middle",marginRight:7}}/>{b.message}</div>)}
 </div></div>
 <section className="plan-section"><div className="plan-section-title"><div><h3>Earning Types</h3><p>Each Earning Type defines what someone can earn, when it becomes Earned, and when it can be paid.</p></div>{version.status==="draft"&&<Link className="plan-button brand" href={`/plans/component/new?version=${version.version_id}`}><Plus size={14}/>Add Earning Type</Link>}</div>{version.components.map(c=><div key={c.component_id} style={{border:"1px solid #e3e8ef",borderRadius:10,padding:"14px 16px",marginTop:10,display:"grid",gridTemplateColumns:"minmax(180px,1.2fr) repeat(3,minmax(150px,1fr)) 28px",gap:14,alignItems:"center"}}><div><b>{c.name}</b><div style={{fontSize:11,color:"#667085",fontFamily:"monospace",marginTop:3}}>{c.component_code}</div></div><div><small style={{color:"#667085"}}>PAYS</small><div style={{fontSize:12,fontWeight:600,marginTop:3}}>{payText(c)}</div></div><div><small style={{color:"#2095f3"}}>EARNED WHEN</small><div style={{fontSize:12,fontWeight:600,marginTop:3}}>{earnedText(c)}</div></div><div><small style={{color:"#b66a00"}}>CAN BE PAID WHEN</small><div style={{fontSize:12,fontWeight:600,marginTop:3}}>{eligibleText(c)}</div></div><Link href={`/plans/component/${c.component_id}?version=${version.version_id}`} aria-label={`Open ${c.name}`}><ChevronRight size={18}/></Link></div>)}{!version.components.length&&<div className="plan-empty">No Earning Types yet. Add one to define what this plan pays.</div>}</section>
 <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginTop:16}}><section className="plan-section" style={{margin:0}}><div className="plan-section-title"><div><h3>Signed agreements</h3><p>Attach multiple agreements and scope each to one person or everyone on the plan. Files also appear on employee records.</p></div><Link className="plan-button secondary" href={`/plans/agreements/${version.version_id}`}><FileText size={14}/>{version.status==="draft"?"Manage agreements":"View agreements"}</Link></div>{blockers.filter(b=>b.section==="agreements").length?<div className="plan-alert warning">{blockers.filter(b=>b.section==="agreements").length} person{blockers.filter(b=>b.section==="agreements").length===1?" is":" are"} missing a signed agreement.</div>:assignments.length?<div className="plan-info-row"><CheckCircle2 size={15}/>Everyone on this plan has an agreement on file.</div>:<div className="plan-empty">Add people to the plan to track their agreement coverage.</div>}</section><section className="plan-section" style={{margin:0}}><div className="plan-section-title"><div><h3>People on this plan</h3><p>Draft applicability stays hidden from employees until activation.</p></div><Link className="plan-button secondary" href={`/plans/applicability/${version.version_id}`}><Users size={14}/>Manage</Link></div>{assignments.length?assignments.map(a=><span className="plan-assignment-pill" key={a.draft_assignment_id||a.assignment_id}><b>{a.employee_name}</b> · {a.allocation_percent}%</span>):<div className="plan-empty">No people added yet.</div>}</section></div>
 </>}</div></main>
}
