"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,ArrowLeft,CheckCircle2,History,RefreshCw,Search} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Earning={earning_id:string;employee_name:string;earning_name:string;source_external_id:string|null;earned_date:string|null;earned_amount:number;eligible_amount:number;approved_amount:number;paid_amount:number;payment_status:string;reconciliation_status:string|null;source_match_status:string|null;hold_reason:string|null;updated_at:string;};
type Payload={earnings:Earning[]};
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function label(v:string|null|undefined){return String(v||"not reconciled").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function reconciled(e:Earning){return ["reconciled","matched","complete","not_required"].includes(String(e.reconciliation_status||""))}

export default function ReconciliationPage(){
 const[data,setData]=useState<Payload>({earnings:[]});const[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[view,setView]=useState("open");
 const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const{data:result,error:rpcError}=await supabase.rpc("get_admin_earnings_data");if(rpcError)setError(rpcError.message);else setData((result||{earnings:[]}) as Payload);setLoading(false)};useEffect(()=>{load()},[]);
 const open=data.earnings.filter(e=>!reconciled(e)),done=data.earnings.filter(reconciled),difference=data.earnings.reduce((a,e)=>a+Number(e.approved_amount||0)-Number(e.paid_amount||0),0);
 const rows=useMemo(()=>data.earnings.filter(e=>(view==="all"||(view==="open"?!reconciled(e):reconciled(e)))&&(!query||`${e.employee_name} ${e.earning_name} ${e.source_external_id||""}`.toLowerCase().includes(query.toLowerCase()))),[data.earnings,query,view]);
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1320,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:22,flexWrap:"wrap"}}><div><Link href="/manage" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700,fontSize:13}}><ArrowLeft size={15}/>Management</Link><small style={{display:"block",fontWeight:800,letterSpacing:1.1,color:"#2095f3",marginTop:12}}>HISTORICAL INTEGRITY</small><h1 style={{fontSize:34,margin:"6px 0"}}>Reconciliation</h1><p style={{margin:0,color:"#647184"}}>Live earning-level reconciliation replaces the old import checklist. Approved, paid, held, and source-match differences remain traceable.</p></div><button onClick={load} disabled={loading} style={{display:"flex",gap:7,alignItems:"center",padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:700}}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>{error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginBottom:16}}><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small>Open reconciliation</small><b style={{display:"block",fontSize:26}}>{loading?"—":open.length}</b></div><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small>Reconciled</small><b style={{display:"block",fontSize:26}}>{loading?"—":done.length}</b></div><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small>Approved less paid</small><b style={{display:"block",fontSize:24}}>{loading?"—":money(difference)}</b></div></section>
 <section style={{display:"flex",gap:10,marginBottom:14,flexWrap:"wrap"}}><label style={{position:"relative",flex:"1 1 320px"}}><Search size={17} style={{position:"absolute",left:11,top:11,color:"#8b98a8"}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee, earning, source ID" style={{width:"100%",boxSizing:"border-box",padding:"10px 12px 10px 36px",border:"1px solid #d6dee8",borderRadius:9}}/></label><select value={view} onChange={e=>setView(e.target.value)} style={{padding:"10px 12px",border:"1px solid #d6dee8",borderRadius:9,background:"white"}}><option value="open">Open</option><option value="done">Reconciled</option><option value="all">All</option></select></section>
 <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,overflow:"hidden"}}>{rows.length===0?<div style={{padding:34,textAlign:"center",color:"#647184"}}><CheckCircle2 size={28}/><h2>No records in this view</h2></div>:rows.map(e=><div key={e.earning_id} style={{display:"grid",gridTemplateColumns:"1.1fr 1.5fr .75fr .75fr .9fr",gap:12,padding:"14px 16px",borderBottom:"1px solid #edf1f5",alignItems:"center"}}><div><b>{e.employee_name}</b><small style={{display:"block",color:"#718096"}}>{e.earned_date||"No earned date"}</small></div><div><b>{e.earning_name}</b><small style={{display:"block",color:"#718096"}}>{e.source_external_id||"No source ID"}</small></div><div><small style={{display:"block",color:"#718096"}}>Approved</small><b>{money(e.approved_amount)}</b></div><div><small style={{display:"block",color:"#718096"}}>Paid</small><b>{money(e.paid_amount)}</b></div><div><span style={{display:"flex",gap:5,alignItems:"center",fontWeight:800,color:reconciled(e)?"#0f7a50":"#9b5d00"}}>{reconciled(e)?<CheckCircle2 size={15}/>:<AlertTriangle size={15}/>} {label(e.reconciliation_status)}</span><small style={{display:"block",color:"#718096",marginTop:3}}>Source: {label(e.source_match_status)} · {label(e.payment_status)}</small></div></div>)}</section>
 <section style={{marginTop:18,background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:16,display:"flex",gap:10}}><History size={19}/><div><b>Corrections preserve history</b><p style={{margin:"4px 0 0",color:"#647184"}}>Paid compensation should never be silently rewritten. Reconciliation identifies differences; corrections are handled as explicit adjustments with audit history.</p></div></section></div></main>
}
