"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,CheckCircle2,History,RefreshCw,Search} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Earning={earning_id:string;employee_name:string;earning_name:string;source_external_id:string|null;earned_date:string|null;earned_amount:number;eligible_amount:number;approved_amount:number;paid_amount:number;payment_status:string;reconciliation_status:string|null;source_match_status:string|null;hold_reason:string|null;updated_at:string;};
type Payload={earnings:Earning[]};
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function label(v:string|null|undefined){return String(v||"not reconciled").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function reconciled(e:Earning){return ["reconciled","matched","complete","not_required"].includes(String(e.reconciliation_status||""))}

export default function ReconciliationPage(){
 const[data,setData]=useState<Payload>({earnings:[]});const[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[view,setView]=useState("open"),[resolving,setResolving]=useState<string|null>(null);
 const load=async()=>{if(!supabase){setError("Reconciliation data is temporarily unavailable.");setLoading(false);return}setLoading(true);setError("");const{data:result,error:rpcError}=await supabase.rpc("get_admin_earnings_data");if(rpcError)setError("We couldn't load reconciliation data. Try again or check the audit log if the problem continues.");else setData((result||{earnings:[]}) as Payload);setLoading(false)};useEffect(()=>{load()},[]);
 const resolve=async(e:Earning,decision:"underpayment"|"overpayment"|"ignore")=>{if(!supabase)return;let amount:number|null=null;if(decision!=="ignore"){const raw=window.prompt(`Enter the confirmed ${decision} amount for this earning:`);if(raw===null)return;amount=Number(raw);if(!Number.isFinite(amount)||amount<=0){setError("Enter a positive difference amount.");return}}const comments=window.prompt(decision==="ignore"?"Optional note explaining why the prior settlement is accepted:":"Optional reconciliation note:")||null;setResolving(e.earning_id);setError("");const{error:rpcError}=await supabase.rpc("resolve_reconciliation_review",{target_earning_id:e.earning_id,requested_decision:decision,requested_difference_amount:amount,requested_comments:comments});if(rpcError)setError(rpcError.message);else await load();setResolving(null)};
 const open=data.earnings.filter(e=>!reconciled(e)),done=data.earnings.filter(reconciled),difference=data.earnings.reduce((a,e)=>a+Number(e.approved_amount||0)-Number(e.paid_amount||0),0);
 const rows=useMemo(()=>data.earnings.filter(e=>(view==="all"||(view==="open"?!reconciled(e):reconciled(e)))&&(!query||`${e.employee_name} ${e.earning_name} ${e.source_external_id||""}`.toLowerCase().includes(query.toLowerCase()))),[data.earnings,query,view]);
 const stat=(title:string,value:string|number)=><div className="eng-card"><div className="eng-card__body"><small className="eng-page-header__eyebrow">{title.toUpperCase()}</small><b className="eng-figure eng-figure--strong" style={{display:"block",fontSize:26}}>{loading?"—":value}</b></div></div>;
 return <main className="eng-page"><div className="eng-page__shell"><nav className="eng-breadcrumb"><Link href="/manage">Control Center</Link><span className="eng-breadcrumb__sep">/</span><span className="eng-breadcrumb__current">Reconciliation</span></nav><header className="eng-page-header"><div className="eng-page-header__main"><span className="eng-page-header__eyebrow">HISTORICAL INTEGRITY</span><h1>Reconciliation</h1><p className="eng-page-header__lede">Compare approval, payment, and source-match state at the earning level. Differences remain traceable rather than being silently overwritten.</p></div><div className="eng-page-header__actions"><button onClick={load} disabled={loading} className="eng-btn"><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></div></header>{error&&<div className="eng-callout eng-callout--danger"><div className="eng-callout__body"><b>Could not load reconciliation</b>{error}</div></div>}
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,margin:"16px 0"}}>{stat("Open reconciliation",open.length)}{stat("Reconciled",done.length)}{stat("Approved less paid",money(difference))}</section>
 <section className="eng-card" style={{marginBottom:14}}><div className="eng-card__body" style={{display:"flex",gap:10,flexWrap:"wrap"}}><label style={{position:"relative",flex:"1 1 320px"}}><Search size={17} style={{position:"absolute",left:11,top:11,color:"var(--eng-ink-faint)"}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee, earning, source ID" className="eng-input" style={{width:"100%",paddingLeft:36}}/></label><select value={view} onChange={e=>setView(e.target.value)} className="eng-input"><option value="open">Open</option><option value="done">Reconciled</option><option value="all">All</option></select></div></section>
 <section className="eng-card">{rows.length===0?<div className="eng-empty eng-empty--inline"><div className="eng-empty__icon eng-empty__icon--success"><CheckCircle2 size={20}/></div><h2>No records in this view</h2><p>Try a different reconciliation status or clear the search.</p></div>:rows.map(e=><div key={e.earning_id} style={{display:"grid",gridTemplateColumns:"minmax(180px,1.1fr) minmax(220px,1.5fr) minmax(120px,.75fr) minmax(120px,.75fr) minmax(180px,.9fr)",gap:12,padding:"14px 16px",borderBottom:"1px solid var(--eng-border-soft)",alignItems:"center"}}><div><b>{e.employee_name}</b><small style={{display:"block",color:"var(--eng-ink-meta)"}}>{e.earned_date||"No earned date"}</small></div><div><b>{e.earning_name}</b><small className="eng-ident" style={{display:"block",marginTop:2}}>{e.source_external_id||"No source ID"}</small></div><div><small style={{display:"block",color:"var(--eng-ink-meta)"}}>Approved</small><b className="eng-figure">{money(e.approved_amount)}</b></div><div><small style={{display:"block",color:"var(--eng-ink-meta)"}}>Paid</small><b className="eng-figure">{money(e.paid_amount)}</b></div><div><span className={`eng-badge ${reconciled(e)?"eng-badge--success":"eng-badge--warn"}`}>{reconciled(e)?<CheckCircle2 size={13}/>:<AlertTriangle size={13}/>} {label(e.reconciliation_status)}</span><small style={{display:"block",color:"var(--eng-ink-meta)",marginTop:5}}>Source: {label(e.source_match_status)} · {label(e.payment_status)}</small>{e.reconciliation_status==="needs_information"&&<div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:8}}><button className="eng-btn eng-btn--small" disabled={resolving===e.earning_id} onClick={()=>resolve(e,"underpayment")}>Underpayment</button><button className="eng-btn eng-btn--small" disabled={resolving===e.earning_id} onClick={()=>resolve(e,"overpayment")}>Overpayment</button><button className="eng-btn eng-btn--small" disabled={resolving===e.earning_id} onClick={()=>resolve(e,"ignore")}>Accept prior amount</button></div>}</div></div>)}</section>
 <div className="eng-callout eng-callout--info" style={{marginTop:18}}><History size={19}/><div className="eng-callout__body"><b>Corrections preserve history</b>Paid compensation is never silently rewritten. Reconciliation surfaces the difference; any correction is handled through an explicit, auditable adjustment workflow.</div></div></div></main>
}
