"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {CheckCircle2,Clock3,FileCheck2,History,Home,RefreshCw,Send,ShieldCheck,WalletCards,ListChecks,Hourglass,LogOut,ChevronRight} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Access={employee_id?:string;roles?:string[]};
type Employee={id:string;full_name:string;email:string;job_title:string|null;department:string|null};
type Plan={assignment_id:string;plan_version_id:string;plan_name:string;version_number:number;status:string;effective_start_date:string;effective_end_date:string|null;acknowledged:boolean};
type Component={component_id:string;component_name:string;component_code:string;description:string|null;calculation_type:string|null;measurement_source:string|null;measurement_period:string|null;rule_configuration:Record<string,unknown>;earned_amount:number;eligible_amount:number;paid_amount:number;earning_count:number};
type Earning={earning_id:string;plan_component_id:string|null;component_name:string|null;component_code:string|null;earning_name:string;source_external_id:string|null;source_url:string|null;earned_date:string;earned_amount:number;eligibility_status:string;eligible_date:string|null;eligible_amount:number;employee_verification_status:string;manager_approval_status:string;payment_status:string;paid_amount:number;source_snapshot:Record<string,unknown>};
type Payload={employee:Employee|null;plans:Plan[];components:Component[];earnings:Earning[]};
type View="overview"|"ready"|"progress"|"payments"|"plan"|"history";

function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function label(v:string|null|undefined){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}

export default function MePage(){
 const[data,setData]=useState<Payload>({employee:null,plans:[],components:[],earnings:[]});
 const[access,setAccess]=useState<Access|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null),[notes,setNotes]=useState<Record<string,string>>({}),[selected,setSelected]=useState<string[]>([]),[bulkNote,setBulkNote]=useState(""),[resultMessage,setResultMessage]=useState("");
 const[requestedEmployee,setRequestedEmployee]=useState<string|null>(null),[view,setView]=useState<View>("overview");
 useEffect(()=>{const params=new URLSearchParams(window.location.search);setRequestedEmployee(params.get("employee"));const v=params.get("view") as View|null;if(v&&["overview","ready","progress","payments","plan","history"].includes(v))setView(v)},[]);
 const isAdmin=Boolean(access?.roles?.includes("system_administrator"));
 const isTestMode=Boolean(isAdmin&&requestedEmployee&&requestedEmployee!==access?.employee_id);
 const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const accessResult=await supabase.rpc("get_current_user_access");if(accessResult.error){setError(accessResult.error.message);setLoading(false);return}const currentAccess=(accessResult.data||{}) as Access;setAccess(currentAccess);const target=currentAccess.roles?.includes("system_administrator")&&requestedEmployee?requestedEmployee:null;const{data:result,error:rpcError}=await supabase.rpc("get_compensation_employee_data",{target_employee_id:target});if(rpcError)setError(rpcError.message);else{const payload=(result||{employee:null,plans:[],components:[],earnings:[]}) as Payload;setData(payload);setSelected(current=>current.filter(id=>payload.earnings.some(e=>e.earning_id===id&&canSubmit(e))))}setLoading(false)};
 useEffect(()=>{if(requestedEmployee!==null)load()},[requestedEmployee]);
 const go=(next:View)=>{setView(next);const params=new URLSearchParams(window.location.search);params.set("view",next);window.history.replaceState({},"",`${window.location.pathname}?${params.toString()}`)};
 const canSubmit=(e:Earning)=>e.eligibility_status==="eligible"&&e.employee_verification_status!=="verified"&&e.manager_approval_status!=="approved"&&e.payment_status!=="paid";
 const selectable=useMemo(()=>data.earnings.filter(canSubmit),[data.earnings]);
 const inProgress=useMemo(()=>data.earnings.filter(e=>e.employee_verification_status==="verified"&&e.payment_status!=="paid"),[data.earnings]);
 const paid=useMemo(()=>data.earnings.filter(e=>e.payment_status==="paid"||Number(e.paid_amount||0)>0),[data.earnings]);
 const waitingEligibility=useMemo(()=>data.earnings.filter(e=>e.eligibility_status!=="eligible"&&e.employee_verification_status!=="verified"&&e.payment_status!=="paid"),[data.earnings]);
 const totals=useMemo(()=>data.earnings.reduce((a,e)=>({earned:a.earned+Number(e.earned_amount||0),eligible:a.eligible+Number(e.eligible_amount||0),approved:a.approved+((e.manager_approval_status==="approved")?Number(e.earned_amount||0):0),paid:a.paid+Number(e.paid_amount||0)}),{earned:0,eligible:0,approved:0,paid:0}),[data.earnings]);
 const componentGroups=useMemo(()=>Array.from(new Set(selectable.map(e=>e.component_name||e.earning_name))).map(name=>({name,count:selectable.filter(e=>(e.component_name||e.earning_name)===name).length,ids:selectable.filter(e=>(e.component_name||e.earning_name)===name).map(e=>e.earning_id)})),[selectable]);
 const submitOne=async(e:Earning)=>{if(!supabase)return;setBusy(e.earning_id);setError("");setResultMessage("");const rpc=isTestMode?"admin_test_submit_comp_earning_for_approval":"submit_my_comp_earning_for_approval";const{error:rpcError}=await supabase.rpc(rpc,{target_earning_id:e.earning_id,verification_notes:notes[e.earning_id]||null});if(rpcError)setError(rpcError.message);else{setNotes(x=>({...x,[e.earning_id]:""}));setResultMessage("Submitted 1 earning for approval.");await load()}setBusy(null)};
 const submitMany=async(ids:string[],description:string)=>{if(!supabase||!ids.length)return;const confirmed=window.confirm(`${isTestMode?"TEST SUBMISSION: ":""}Submit ${ids.length} ${description} for approval? Each earning will create its own audited approval workflow.`);if(!confirmed)return;setBusy("bulk");setError("");setResultMessage("");const rpc=isTestMode?"admin_test_submit_comp_earning_for_approval":"submit_my_comp_earning_for_approval";let success=0;const failures:string[]=[];for(const id of ids){const earning=data.earnings.find(e=>e.earning_id===id);const{error:rpcError}=await supabase.rpc(rpc,{target_earning_id:id,verification_notes:bulkNote||notes[id]||null});if(rpcError)failures.push(`${earning?.earning_name||id}: ${rpcError.message}`);else success++}setSelected([]);if(success)setResultMessage(`Submitted ${success} earning${success===1?"":"s"} for approval${isTestMode?" in System Admin test mode":""}.`);if(failures.length)setError(`${failures.length} item${failures.length===1?"":"s"} could not be submitted: ${failures.join(" | ")}`);setBusy(null);await load()};
 const acknowledge=async(p:Plan)=>{if(!supabase||isTestMode)return;setBusy(p.plan_version_id);setError("");const{error:rpcError}=await supabase.rpc("acknowledge_my_compensation_plan",{selected_plan_version_id:p.plan_version_id,selected_acknowledgment_text:`I acknowledge receipt and review of ${p.plan_name}, version ${p.version_number}.`});if(rpcError)setError(rpcError.message);else await load();setBusy(null)};
 const approvalLabel=(e:Earning)=>e.employee_verification_status==="verified"&&e.manager_approval_status==="pending"?"Submitted":label(e.manager_approval_status);
 const nav=[
  {key:"overview" as View,label:"Overview",icon:Home,count:0},
  {key:"ready" as View,label:"Ready to Submit",icon:ListChecks,count:selectable.length},
  {key:"progress" as View,label:"In Progress",icon:Hourglass,count:inProgress.length},
  {key:"payments" as View,label:"Payment History",icon:WalletCards,count:paid.length},
  {key:"plan" as View,label:"My Plan",icon:FileCheck2,count:0},
  {key:"history" as View,label:"History",icon:History,count:data.earnings.length},
 ];
 const EarningCard=({e,allowSubmit=false}:{e:Earning;allowSubmit?:boolean})=><article key={e.earning_id} style={{border:"1px solid #e5ebf1",borderRadius:10,padding:12,background:"white"}}><div style={{display:"grid",gridTemplateColumns:"1.5fr repeat(4,minmax(100px,.7fr))",gap:10,alignItems:"start"}}><div style={{display:"flex",gap:9,alignItems:"flex-start"}}>{allowSubmit&&canSubmit(e)&&<input type="checkbox" checked={selected.includes(e.earning_id)} onChange={()=>setSelected(s=>s.includes(e.earning_id)?s.filter(x=>x!==e.earning_id):[...s,e.earning_id])} style={{marginTop:3}}/>}<div><b>{e.earning_name}</b><small style={{display:"block",color:"#718096",marginTop:3}}>{e.component_name||"Compensation"} · {e.earned_date}</small></div></div><span><small>Earned</small><b style={{display:"block"}}>{money(e.earned_amount)}</b></span><span><small>Eligible</small><b style={{display:"block"}}>{label(e.eligibility_status)}</b></span><span><small>Approval</small><b style={{display:"block"}}>{approvalLabel(e)}</b></span><span><small>Payment</small><b style={{display:"block"}}>{label(e.payment_status)}</b></span></div>{allowSubmit&&canSubmit(e)&&<div style={{display:"flex",gap:8,marginTop:10,alignItems:"center",flexWrap:"wrap"}}><input value={notes[e.earning_id]||""} onChange={x=>setNotes(n=>({...n,[e.earning_id]:x.target.value}))} placeholder="Optional note for approver" style={{flex:"1 1 280px",padding:"9px 10px",border:"1px solid #d8e0e8",borderRadius:8}}/><button onClick={()=>submitOne(e)} disabled={busy!==null} style={{display:"flex",gap:6,alignItems:"center",padding:"9px 11px",border:0,borderRadius:8,background:isTestMode?"#a36a00":"#2095f3",color:"white",fontWeight:800}}><Send size={15}/>{busy===e.earning_id?"Submitting…":isTestMode?"Test submit as employee":"Verify & submit"}</button></div>}{e.eligibility_status!=="eligible"&&e.payment_status!=="paid"&&<div style={{marginTop:8,color:"#7b6a42",fontSize:13,display:"flex",gap:6,alignItems:"center"}}><Clock3 size={15}/>Earned, but not yet eligible for payout.</div>}</article>;

 return <main style={{minHeight:"100vh",background:"#f5f7fa",fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{display:"grid",gridTemplateColumns:"260px minmax(0,1fr)",minHeight:"100vh"}}>
  <aside style={{background:"#051b34",color:"white",padding:22,position:"sticky",top:0,height:"100vh",boxSizing:"border-box",display:"flex",flexDirection:"column"}}>
   <div style={{fontWeight:900,letterSpacing:1.2,color:"#77c4ff",fontSize:12}}>ENGAGIFII COMPENSATION</div>
   <div style={{marginTop:22,marginBottom:18}}><div style={{fontSize:19,fontWeight:800}}>{data.employee?.full_name||"Employee"}</div><small style={{color:"#a9b9ca"}}>{data.employee?.job_title||"Employee"}{data.employee?.department?` · ${data.employee.department}`:""}</small></div>
   <nav style={{display:"grid",gap:6}}>{nav.map(item=>{const Icon=item.icon;const active=view===item.key;return <button key={item.key} onClick={()=>go(item.key)} style={{display:"flex",alignItems:"center",gap:10,width:"100%",padding:"10px 11px",borderRadius:9,border:0,background:active?"#123657":"transparent",color:"white",textAlign:"left",cursor:"pointer"}}><Icon size={18}/><span style={{flex:1,fontWeight:active?800:600}}>{item.label}</span>{item.count>0&&<span style={{minWidth:23,height:23,borderRadius:12,display:"grid",placeItems:"center",background:active?"#2095f3":"#173f62",fontSize:12,fontWeight:800}}>{item.count}</span>}</button>})}</nav>
   <div style={{marginTop:"auto",borderTop:"1px solid #27445f",paddingTop:16}}>{isTestMode?<><div style={{fontSize:12,color:"#f2c873",fontWeight:800,marginBottom:8}}>VIEWING AS EMPLOYEE</div><div style={{fontSize:12,color:"#b6c5d4",marginBottom:11}}>Using {data.employee?.full_name}&apos;s employee navigation and actions. Audit actor remains Sharon.</div><Link href="/manage" style={{display:"flex",alignItems:"center",gap:8,padding:"10px 11px",borderRadius:9,background:"#fff8e7",color:"#6d4b00",textDecoration:"none",fontWeight:800}}><LogOut size={17}/>Return to Sharon Wells</Link></>:<small style={{color:"#91a6b9"}}>{data.employee?.email}</small>}</div>
  </aside>
  <section style={{padding:28,maxWidth:1320,width:"100%",boxSizing:"border-box"}}>
   {isTestMode&&<div style={{background:"#fff8e7",border:"1px solid #e7cf91",borderRadius:12,padding:13,marginBottom:16,display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div style={{display:"flex",gap:9,alignItems:"center"}}><ShieldCheck size={19}/><div><b>System Admin test mode · Viewing as {data.employee?.full_name}</b><small style={{display:"block",color:"#6b5b32",marginTop:2}}>This is the employee experience. Actions are audited to Sharon, not the employee.</small></div></div><Link href="/manage" style={{fontWeight:800,color:"#6d4b00",textDecoration:"none"}}>Return to Sharon Wells →</Link></div>}
   <header style={{display:"flex",justifyContent:"space-between",gap:15,alignItems:"flex-start",marginBottom:20}}><div><small style={{fontWeight:800,letterSpacing:1.1,color:"#2095f3"}}>MY COMPENSATION</small><h1 style={{fontSize:32,margin:"5px 0"}}>{nav.find(n=>n.key===view)?.label}</h1><p style={{margin:0,color:"#647184"}}>{view==="overview"?"Your compensation status and actions at a glance.":view==="ready"?"Eligible compensation that is ready for you to verify and submit.":view==="progress"?"Compensation you submitted that is moving through approval and payment.":view==="payments"?"Compensation that has actually been paid.":view==="plan"?"Your current and historical compensation plan assignments.":"A chronological record of your compensation activity."}</p></div><button onClick={load} disabled={loading} style={{display:"flex",gap:7,alignItems:"center",padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:700}}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>
   {error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}{resultMessage&&<div style={{background:"#eefaf4",border:"1px solid #bfe1cf",borderRadius:10,padding:13,marginBottom:15,color:"#0f6b47",fontWeight:700}}>{resultMessage}</div>}
   {view==="overview"&&<><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginBottom:18}}>{[["Earned",totals.earned],["Eligible",totals.eligible],["Approved",totals.approved],["Paid",totals.paid]].map(([a,b])=><div key={String(a)} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small>{a}</small><b style={{display:"block",fontSize:25,marginTop:4}}>{money(Number(b))}</b></div>)}</section><section style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12,marginBottom:16}}><button onClick={()=>go("ready")} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:16,textAlign:"left"}}><small>READY FOR YOUR ACTION</small><b style={{display:"block",fontSize:24,margin:"5px 0"}}>{selectable.length}</b><span>{money(selectable.reduce((s,e)=>s+Number(e.eligible_amount||0),0))} ready to submit</span><ChevronRight size={17} style={{marginTop:10}}/></button><button onClick={()=>go("progress")} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:16,textAlign:"left"}}><small>IN PROGRESS</small><b style={{display:"block",fontSize:24,margin:"5px 0"}}>{inProgress.length}</b><span>Submitted and moving through approval/payment</span><ChevronRight size={17} style={{marginTop:10}}/></button><button onClick={()=>go("payments")} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:16,textAlign:"left"}}><small>PAID</small><b style={{display:"block",fontSize:24,margin:"5px 0"}}>{paid.length}</b><span>{money(totals.paid)} actually paid</span><ChevronRight size={17} style={{marginTop:10}}/></button></section>{waitingEligibility.length>0&&<section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:16}}><b>{waitingEligibility.length} earned item{waitingEligibility.length===1?"":"s"} waiting on eligibility conditions</b><p style={{margin:"5px 0 0",color:"#647184"}}>These are earned but are not ready for submission yet.</p></section>}</>}
   {view==="ready"&&<><section style={{background:"#f7faff",border:"1px solid #d8e8f7",borderRadius:12,padding:14,marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><b>{selectable.length} eligible earning{selectable.length===1?"":"s"} ready to submit</b><small style={{display:"block",color:"#647184",marginTop:3}}>{money(selectable.reduce((s,e)=>s+Number(e.eligible_amount||0),0))} total eligible</small></div><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button onClick={()=>setSelected(selectable.map(e=>e.earning_id))}>Select all</button><button onClick={()=>setSelected([])} disabled={!selected.length}>Clear</button><button onClick={()=>submitMany(selectable.map(e=>e.earning_id),"eligible earnings")} disabled={busy!==null} style={{background:isTestMode?"#a36a00":"#2095f3",color:"white"}}>{isTestMode?"Test submit all eligible":"Submit all eligible"}</button></div></div><div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:10}}>{componentGroups.map(g=><button key={g.name} onClick={()=>setSelected(s=>Array.from(new Set([...s,...g.ids])))}>Select {g.name} ({g.count})</button>)}</div><div style={{display:"flex",gap:8,marginTop:10}}><input value={bulkNote} onChange={e=>setBulkNote(e.target.value)} placeholder="Optional note applied to selected earnings" style={{flex:1,padding:9,border:"1px solid #d8e0e8",borderRadius:8}}/><button onClick={()=>submitMany(selected,"selected earnings")} disabled={!selected.length||busy!==null} style={{background:selected.length?(isTestMode?"#a36a00":"#2095f3"):"#b9c2cc",color:"white"}}>{isTestMode?`Test submit selected (${selected.length})`:`Submit selected (${selected.length})`}</button></div></section><div style={{display:"grid",gap:9}}>{selectable.map(e=><EarningCard key={e.earning_id} e={e} allowSubmit/>)}</div></>}
   {view==="progress"&&<div style={{display:"grid",gap:9}}>{inProgress.length?inProgress.map(e=><EarningCard key={e.earning_id} e={e}/>):<div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:18}}>Nothing is currently in progress.</div>}</div>}
   {view==="payments"&&<div style={{display:"grid",gap:9}}>{paid.length?paid.map(e=><EarningCard key={e.earning_id} e={e}/>):<div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:18}}>No payments have been recorded yet.</div>}</div>}
   {view==="plan"&&<><section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,padding:18,marginBottom:16}}><div style={{display:"flex",alignItems:"center",gap:9}}><FileCheck2 size={20}/><h2 style={{margin:0}}>Plan assignments</h2></div>{data.plans.length===0?<p>No compensation plan is assigned.</p>:data.plans.map(p=><div key={p.assignment_id} style={{borderTop:"1px solid #edf1f5",paddingTop:12,marginTop:12}}><b>{p.plan_name} · Version {p.version_number}</b><small style={{display:"block",color:"#718096",marginTop:3}}>{p.effective_start_date} → {p.effective_end_date||"open ended"} · {label(p.status)}</small><div style={{marginTop:8}}>{p.acknowledged?<span style={{color:"#0f7a50",fontWeight:800}}>Acknowledged</span>:isTestMode?<span style={{color:"#8a6a20",fontWeight:800}}>Not acknowledged · employee action disabled in test mode</span>:p.status==="active"?<button onClick={()=>acknowledge(p)}>Acknowledge plan</button>:<span>Not available for acknowledgment</span>}</div></div>)}</section><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:10}}>{data.components.map(c=><div key={c.component_id} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><b>{c.component_name}</b><small style={{display:"block",color:"#718096",marginTop:3}}>{c.component_code} · {label(c.calculation_type)}</small><p style={{fontSize:13,color:"#647184"}}>{c.description||"Compensation plan component"}</p><div style={{fontSize:13}}>Earned <b>{money(c.earned_amount)}</b> · Eligible <b>{money(c.eligible_amount)}</b> · Paid <b>{money(c.paid_amount)}</b></div></div>)}</section></>}
   {view==="history"&&<div style={{display:"grid",gap:9}}>{[...data.earnings].sort((a,b)=>b.earned_date.localeCompare(a.earned_date)).map(e=><EarningCard key={e.earning_id} e={e}/>)}</div>}
  </section>
 </div></main>
}
