"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CalendarDays,Download,FileText,Link2,Plus} from "lucide-react";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Employee={employee_id:string;full_name:string;email:string;title:string|null;department:string|null;manager_name:string|null;is_active:boolean;plan_name:string|null;plan_status:string|null;plan_effective_start_date:string|null;plan_effective_end_date:string|null;readiness:string;readiness_reasons:string[]};
type Agreement={agreement_id:string;file_name:string;storage_path:string;mime_type:string|null;file_size_bytes:number|null;signed_at:string|null;notes:string|null;applies_to_everyone:boolean;plan_version_id:string;version_number:number;plan_name:string;plan_code:string;created_at:string};
type PlanAssignment={employee_id:string;employee_name:string;effective_start_date:string;effective_end_date:string|null;allocation_percent:number};
type PlanVersion={version_id:string;version_number:number;status:string;effective_start_date:string;effective_end_date:string|null;assignments:PlanAssignment[];draft_assignments:PlanAssignment[]};
type Plan={plan_id:string;name:string;plan_code:string;versions:PlanVersion[]};
const size=(n:number|null)=>n==null?"":n<1048576?`${Math.max(1,Math.round(n/1024))} KB`:`${(n/1048576).toFixed(1)} MB`;
export default function EmployeeRecordPage(){
 const params=useParams<{employeeId:string}>();const employeeId=params.employeeId;
 const[employees,setEmployees]=useState<Employee[]>([]),[agreements,setAgreements]=useState<Agreement[]>([]),[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const[selectedVersion,setSelectedVersion]=useState(""),[assignmentStart,setAssignmentStart]=useState(""),[assignmentEnd,setAssignmentEnd]=useState("");
 const employee=useMemo(()=>employees.find(e=>e.employee_id===employeeId),[employees,employeeId]);
 const draftOptions=useMemo(()=>plans.flatMap(p=>p.versions.filter(v=>v.status==="draft").map(v=>({plan:p,version:v}))),[plans]);
 const selected=draftOptions.find(x=>x.version.version_id===selectedVersion)||null;
 const liveAssignments=useMemo(()=>plans.flatMap(p=>p.versions.filter(v=>v.status!=="draft").flatMap(v=>v.assignments.filter(a=>a.employee_id===employeeId).map(a=>({plan:p,version:v,assignment:a})))),[plans,employeeId]);
 const draftAssignments=useMemo(()=>plans.flatMap(p=>p.versions.filter(v=>v.status==="draft").flatMap(v=>v.draft_assignments.filter(a=>a.employee_id===employeeId).map(a=>({plan:p,version:v,assignment:a})))),[plans,employeeId]);
 const load=async()=>{setLoading(true);setError("");const[e,a,p]=await Promise.all([supabase.rpc("get_employee_administration_data"),supabase.rpc("get_employee_comp_plan_agreements",{selected_employee_id:employeeId}),supabase.rpc("get_compensation_plan_admin_data")]);if(e.error)setError(e.error.message);else setEmployees((e.data?.employees||[]) as Employee[]);if(a.error)setError(x=>x||a.error!.message);else setAgreements((a.data||[]) as Agreement[]);if(p.error)setError(x=>x||p.error!.message);else{const next=(p.data?.plans||[]) as Plan[];setPlans(next);const first=next.flatMap(pl=>pl.versions.filter(v=>v.status==="draft").map(v=>({pl,v})))[0];if(first&&!selectedVersion){setSelectedVersion(first.v.version_id);setAssignmentStart(first.v.effective_start_date||"")}}setLoading(false)};
 useEffect(()=>{load()},[employeeId]);
 useEffect(()=>{if(selected){setAssignmentStart(selected.version.effective_start_date||"");setAssignmentEnd(selected.version.effective_end_date||"")}},[selectedVersion]);
 const open=async(a:Agreement)=>{setError("");const{data,error:e}=await supabase.storage.from("compensation-agreements").createSignedUrl(a.storage_path,60);if(e||!data?.signedUrl){setError(e?.message||"Could not open agreement.");return}window.open(data.signedUrl,"_blank","noopener,noreferrer")};
 const assign=async(e:FormEvent)=>{e.preventDefault();if(!selectedVersion||!assignmentStart)return;setSaving(true);setError("");setMessage("");const{error:rpcError}=await supabase.rpc("save_comp_plan_draft_assignment",{selected_plan_version_id:selectedVersion,selected_employee_id:employeeId,selected_effective_start_date:assignmentStart,selected_effective_end_date:assignmentEnd||null,selected_allocation_percent:100,selected_eligibility_waiting_period_days:0,selected_assignment_notes:"Assigned from employee record"});if(rpcError)setError(rpcError.message);else{setMessage("Draft plan assignment saved. It will become live only when that plan version is activated.");await load()}setSaving(false)};
 if(loading)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-empty">Loading employee record…</div></div></main>;
 if(!employee)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-alert error">{error||"Employee not found."}</div></div></main>;
 return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-breadcrumb"><Link href="/employees"><ArrowLeft size={15}/>Employees</Link><span>/</span><span>{employee.full_name}</span></div><header className="plan-page-header"><div><span className="plan-kicker">EMPLOYEE RECORD</span><h1>{employee.full_name}</h1><p>{employee.title||"No title"}{employee.department?` · ${employee.department}`:""} · {employee.email}</p></div></header>{error&&<div className="plan-alert error">{error}</div>}{message&&<div className="plan-info-row" style={{marginBottom:14}}>{message}</div>}
 <div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12,marginBottom:16}}><section className="plan-section" style={{margin:0}}><small>Current plan</small><h3 style={{margin:"5px 0"}}>{employee.plan_name||"No plan assigned"}</h3><p style={{margin:0,fontSize:12,color:"#667085"}}>{employee.plan_status||""}</p></section><section className="plan-section" style={{margin:0}}><small>Manager</small><h3 style={{margin:"5px 0"}}>{employee.manager_name||"Not assigned"}</h3></section><section className="plan-section" style={{margin:0}}><small>Readiness</small><h3 style={{margin:"5px 0"}}>{employee.readiness.replaceAll("_"," ")}</h3></section></div>
 <section className="plan-section"><div className="plan-section-title"><div><h3>Compensation plans</h3><p>See this employee's current and upcoming plan assignments. Draft assignments do not affect earnings until the plan version is activated.</p></div><Link2 size={18}/></div>
 {liveAssignments.length?liveAssignments.map(x=><div key={`${x.version.version_id}-${x.assignment.employee_id}`} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:12,alignItems:"center",padding:"12px 0",borderTop:"1px solid #e6e8ec"}}><div><b>{x.plan.name}</b><div style={{fontSize:12,color:"#667085",marginTop:3}}>v{x.version.version_number} · {x.version.status} · {x.assignment.effective_start_date}{x.assignment.effective_end_date?` through ${x.assignment.effective_end_date}`:" · open ended"}</div></div><Link className="plan-button secondary" href={`/plans?version=${x.version.version_id}`}>View plan</Link></div>):<div className="plan-empty">No active plan assignment is on file.</div>}
 {draftAssignments.length>0&&<div style={{marginTop:14}}><small style={{fontWeight:800,color:"#667085"}}>UPCOMING / DRAFT</small>{draftAssignments.map(x=><div key={`draft-${x.version.version_id}`} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:12,alignItems:"center",padding:"12px 0",borderTop:"1px solid #e6e8ec"}}><div><b>{x.plan.name}</b><div style={{fontSize:12,color:"#667085",marginTop:3}}>Draft v{x.version.version_number} · planned from {x.assignment.effective_start_date}{x.assignment.effective_end_date?` through ${x.assignment.effective_end_date}`:""}</div></div><Link className="plan-button secondary" href={`/plans/manage/${x.version.version_id}`}>Manage draft</Link></div>)}</div>}
 {draftOptions.length>0&&<form onSubmit={assign} style={{marginTop:18,paddingTop:16,borderTop:"1px solid #e6e8ec"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:10}}><Plus size={16}/><b>Assign a draft compensation plan</b></div><div className="plan-form-grid two"><label>Plan version<select value={selectedVersion} onChange={e=>setSelectedVersion(e.target.value)} required>{draftOptions.map(x=><option key={x.version.version_id} value={x.version.version_id}>{x.plan.name} · draft v{x.version.version_number}</option>)}</select></label><label>Effective start date<input type="date" value={assignmentStart} onChange={e=>setAssignmentStart(e.target.value)} required/></label><label>Effective end date<input type="date" min={assignmentStart||undefined} value={assignmentEnd} onChange={e=>setAssignmentEnd(e.target.value)}/><small>Leave blank if the assignment is open ended.</small></label><div style={{display:"flex",alignItems:"end"}}><button className="plan-button brand" disabled={saving}><Plus size={14}/>{saving?"Saving…":"Assign draft plan"}</button></div></div><div className="plan-info-row" style={{marginTop:10}}>This creates a safe draft assignment only. The employee's current live plan remains unchanged until the new plan version is approved and activated.</div></form>}
 </section>
 <section className="plan-section"><div className="plan-section-title"><div><h3>Compensation agreements</h3><p>Agreements attached to this employee or to everyone on one of their plan versions.</p></div><FileText size={18}/></div>{agreements.length?agreements.map(a=><div key={a.agreement_id} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:12,alignItems:"center",padding:"12px 0",borderTop:"1px solid #e6e8ec"}}><div><b>{a.file_name}</b><div style={{fontSize:12,color:"#667085",marginTop:3}}>{a.plan_name} · v{a.version_number}{a.applies_to_everyone?" · plan-wide agreement":""}{a.signed_at?` · signed ${a.signed_at}`:""}{a.file_size_bytes?` · ${size(a.file_size_bytes)}`:""}</div>{a.notes&&<div style={{fontSize:12,color:"#475467",marginTop:4}}>{a.notes}</div>}</div><button className="plan-button secondary" onClick={()=>open(a)}><Download size={14}/>Open</button></div>):<div className="plan-empty">No compensation agreements are on file for this employee.</div>}</section>
 </div></main>;
}
