"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, Database, RefreshCw, ShieldCheck } from "lucide-react";
import { createClient } from "@supabase/supabase-js";
import AdminShell from "../components/admin-shell";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"");

type DashboardData={deals:number;companies:number;associations:number;unlinkedDeals:number;unreviewedChanges:number;lastSync:string|null;recentChanges:Array<{detected_at:string;deal_name:string;field_name:string;old_value:string|null;new_value:string|null;review_status:string}>};
const empty:DashboardData={deals:0,companies:0,associations:0,unlinkedDeals:0,unreviewedChanges:0,lastSync:null,recentChanges:[]};

export default function DataIntegrationsPage(){
 const[data,setData]=useState<DashboardData>(empty),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{setLoading(true);setError("");const{data:r,error:e}=await supabase.rpc("get_compensation_dashboard_data");if(e)setError(e.message);else setData({...empty,...(r||{})});setLoading(false)};
 const refresh=async()=>{setSyncing(true);setError("");setNotice("");const{error:e}=await supabase.rpc("refresh_compensation_management_data",{force_refresh:true});if(e)setError(e.message);else{setNotice("HubSpot compensation data refresh completed.");await load()}setSyncing(false)};
 useEffect(()=>{load()},[]);
 return <AdminShell section="data" title="Data & Integrations" description="Source-system health, synchronization, mappings, and compensation data readiness."><div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-bold">HubSpot compensation data</h1><p className="mt-1 text-xs text-[#77808e]">Monitor the data feeding compensation calculations without mixing integration operations into Settings.</p></div><div className="flex gap-2"><button onClick={load} disabled={loading} className="flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-xs font-bold"><RefreshCw size={14}/>Reload</button><button onClick={refresh} disabled={syncing} className="flex items-center gap-1 rounded-lg bg-[#2095f3] px-3 py-2 text-xs font-bold text-white"><Database size={14}/>{syncing?"Refreshing…":"Refresh HubSpot data"}</button></div></div>
  {error&&<div className="flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={17}/><div><b>Data operation could not complete</b><div className="text-xs">{error}</div></div></div>}{notice&&<div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
  <div className="grid gap-3 md:grid-cols-5"><article className="rounded-xl border bg-white p-4 shadow-sm"><small className="text-[10px] font-bold text-[#77808e]">DEALS</small><b className="mt-1 block text-2xl">{loading?"—":data.deals}</b></article><article className="rounded-xl border bg-white p-4 shadow-sm"><small className="text-[10px] font-bold text-[#77808e]">COMPANIES</small><b className="mt-1 block text-2xl">{loading?"—":data.companies}</b></article><article className="rounded-xl border bg-white p-4 shadow-sm"><small className="text-[10px] font-bold text-[#77808e]">ASSOCIATIONS</small><b className="mt-1 block text-2xl">{loading?"—":data.associations}</b></article><article className="rounded-xl border bg-white p-4 shadow-sm"><small className="text-[10px] font-bold text-[#77808e]">UNLINKED DEALS</small><b className="mt-1 block text-2xl">{loading?"—":data.unlinkedDeals}</b></article><article className="rounded-xl border bg-white p-4 shadow-sm"><small className="text-[10px] font-bold text-[#77808e]">REVIEW NEEDED</small><b className="mt-1 block text-2xl">{loading?"—":data.unreviewedChanges}</b></article></div>
  <section className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="text-sm font-bold">Integration readiness</h2><p className="mt-1 text-xs text-[#77808e]">Operational controls belong here. Connection credentials, security policy, and organization-wide defaults remain in Settings.</p></div><ShieldCheck size={18} className="text-[#2095f3]"/></div><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-lg border bg-[#fafbfd] p-3"><small className="text-[9px] font-bold text-[#77808e]">LAST SUCCESSFUL SYNC</small><b className="mt-1 block text-xs">{data.lastSync?new Date(data.lastSync).toLocaleString():"No completed sync found"}</b></div><div className="rounded-lg border bg-[#fafbfd] p-3"><small className="text-[9px] font-bold text-[#77808e]">LINKAGE HEALTH</small><b className="mt-1 block text-xs">{data.unlinkedDeals===0?"No unlinked deals detected":`${data.unlinkedDeals} deal${data.unlinkedDeals===1?"":"s"} need company linkage review`}</b></div><div className="rounded-lg border bg-[#fafbfd] p-3"><small className="text-[9px] font-bold text-[#77808e]">CHANGE REVIEW</small><b className="mt-1 block text-xs">{data.unreviewedChanges===0?"No changes waiting for review":`${data.unreviewedChanges} source change${data.unreviewedChanges===1?"":"s"} require review`}</b></div></div></section>
  <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="text-sm font-bold">Recent source changes</h2><p className="mt-1 text-xs text-[#77808e]">A focused operational feed of recent HubSpot changes affecting compensation source records.</p><div className="mt-4 overflow-x-auto"><div className="min-w-[760px]">{data.recentChanges.length===0?<div className="rounded-lg bg-[#fafbfd] p-6 text-center text-xs text-[#77808e]">No recent source changes are available.</div>:data.recentChanges.map((row,i)=><div key={`${row.detected_at}-${i}`} className="grid grid-cols-[160px_1.3fr_1fr_1fr_1fr] gap-3 border-b py-3 text-xs"><span className="text-[#77808e]">{new Date(row.detected_at).toLocaleString()}</span><b>{row.deal_name}</b><span>{row.field_name}</span><span className="text-[#77808e]">{row.old_value??"—"} → {row.new_value??"—"}</span><span className="font-semibold">{row.review_status}</span></div>)}</div></div></section>
 </div></AdminShell>;
}
