"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,ArrowLeft,CheckCircle2,RefreshCw,Search,UserCog} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Employee={employee_id:string;full_name:string;email:string;title:string|null;department:string|null;manager_name:string|null;is_active:boolean;profile_status:string;has_app_access:boolean;draft_status:string|null;draft_roles:string[];compensation_participant:boolean;plan_name:string|null;plan_status:string|null;plan_effective_start_date:string|null;plan_effective_end_date:string|null;earnings_eligibility_date:string|null;workflow_name:string|null;workflow_status:string|null;readiness:string;readiness_reasons:string[]};
type Payload={employees:Employee[]};
function label(v:string|null|undefined){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}

export default function EmployeesPage(){
 const[data,setData]=useState<Payload>({employees:[]});const[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[view,setView]=useState("all");
 const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const{data:result,error:rpcError}=await supabase.rpc("get_employee_administration_data");if(rpcError)setError(rpcError.message);else setData((result||{employees:[]}) as Payload);setLoading(false)};useEffect(()=>{load()},[]);
 const rows=useMemo(()=>data.employees.filter(e=>(view==="all"||e.readiness===view)&&(!query||`${e.full_name} ${e.email} ${e.title||""} ${e.plan_name||""}`.toLowerCase().includes(query.toLowerCase()))),[data.employees,query,view]);
 const ready=data.employees.filter(e=>["ready","preinvite_ready"].includes(e.readiness)).length,needs=data.employees.filter(e=>e.readiness==="needs_setup").length;
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1320,margin:"0 auto"}}><header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:22,flexWrap:"wrap"}}><div><Link href="/manage" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700,fontSize:13}}><ArrowLeft size={15}/>Management</Link><small style={{display:"block",fontWeight:800,letterSpacing:1.1,color:"#2095f3",marginTop:12}}>PEOPLE & READINESS</small><h1 style={{fontSize:34,margin:"6px 0"}}>Employees</h1><p style={{margin:0,color:"#647184"}}>App access, plan assignment, earnings eligibility, and approval workflow readiness in one place.</p></div><button onClick={load} disabled={loading} style={{display:"flex",gap:7,alignItems:"center",padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:700}}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>{error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginBottom:16}}><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small>Active employees</small><b style={{display:"block",fontSize:26}}>{loading?"—":data.employees.length}</b></div><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small>Ready / pre-invite ready</small><b style={{display:"block",fontSize:26}}>{loading?"—":ready}</b></div><div style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small>Needs setup</small><b style={{display:"block",fontSize:26}}>{loading?"—":needs}</b></div></section>
 <section style={{display:"flex",gap:10,marginBottom:14,flexWrap:"wrap"}}><label style={{position:"relative",flex:"1 1 320px"}}><Search size={17} style={{position:"absolute",left:11,top:11,color:"#8b98a8"}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee, title, plan" style={{width:"100%",boxSizing:"border-box",padding:"10px 12px 10px 36px",border:"1px solid #d6dee8",borderRadius:9}}/></label><select value={view} onChange={e=>setView(e.target.value)} style={{padding:"10px 12px",border:"1px solid #d6dee8",borderRadius:9,background:"white"}}><option value="all">All readiness</option><option value="ready">Ready</option><option value="preinvite_ready">Pre-invite ready</option><option value="needs_setup">Needs setup</option></select></section>
 <section style={{display:"grid",gap:10}}>{rows.map(e=><article key={e.employee_id} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:16,display:"grid",gridTemplateColumns:"1.2fr 1fr 1fr 1fr",gap:14,alignItems:"start"}}><div><div style={{display:"flex",gap:9,alignItems:"center"}}><span style={{width:36,height:36,borderRadius:10,display:"grid",placeItems:"center",background:"#eaf5ff",color:"#2095f3"}}><UserCog size={18}/></span><div><b>{e.full_name}</b><small style={{display:"block",color:"#718096"}}>{e.email}</small></div></div><small style={{display:"block",marginTop:8,color:"#647184"}}>{e.title||"No title"}{e.department?` · ${e.department}`:""}{e.manager_name?` · Manager: ${e.manager_name}`:""}</small></div><div><small style={{color:"#718096"}}>App access</small><b style={{display:"block",marginTop:3}}>{label(e.profile_status)}</b><small style={{color:"#647184"}}>{e.has_app_access?"Provisioned":e.draft_status?`Draft: ${label(e.draft_status)}`:"Not provisioned"}</small></div><div><small style={{color:"#718096"}}>Compensation</small><b style={{display:"block",marginTop:3}}>{e.plan_name|| (e.compensation_participant?"Plan missing":"Not a participant")}</b><small style={{color:"#647184"}}>{e.earnings_eligibility_date?`Eligible from ${e.earnings_eligibility_date}`:"No eligibility date"}</small></div><div><small style={{color:"#718096"}}>Readiness</small><b style={{display:"flex",alignItems:"center",gap:5,marginTop:3,color:e.readiness==="needs_setup"?"#9b5d00":"#0f7a50"}}>{e.readiness==="needs_setup"?<AlertTriangle size={15}/>:<CheckCircle2 size={15}/>} {label(e.readiness)}</b><small style={{display:"block",color:"#647184",marginTop:4}}>{e.workflow_name||"No active workflow"}</small>{e.readiness_reasons?.length>0&&<ul style={{margin:"7px 0 0",paddingLeft:18,color:"#7a5b22",fontSize:12}}>{e.readiness_reasons.map(r=><li key={r}>{r}</li>)}</ul>}</div></article>)}</section></div></main>
}
