"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,BarChart3,RefreshCw,Save} from "lucide-react";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH");
type Component={component_id:string;name:string;component_code:string;description:string|null;calculation_type:string|null;measurement_source:string|null;measurement_period:string|null;calculation_order?:number|null;maximum_payout:number|null;is_active?:boolean|null;payout_timing_method?:string|null;allow_manager_payout_override?:boolean|null;measurement_label?:string|null;rule_configuration:any};
type Version={version_id:string;version_number:number;status:string;components:Component[]};
type Plan={plan_id:string;name:string;versions:Version[]};
type PreviewRow={employee_id:string;employee_name:string;qualifying_total:number;baseline_amount:number;attainment_value:number;benchmark_amount:number|null;attainment_percent:number|null;qualifying_record_count:number;calculation?:{status?:string;calculated_amount?:number;threshold_met?:boolean;explanation?:string}};
type Preview={period:string;period_start:string;period_end:string;rows:PreviewRow[]};

export default function AggregateAttainmentPage(){
 const params=useParams<{componentId:string}>();
 const[plans,setPlans]=useState<Plan[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[previewing,setPreviewing]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const[sourceCodes,setSourceCodes]=useState<string[]>([]),[period,setPeriod]=useState("annual"),[baseline,setBaseline]=useState("0"),[benchmark,setBenchmark]=useState(""),[comparison,setComparison]=useState("greater_than"),[payout,setPayout]=useState("");
 const[measurementDate,setMeasurementDate]=useState(()=>new Date().toISOString().slice(0,10)),[preview,setPreview]=useState<Preview|null>(null);

 useEffect(()=>{(async()=>{setLoading(true);const{data,error:e}=await supabase.rpc("get_compensation_plan_admin_data");if(e){setError(e.message);setLoading(false);return}const ps=(data?.plans||[]) as Plan[];setPlans(ps);for(const p of ps)for(const v of p.versions){const c=v.components.find(x=>x.component_id===params.componentId);if(!c)continue;const cfg=c.rule_configuration||{},agg=cfg.aggregate||{};setSourceCodes(Array.isArray(agg.source_component_codes)?agg.source_component_codes:Array.isArray(cfg.aggregate_component_codes)?cfg.aggregate_component_codes:[]);setPeriod(agg.period||c.measurement_period||"annual");setBaseline(String(agg.baseline_amount??cfg.aggregate_fixed_uplift??0));setBenchmark(String(agg.benchmark_amount??cfg.threshold_amount??""));setComparison(agg.comparison||cfg.comparison||"greater_than");setPayout(String(agg.payout_amount??cfg.bonus_amount??""));}setLoading(false)})()},[params.componentId]);
 const context=useMemo(()=>{for(const p of plans)for(const v of p.versions){const c=v.components.find(x=>x.component_id===params.componentId);if(c)return{plan:p,version:v,component:c}}return null},[plans,params.componentId]);
 const sourceOptions=(context?.version.components||[]).filter(c=>c.component_id!==params.componentId&&c.calculation_type!=="threshold_bonus");
 const editable=context?.version.status==="draft";
 const toggle=(code:string)=>setSourceCodes(v=>v.includes(code)?v.filter(x=>x!==code):[...v,code]);
 const save=async()=>{if(!context||!editable)return;if(!benchmark||!payout){setError("Enter a benchmark and payout amount.");return}if(sourceCodes.length===0){setError("Choose at least one Earning Type that counts toward this benchmark.");return}setSaving(true);setError("");setMessage("");const c=context.component,cfg={...(c.rule_configuration||{})};cfg.threshold_amount=Number(benchmark);cfg.bonus_amount=Number(payout);cfg.comparison=comparison;cfg.aggregate_component_codes=sourceCodes;cfg.aggregate_fixed_uplift=Number(baseline||0);cfg.aggregate={function:"sum",period,source_component_codes:sourceCodes,baseline_amount:Number(baseline||0),benchmark_amount:Number(benchmark),comparison,payout_amount:Number(payout)};const{error:e}=await supabase.rpc("save_compensation_plan_component",{selected_plan_version_id:context.version.version_id,selected_component_id:c.component_id,selected_name:c.name,selected_component_code:c.component_code,selected_description:c.description||null,selected_calculation_type:c.calculation_type||"threshold_bonus",selected_measurement_source:c.measurement_source||"book_of_business",selected_measurement_period:period,selected_calculation_order:c.calculation_order??1,selected_rule_configuration:cfg,selected_maximum_payout:c.maximum_payout,selected_is_active:c.is_active??true,selected_payout_timing_method:c.payout_timing_method||"annual",selected_allow_manager_payout_override:c.allow_manager_payout_override??true,selected_measurement_label:c.measurement_label??null});setSaving(false);if(e){setError(e.message);return}setMessage("Aggregate benchmark saved.");await runPreview()};
 const runPreview=async()=>{setPreviewing(true);setError("");const{data,error:e}=await supabase.rpc("preview_comp_component_aggregate",{target_component_id:params.componentId,selected_measurement_date:measurementDate});setPreviewing(false);if(e){setError(e.message);return}setPreview((data||null) as Preview|null)};
 if(loading)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-empty">Loading aggregate setup…</div></div></main>;
 if(!context)return <main className="plan-workspace"><div className="plan-page-shell"><div className="plan-alert error">Earning Type not found.</div></div></main>;
 return <main className="plan-workspace"><div className="plan-page-shell" style={{paddingBottom:90}}>
   <div className="plan-breadcrumb"><Link href={`/plans/component/${params.componentId}?version=${context.version.version_id}`}><ArrowLeft size={15}/>Earning Type</Link><span>/</span><span>Quota & benchmark</span></div>
   <header className="plan-page-header"><div><span className="plan-kicker">AGGREGATE ATTAINMENT</span><h1>{context.component.name}</h1><p>Build a running total from qualifying Earning Types, compare it with a benchmark, and calculate the attainment payout.</p></div><span className={`plan-status ${context.version.status}`}>{context.version.status} v{context.version.version_number}</span></header>
   {error&&<div className="plan-alert error">{error}</div>}{message&&<div className="plan-info-row">{message}</div>}
   <section className="plan-step-card"><div className="plan-step-card__head"><div><h2>1. What counts toward attainment?</h2><p>Select the Earning Types whose qualifying HubSpot records should roll into this benchmark.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:8}}>{sourceOptions.map(c=><label key={c.component_id} style={{display:"flex",gap:9,alignItems:"center",border:"1px solid #e3e8ef",borderRadius:9,padding:"10px 12px",fontWeight:600,fontSize:12}}><input type="checkbox" checked={sourceCodes.includes(c.component_code)} onChange={()=>toggle(c.component_code)} disabled={!editable}/><span>{c.name}<small style={{display:"block",color:"#667085",fontWeight:500,marginTop:2}}>{c.component_code}</small></span></label>)}</div></section>
   <section className="plan-step-card"><div className="plan-step-card__head"><div><h2>2. Benchmark and payout</h2><p>The running total can include a starting baseline, then compares attainment with the benchmark.</p></div></div><div className="plan-form-grid two"><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)} disabled={!editable}><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option></select></label><label>Starting baseline<input type="number" min="0" step="0.01" value={baseline} onChange={e=>setBaseline(e.target.value)} disabled={!editable}/></label><label>Benchmark *<input type="number" min="0" step="0.01" value={benchmark} onChange={e=>setBenchmark(e.target.value)} disabled={!editable}/></label><label>Comparison<select value={comparison} onChange={e=>setComparison(e.target.value)} disabled={!editable}><option value="greater_than">Greater than</option><option value="greater_than_or_equal">Greater than or equal</option><option value="equal">Equal</option></select></label><label>Payout when benchmark is met *<input type="number" min="0" step="0.01" value={payout} onChange={e=>setPayout(e.target.value)} disabled={!editable}/></label></div>{editable&&<div className="plan-actions"><button type="button" className="plan-button brand" disabled={saving} onClick={()=>void save()}><Save size={14}/>{saving?"Saving…":"Save benchmark"}</button></div>}</section>
   <section className="plan-step-card"><div className="plan-step-card__head"><div><h2>3. Preview current attainment</h2><p>Preview uses the same qualifying deal rules and employee attribution configured by the source Earning Types, including draft assignments.</p></div></div><div className="plan-form-grid two"><label>Measurement date<input type="date" value={measurementDate} onChange={e=>setMeasurementDate(e.target.value)}/></label><div style={{alignSelf:"end"}}><button type="button" className="plan-button secondary" onClick={()=>void runPreview()} disabled={previewing}><RefreshCw size={14}/>{previewing?"Calculating…":"Preview attainment"}</button></div></div>{preview&&<div style={{marginTop:16}}><div className="plan-info-row"><BarChart3 size={16}/><span>{preview.period_start} through {preview.period_end}</span></div>{preview.rows.map(r=><div key={r.employee_id} style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:12,padding:"12px 4px",borderTop:"1px solid #eef1f4",alignItems:"center"}}><b>{r.employee_name}</b><span><small>QUALIFYING</small><br/>${Number(r.qualifying_total||0).toLocaleString()}</span><span><small>ATTAINMENT</small><br/>${Number(r.attainment_value||0).toLocaleString()}</span><span><small>PROGRESS</small><br/>{r.attainment_percent==null?"—":`${r.attainment_percent}%`}</span><span><small>PAYOUT</small><br/>${Number(r.calculation?.calculated_amount||0).toLocaleString()}</span></div>)}{preview.rows.length===0&&<div className="plan-empty">No assigned employees were available for this plan version.</div>}</div>}</section>
   <div className="plan-wizard-actions"><Link className="plan-button secondary" href={`/plans/component/${params.componentId}?version=${context.version.version_id}`}><ArrowLeft size={15}/>Back to Earning Type</Link></div>
 </div></main>;
}
