"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,ArrowLeft,RefreshCw,Search} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Earning={earning_id:string;employee_name:string;earning_name:string;source_type:string|null;source_external_id:string|null;source_url:string|null;earned_date:string|null;earned_amount:number;eligibility_status:string;eligible_amount:number;employee_verification_status:string;manager_approval_status:string;executive_approval_status:string;executive_approval_required?:boolean;approved_amount:number;payment_status:string;paid_amount:number;hold_reason:string|null;expected_payment_date:string|null;expected_pay_period_label:string|null;reconciliation_status:string|null;source_match_status:string|null;updated_at:string;};
type Payload={summary:{current_earnings:number;earned_amount:number;eligible_amount:number;approved_amount:number;paid_amount:number;awaiting_approval:number;payment_exceptions:number};earnings:Earning[]};
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function label(v:string|null|undefined){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function workflowState(e:Earning){
 if(e.payment_status==="paid")return "Paid";
 if(e.payment_status==="partially_paid")return "Partially paid";
 if(e.payment_status==="scheduled")return "Scheduled for payment";
 if(e.payment_status==="ready_for_payroll")return "Ready for payroll";
 if(e.payment_status==="held")return "Payment held";
 if(["returned","rejected"].includes(e.manager_approval_status)||["returned","rejected"].includes(e.executive_approval_status))return "Returned / rejected";
 if(Number(e.approved_amount||0)>0&&e.executive_approval_status==="approved")return "Fully approved";
 if(e.manager_approval_status==="approved"&&e.employee_verification_status==="verified")return "In approval · awaiting executive approval";
 if(e.employee_verification_status==="verified")return "In approval · awaiting compensation review";
 if(e.eligibility_status==="eligible")return "Eligible · ready to submit";
 if(e.eligibility_status==="pending_condition")return "Earned · waiting on eligibility";
 return label(e.eligibility_status)
}
function statusMatch(e:Earning,status:string){if(status==="all")return true;if(status==="eligible")return e.eligibility_status==="eligible";if(status==="waiting_eligibility")return e.eligibility_status==="pending_condition";if(status==="ready_submit")return e.eligibility_status==="eligible"&&e.employee_verification_status!=="verified"&&e.payment_status!=="paid";if(status==="comp_review")return e.employee_verification_status==="verified"&&e.manager_approval_status==="pending";if(status==="exec_review")return e.employee_verification_status==="verified"&&e.manager_approval_status==="approved"&&e.executive_approval_status!=="approved";if(status==="approved")return Number(e.approved_amount||0)>0;return e.payment_status===status}

export default function EarningsPage(){
 const[data,setData]=useState<Payload>({summary:{current_earnings:0,earned_amount:0,eligible_amount:0,approved_amount:0,paid_amount:0,awaiting_approval:0,payment_exceptions:0},earnings:[]});const[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("all");
 const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const{data:result,error:rpcError}=await supabase.rpc("get_admin_earnings_data");if(rpcError)setError(rpcError.message);else setData((result||data) as Payload);setLoading(false)};useEffect(()=>{load()},[]);
 const rows=useMemo(()=>data.earnings.filter(e=>{const hay=`${e.employee_name} ${e.earning_name} ${e.source_external_id||""}`.toLowerCase();return (!query||hay.includes(query.toLowerCase()))&&statusMatch(e,status)}),[data.earnings,query,status]);
 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1350,margin:"0 auto"}}>
 <section style={{display:"flex",justifyContent:"space-between",gap:24,alignItems:"flex-start",marginBottom:28,flexWrap:"wrap"}}><div style={{flex:"1 1 700px"}}><Link href="/manage" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#647184",fontWeight:700,fontSize:13}}><ArrowLeft size={15}/>Management</Link><small style={{display:"block",fontWeight:800,letterSpacing:1.1,color:"#2095f3",marginTop:12}}>AUTHORITATIVE LEDGER</small><h1 style={{fontSize:34,margin:"6px 0"}}>Earnings</h1><p style={{margin:0,color:"#647184"}}>Current compensation ledger with earned, eligible, submitted, approved, and paid states kept distinct.</p></div><button onClick={load} disabled={loading} style={{display:"flex",gap:7,alignItems:"center",padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:700}}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></section>
 {error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10,marginBottom:18}}>{[["Earned",data.summary.earned_amount],["Eligible",data.summary.eligible_amount],["Fully approved",data.summary.approved_amount],["Paid",data.summary.paid_amount]].map(([a,b])=><div key={String(a)} style={{background:"white",border:"1px solid #dfe6ee",borderRadius:12,padding:15}}><small style={{fontWeight:800,color:"#718096"}}>{a}</small><b style={{display:"block",fontSize:24,marginTop:6}}>{loading?"—":money(Number(b))}</b></div>)}</section>
 <section style={{display:"flex",gap:10,marginBottom:14,flexWrap:"wrap"}}><label style={{flex:"1 1 320px",position:"relative"}}><Search size={17} style={{position:"absolute",left:11,top:11,color:"#8b98a8"}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee, earning, or source ID" style={{width:"100%",boxSizing:"border-box",padding:"10px 12px 10px 36px",border:"1px solid #d6dee8",borderRadius:9}}/></label><select value={status} onChange={e=>setStatus(e.target.value)} style={{padding:"10px 12px",border:"1px solid #d6dee8",borderRadius:9,background:"white"}}><option value="all">All workflow states</option><option value="waiting_eligibility">Waiting on eligibility</option><option value="ready_submit">Eligible · ready to submit</option><option value="comp_review">Awaiting compensation review</option><option value="exec_review">Awaiting executive approval</option><option value="approved">Fully approved</option><option value="ready_for_payroll">Ready for payroll</option><option value="held">Held</option><option value="scheduled">Scheduled</option><option value="paid">Paid</option></select></section>
 <section style={{background:"white",border:"1px solid #dfe6ee",borderRadius:14,overflow:"hidden"}}>{rows.length===0?<div style={{padding:34,textAlign:"center",color:"#647184"}}>No earnings match this view.</div>:rows.map(e=><div key={e.earning_id} style={{display:"grid",gridTemplateColumns:"1.05fr 1.35fr .72fr .72fr 1.15fr",gap:12,padding:"14px 16px",borderBottom:"1px solid #edf1f5",alignItems:"center"}}><div><b>{e.employee_name}</b><small style={{display:"block",color:"#718096",marginTop:3}}>{e.earned_date||"No earned date"}</small></div><div><b style={{fontSize:14}}>{e.earning_name}</b><small style={{display:"block",color:"#718096",marginTop:3}}>{label(e.source_type)}{e.source_external_id?` · ${e.source_external_id}`:""}</small></div><div><small style={{display:"block",color:"#718096"}}>Earned</small><b>{money(e.earned_amount)}</b></div><div><small style={{display:"block",color:"#718096"}}>Eligible</small><b>{money(e.eligible_amount)}</b></div><div><small style={{display:"block",color:"#718096"}}>Workflow state</small><b style={{fontSize:13}}>{workflowState(e)}</b>{e.paid_amount>0&&<small style={{display:"block",color:"#647184",marginTop:3}}>{money(e.paid_amount)} paid</small>}{e.hold_reason&&<span title={e.hold_reason}><AlertTriangle size={14} style={{marginLeft:5,color:"#b7791f"}}/></span>}</div></div>)}</section>
 </div></main>
}
