"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, RefreshCw, WalletCards } from "lucide-react";
import { createClient } from "@supabase/supabase-js";
import AdminShell from "../components/admin-shell";

const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"");

type Earning={earning_id:string;employee_id:string;employee_name:string;employee_email:string;job_title:string|null;earning_name:string;earning_description:string|null;source_type:string|null;earned_date:string|null;earned_amount:number|null;eligibility_status:string|null;eligible_date:string|null;eligible_amount:number|null;employee_verification_status:string|null;manager_approval_status:string|null;executive_approval_required:boolean;executive_approval_status:string|null;approved_amount:number|null;payment_status:string|null;paid_amount:number|null;hold_reason:string|null;expected_payment_date:string|null;expected_pay_period_label:string|null;reconciliation_status:string|null;source_match_status:string|null;updated_at:string};
type Payload={summary:{current_earnings:number;earned_amount:number;eligible_amount:number;approved_amount:number;paid_amount:number;awaiting_approval:number;payment_exceptions:number};earnings:Earning[]};
const empty:Payload={summary:{current_earnings:0,earned_amount:0,eligible_amount:0,approved_amount:0,paid_amount:0,awaiting_approval:0,payment_exceptions:0},earnings:[]};
const money=(v:number|null|undefined)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0));
const date=(v:string|null|undefined)=>v?new Date(`${v}${v.length===10?"T00:00:00":""}`).toLocaleDateString():"—";

export default function EarningsPage(){
 const[data,setData]=useState<Payload>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("all");
 const load=async()=>{setLoading(true);setError("");const{data:r,error:e}=await supabase.rpc("get_admin_earnings_data");if(e)setError(e.message);else setData({...empty,...(r||{})});setLoading(false)};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>data.earnings.filter(e=>{const q=query.trim().toLowerCase();const matches=!q||[e.employee_name,e.employee_email,e.earning_name,e.source_type,e.payment_status,e.manager_approval_status,e.reconciliation_status].some(v=>String(v||"").toLowerCase().includes(q));const statusMatch=status==="all"||status==="approval"&&(e.manager_approval_status==="pending"||e.manager_approval_status==="submitted"||e.employee_verification_status==="submitted")||status==="payment"&&(e.payment_status==="held"||!!e.hold_reason)||status==="paid"&&e.payment_status==="paid";return matches&&statusMatch}),[data.earnings,query,status]);
 return <AdminShell section="earnings" title="Earnings & Credits" description="Current compensation earnings, approval state, payment readiness, source integrity, and exceptions."><div className="space-y-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-bold">Earnings operations</h1><p className="mt-1 text-xs text-[#77808e]">A permission-scoped operational view of current earnings without exposing raw tables directly.</p></div><button onClick={load} disabled={loading} className="flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-xs font-bold"><RefreshCw size={14}/>Refresh</button></div>
  {error&&<div className="flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={17}/><div><b>Unable to load earnings</b><div className="text-xs">{error}</div></div></div>}
  <div className="grid gap-3 md:grid-cols-4 xl:grid-cols-7">{[["CURRENT",data.summary.current_earnings],["EARNED",money(data.summary.earned_amount)],["ELIGIBLE",money(data.summary.eligible_amount)],["APPROVED",money(data.summary.approved_amount)],["PAID",money(data.summary.paid_amount)],["AWAITING APPROVAL",data.summary.awaiting_approval],["PAYMENT EXCEPTIONS",data.summary.payment_exceptions]].map(([label,value])=><article key={String(label)} className="rounded-xl border bg-white p-4 shadow-sm"><small className="text-[9px] font-bold text-[#77808e]">{label}</small><b className="mt-1 block text-xl">{loading?"—":String(value)}</b></article>)}</div>
  <section className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex flex-wrap gap-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee, earning, source or status" className="min-w-[280px] flex-1 rounded-lg border px-3 py-2 text-sm"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="all">All current earnings</option><option value="approval">Awaiting approval</option><option value="payment">Payment exceptions</option><option value="paid">Paid</option></select></div></section>
  {loading?<div className="rounded-xl border bg-white p-8 text-center text-sm text-[#77808e]">Loading earnings…</div>:filtered.length===0?<div className="rounded-xl border bg-white p-8 text-center"><WalletCards className="mx-auto text-[#2095f3]"/><b className="mt-3 block text-sm">No earnings match this view</b></div>:<div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><div className="min-w-[1180px]"><div className="grid grid-cols-[1.25fr_1.3fr_110px_115px_120px_120px_120px_130px] gap-3 border-b bg-[#fafbfd] px-4 py-3 text-[10px] font-bold text-[#66717f]"><span>EMPLOYEE</span><span>EARNING</span><span>EARNED</span><span>ELIGIBLE</span><span>APPROVAL</span><span>APPROVED</span><span>PAYMENT</span><span>RECONCILIATION</span></div>{filtered.map(e=><div key={e.earning_id} className="grid grid-cols-[1.25fr_1.3fr_110px_115px_120px_120px_120px_130px] gap-3 border-b px-4 py-4 text-xs last:border-b-0"><span><b className="block text-sm">{e.employee_name}</b><small className="text-[#77808e]">{e.job_title||e.employee_email}</small></span><span><b className="block">{e.earning_name}</b><small className="text-[#77808e]">{e.source_type||"Application"} · {date(e.earned_date)}</small>{e.hold_reason&&<small className="mt-1 block text-amber-700">Hold: {e.hold_reason}</small>}</span><b>{money(e.earned_amount)}</b><span><b className="block">{money(e.eligible_amount)}</b><small>{e.eligibility_status||"—"}</small></span><span><b className="block">{e.manager_approval_status||e.employee_verification_status||"—"}</b>{e.executive_approval_required&&<small>Exec: {e.executive_approval_status||"pending"}</small>}</span><b>{money(e.approved_amount)}</b><span><b className="block">{e.payment_status||"—"}</b><small>{money(e.paid_amount)} paid</small></span><span><b className="block">{e.reconciliation_status||"—"}</b><small>{e.source_match_status||""}</small></span></div>)}</div></div>}
 </div></AdminShell>;
}
