"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,RefreshCw,Search} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;
type Earning={earning_id:string;employee_name:string;earning_name:string;source_type:string|null;source_external_id:string|null;source_url:string|null;earned_date:string|null;earned_amount:number;eligibility_status:string;eligible_amount:number;employee_verification_status:string;manager_approval_status:string;executive_approval_status:string;executive_approval_required?:boolean;approved_amount:number;payment_status:string;paid_amount:number;hold_reason:string|null;expected_payment_date:string|null;expected_pay_period_label:string|null;reconciliation_status:string|null;source_match_status:string|null;updated_at:string;};
type Payload={summary:{current_earnings:number;earned_amount:number;eligible_amount:number;approved_amount:number;paid_amount:number;awaiting_approval:number;payment_exceptions:number};earnings:Earning[]};
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function label(v:string|null|undefined){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function workflowState(e:Earning){if(e.payment_status==="paid")return "Paid";if(e.payment_status==="partially_paid")return "Partially paid";if(e.payment_status==="scheduled")return "Scheduled for payment";if(e.payment_status==="ready_for_payroll")return "Ready for payroll";if(e.payment_status==="held")return "Payment held";if(["returned","rejected"].includes(e.manager_approval_status)||["returned","rejected"].includes(e.executive_approval_status))return "Returned / rejected";if(Number(e.approved_amount||0)>0&&e.executive_approval_status==="approved")return "Fully approved";if(e.manager_approval_status==="approved"&&e.employee_verification_status==="verified")return "In approval · awaiting executive approval";if(e.employee_verification_status==="verified")return "In approval · awaiting compensation review";if(e.eligibility_status==="eligible")return "Eligible · ready to submit";if(e.eligibility_status==="pending_condition")return "Earned · waiting on eligibility";return label(e.eligibility_status)}
function statusMatch(e:Earning,status:string){if(status==="all")return true;if(status==="eligible")return e.eligibility_status==="eligible";if(status==="waiting_eligibility")return e.eligibility_status==="pending_condition";if(status==="ready_submit")return e.eligibility_status==="eligible"&&e.employee_verification_status!=="verified"&&e.payment_status!=="paid";if(status==="comp_review")return e.employee_verification_status==="verified"&&e.manager_approval_status==="pending";if(status==="exec_review")return e.employee_verification_status==="verified"&&e.manager_approval_status==="approved"&&e.executive_approval_status!=="approved";if(status==="approved")return Number(e.approved_amount||0)>0;return e.payment_status===status}

export default function EarningsPage(){
 const[data,setData]=useState<Payload>({summary:{current_earnings:0,earned_amount:0,eligible_amount:0,approved_amount:0,paid_amount:0,awaiting_approval:0,payment_exceptions:0},earnings:[]});const[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("all");
 const load=async()=>{if(!supabase){setError("The compensation ledger is temporarily unavailable.");setLoading(false);return}setLoading(true);setError("");const{data:result,error:rpcError}=await supabase.rpc("get_admin_earnings_data");if(rpcError)setError("We couldn't load the compensation ledger. Try again.");else setData((result||data) as Payload);setLoading(false)};useEffect(()=>{load()},[]);
 const rows=useMemo(()=>data.earnings.filter(e=>{const hay=`${e.employee_name} ${e.earning_name} ${e.source_external_id||""}`.toLowerCase();return (!query||hay.includes(query.toLowerCase()))&&statusMatch(e,status)}),[data.earnings,query,status]);
 return <main className="eng-page"><div className="eng-page__shell">
  <nav className="eng-page__crumbs" aria-label="Breadcrumb"><Link href="/manage">Control Center</Link><span>/</span><span>Earnings & Credits</span></nav>
  <header className="eng-page__header"><div><div className="eng-page__eyebrow">AUTHORITATIVE LEDGER</div><h1>Earnings</h1><p className="eng-page__lede">Current compensation ledger with Earned, Eligible, Approved, and Paid kept distinct. Use Credit Lineage when you need to inspect how source deals and employee credit produced an earning.</p></div><div className="eng-page__actions"><Link className="eng-page__button" href="/credits">View credit lineage</Link><button className="eng-page__button eng-page__button--primary" onClick={load} disabled={loading}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></div></header>
  {error&&<div className="eng-page__alert eng-page__alert--danger">{error}</div>}
  <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10,marginBottom:18}}>{[["Earned",data.summary.earned_amount],["Eligible",data.summary.eligible_amount],["Fully approved",data.summary.approved_amount],["Paid",data.summary.paid_amount]].map(([a,b])=><div key={String(a)} className="eng-page__card"><small>{a}</small><b style={{display:"block",fontSize:24,marginTop:6}}>{loading?"—":money(Number(b))}</b></div>)}</section>
  <section className="eng-page__filters"><label style={{flex:"1 1 320px",position:"relative"}}><Search size={17} style={{position:"absolute",left:11,top:11}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search employee, earning, or source ID" style={{width:"100%",boxSizing:"border-box",padding:"10px 12px 10px 36px"}}/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All workflow states</option><option value="waiting_eligibility">Waiting on eligibility</option><option value="ready_submit">Eligible · ready to submit</option><option value="comp_review">Awaiting compensation review</option><option value="exec_review">Awaiting executive approval</option><option value="approved">Fully approved</option><option value="ready_for_payroll">Ready for payroll</option><option value="held">Held</option><option value="scheduled">Scheduled</option><option value="paid">Paid</option></select></section>
  <section className="eng-page__card" style={{padding:0,overflow:"hidden"}}>{rows.length===0?<div className="eng-page__empty"><strong>No earnings match this view</strong><span>Change the search or workflow filter to see other compensation items.</span></div>:<div style={{overflowX:"auto"}}><div style={{minWidth:850}}>{rows.map(e=><div key={e.earning_id} style={{display:"grid",gridTemplateColumns:"1.05fr 1.35fr .72fr .72fr 1.15fr",gap:12,padding:"14px 16px",borderBottom:"1px solid var(--eng-border, #edf1f5)",alignItems:"center"}}><div><b>{e.employee_name}</b><small style={{display:"block",marginTop:3}}>{e.earned_date||"No earned date"}</small></div><div><b style={{fontSize:14}}>{e.earning_name}</b><small style={{display:"block",marginTop:3}}>{label(e.source_type)}{e.source_external_id?` · ${e.source_external_id}`:""}</small></div><div><small style={{display:"block"}}>Earned</small><b>{money(e.earned_amount)}</b></div><div><small style={{display:"block"}}>Eligible</small><b>{money(e.eligible_amount)}</b></div><div><small style={{display:"block"}}>Workflow state</small><b style={{fontSize:13}}>{workflowState(e)}</b>{e.paid_amount>0&&<small style={{display:"block",marginTop:3}}>{money(e.paid_amount)} paid</small>}{e.hold_reason&&<span title={e.hold_reason}><AlertTriangle size={14} style={{marginLeft:5}}/></span>}</div></div>)}</div></div>}</section>
 </div></main>;
}