"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,CheckCircle2,MessageCircle,RefreshCw,RotateCcw,ShieldCheck,Undo2,XCircle} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Access={full_name?:string;email?:string;roles?:string[];permissions?:string[]};
type RequestRow={approval_request_id:string;earning_id:string;employee_id:string;employee_name:string;employee_email:string;plan_id:string|null;plan_name:string|null;plan_code:string|null;plan_version_id:string|null;plan_version_number:number|null;earning_name:string;earning_description:string|null;earned_date:string;earned_amount:number;eligible_amount:number;approved_amount:number;approval_level:string;approval_order:number;status:string;requested_at:string;completed_at:string|null;notes:string|null;requested_from:string|null;backup_requested_from:string|null;approver_employee_id:string|null;approver_name:string|null;assignee_activation_required:boolean;source_snapshot:Record<string,unknown>;payment_status:string;employee_verification_status:string};
type ThreadMessage={id:string;sender_name:string;message_body:string;created_at:string};

function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function label(v:string|null|undefined){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function dateLabel(v:string|null){return v?new Date(v).toLocaleString():"—"}
function stageLabel(row:RequestRow){if(row.approval_level==="compensation_admin_review")return "Compensation review";if(row.approval_level==="executive_approval")return "Executive approval";return label(row.approval_level)}

export default function SubmissionsPage(){
 const[rows,setRows]=useState<RequestRow[]>([]),[access,setAccess]=useState<Access|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null),[comments,setComments]=useState<Record<string,string>>({}),[showCompleted,setShowCompleted]=useState(false);
 const[openThread,setOpenThread]=useState<string|null>(null),[threads,setThreads]=useState<Record<string,ThreadMessage[]>>({}),[threadDrafts,setThreadDrafts]=useState<Record<string,string>>({});
 const isAdmin=Boolean(access?.roles?.includes("system_administrator"));
 const canApprove=isAdmin||Boolean(access?.permissions?.includes("earnings.approve"));
 const load=async()=>{if(!supabase){setError("Compensation activity is temporarily unavailable.");setLoading(false);return}setLoading(true);setError("");const[a,b]=await Promise.all([supabase.rpc("get_current_user_access"),supabase.rpc("get_my_comp_earning_approval_requests",{include_completed:showCompleted})]);if(a.error)setError("We couldn't load your access information.");else setAccess((a.data||{}) as Access);if(b.error)setError(x=>x||"We couldn't load pending compensation actions. Try refreshing the page.");else setRows((b.data||[]) as RequestRow[]);setLoading(false)};
 useEffect(()=>{load()},[showCompleted]);
 const pending=useMemo(()=>rows.filter(r=>r.status==="pending"),[rows]),completed=useMemo(()=>rows.filter(r=>r.status!=="pending"),[rows]);
 const act=async(row:RequestRow,action:"approved"|"returned"|"rejected")=>{if(!supabase)return;const note=(comments[row.approval_request_id]||"").trim();if((action==="returned"||action==="rejected")&&!note){setError("A comment is required when returning or rejecting an earning.");return}setBusy(row.approval_request_id+action);setError("");const{error:rpcError}=await supabase.rpc("act_on_comp_earning_approval",{target_approval_request_id:row.approval_request_id,requested_action:action,action_comments:note||null});if(rpcError)setError("That approval action could not be completed. No compensation state was changed.");else{setComments(x=>({...x,[row.approval_request_id]:""}));await load()}setBusy(null)};
 const loadThread=async(id:string)=>{if(!supabase)return;setOpenThread(id);const{data,error:e}=await supabase.rpc("get_approval_request_messages",{target_approval_request_id:id});if(e){setError("The clarification conversation could not be loaded.");return}setThreads(x=>({...x,[id]:(data||[]) as ThreadMessage[]}))};
 const sendMessage=async(row:RequestRow)=>{if(!supabase)return;const text=(threadDrafts[row.approval_request_id]||"").trim();if(!text){setError("Enter a message before sending.");return}setBusy(`message-${row.approval_request_id}`);setError("");const{error:e}=await supabase.rpc("add_approval_request_message",{target_approval_request_id:row.approval_request_id,message_body:text});if(e)setError("Your clarification message could not be sent.");else{setThreadDrafts(x=>({...x,[row.approval_request_id]:""}));await loadThread(row.approval_request_id)}setBusy(null)};
 const unapprove=async(row:RequestRow)=>{if(!supabase)return;const reason=window.prompt(`Why are you reversing approval for ${row.employee_name} · ${row.earning_name}?`);if(!reason?.trim())return;setBusy(`unapprove-${row.earning_id}`);setError("");const{error:e}=await supabase.rpc("unapprove_comp_earning",{target_earning_id:row.earning_id,unapproval_reason:reason.trim()});if(e)setError("Approval could not be reversed. Paid or partially paid earnings cannot be unapproved.");else await load();setBusy(null)};

 const QueueCard=({row}:{row:RequestRow})=>{const unassigned=row.status==="pending"&&row.assignee_activation_required;const sourceName=String(row.source_snapshot?.company_name||row.source_snapshot?.deal_name||"");const threadOpen=openThread===row.approval_request_id;const canReverse=showCompleted&&canApprove&&Number(row.approved_amount||0)>0&&!['paid','partially_paid'].includes(String(row.payment_status));return <article className="eng-panel" style={{padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:15,alignItems:"flex-start",flexWrap:"wrap"}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><span className="eng-head__eyebrow" style={{margin:0}}>{stageLabel(row).toUpperCase()}</span><span className={`eng-pill ${row.status==="pending"?"eng-pill--warn":"eng-pill--neutral"}`}>{label(row.status)}</span></div><h2 style={{margin:"7px 0 3px",fontSize:18}}>{row.employee_name} · {row.earning_name}</h2><p style={{margin:0,color:"var(--eng-body)",fontSize:13}}>{sourceName||row.earning_description||"Compensation earning"}</p><div style={{fontSize:12,color:"var(--eng-body)",marginTop:6}}>{row.plan_name?<>Plan: <Link href={row.plan_version_id?`/plans?version=${row.plan_version_id}`:"/plans"} style={{fontWeight:700,color:"var(--eng-blue-strong)",textDecoration:"none"}}>{row.plan_name}{row.plan_version_number?` · v${row.plan_version_number}`:""}</Link></>:"Plan context unavailable"}</div><small style={{display:"block",marginTop:5,color:"var(--eng-muted)"}}>Earned {row.earned_date} · Submitted {dateLabel(row.requested_at)}</small></div><div style={{textAlign:"right"}}><b className="eng-num" style={{fontSize:24}}>{money(row.earned_amount)}</b><small style={{display:"block",color:"var(--eng-muted)",marginTop:3}}>Eligible {money(row.eligible_amount)}</small></div></div>
 {unassigned&&<div className="eng-msg eng-msg--warn" style={{marginTop:13,marginBottom:0}}><AlertTriangle size={17}/><div className="eng-msg__body"><b>Configured for {row.approver_name||"the next approver"}, but that user is not activated yet.</b><span>{isAdmin?"System Administrator may exercise this step for controlled testing; the audit trail records the real actor.":"This step will become actionable when the configured approver is activated."}</span></div></div>}
 {row.status==="pending"&&<div style={{marginTop:14}}><input value={comments[row.approval_request_id]||""} onChange={e=>setComments(x=>({...x,[row.approval_request_id]:e.target.value}))} placeholder="Optional approval note; required for return or reject" className="eng-input" style={{width:"100%",marginBottom:9}}/><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>act(row,"approved")} disabled={busy!==null} className="eng-button eng-button--primary"><CheckCircle2 size={16}/>{busy===row.approval_request_id+"approved"?"Approving…":unassigned&&isAdmin?`Admin test approve ${row.approver_name||"step"}`:"Approve"}</button><button onClick={()=>act(row,"returned")} disabled={busy!==null} className="eng-button"><RotateCcw size={16}/>Return for correction</button><button onClick={()=>act(row,"rejected")} disabled={busy!==null} className="eng-button eng-button--danger"><XCircle size={16}/>Reject</button><button onClick={()=>void loadThread(row.approval_request_id)} disabled={busy!==null} className="eng-button"><MessageCircle size={16}/>Ask / clarify</button></div></div>}
 {row.status!=="pending"&&<div style={{marginTop:12,padding:10,background:"var(--eng-soft)",borderRadius:9,fontSize:13,display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><b>{label(row.status)}</b>{row.notes?` · ${row.notes}`:""}{row.completed_at?` · ${dateLabel(row.completed_at)}`:""}</div><div style={{display:"flex",gap:8}}><button onClick={()=>void loadThread(row.approval_request_id)} className="eng-button eng-button--small"><MessageCircle size={14}/>Conversation</button>{canReverse&&<button onClick={()=>void unapprove(row)} disabled={busy!==null} className="eng-button eng-button--small"><Undo2 size={14}/>{busy===`unapprove-${row.earning_id}`?"Reopening…":"Unapprove"}</button>}</div></div>}
 {threadOpen&&<div style={{marginTop:12,borderTop:"1px solid var(--eng-line)",paddingTop:12}}><div style={{display:"grid",gap:8,marginBottom:10}}>{(threads[row.approval_request_id]||[]).length===0?<small style={{color:"var(--eng-muted)"}}>No clarification messages yet.</small>:(threads[row.approval_request_id]||[]).map(m=><div key={m.id} style={{background:"var(--eng-soft)",border:"1px solid var(--eng-line)",borderRadius:9,padding:9}}><b style={{fontSize:12}}>{m.sender_name}</b><span style={{fontSize:11,color:"var(--eng-muted)",marginLeft:8}}>{dateLabel(m.created_at)}</span><div style={{fontSize:13,marginTop:4}}>{m.message_body}</div></div>)}</div><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input value={threadDrafts[row.approval_request_id]||""} onChange={e=>setThreadDrafts(x=>({...x,[row.approval_request_id]:e.target.value}))} placeholder="Ask a question or provide clarification…" className="eng-input" style={{flex:"1 1 320px"}}/><button onClick={()=>void sendMessage(row)} disabled={busy!==null} className="eng-button eng-button--primary">{busy===`message-${row.approval_request_id}`?"Sending…":"Send"}</button></div></div>}
 </article>};

 return <main className="eng-page"><div className="eng-page__shell">
  <nav className="eng-crumbs" aria-label="Breadcrumb"><Link href="/manage">Control Center</Link><span className="eng-crumbs__sep">/</span><span className="eng-crumbs__here">Pending Actions</span></nav>
  <header className="eng-head"><div className="eng-head__main"><span className="eng-head__eyebrow">COMPENSATION ACTIVITY</span><h1>Pending Actions & Approval History</h1><p>Review submissions, request clarification without rejecting them, see completed actions, and reopen an approval when necessary before anything has been paid.</p><small style={{display:"block",marginTop:7,color:"var(--eng-muted)"}}>{access?.full_name||access?.email||"Signed-in user"}{isAdmin?" · System Administrator":""}</small></div><div className="eng-head__actions"><button onClick={load} disabled={loading} className="eng-button"><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></div></header>
  {error&&<div className="eng-msg eng-msg--bad"><div className="eng-msg__body"><b>Action needed</b><span>{error}</span></div></div>}
  <section style={{display:"flex",gap:8,marginBottom:15,flexWrap:"wrap"}}><button onClick={()=>setShowCompleted(false)} className={`eng-button ${!showCompleted?"eng-button--primary":""}`}>Needs my action {pending.length}</button><button onClick={()=>setShowCompleted(true)} className={`eng-button ${showCompleted?"eng-button--primary":""}`}>History</button></section>
  {loading?<div className="eng-loading"><div className="eng-loading__row"><span className="eng-bar" style={{width:"42%"}}/></div><div className="eng-loading__row"><span className="eng-bar" style={{width:"68%"}}/></div><div className="eng-loading__row"><span className="eng-bar" style={{width:"54%"}}/></div></div>:rows.length===0?<section className="eng-state"><div className="eng-state__icon eng-state__icon--ok"><ShieldCheck size={24}/></div><h2>{showCompleted?"No approval history yet":"Nothing needs your action"}</h2><p>{showCompleted?"Completed approval actions will appear here.":"When an employee submission reaches a step assigned to you, it will appear here with its plan context and submission date."}</p></section>:<section style={{display:"grid",gap:11}}>{(showCompleted?completed:pending).map(row=><QueueCard key={row.approval_request_id} row={row}/>)}</section>}
 </div></main>
}
