"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "@supabase/supabase-js";
import {AlertTriangle,CheckCircle2,ChevronRight,Home,MessageCircle,RefreshCw,RotateCcw,ShieldCheck,Undo2,XCircle} from "lucide-react";

const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bwdtbsqojtxfbeyfkang.supabase.co";
const supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||"sb_publishable_UEFOn-Rc0sczK9PwqVI91w_IAz95BcH";
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;

type Access={full_name?:string;email?:string;roles?:string[];permissions?:string[]};
type RequestRow={approval_request_id:string;earning_id:string;employee_id:string;employee_name:string;employee_email:string;plan_id:string|null;plan_name:string|null;plan_code:string|null;plan_version_id:string|null;plan_version_number:number|null;earning_name:string;earning_description:string|null;earned_date:string;earned_amount:number;eligible_amount:number;approved_amount:number;approval_level:string;approval_order:number;status:string;requested_at:string;completed_at:string|null;notes:string|null;requested_from:string|null;backup_requested_from:string|null;approver_employee_id:string|null;approver_name:string|null;assignee_activation_required:boolean;source_snapshot:Record<string,unknown>;payment_status:string;employee_verification_status:string};
type ThreadMessage={id:string;sender_name:string;message_body:string;created_at:string};

function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0))}
function label(v:string|null|undefined){return String(v||"—").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function dateLabel(v:string|null){return v?new Date(v).toLocaleString():"—"}
function stageLabel(row:RequestRow){if(row.approval_level==="compensation_admin_review")return "Compensation review";if(row.approval_level==="executive_approval")return "Executive approval";return label(row.approval_level)}

export default function SubmissionsPage(){
 const[rows,setRows]=useState<RequestRow[]>([]),[access,setAccess]=useState<Access|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState<string|null>(null),[comments,setComments]=useState<Record<string,string>>({}),[showCompleted,setShowCompleted]=useState(false);
 const[openThread,setOpenThread]=useState<string|null>(null),[threads,setThreads]=useState<Record<string,ThreadMessage[]>>({}),[threadDrafts,setThreadDrafts]=useState<Record<string,string>>({});
 const isAdmin=Boolean(access?.roles?.includes("system_administrator"));
 const canApprove=isAdmin||Boolean(access?.permissions?.includes("earnings.approve"));
 const load=async()=>{if(!supabase){setError("Database connection unavailable");setLoading(false);return}setLoading(true);setError("");const[a,b]=await Promise.all([supabase.rpc("get_current_user_access"),supabase.rpc("get_my_comp_earning_approval_requests",{include_completed:showCompleted})]);if(a.error)setError(a.error.message);else setAccess((a.data||{}) as Access);if(b.error)setError(x=>x||b.error.message);else setRows((b.data||[]) as RequestRow[]);setLoading(false)};
 useEffect(()=>{load()},[showCompleted]);
 const pending=useMemo(()=>rows.filter(r=>r.status==="pending"),[rows]),completed=useMemo(()=>rows.filter(r=>r.status!=="pending"),[rows]);
 const act=async(row:RequestRow,action:"approved"|"returned"|"rejected")=>{if(!supabase)return;const note=(comments[row.approval_request_id]||"").trim();if((action==="returned"||action==="rejected")&&!note){setError("A comment is required when returning or rejecting an earning.");return}setBusy(row.approval_request_id+action);setError("");const{error:rpcError}=await supabase.rpc("act_on_comp_earning_approval",{target_approval_request_id:row.approval_request_id,requested_action:action,action_comments:note||null});if(rpcError)setError(rpcError.message);else{setComments(x=>({...x,[row.approval_request_id]:""}));await load()}setBusy(null)};
 const loadThread=async(id:string)=>{if(!supabase)return;setOpenThread(id);const{data,error:e}=await supabase.rpc("get_approval_request_messages",{target_approval_request_id:id});if(e){setError(e.message);return}setThreads(x=>({...x,[id]:(data||[]) as ThreadMessage[]}))};
 const sendMessage=async(row:RequestRow)=>{if(!supabase)return;const text=(threadDrafts[row.approval_request_id]||"").trim();if(!text){setError("Enter a message before sending.");return}setBusy(`message-${row.approval_request_id}`);setError("");const{error:e}=await supabase.rpc("add_approval_request_message",{target_approval_request_id:row.approval_request_id,message_body:text});if(e)setError(e.message);else{setThreadDrafts(x=>({...x,[row.approval_request_id]:""}));await loadThread(row.approval_request_id)}setBusy(null)};
 const unapprove=async(row:RequestRow)=>{if(!supabase)return;const reason=window.prompt(`Why are you reversing approval for ${row.employee_name} · ${row.earning_name}?`);if(!reason?.trim())return;setBusy(`unapprove-${row.earning_id}`);setError("");const{error:e}=await supabase.rpc("unapprove_comp_earning",{target_earning_id:row.earning_id,unapproval_reason:reason.trim()});if(e)setError(e.message);else await load();setBusy(null)};

 const QueueCard=({row}:{row:RequestRow})=>{const unassigned=row.status==="pending"&&row.assignee_activation_required;const sourceName=String(row.source_snapshot?.company_name||row.source_snapshot?.deal_name||"");const threadOpen=openThread===row.approval_request_id;const canReverse=showCompleted&&canApprove&&Number(row.approved_amount||0)>0&&!['paid','partially_paid'].includes(String(row.payment_status));return <article style={{background:"white",border:"1px solid #dfe6ee",borderRadius:13,padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:15,alignItems:"flex-start",flexWrap:"wrap"}}><div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><small style={{fontWeight:900,color:"#2095f3",letterSpacing:.5}}>{stageLabel(row).toUpperCase()}</small><span style={{fontSize:11,fontWeight:800,padding:"4px 7px",borderRadius:999,background:row.status==="pending"?"#fff4df":"#eef2f6"}}>{label(row.status)}</span></div><h2 style={{margin:"6px 0 3px",fontSize:20}}>{row.employee_name} · {row.earning_name}</h2><p style={{margin:0,color:"#647184",fontSize:13}}>{sourceName||row.earning_description||"Compensation earning"}</p><div style={{fontSize:12,color:"#475467",marginTop:6}}>{row.plan_name?<>Plan: <Link href={row.plan_version_id?`/plans?version=${row.plan_version_id}`:"/plans"} style={{fontWeight:800,color:"#1677c8",textDecoration:"none"}}>{row.plan_name}{row.plan_version_number?` · v${row.plan_version_number}`:""}</Link></>:"Plan context unavailable"}</div><small style={{display:"block",marginTop:5,color:"#8793a1"}}>Earned {row.earned_date} · Submitted {dateLabel(row.requested_at)}</small></div><div style={{textAlign:"right"}}><b style={{fontSize:24}}>{money(row.earned_amount)}</b><small style={{display:"block",color:"#718096",marginTop:3}}>Eligible {money(row.eligible_amount)}</small></div></div>
 {unassigned&&<div style={{marginTop:13,padding:11,background:"#fff8e7",border:"1px solid #e7cf91",borderRadius:9,display:"flex",gap:8,alignItems:"flex-start"}}><AlertTriangle size={17}/><div><b>Configured for {row.approver_name||"the next approver"}, but that user is not activated yet.</b><small style={{display:"block",marginTop:2,color:"#6d5a2f"}}>{isAdmin?"System Administrator may exercise this step for controlled testing; the audit trail records the real actor.":"This step will become actionable when the configured approver is activated."}</small></div></div>}
 {row.status==="pending"&&<div style={{marginTop:14}}><input value={comments[row.approval_request_id]||""} onChange={e=>setComments(x=>({...x,[row.approval_request_id]:e.target.value}))} placeholder="Optional approval note; required for return or reject" style={{width:"100%",boxSizing:"border-box",padding:"10px 11px",border:"1px solid #d6dee8",borderRadius:8,marginBottom:9}}/><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={()=>act(row,"approved")} disabled={busy!==null} style={{display:"flex",gap:6,alignItems:"center",padding:"9px 12px",border:0,borderRadius:8,background:"#0f8a57",color:"white",fontWeight:800}}><CheckCircle2 size={16}/>{busy===row.approval_request_id+"approved"?"Approving…":unassigned&&isAdmin?`Admin test approve ${row.approver_name||"step"}`:"Approve"}</button><button onClick={()=>act(row,"returned")} disabled={busy!==null} style={{display:"flex",gap:6,alignItems:"center",padding:"9px 12px",border:"1px solid #d5dde6",borderRadius:8,background:"white",fontWeight:800}}><RotateCcw size={16}/>Return for correction</button><button onClick={()=>act(row,"rejected")} disabled={busy!==null} style={{display:"flex",gap:6,alignItems:"center",padding:"9px 12px",border:"1px solid #efcaca",borderRadius:8,background:"#fff8f8",fontWeight:800,color:"#8b3030"}}><XCircle size={16}/>Reject</button><button onClick={()=>void loadThread(row.approval_request_id)} disabled={busy!==null} style={{display:"flex",gap:6,alignItems:"center",padding:"9px 12px",border:"1px solid #d5dde6",borderRadius:8,background:"white",fontWeight:800}}><MessageCircle size={16}/>Ask / clarify</button></div></div>}
 {row.status!=="pending"&&<div style={{marginTop:12,padding:10,background:"#f8fafc",borderRadius:8,fontSize:13,display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><b>{label(row.status)}</b>{row.notes?` · ${row.notes}`:""}{row.completed_at?` · ${dateLabel(row.completed_at)}`:""}</div><div style={{display:"flex",gap:8}}><button onClick={()=>void loadThread(row.approval_request_id)} style={{display:"inline-flex",gap:6,alignItems:"center",padding:"7px 10px",border:"1px solid #d5dde6",borderRadius:8,background:"white",fontWeight:700}}><MessageCircle size={14}/>Conversation</button>{canReverse&&<button onClick={()=>void unapprove(row)} disabled={busy!==null} style={{display:"inline-flex",gap:6,alignItems:"center",padding:"7px 10px",border:"1px solid #e8c88c",borderRadius:8,background:"#fffaf0",fontWeight:800,color:"#7a5712"}}><Undo2 size={14}/>{busy===`unapprove-${row.earning_id}`?"Reopening…":"Unapprove"}</button>}</div></div>}
 {threadOpen&&<div style={{marginTop:12,borderTop:"1px solid #e8edf2",paddingTop:12}}><div style={{display:"grid",gap:8,marginBottom:10}}>{(threads[row.approval_request_id]||[]).length===0?<small style={{color:"#718096"}}>No clarification messages yet.</small>:(threads[row.approval_request_id]||[]).map(m=><div key={m.id} style={{background:"#f8fafc",border:"1px solid #e4e9ef",borderRadius:8,padding:9}}><b style={{fontSize:12}}>{m.sender_name}</b><span style={{fontSize:11,color:"#8793a1",marginLeft:8}}>{dateLabel(m.created_at)}</span><div style={{fontSize:13,marginTop:4}}>{m.message_body}</div></div>)}</div><div style={{display:"flex",gap:8}}><input value={threadDrafts[row.approval_request_id]||""} onChange={e=>setThreadDrafts(x=>({...x,[row.approval_request_id]:e.target.value}))} placeholder="Ask a question or provide clarification…" style={{flex:1,padding:"9px 10px",border:"1px solid #d6dee8",borderRadius:8}}/><button onClick={()=>void sendMessage(row)} disabled={busy!==null} style={{padding:"9px 12px",border:0,borderRadius:8,background:"#051b34",color:"white",fontWeight:800}}>{busy===`message-${row.approval_request_id}`?"Sending…":"Send"}</button></div></div>}
 </article>};

 return <main style={{minHeight:"100vh",background:"#f5f7fa",padding:28,fontFamily:"Inter,Arial,sans-serif",color:"#051b34"}}><div style={{maxWidth:1200,margin:"0 auto"}}><nav style={{display:"flex",gap:8,alignItems:"center",marginBottom:18}}><Link href="/manage" style={{display:"inline-flex",gap:6,alignItems:"center",textDecoration:"none",color:"#31465a",fontWeight:700}}><Home size={16}/>Control Center</Link><ChevronRight size={15} color="#9aa7b4"/><b>Pending actions & approval history</b></nav>
 <header style={{display:"flex",justifyContent:"space-between",gap:18,alignItems:"flex-start",marginBottom:20,flexWrap:"wrap"}}><div><small style={{fontWeight:800,letterSpacing:1.2,color:"#2095f3"}}>COMPENSATION ACTIVITY</small><h1 style={{fontSize:34,margin:"7px 0"}}>Pending actions & approval history</h1><p style={{margin:0,color:"#647184",maxWidth:800}}>Review submissions, ask for clarification without rejecting them, see completed actions, and reopen an approval when necessary before anything has been paid.</p><small style={{display:"block",marginTop:7,color:"#718096"}}>{access?.full_name||access?.email||"Signed-in user"}{isAdmin?" · System Administrator":""}</small></div><button onClick={load} disabled={loading} style={{display:"flex",gap:7,alignItems:"center",padding:"10px 13px",background:"white",border:"1px solid #d9e2eb",borderRadius:9,fontWeight:700}}><RefreshCw size={16}/>{loading?"Refreshing…":"Refresh"}</button></header>
 {error&&<div style={{background:"#fff3f3",border:"1px solid #f2caca",borderRadius:10,padding:13,marginBottom:15}}>{error}</div>}
 <section style={{display:"flex",gap:8,marginBottom:15}}><button onClick={()=>setShowCompleted(false)} style={{padding:"9px 12px",border:"1px solid #d6dee8",borderRadius:8,background:!showCompleted?"#051b34":"white",color:!showCompleted?"white":"#051b34",fontWeight:800}}>Needs my action {pending.length}</button><button onClick={()=>setShowCompleted(true)} style={{padding:"9px 12px",border:"1px solid #d6dee8",borderRadius:8,background:showCompleted?"#051b34":"white",color:showCompleted?"white":"#051b34",fontWeight:800}}>History</button></section>
 {loading?<p>Loading compensation activity…</p>:rows.length===0?<section style={{background:"white",border:"1px dashed #cbd5df",borderRadius:14,padding:34,textAlign:"center",color:"#647184"}}><ShieldCheck size={28}/><h2>{showCompleted?"No approval history yet":"Nothing needs your action"}</h2><p>{showCompleted?"Completed approval actions will appear here.":"When an employee submission reaches a step assigned to you, it will appear here with its plan context and submission date."}</p></section>:<section style={{display:"grid",gap:11}}>{(showCompleted?completed:pending).map(row=><QueueCard key={row.approval_request_id} row={row}/>)}</section>}
 </div></main>
}
